### PR TITLE
statistics: fix anticount and cold peer statistics

### LINKED ISSUE #5478: statistics: hot peer cache contains unexpected data when cold peer and hot peer appear alternately
### What did you do?

bench tpcc

### What did you expect to see?

stable statistic

### What did you see instead?

img_v2_c225cadc-57d6-489c-a09c-b6c553052abg

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Issue Number: Close #5478

### What is changed and how does it work?

1. The cold peer needs to wait the same time as the cooling interval before being activated again 

2. For unreported peers, the padding load uses 0 instead of the threshold

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/statistics/hot_peer_cache.go [hunk 1]
```diff
@@ -229,7 +229,7 @@ func (f *hotPeerCache) checkColdPeer(storeID uint64, reportRegions map[uint64]*c
 				RegionID: regionID,
 				Kind:     f.kind,
 				// use oldItem.thresholds to make the newItem won't affect the threshold
```
Comment (HunDunDM) [inline server/statistics/hot_peer_cache.go:231]: needs to be modified

**Comment by nolouch** [comment]
@lhy1024  ci failed.

**Review by nolouch — APPROVED** [review]
lgtm

**Review by HunDunDM — APPROVED** [review]
