### PR TITLE
tests: improve the wait time of WaitForPrimaryServing

### LINKED ISSUE #6991: `TestKeyspaceGroupMergeIntoDefault` failed
### Which jobs are failing
```
    testutil.go:63: 
        	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/testutil.go:63
        	            				/home/runner/work/pd/pd/tests/tso_cluster.go:168
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/keyspace_group_manager_test.go:787
        	Error:      	Condition never satisfied
        	Test:       	TestTSOKeyspaceGroupManager/TestKeyspaceGroupMergeIntoDefault
```

### CI link
https://github.com/tikv/pd/actions/runs/5995496714/job/16258601063?pr=6985

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: Close #6991.

### What is changed and how does it work?

```commit-message
Improve the wait time of `WaitForPrimaryServing` to reduce the test failure rate.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/tso_cluster.go [hunk 1]
```diff
@@ -173,7 +173,7 @@ func (tc *TestTSOCluster) WaitForPrimaryServing(re *require.Assertions, keyspace
 			}
 		}
 		return false
-	}, testutil.WithWaitFor(5*time.Second), testutil.WithTickInterval(50*time.Millisecond))
+	}, testutil.WithWaitFor(30*time.Second), testutil.WithTickInterval(100*time.Millisecond))
```
Comment (rleungx) [inline tests/tso_cluster.go:176]: Is it only a case problem?

Comment (JmPotato) [reply tests/tso_cluster.go:176]: No, according to the test log, it's just because we created a lot of keyspace groups at one time and the election can not finish that fast. The log shows that the failure point has a 10-second gap with the election success which the condition waiting requires. I believe this could fix it.

**Review by rleungx — APPROVED** [review]
