### PR TITLE
tests/tso: stabilize TestRandomShutdown

### LINKED ISSUE #10343: TestMicroserviceTSOClientSuite is flaky
### Which jobs are failing
```text
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2260397Z [2026/03/12 02:56:35.312 +00:00] [INFO] [raft] [zap_raft.go:77] ["ae7f38ba030a4413 [logterm: 1, index: 3] sent MsgPreVote request to 136dd459747cee69 at term 1"]
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2260832Z [2026/03/12 02:56:35.312 +00:00] [INFO] [raft] [zap_raft.go:77] ["ae7f38ba030a4413 [logterm: 1, index: 3] sent MsgPreVote request to 94204e2d2c71fd76 at term 1"]
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2260952Z coverage: 6.1% of statements in ../../...
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2261060Z panic: test timed out after 5m0s
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2261155Z 	running tests:
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2261569Z 		TestMicroserviceTSOClientSuite (5m0s)
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2261578Z
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2261679Z goroutine 26786 [running]:
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2261778Z testing.(*M).startAlarm.func1()
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2262016Z 	/opt/hostedtoolcache/go/1.25.8/x64/src/testing/testing.go:2682 +0x605
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2262110Z created by time.goFunc
chunks (8, TSO Integration Test)	UNKNOWN STEP	2026-03-12T02:56:39.2262308Z 	/opt/hostedtoolcache/go/1.25.8/x64/src/time/sleep.go:215 +0x45
```
### CI link
https://github.com/tikv/pd/actions/runs/22983139905/job/66730675006
https://github.com/tikv/pd/actions/runs/22993683711/job/66760451516
https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10334/pull-unit-test-next-gen-3/2031971387177963520
### Anything else
test=TestMicroserviceTSOClientSuite signatures=TIMEOUT_PANIC,PANIC,UNKNOWN_FAILURE

### PR DESCRIPTION
**Pull request by okJiang**
### What problem does this PR solve?

Issue Number: close #10343

`TestMicroserviceTSOClientSuite` times out in CI, and the only microservice subtest that rebuilds the whole suite in the middle of execution is `TestRandomShutdown`.

The issue log for #10343 shows the suite-level timeout after 5 minutes in `TSO Integration Test`:

- `panic: test timed out after 5m0s`
- running test: `TestMicroserviceTSOClientSuite`

Local evidence points to the same hotspot:

- before this change, `cd tests/integrations && make gotest GOTEST_ARGS='-tags=without_dashboard ./tso -run TestMicroserviceTSOClientSuite -count=1 -v -timeout 90s'` passed in `85.30s`
- in that run, `TestRandomShutdown` alone took `24.82s`
- the microservice path in `TestRandomShutdown` was closing a TSO primary and then calling `suite.TearDownSuite()` / `suite.SetupSuite()`, which re-bootstraped the full PD + TSO test environment inside one subtest

That rebuild is much heavier than the failure being exercised and re-enters leader-election/bootstrap work on the shared suite context, making the suite much more likely to hit CI timeouts.

### What is changed and how does it work?

- In microservice mode, `TestRandomShutdown` now records the closed default-primary TSO address, closes that single server, and restores it with `suite.tsoCluster.AddServer(closedTSOAddr)` after the request loop finishes.
- The microservice path now uses a fixed `2s` wait before and after the shutdown instead of the older `3-4s` random sleeps.
- The legacy path is unchanged and still rebuilds the full suite, because it shuts down a PD server rather than a TSO node.

This keeps the microservice test focused on temporary TSO-primary loss instead of paying the cost and instability of a full suite restart.

Risk

- The change only affects the microservice branch of one integration test.
- It keeps the same shutdown stimulus and restores the same TSO listen address, so keyspace-group membership stays aligned with the existing test setup.

Historical analog

- #10203 `test: fix flaky test TestForwardTestSuite in next-gen`
- #10134 `tests: fix some unstable tests`

Both are test-harness-alignment flaky fixes rather than production behavior changes.

Does this PR introduce _any_ user-facing change?

No.

### Check List

Tests

- `cd tests/integrations && make gotest GOTEST_ARGS='-tags=without_dashboard ./tso -run TestMicroserviceTSOClientSuite -count=1 -v -timeout 90s'
  - passed
  - suite time: `72.57s`
  - `TestRandomShutdown`: `5.05s`
- `make basic-test`
  - still fails in this worktree due unrelated baseline issues:
  - `pkg/gctuner`: goleak reports `memoryLimitTuner.tuning.func1`
  - `pkg/storage/endpoint`: `TestDataPhysicalRepresentation` expects `/pd/0/gc/gc_state_revision` but gets a cluster-scoped key

### Release note

```release-note
None.
```

## Summary by CodeRabbit

* **Tests**
  * Improved TSO shutdown tests: added readiness synchronization so all TSO clients report availability before inducing shutdown; added a wait-for-all-services recovery step and deferred restoration of a closed TSO server in non-legacy flows.
  * Adjusted test flow to return early in non-legacy mode after multi-keyspace verification, preserving legacy teardown behavior.
* **Test Utilities**
  * Added a utility to wait until every TSO client is responsive before proceeding.

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

File: tests/integrations/tso/client_test.go [hunk 1]
```diff
@@ -435,22 +435,32 @@ func (suite *tsoClientTestSuite) TestRandomResignLeader() {
...
-		// to the previous time taken < 1s.
-		n := rand.IntN(2) + 3
-		time.Sleep(time.Duration(n) * time.Second)
 		if !suite.legacy {
-			suite.tsoCluster.WaitForDefaultPrimaryServing(re).Close()
+			time.Sleep(2 * time.Second)
+			primary := suite.tsoCluster.WaitForDefaultPrimaryServing(re)
+			closedTSOAddr = primary.GetAddr()
+			primary.Close()
+			time.Sleep(2 * time.Second)
```
Comment (JmPotato) [inline tests/integrations/tso/client_test.go]: Can we avoid adding this kind of hard-coded sleep logic?

Comment (okJiang) [reply tests/integrations/tso/client_test.go]: Replaced the fixed microservice sleeps with explicit waits. `CheckMultiKeyspacesTSO` now waits until each client has observed TSO traffic before the fault injection starts, and `TestRandomShutdown` now waits for a new default primary plus TSO recovery on the existing clients after closing the old primary. I also moved the TSO restart into a deferred cleanup so the closed node is restored on every exit.

File: tests/integrations/mcs/utils/testutil.go [hunk 2]
```diff
@@ -60,6 +61,23 @@ func WaitForTSOServiceAvailable(
...
+	ctx context.Context, re *require.Assertions, clients []pd.Client,
+) {
+	wg := sync.WaitGroup{}
+	wg.Add(len(clients))
+
+	for _, client := range clients {
+		go func(cli pd.Client) {
+			defer wg.Done()
+			WaitForTSOServiceAvailable(ctx, re, cli)
+		}(client)
```
[the remark this answers is not in the document]
Comment (okJiang) [reply tests/integrations/mcs/utils/testutil.go]: Fixed. `WaitForAllTSOServiceAvailable` now waits inline instead of spawning worker goroutines, so the `require` assertions stay on the test goroutine.

File: tests/integrations/mcs/utils/testutil.go [hunk 3]
```diff
@@ -89,10 +109,18 @@ func CheckMultiKeyspacesTSO(
...
+					readyClients.Add(1)
+					ready = true
+				}
 			}
 		}(client)
 	}
 
+	testutil.Eventually(re, func() bool {
+		return readyClients.Load() == int64(len(clients))
+	})
```
[the remark this answers is not in the document]
Comment (okJiang) [reply tests/integrations/mcs/utils/testutil.go:115]: Fixed. Added `defer cancel()` right after `context.WithCancel` so the polling goroutines are always released even if the readiness barrier fails before `parallelAct` runs.

File: tests/integrations/tso/client_test.go (hunk 1 above)
Comment (okJiang) [reply tests/integrations/tso/client_test.go]: ptal again~

**Comment by okJiang** [comment]
ping @JmPotato
