### PR TITLE
schedule: fix progress cannot display when enabling scheduling service

### LINKED ISSUE #8331: pdms: after scale out, online number can't return to 0 even if cluster is balance
### What did you see instead?
583a7319-6406-46e9-be71-1ed0c0264d4c

b4e4c0e3-c483-49e4-b420-a36044e120a0

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #8331.

### What is changed and how does it work?

When enabling scheduling service, use an individual function to check if the cluster is prepared.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/integrations/mcs/scheduling/server_test.go [hunk 1]
```diff
@@ -675,3 +675,70 @@ func (suite *multipleServerTestSuite) TestReElectLeader() {
 	rc = suite.pdLeader.GetServer().GetRaftCluster()
 	rc.IsPrepared()
 }
+
+func (suite *serverTestSuite) TestOnlineProgress() {
```
Comment (HuSharp) [inline tests/integrations/mcs/scheduling/server_test.go:679]: nit , please move TestOnlineProgress into `serverTestSuite` scope instead of behind multipleServerTestSuite :)

**Comment by HuSharp** [comment]
```bash
--- FAIL: TestServerTestSuite (49.63s)
    --- FAIL: TestServerTestSuite/TestStoreLimit (0.24s)
        server_test.go:596: 
            	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/scheduling/server_test.go:596
            	            				/home/runner/work/pd/pd/tests/integrations/mcs/scheduling/server_test.go:550
            	Error:      	Should be true
            	Test:       	TestServerTestSuite/TestStoreLimit
```
ci failed, because API cluster didn't clear the environment (the suite is internally serialized), and the InitRegions called by TestOnlineProgress generated region 2 which is different from TestStoreLimit needed, causing it to fail.

File: pkg/schedule/prepare_checker.go [hunk 2]
```diff
@@ -51,8 +51,8 @@ func (checker *prepareChecker) check(c *core.BasicCluster, collectWaitTime ...ti
 	}
 	notLoadedFromRegionsCnt := c.GetClusterNotFromStorageRegionsCnt()
 	totalRegionsCnt := c.GetTotalRegionCount()
-	// The number of active regions should be more than total region of all stores * collectFactor
-	if float64(totalRegionsCnt)*collectFactor > float64(notLoadedFromRegionsCnt) {
+	// The number of active regions should be more than total region of all stores * CollectFactor
+	if float64(totalRegionsCnt)*CollectFactor > float64(notLoadedFromRegionsCnt) {
 		return false
 	}
 	for _, store := range c.GetStores() {
```
Comment (lhy1024) [inline pkg/schedule/prepare_checker.go:58]: Could we use the similiar function with `isStorePrepared` to avoid to maintain the two functions?

**Review by lhy1024 — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

File: server/cluster/cluster.go [hunk 3]
```diff
@@ -1590,6 +1590,19 @@ func (c *RaftCluster) setStore(store *core.StoreInfo) error {
 	return nil
 }
 
+func (c *RaftCluster) isStorePrepared() bool {
+	for _, store := range c.GetStores() {
+		if !store.IsPreparing() && !store.IsServing() {
```
Comment (HuSharp) [inline server/cluster/cluster.go:1595]: NodeState is exclusive

**Review by HuSharp — APPROVED** [review]
