### PR TITLE
operator: fix some error checks

### LINKED ISSUE #5623: Certain properly executed schedules print error logs
### What did you do?

* `tiup playground nightly --db=1 --pd=1 --kv=3 --tiflash=0`
* `pd-ctl config placement-rules save`

rules.json:

```json
[
  {
    "group_id": "pd",
    "id": "default",
    "start_key": "",
    "end_key": "",
    "role": "voter",
    "count": 2
  },
  {
    "group_id": "test",
    "id": "test",
    "start_key": "",
    "end_key": "",
    "role": "learner",
    "count": 1
  }
]
```

### What did you expect to see?

The schedule executes correctly and there are no error logs.

### What did you see instead?

The schedule is executed correctly.

Before

```json
{
  "id": 5,
  "start_key": "7480000000000000FF4400000000000000F8",
  "end_key": "",
  "epoch": {
    "conf_ver": 5,
    "version": 34
  },
  "peers": [
    {
      "id": 7,
      "store_id": 1,
      "role_name": "Voter"
    },
    {
      "id": 82,
      "store_id": 3,
      "role_name": "Voter"
    },
    {
      "id": 143,
      "store_id": 2,
      "role_name": "Voter"
    }
  ],
  "leader": {
    "id": 7,
    "store_id": 1,
    "role_name": "Voter"
  },
  "written_bytes": 0,
  "read_bytes": 0,
  "written_keys": 0,
  "read_keys": 0,
  "approximate_size": 1,
  "approximate_keys": 115
}
```

After

```json
{
  "id": 5,
  "start_key": "7480000000000000FF4400000000000000F8",
  "end_key": "",
  "epoch": {
    "conf_ver": 6,
    "version": 34
  },
  "peers": [
    {
      "id": 7,
      "store_id": 1,
      "role_name": "Voter"
    },
    {
      "id": 82,
      "store_id": 3,
      "role_name": "Voter"
    },
    {
      "id": 143,
      "store_id": 2,
      "role": 1,
      "role_name": "Learner",
      "is_learner": true
    }
  ],
  "leader": {
    "id": 7,
    "store_id": 1,
    "role_name": "Voter"
  },
  "written_bytes": 96,
  "read_bytes": 0,
  "written_keys": 2,
  "read_keys": 0,
  "approximate_size": 1,
  "approximate_keys": 115
}
```

But monitoring shows that the schedule is canceled and the error log can be found in the log.

```
[2022/10/21 17:16:44.064 +08:00] [INFO] [operator_controller.go:603] ["operator canceled"] [region-id=58] [takes=8.733192ms] [operator="\"fix-demote-voter {demote peer: store [2]} (kind:unknown, region:58(26, 5), createAt:2022-10-21 17:16:44.055566089 +0800 CST m=+63.988023359, startAt:2022-10-21 17:16:44.055684695 +0800 CST m=+63.988141961, currentStep:0, size:1, steps:[use joint consensus, demote voter peer 134 on store 2 to learner])\""] [additional-info=] [reason="peer already is a learner"]
[2022/10/21 17:16:44.065 +08:00] [INFO] [region.go:597] ["region ConfVer changed"] [region-id=5] [detail="Remove peer:{id:143 store_id:2 },Add peer:{id:143 store_id:2 role:Learner }"] [old-confver=5] [new-confver=6]
[2022/10/21 17:16:44.065 +08:00] [INFO] [operator_controller.go:521] ["operator removed"] [region-id=5] [takes=7.162767ms] [operator="\"fix-demote-voter {demote peer: store [2]} (kind:unknown, region:5(34, 5), createAt:2022-10-21 17:16:44.057779272 +0800 CST m=+63.990236536, startAt:2022-10-21 17:16:44.057911033 +0800 CST m=+63.990368321, currentStep:0, size:1, steps:[use joint consensus, demote voter peer 143 on store 2 to learner])\""]
```

### What version of PD are you using (`pd-server -V`)?

v6.3.0

### PR DESCRIPTION
**Pull request by HunDunDM**
### What problem does this PR solve?

Issue Number: Close #5623 

### What is changed and how does it work?

* Improve checks of `PromoteLearner` and `DemoteVoter`
* Allow to directly promote or demote in `ChangePeerV2Enter`.

### Check List

Tests

- Unit test

Code changes

Side effects

Related changes

- Since this issue just results in incorrect logging, this PR is not cherry-picked.

### Release note

```release-note
None
```

### CODE REVIEW

File: server/schedule/operator/step.go [hunk 1]
```diff
@@ -406,7 +406,7 @@ type PromoteLearner struct {
 // ConfVerChanged returns the delta value for version increased by this step.
 func (pl PromoteLearner) ConfVerChanged(region *core.RegionInfo) uint64 {
 	peer := region.GetStoreVoter(pl.ToStore)
-	return typeutil.BoolToUint64(peer.GetId() == pl.PeerID)
+	return typeutil.BoolToUint64(peer.GetId() == pl.PeerID && peer.GetRole() == metapb.PeerRole_Voter)
```
Comment (HunDunDM) [inline server/schedule/operator/step.go:409]: Currently, IncomingVoter and DemotingVoter are also considered Voter, so additional checks are required.

File: server/schedule/operator/step.go [hunk 2]
```diff
@@ -643,9 +643,10 @@ func (dv DemoteVoter) String() string {
 }
 
 // ConfVerChanged returns the delta value for version increased by this step.
-func (dv DemoteVoter) ConfVerChanged(region *core.RegionInfo) bool {
-	peer := region.GetStoreLearner(dv.ToStore)
-	return peer.GetId() == dv.PeerID
+func (dv DemoteVoter) ConfVerChanged(region *core.RegionInfo) uint64 {
```
Comment (HunDunDM) [inline server/schedule/operator/step.go:646]: `ConfVerChanged` will be called when the next steps are performed, and it is necessary to consider that the Peer may have been removed in the future.

File: server/schedule/operator/step.go [hunk 3]
```diff
@@ -700,7 +701,8 @@ func (cpe ChangePeerV2Enter) ConfVerChanged(region *core.RegionInfo) uint64 {
 		}
 	}
 	for _, dv := range cpe.DemoteVoters {
-		peer := region.GetStoreVoter(dv.ToStore)
+		peer := region.GetStorePeer(dv.ToStore)
```
Comment (HunDunDM) [inline server/schedule/operator/step.go:704]: There may be `Learner` here, the previous `GetStoreVoter` was used incorrectly.

File: server/schedule/operator/step.go [hunk 4]
```diff
@@ -715,16 +717,16 @@ func (cpe ChangePeerV2Enter) IsFinish(region *core.RegionInfo) bool {
 		if peer != nil && peer.GetId() != pl.PeerID {
 			log.Warn("obtain unexpected peer", zap.String("expect", pl.String()), zap.Uint64("obtain-voter", peer.GetId()))
 		}
-		if peer.GetId() != pl.PeerID || peer.GetRole() != metapb.PeerRole_IncomingVoter {
+		if peer.GetId() != pl.PeerID || !core.IsVoterOrIncomingVoter(peer) {
```
Comment (HunDunDM) [inline server/schedule/operator/step.go:720]: Allow to promote directly.

File: server/schedule/operator/step.go [hunk 5]
```diff
@@ -740,12 +742,10 @@ func (cpe ChangePeerV2Enter) CheckInProgress(_ ClusterInformer, region *core.Reg
 			return errors.New("peer does not exist")
 		}
 		switch peer.GetRole() {
-		case metapb.PeerRole_Learner:
+		case metapb.PeerRole_Learner, metapb.PeerRole_Voter:
```
Comment (HunDunDM) [inline server/schedule/operator/step.go:745]: Allow to promote directly.

File: server/schedule/operator/step.go (hunk 1 above)
Comment (lhy1024) [reply server/schedule/operator/step.go:409]: maybe we should add these comments to code, which is convenient to read code.

Comment (HunDunDM) [reply server/schedule/operator/step.go:411]: add some comment

**Review by nolouch — APPROVED** [review]
lgtm.

**Review by nolouch — COMMENTED** [review]
Does it will impact the simulator?

**Review by lhy1024 — APPROVED** [review]

**Comment by HunDunDM** [comment]
> Does it will impact the simulator?

does not affect
