### PR TITLE
unsafe recovery: Fix learner nodes got ignored in auto detect mode error

### LINKED ISSUE #6690: Unsafe recovery hang in auto detect mode.
## Bug Report

Unsafe recovery hang in auto detect mode, since learner replicas/ stores are ignored, not considered failed stores.

### PR DESCRIPTION
**Pull request by v01dstar**
### What problem does this PR solve?

Issue Number: Close #6690 

### What is changed and how does it work?

```commit-message
Fix learner nodes got ignored in auto detect mode error
```

### Check List

Tests

- Unit test

Code changes

Side effects

Related changes

This PR does not need to be cherry-picked into release 6.5, since the customized PR #6683 will be.

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/unsaferecovery/unsafe_recovery_controller_test.go [hunk 1]
```diff
@@ -609,6 +609,48 @@ func TestAutoDetectMode(t *testing.T) {
 	}
 }
 
+// Failed learner replica/ store should be considered by auto-recover.
```
Comment (Connor1996) [inline pkg/unsaferecovery/unsafe_recovery_controller_test.go:612]:
```suggestion
// Failed learner replica store should be considered by auto-detect mode.
```

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by disksing — APPROVED** [review]
