### PR TITLE
tests: make TestAllocIDAfterLeaderChange more stable

### LINKED ISSUE #8557: TestAllocIDAfterLeaderChange is unstable
## Flaky Test
TestAllocIDAfterLeaderChange is unstable

### Which jobs are failing
```bash
2024-08-22T02:33:09.9000891Z [2024/08/22 02:33:09.268 +00:00] [INFO] [server.go:1678] ["skip campaigning of pd leader and check later"] [server-name=pd2] [etcd-leader-id=16910137396250798226] [member-id=7914137599778630982]
2024-08-22T02:33:09.9002667Z     server_test.go:117: 
2024-08-22T02:33:09.9004241Z         	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/scheduling/server_test.go:117
2024-08-22T02:33:09.9005646Z         	Error:      	Received unexpected error:
2024-08-22T02:33:09.9006974Z         	            	rpc error: code = Unavailable desc = not leader
2024-08-22T02:33:09.9008239Z         	Test:       	TestServerTestSuite/TestAllocIDAfterLeaderChange
```

### CI link
https://github.com/tikv/pd/actions/runs/10500794166/job/29089748958?pr=8556
https://github.com/tikv/pd/actions/runs/10485694539/job/29042347520

### Reason for failure (if possible)
need to wait leader

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Close #8557

### What is changed and how does it work?

```bash
2024-08-22T02:33:09.9000891Z [2024/08/22 02:33:09.268 +00:00] [INFO] [server.go:1678] ["skip campaigning of pd leader and check later"] [server-name=pd2] [etcd-leader-id=16910137396250798226] [member-id=7914137599778630982]
2024-08-22T02:33:09.9002667Z     server_test.go:117: 
2024-08-22T02:33:09.9004241Z         	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/scheduling/server_test.go:117
2024-08-22T02:33:09.9005646Z         	Error:      	Received unexpected error:
2024-08-22T02:33:09.9006974Z         	            	rpc error: code = Unavailable desc = not leader
2024-08-22T02:33:09.9008239Z         	Test:       	TestServerTestSuite/TestAllocIDAfterLeaderChange
```

```commit-message
need to wait leader
```

### Check List

Tests

- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/integrations/mcs/scheduling/server_test.go [hunk 1]
```diff
@@ -106,6 +106,7 @@ func (suite *serverTestSuite) TestAllocIDAfterLeaderChange() {
 	pd2, err := suite.cluster.Join(suite.ctx)
 	re.NoError(err)
 	err = pd2.Run()
+	re.NotEmpty(suite.cluster.WaitLeader())
```
Comment (lhy1024) [inline tests/integrations/mcs/scheduling/server_test.go:109]: There are still some cases that are not judged empty, do we need also modify them or add comments?

Comment (HuSharp) [reply tests/integrations/mcs/scheduling/server_test.go:109]: Added more waiting leaders for tests related to joining situation

**Review by lhy1024 — APPROVED** [review]

**Review by rleungx — APPROVED** [review]
