### PR TITLE
tests: fix `TestTransferRegionWithPlacementRule` and `TestUpdateMemberWhenRecovery`

### LINKED ISSUE #9511: TestPreparingProgress is unstable again
### Which jobs are failing
```
    testutil.go:68: 
        	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/testutil.go:68
        	            				/home/runner/work/pd/pd/tests/testutil.go:214
        	            				/home/runner/work/pd/pd/tests/server/api/api_test.go:1094
        	Error:      	Condition never satisfied
        	Test:       	TestPreparingProgress
```

### CI link
https://github.com/tikv/pd/actions/runs/16159076607/job/45607138263?pr=9510

it is base on 7db3b6232c074f587d7a6ecab802f8042bbdf785

### LINKED ISSUE #9994: TestUpdateMemberWhenRecovery is flaky
### Which jobs are failing
```shell
make failpoint-enable
cd tests/integrations/mcs/keyspace
go test -v -run TestKeyspaceGroupTestSuite/TestUpdateMemberWhenRecovery
```
https://github.com/tikv/pd/blob/33a67caac489ef9430778357b0aa929dd97044b9/tests/integrations/mcs/keyspace/tso_keyspace_group_test.go#L661-L673

### CI link
https://github.com/tikv/pd/actions/runs/20056411798/job/57522640945?pr=10016

* [linux.log](https://github.com/user-attachments/files/23904762/linux.log)
* [macos.log](https://github.com/user-attachments/files/23904753/macos.log)

### Reason for failure (if possible)
investigation pending

### Anything else
Tested on 33a67caac489ef9430778357b0aa929dd97044b9

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9994, close #9511

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

## Summary by CodeRabbit

* **Tests**
  * Improved test stability by increasing timeouts and using isolated operation contexts to reduce flakiness.
  * Added synchronization checks to ensure configuration changes propagate before proceeding.
  * Hardened leader-related test setup by adjusting lease timing and simplifying leader readiness checks to avoid fragile recovery paths.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: tests/server/api/api_test.go [hunk 1]
```diff
@@ -1277,12 +1279,6 @@ func TestPreparingProgress(t *testing.T) {
 	leader = cluster.GetLeaderServer()
 	if !leader.GetRaftCluster().IsPrepared() {
 		testutil.Eventually(re, func() bool {
-			leader = cluster.GetLeaderServer()
-			if leader == nil {
-				re.NotEmpty(cluster.WaitLeader())
-				leader = cluster.GetLeaderServer()
-				return false
-			}
```
Comment (lhy1024) [inline tests/server/api/api_test.go:1285]: why remove it

Comment (rleungx) [reply tests/server/api/api_test.go:1285]: @JmPotato 's PR will change here.
