### PR TITLE
schedule: fix a deadlock in GetOpInfluence

### LINKED ISSUE #1338: `operator show` blocked
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Type `operator show` in pd-ctl

2. What did you expect to see?
Return existing operators.

3. What did you see instead?
`operator show` command in pd-ctl doesn't return.
screen shot 2018-11-22 at 3 08 32 pm

4. What version of PD are you using (`pd-server -V`)?
Release Version: v2.1.0-rc.2-52-gd9cde51-dirty
Git Commit Hash: d9cde51f5e5608d72259842c36025c24f861ad3b
Git Branch: HEAD
UTC Build Time:  2018-11-22 03:34:33

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve? 
#1310 changes the logic when getting `OpInfluence` and use `GetOperator` in `GetOpInfluence`. These two functions both add `RLock` which might cause a deadlock.

### What is changed and how it works?
This PR uses `oc.operators` directly rather than call `GetOperator` in `GetOpInfluence`. Closes #1338.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

File: server/schedule/operator_controller_test.go [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+		for {
+			oc.RemoveOperator(op1)
+		}
+	}()
+	go func() {
+		for {
+			oc.GetOpInfluence(tc)
+		}
+	}()
+	time.Sleep(1 * time.Second)
```
Comment (disksing) [inline server/schedule/operator_controller_test.go]: Don't sleep. Use waitGroup to save test time.
