### PR TITLE
mcs: update client when meet transport is closing

### LINKED ISSUE #6340: mcs: get global tso from tso service primary addr failed
### What did you do?

run in api mode

### What did you expect to see?

tikv/tidb can get tso, but cannot update gc safe point.

### What did you see instead?

```
[2023/04/18 11:51:29.565 +00:00] [WARN] [grpc_service.go:1494] ["trying to update gc safe point"] [old-safe-point=440217670660915200] [new-safe-point=0]
[2023/04/18 11:51:29.564 +00:00] [ERROR] [grpc_service.go:1999] ["get global tso from tso server failed"] [error="rpc error: code = Unavailable desc = transport is closing"]
```

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #6340

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/grpc_service.go [hunk 1]
```diff
@@ -1787,7 +1788,12 @@ func (s *GrpcServer) getGlobalTSOFromTSOServer(ctx context.Context) (pdpb.Timest
 	})
 	ts, err := forwardStream.Recv()
 	if err != nil {
-		log.Error("get global tso from tso server failed", zap.Error(err))
+		log.Error("get global tso from tso service primary addr failed", zap.Error(err), zap.String("tso", forwardedHost))
+		if strings.Contains(err.Error(), "transport is closing") {
```
Comment (rleungx) [inline server/grpc_service.go:1792]: What if it is another kind of error?

Comment (lhy1024) [reply server/grpc_service.go:1792]: Update the client for any errors encountered? I'm not sure if this will keep updating repeatedly

Comment (rleungx) [reply server/grpc_service.go:1792]: Can you add more descriptions about why this issue happens?

Comment (rleungx) [reply server/grpc_service.go:1792]: Then, how to ensure that this situation does not happen again? Maybe we need to first know how many kinds of errors it might return.

Comment (lhy1024) [reply server/grpc_service.go:1792]: maybe it is better to judge by error code https://github.com/grpc/grpc-go/blob/16651f60ddc5b1adb810fca8b1a732d57fecb270/codes/codes.go#L180

"transport is closing" is defined in https://github.com/grpc/grpc-go/blob/3151e834fa2536844f801bb132c684fbb10364fd/internal/transport/transport.go#L782

Comment (lhy1024) [reply server/grpc_service.go]: And I will add retry with new client for this error

**Review by binshi-bing — APPROVED** [review]

**Review by binshi-bing — APPROVED** [review]
LGTM

**Review by rleungx — APPROVED** [review]
