### PR TITLE
schedulers: rollback the scheduler when failing to persist

### LINKED ISSUE #2572: evict-leader-scheduler may fail to persist configuration
It is a hypothetically speculated bug: when remove a store id from `evict-leader-scheduler`, PD first update the in-memory configuration and then persist it. If it fails to persist to etcd, the operation looks successful, but later when PD leader changes, the removed store id will come up again.

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Try to fix #2572.

### What is changed and how it works?

This PR corrects the status code and rollback the scheduler when failing to persist.

### Check List

Tests

- Unit test

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
Fix the issue that the scheduler may appear again even if we have already executed the delete operation
```

### CODE REVIEW

File: server/cluster/coordinator.go [hunk 1]
```diff
@@ -613,7 +613,6 @@ func (c *coordinator) removeScheduler(name string) error {
 
 	s.Stop()
```
Comment (nolouch) [inline server/cluster/coordinator.go:614]: also need to move this line?

**Review by disksing — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]
