### PR TITLE
api: fix some wrong metrics and add bucket version

### LINKED ISSUE #9557: Region API doesn't have bucket version
## Enhancement Task
We need to investigate whether the bucket is updated successfully sometimes. Both TiDB and TiKV track the bucket version numbers in the log. However, we don't have a way to find the bucket version of a specified region on the PD side, which is inconvenient for troubleshooting problems. 

Also, we don't have any logs either.

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #9557

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test

Code changes

- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))

Side effects

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/response/region_easyjson.go [hunk 1]
```diff
@@ -139,6 +317,8 @@ func easyjson75d7afa0DecodeGithubComTikvPdServerApi(in *jlexer.Lexer, out *Regio
 			out.ApproximateSize = int64(in.Int64())
 		case "approximate_keys":
 			out.ApproximateKeys = int64(in.Int64())
+		case "approximate_kv_size":
```
Comment (lhy1024) [inline pkg/response/region_easyjson.go:320]: After https://github.com/tikv/pd/pull/8403, we added `ApproximateKvSize` but no call easyjson. Do we need to create another PR to pick it to other branches?

File: tests/server/api/region_test.go [hunk 2]
```diff
@@ -409,7 +409,9 @@ func (suite *regionTestSuite) checkRegion(cluster *tests.TestCluster) {
 		core.SetWrittenBytes(100*units.MiB),
 		core.SetWrittenKeys(1*units.MiB),
 		core.SetReadBytes(200*units.MiB),
-		core.SetReadKeys(2*units.MiB))
+		core.SetReadKeys(2*units.MiB),
```
Comment (lhy1024) [inline tests/server/api/region_test.go:412]: Do we need to add a test for bucket version?

**Review by lhy1024 — COMMENTED** [review]
the rest LGTM

File: tests/server/api/region_test.go (hunk 2 above)
Comment (bufferflies) [reply tests/server/api/region_test.go:412]: This test case verifies the bucket version if we marshal the bucket version.

File: pkg/response/region_easyjson.go (hunk 1 above)
Comment (bufferflies) [reply pkg/response/region_easyjson.go:320]: I don't think so; it means that nobody uses this information now. If someone needs it, we can cp this later.

**Review by rleungx — APPROVED** [review]
