### PR TITLE
test(scheduler/checker): add failpoint to skip region patrol for TestAccelerateRegionsScheduleInRanges

### LINKED ISSUE #9926: Flaky test TestAccelerateRegionsScheduleInRanges
### Which jobs are failing

`TestRegionTestSuite/TestAccelerateRegionsScheduleInRanges`

### CI link

https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/9920/pull-unit-test-next-gen/1988500239681589248

### Reason for failure (if possible)

```log
=== NAME  TestRegionTestSuite/TestAccelerateRegionsScheduleInRanges
    testutil.go:68: 
        	Error Trace:	/home/prow/go/src/github.com/tikv/pd/pkg/utils/testutil/testutil.go:68
        	            				/home/prow/go/src/github.com/tikv/pd/tests/server/api/region_test.go:140
        	            				/home/prow/go/src/github.com/tikv/pd/tests/testutil.go:592
        	            				/home/prow/go/src/github.com/tikv/pd/tests/testutil.go:411
        	            				/home/prow/go/src/github.com/tikv/pd/tests/testutil.go:383
        	            				/home/prow/go/src/github.com/tikv/pd/tests/server/api/region_test.go:109
        	Error:      	Condition never satisfied
        	Test:       	TestRegionTestSuite/TestAccelerateRegionsScheduleInRanges
```

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: close #9926.

### What is changed and how does it work?

```commit-message
Introduce a `skipPatrolRegions` failpoint in `CheckerController.PatrolRegions` to allow tests to temporarily
disable periodic region patrol behavior. This makes it easier to verify region scheduling logic deterministically
without interference from background patrol routines.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/server/api/region_test.go [hunk 1]
```diff
@@ -65,54 +66,18 @@ func (suite *regionTestSuite) TearDownTest() {
 	suite.env.Reset(re)
 }
 
-func (suite *regionTestSuite) TestAccelerateRegionsScheduleInRange() {
```
Comment (lhy1024) [inline tests/server/api/region_test.go:68]: remove it?

Comment (JmPotato) [reply tests/server/api/region_test.go:68]: Merged into `TestAccelerateRegionsScheduleInRanges`.

**Review by lhy1024 — APPROVED** [review]

**Comment by rleungx** [comment]
"listen tcp 127.0.0.1:36409: bind: address already in use" seems this issue still exists.

**Review by rleungx — APPROVED** [review]
