### PR TITLE
api: use suitable status code and make TestResetTS stable

### LINKED ISSUE #7314: TestResetTS is unstable
### Which jobs are failing
```
2023-11-03T02:17:32.7014932Z --- FAIL: TestAdminTestSuite (33.40s)
2023-11-03T02:17:32.7015364Z     --- FAIL: TestAdminTestSuite/TestResetTS (0.03s)
2023-11-03T02:17:32.7015779Z         api_check.go:29: 
2023-11-03T02:17:32.7016898Z             	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/api_check.go:29
2023-11-03T02:17:32.7019320Z             	            				/home/runner/work/pd/pd/pkg/utils/testutil/api_check.go:142
2023-11-03T02:17:32.7020790Z             	            				/home/runner/work/pd/pd/pkg/utils/testutil/api_check.go:105
2023-11-03T02:17:32.7022287Z             	            				/home/runner/work/pd/pd/server/api/admin_test.go:191
2023-11-03T02:17:32.7022608Z             	Error:      	Not equal: 
2023-11-03T02:17:32.7023173Z             	            	expected: 200
2023-11-03T02:17:32.7023568Z             	            	actual  : 403
2023-11-03T02:17:32.7024091Z             	Test:       	TestAdminTestSuite/TestResetTS
2023-11-03T02:17:32.7025089Z             	Messages:   	resp: "[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"
```

### CI link
https://github.com/tikv/pd/actions/runs/6740464608/job/18323580850

### LINKED ISSUE #7411: resetTS should use suitable status code
### What did you do?

Test

### What did you expect to see?

The server returns a suitable status code when meeting ErrEtcdTxnConflict

### What did you see instead?

The server returns 403 when meeting any errors, but for temporary failure, we should return 503

https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.4

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #7411 #7314

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by rleungx** [comment]
Please add some explanation of the reason for this unstable test.

**Comment by lhy1024** [comment]
> Please add some explanation of the reason for this unstable test.

When we call ResetTS, we may meet etcd transaction conflict.

File: server/api/admin_test.go [hunk 1]
```diff
@@ -188,9 +190,24 @@ func (suite *adminTestSuite) TestResetTS() {
...
+		resp, err := apiutil.PostJSON(testDialClient, url, values)
+		re.NoError(err)
+		defer resp.Body.Close()
+		b, err := io.ReadAll(resp.Body)
+		re.NoError(err)
+		switch resp.StatusCode {
+		case http.StatusOK:
+			re.Contains(string(b), "Reset ts successfully.")
+			return true
+		case http.StatusForbidden:
```
Comment (rleungx) [inline server/api/admin_test.go:203]: The status code is strange.

Comment (lhy1024) [reply server/api/admin_test.go]: replace it with 503

**Review by rleungx — APPROVED** [review]

File: server/api/admin_test.go (hunk 1 above)
Comment (lhy1024) [reply server/api/admin_test.go]: Ref: https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.4

File: pkg/mcs/tso/server/apis/v1/api.go [hunk 2]
```diff
@@ -185,6 +185,11 @@ func ResetTS(c *gin.Context) {
 	if err = svr.ResetTS(ts, ignoreSmaller, skipUpperBoundCheck, 0); err != nil {
 		if err == errs.ErrServerNotStarted {
 			c.String(http.StatusInternalServerError, err.Error())
+		} else if err == errs.ErrEtcdTxnConflict {
```
Comment (CabinfeverB) [inline pkg/mcs/tso/server/apis/v1/api.go:188]: This is not only for test? Because it will effect the resp to users.
I want to know whether this PR needs to cherry-pick.

**Review by CabinfeverB — APPROVED** [review]

File: pkg/mcs/tso/server/apis/v1/api.go (hunk 2 above)
Comment (lhy1024) [reply pkg/mcs/tso/server/apis/v1/api.go:188]: yes, not only for test. But I am not sure whether it is a bug to need cherry-pick.

Comment (rleungx) [reply pkg/mcs/tso/server/apis/v1/api.go:188]: If it's only for TSO services, IMO we don't need to.

Comment (lhy1024) [reply pkg/mcs/tso/server/apis/v1/api.go:188]: PD mode also returns 403 when meeting ErrEtcdTxnConflict

Comment (lhy1024) [reply pkg/mcs/tso/server/apis/v1/api.go:190]: BR is using it https://github.com/pingcap/tidb/blob/1f7c1e02bcd402cfbc1a0b0a26acfbd0d0fe4d8c/br/pkg/pdutil/pd.go#L892

**Comment by lhy1024** [comment]
After a discussion with @niubell, we will only fix it on the master branch.

File: pkg/mcs/tso/server/apis/v1/api.go (hunk 2 above)
Comment (lhy1024) [reply pkg/mcs/tso/server/apis/v1/api.go:190]: After discussion with @niubell, we will only fix it on master branch.
