### PR TITLE
pkg/schedule, grpc_service : Add error code if scatter_region grpc is failed

### LINKED ISSUE #6950: PD server not returning correct status on failure
### What did you do?
scatter operations on empty regions are skewed to few nodes. It has hit the operator limit and returned success which made lightning or tidb not to retry the requests.

1. Set the store limit to 5
2. run sql presplit command. It will return success but get regions will show skewed regions
### What did you expect to see?
regions to be scattered on all the nodes
### What did you see instead?
regions are skewed to fewer node
### What version of PD are you using (`pd-server -V`)?
6.5.1

### PR DESCRIPTION
**Pull request by mittalrishabh**
### What problem does this PR solve?
Scatter_region grpc doesn't fail and return success. It prevents clients to correctly retry the requests and eventually regions are skewed to few nodes.

Issue Number: Close #6950 6950

### What is changed and how does it work?
Return the error code if it fails. 

```commit-message
```

### Check List

Tests

- manual test
- Steps
1. Set the store limit to 5
2.  Run the pre split sql command with 32 regions.
3. Verify that regions are scattered by using get_region.

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by mittalrishabh** [comment]
I didn't add a new error code. Let me know if you want to add new error code or use any existing error code.

File: pkg/schedule/operator/operator_controller.go [hunk 1]
```diff
@@ -329,6 +329,7 @@ func (oc *Controller) AddOperator(ops ...*Operator) bool {
 	// but maybe user want to add operator when waiting queue is busy
 	if oc.exceedStoreLimitLocked(ops...) {
 		for _, op := range ops {
+            operatorCounter.WithLabelValues(op.Desc(), "store_limit").Inc()
```
Comment (CabinfeverB) [inline pkg/schedule/operator/operator_controller.go:332]: It cloud be same as Line366/367
```suggestion
            operatorCounter.WithLabelValues(op.Desc(), "exceed-limit").Inc()
```

File: server/grpc_service.go [hunk 2]
```diff
@@ -1621,7 +1621,12 @@ func (s *GrpcServer) ScatterRegion(ctx context.Context, request *pdpb.ScatterReg
 		return nil, err
 	}
 	if op != nil {
-		rc.GetOperatorController().AddOperator(op)
+		if !rc.GetOperatorController().AddOperator(op) {
```
Comment (rleungx) [inline server/grpc_service.go:1624]: How about adding a retry for it and returning an error if it finally fails? /cc @nolouch @bufferflies

Comment (mittalrishabh) [reply server/grpc_service.go:1624]: I think it should depend on a caller.  Caller should retry with back off.

Comment (bufferflies) [reply server/grpc_service.go:1624]: I aggre with the mittalrishabh, the producer should response with the error.

**Comment by mittalrishabh** [comment]
do i need to do anything else to get approval

**Review by rleungx — APPROVED** [review]

File: server/grpc_service.go [hunk 3]
```diff
@@ -1621,7 +1621,12 @@ func (s *GrpcServer) ScatterRegion(ctx context.Context, request *pdpb.ScatterReg
...
+			return &pdpb.ScatterRegionResponse{
+				Header: s.wrapErrorToHeader(pdpb.ErrorType_UNKNOWN,
+					"operator cancelled"),
```
Comment (CabinfeverB) [inline server/grpc_service.go:1627]: How aboud `exceeded store limit causing operator canceled`?

**Comment by mittalrishabh** [comment]
Can i get one more approval again. Thanks

File: server/grpc_service.go (hunk 3 above)
Comment (CabinfeverB) [reply server/grpc_service.go:1627]: I don't think this message allows caller to determine why.

Comment (JmPotato) [reply server/grpc_service.go:1627]: @mittalrishabh You may need to resolve this comment before getting approved and merged.

Comment (mittalrishabh) [reply server/grpc_service.go:1627]: created a PR https://github.com/pingcap/kvproto/pull/1173

Comment (JmPotato) [reply server/grpc_service.go:1627]: I think you could just adjust the error message "operator cancelled" here.

**Review by CabinfeverB — APPROVED** [review]

File: server/grpc_service.go (hunk 2 above)
Comment (JmPotato) [inline server/grpc_service.go:1624]: Maybe this could be merged into one `if` block like:

```suggestion
		if op != nil && !rc.GetOperatorController().AddOperator(op) {
```

**Comment by nolouch** [comment]
The changes contain some other guys' commits.

**Comment by mittalrishabh** [comment]
> 

I think it took my company email ID in one commit. Do you want me to open a new PR. I can do that as it is a small change

**Comment by mittalrishabh** [comment]
what is pending to get approval on this PR

**Comment by CabinfeverB** [comment]
Can u merge the upstream(tikv/pd) master?

**Comment by CabinfeverB** [comment]
Or re-open a PR

**Comment by mittalrishabh** [comment]
are you asking me to rebase the PR ?

**Review by nolouch — APPROVED** [review]

**Comment by CabinfeverB** [comment]
`TestScatterRegion` CI failed.
Do u want to fix it yourself?

**Comment by mittalrishabh** [comment]
I couldn't get time today. I will fix CI tomorrow.

**Comment by mittalrishabh** [comment]
please remove the /hold flag. I fixed the test case

File: tests/integrations/client/client_test.go [hunk 4]
```diff
@@ -1325,6 +1325,11 @@ func (suite *clientTestSuite) TestScatterRegion() {
 		Leader: peers[0],
 	}
 	err := suite.regionHeartbeat.Send(req)
+	return regionID
+}
+
+func (suite *clientTestSuite) TestScatterRegion() {
+	var regionID int = CreateRegion()
```
Comment (CabinfeverB) [inline tests/integrations/client/client_test.go:1332]: `CreateRegion` is a method

File: tests/integrations/client/client_test.go [hunk 5]
```diff
@@ -1308,25 +1308,29 @@ func (suite *clientTestSuite) TestUpdateServiceGCSafePoint() {
...
+		req := &pdpb.RegionHeartbeatRequest{
+			Header: newHeader(suite.srv),
+			Region: region,
+			Leader: peers[0],
+		}
+		err := suite.regionHeartbeat.Send(req)
+		suite.NoError(err)
+		return regionID
 	}
-	err := suite.regionHeartbeat.Send(req)
```
Comment (CabinfeverB) [inline tests/integrations/client/client_test.go:1327]: why remove it

File: tests/integrations/client/client_test.go [hunk 6]
```diff
@@ -1308,25 +1308,29 @@ func (suite *clientTestSuite) TestUpdateServiceGCSafePoint() {
...
-		},
-		Peers:    peers,
-		StartKey: []byte("fff"),
-		EndKey:   []byte("ggg"),
-	}
-	req := &pdpb.RegionHeartbeatRequest{
-		Header: newHeader(suite.srv),
-		Region: region,
-		Leader: peers[0],
+	CreateRegion := func() int {
```
Comment (CabinfeverB) [inline tests/integrations/client/client_test.go:1311]:
```suggestion
	CreateRegion := func() uint64 {
```

File: tests/integrations/client/client_test.go (hunk 5 above)
Comment (mittalrishabh) [reply tests/integrations/client/client_test.go:1327]: it is moved above in the function

File: server/grpc_service.go [hunk 7]
```diff
@@ -1709,8 +1709,19 @@ func (s *GrpcServer) ScatterRegion(ctx context.Context, request *pdpb.ScatterReg
 	if err != nil {
 		return nil, err
 	}
-	if op != nil {
-		rc.GetOperatorController().AddOperator(op)
+
+	if op == nil {
+		return &pdpb.ScatterRegionResponse{
+			Header: s.wrapErrorToHeader(pdpb.ErrorType_UNKNOWN,
```
Comment (nolouch) [inline server/grpc_service.go:1715]: It should not be an error. for example, if there are 6 tikv nodes， scatter a batch of regionscontinuously, 50% of the ops should be nil.

**Comment by nolouch** [comment]
ref https://github.com/tikv/pd/issues/7073

File: server/grpc_service.go (hunk 7 above)
Comment (mittalrishabh) [reply server/grpc_service.go:1715]: it come here for the scatter of one region only.
