### PR TITLE
*: fix region stats check

### LINKED ISSUE #7728: metrics: The learner-peer-count  cannot be restored after PD leader changes
## Bug Report

the metrics of `learner-peer-count` cannot be restored after PD leader changes
### What did you do?
1. set up a cluster with playground
```
tiup playground --tag v7.1.1 v7.1.1 --db 1 --pd 3 --kv 3 --tiflash 1 --monitor --host=0.0.0.0 & 
```
2. create table and insert some data into the cluster
```
tiup bench tpcc --warehouses 4 --parts 4 prepare 
```
3. add tiflash replica for the above tables
```
mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| customer       |
| district       |
| history        |
| item           |
| new_order      |
| order_line     |
| orders         |
| stock          |
| warehouse      |
+----------------+
9 rows in set (0.00 sec)

mysql> alter table customer set tiflash replica 1;
Query OK, 0 rows affected (0.21 sec)

mysql> alter table district set tiflash replica 1;
Query OK, 0 rows affected (0.18 sec)

mysql> alter table history set tiflash replica 1;
Query OK, 0 rows affected (0.23 sec)

mysql> alter table item set tiflash replica 1;
Query OK, 0 rows affected (0.14 sec)

mysql> alter table new_order set tiflash replica 1;
Query OK, 0 rows affected (0.25 sec)

mysql> alter table order_line set tiflash replica 1;
Query OK, 0 rows affected (0.19 sec)

mysql> alter table orders set tiflash replica 1;
Query OK, 0 rows affected (0.21 sec)

mysql> alter table stock set tiflash replica 1;
Query OK, 0 rows affected (0.33 sec)

mysql> alter table warehouse set tiflash replica 1;
Query OK, 0 rows affected (0.26 sec)

```

4. check the metrics on PD->region-healthy->learner-peer-count, After the number(`learner-peer-count`) stop changing, manually execute "transfer leader". 
```
fun :: ~ » tiup ctl:v7.1.1 pd -u http://127.0.0.1:2379 member leader transfer pd-2
Starting component `ctl`: /home/fun/.tiup/components/ctl/v7.1.1/ctl pd -u http://127.0.0.1:2379 member leader transfer pd-2
Success!
You have new mail.                                                                                                                                                                                                                                                                                                      
fun :: ~ » tiup ctl:v7.1.1 pd -u http://127.0.0.1:2379 member leader transfer pd-0
Starting component `ctl`: /home/fun/.tiup/components/ctl/v7.1.1/ctl pd -u http://127.0.0.1:2379 member leader transfer pd-0
Success!
fun :: ~ » date
20240117 17:59:24 CST
```
 5. check metrics of `learner-peer-count` again, and it do not restored in 30 minutes（ this number has not recovered even after a day in some cluster .）:
 
![893249a6-d51d-47ac-b7bf-549d2d72e99d](https://github.com/tikv/pd/assets/1085697/e72fb506-0474-4eff-9e1f-37bc79d151a8)


<!-- If possible, provide a recipe for reproducing the error. -->

### What did you expect to see?

The number of `learner-peer-count` should be recover in 10 minutes(https://docs-archive.pingcap.com/tidb/v7.2/tikv-configuration-file#peer-stale-state-check-interval), since hibernate region should sent heartbeat to pd in 10minutes by default. 

### What did you see instead?

it do not restored in 30 minutes（ this number has not recovered even after a day in some cluster .）:

### What version of PD are you using (`pd-server -V`)?
v7.1.1, and this also happens on v6.5.0

### PR DESCRIPTION
**Pull request by CabinfeverB**
### What problem does this PR solve?

Issue Number: Close #7728

### What is changed and how does it work?
1. `isNew` is useless because region source is inexact when leader transfer and no sync. Now, no need to hold `isNew` because `saveCache` must be true if the region in cache does not have leader.
2. check whether the region is observed by its own map

```commit-message
```

### Check List

Tests

- Unit test
- Manual test (add detailed scripts or steps below)

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/core/region.go [hunk 1]
```diff
@@ -718,19 +724,16 @@ func GenerateRegionGuideFunc(enableLog bool) RegionGuideFunc {
 	}
 	// Save to storage if meta is updated.
 	// Save to cache if meta or leader is updated, or contains any down/pending peer.
-	// Mark isNew if the region in cache does not have leader.
-	return func(region, origin *RegionInfo) (isNew, saveKV, saveCache, needSync bool) {
+	// Now, no need to hold `isNew` because `saveCache` must be true if if the region in cache does not have leader.
```
Comment (HuSharp) [inline pkg/core/region.go:727]:
```suggestion
	// Now, no need to hold `isNew` because `saveCache` must be true if the region in cache does not have leader.
```

File: server/cluster/cluster.go [hunk 2]
```diff
@@ -1004,9 +1004,9 @@ func (c *RaftCluster) processRegionHeartbeat(region *core.RegionInfo) error {
 	hasRegionStats := c.regionStats != nil
 	// Save to storage if meta is updated, except for flashback.
 	// Save to cache if meta or leader is updated, or contains any down/pending peer.
-	// Mark isNew if the region in cache does not have leader.
-	isNew, saveKV, saveCache, needSync := regionGuide(region, origin)
-	if !saveKV && !saveCache && !isNew {
+	saveKV, saveCache, needSync := regionGuide(region, origin)
+	fmt.Println("@@@@@", saveKV, saveCache, needSync)
```
Comment (HuSharp) [inline server/cluster/cluster.go:1008]: debug print？

File: pkg/statistics/region_collection.go [hunk 3]
```diff
@@ -240,10 +250,10 @@ func (r *RegionStatistics) Observe(region *core.RegionInfo, stores []*core.Store
 		}
 	}
 	// Remove the info if any of the conditions are not met any more.
-	if oldIndex, ok := r.index[regionID]; ok {
-		deleteIndex = oldIndex &^ peerTypeIndex
+	if oldIndex, ok := r.index[regionID]; ok && oldIndex > 0 {
```
Comment (HuSharp) [inline pkg/statistics/region_collection.go:253]: for `oldIndex > 0`

0 for region state feels a bit weird, do you think we need to add a state name to 0? Like `notRecord` or something.
and maybe better `!= 0`?

File: pkg/core/region.go [hunk 4]
```diff
@@ -718,19 +724,16 @@ func GenerateRegionGuideFunc(enableLog bool) RegionGuideFunc {
 	}
 	// Save to storage if meta is updated.
 	// Save to cache if meta or leader is updated, or contains any down/pending peer.
-	// Mark isNew if the region in cache does not have leader.
-	return func(region, origin *RegionInfo) (isNew, saveKV, saveCache, needSync bool) {
+	// Now, no need to hold `isNew` because `saveCache` must be true if the region in cache does not have leader.
```
Comment (HuSharp) [inline pkg/core/region.go:727]: maybe can move this statement to pr description
```suggestion
```

File: pkg/statistics/region_collection.go (hunk 3 above)
Comment (CabinfeverB) [reply pkg/statistics/region_collection.go:253]: For bit operations. `!=` doesn't seem to be used very often

File: pkg/core/region.go (hunk 4 above)
Comment (CabinfeverB) [reply pkg/core/region.go:727]: Got it. But I think we can keep this comment in code.

Comment (HuSharp) [reply pkg/core/region.go:727]: Oh 😯 I mean, after your code merged, `isNew` is a word which doesn't exist and could be confused others.

Comment (CabinfeverB) [reply pkg/core/region.go:727]: OK

**Review by HuSharp — APPROVED** [review]

**Review by rleungx — APPROVED** [review]
