### PR TITLE
*: make TestGlobalAndLocalTSO stable

### LINKED ISSUE #6250: TestGlobalAndLocalTSO failed
### Which jobs are failing
```
--- FAIL: TestGlobalAndLocalTSO (25.27s)
    client_test.go:458: 
        	Error Trace:	/home/runner/work/pd/pd/tests/integrations/client/client_test.go:458
        	            				/home/runner/work/pd/pd/tests/integrations/client/asm_amd64.s:1598
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of dc-2 allocator
        	            	github.com/tikv/pd/client.(*pdTSOStream).processRequests
        	            		/home/runner/work/pd/pd/client/tso_stream.go:134
        	            	github.com/tikv/pd/client.(*tsoClient).processRequests
        	            		/home/runner/work/pd/pd/client/tso_dispatcher.go:702
        	            	github.com/tikv/pd/client.(*tsoClient).handleDispatcher
        	            		/home/runner/work/pd/pd/client/tso_dispatcher.go:443
        	            	runtime.goexit
        	            		/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/asm_amd64.s:1598
        	            	github.com/tikv/pd/client.(*tsoRequest).Wait
        	            		/home/runner/work/pd/pd/client/tso_dispatcher.go:93
        	            	github.com/tikv/pd/client.(*client).GetLocalTS
        	            		/home/runner/work/pd/pd/client/client.go:629
        	            	github.com/tikv/pd/tests/integrations/client_test.requestGlobalAndLocalTSO.func1
        	            		/home/runner/work/pd/pd/tests/integrations/client/client_test.go:457
        	            	runtime.goexit
        	            		/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/asm_amd64.s:1598
        	Test:       	TestGlobalAndLocalTSO
```

### CI link
https://github.com/tikv/pd/actions/runs/4563140126/jobs/8051267525?pr=6249

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #6250.

### What is changed and how does it work?
Ignore the leader change error to make test more stable.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by binshi-bing — APPROVED** [review]

File: tests/integrations/client/client_test.go [hunk 1]
```diff
@@ -453,13 +454,26 @@ func requestGlobalAndLocalTSO(
 				var lastTS uint64
 				for i := 0; i < tsoRequestRound; i++ {
 					globalPhysical1, globalLogical1, err := cli.GetTS(context.TODO())
-					re.NoError(err)
+					// The allocator leader may be changed due to the environment issue.
+					if err != nil {
+						re.ErrorContains(err, errs.NotLeaderErr)
+					} else {
+						re.NoError(err)
+					}
```
Comment (JmPotato) [inline tests/integrations/client/client_test.go:462]: It's unnecessary since `err` will always be nil in this branch.

**Review by nolouch — APPROVED** [review]
lgtm
