### PR TITLE
test: stablize the mcs TSO integration tests

### LINKED ISSUE #6795: TestGetTSOImmediately failed
### Which jobs are failing
```
2023-07-12T16:54:44.1099413Z     testutil.go:178: 
2023-07-12T16:54:44.1099865Z         	Error Trace:	/home/runner/work/pd/pd/tests/server/apiv2/handlers/testutil.go:178
2023-07-12T16:54:44.1100997Z         	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/keyspace_group_manager_test.go:360
2023-07-12T16:54:44.1102034Z         	            				/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/asm_amd64.s:1598
2023-07-12T16:54:44.1102228Z         	Error:      	Not equal: 
2023-07-12T16:54:44.1102493Z         	            	expected: 200
2023-07-12T16:54:44.1102751Z         	            	actual  : 500
2023-07-12T16:54:44.1103080Z         	Test:       	TestGetTSOImmediately
2023-07-12T16:54:44.1103571Z         	Messages:   	"[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"
```
### CI link

https://github.com/tikv/pd/actions/runs/5534201396/jobs/10098828392?pr=6577

### LINKED ISSUE #9501: TestTSOKeyspaceGroupManagerSuite is unstable
### Which jobs are failing
```
2025-07-07T11:55:50.2918822Z     testutil.go:68: 
2025-07-07T11:55:50.2919178Z         	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/testutil.go:68
2025-07-07T11:55:50.2919967Z         	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/keyspace_group_manager_test.go:380
2025-07-07T11:55:50.2920147Z         	Error:      	Condition never satisfied
2025-07-07T11:55:50.2920685Z         	Test:       	TestTSOKeyspaceGroupManagerSuite/TestTSOKeyspaceGroupSplitElection
2025-07-07T11:55:50.2784550Z     testutil.go:68: 
2025-07-07T11:55:50.2784913Z         	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/testutil.go:68
2025-07-07T11:55:50.2785696Z         	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/keyspace_group_manager_test.go:287
2025-07-07T11:55:50.2785883Z         	Error:      	Condition never satisfied
2025-07-07T11:55:50.2786205Z         	Test:       	TestTSOKeyspaceGroupManagerSuite/TestTSOKeyspaceGroupSplit
2025-07-07T11:55:50.3034573Z --- FAIL: TestTSOKeyspaceGroupManagerSuite (103.12s)
2025-07-07T11:55:50.3034911Z     --- PASS: TestTSOKeyspaceGroupManagerSuite/TestKeyspaceGroupMergeIntoDefault (31.51s)
2025-07-07T11:55:50.3035277Z     --- PASS: TestTSOKeyspaceGroupManagerSuite/TestKeyspacesServedByDefaultKeyspaceGroup (3.27s)
2025-07-07T11:55:50.3035661Z     --- PASS: TestTSOKeyspaceGroupManagerSuite/TestKeyspacesServedByNonDefaultKeyspaceGroups (3.34s)
2025-07-07T11:55:50.3035948Z     --- PASS: TestTSOKeyspaceGroupManagerSuite/TestTSOKeyspaceGroupMembers (0.43s)
2025-07-07T11:55:50.3036223Z     --- PASS: TestTSOKeyspaceGroupManagerSuite/TestTSOKeyspaceGroupMerge (5.44s)
2025-07-07T11:55:50.3036642Z     --- PASS: TestTSOKeyspaceGroupManagerSuite/TestTSOKeyspaceGroupMergeBeforeInitTSO (6.17s)
2025-07-07T11:55:50.3036950Z     --- PASS: TestTSOKeyspaceGroupManagerSuite/TestTSOKeyspaceGroupMergeClient (6.27s)
2025-07-07T11:55:50.3037240Z     --- FAIL: TestTSOKeyspaceGroupManagerSuite/TestTSOKeyspaceGroupSplit (20.12s)
2025-07-07T11:55:50.3037541Z     --- PASS: TestTSOKeyspaceGroupManagerSuite/TestTSOKeyspaceGroupSplitClient (1.96s)
2025-07-07T11:55:50.3037857Z     --- FAIL: TestTSOKeyspaceGroupManagerSuite/TestTSOKeyspaceGroupSplitElection (20.64s)
2025-07-07T11:55:50.3037932Z FAIL
```

### CI link
https://github.com/tikv/pd/actions/runs/16116149449/attempts/1?pr=9499

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: close #9501.

### What is changed and how does it work?

```commit-message
This PR requires specifying the keyspace group ID when checking the keyspace's primary server,
preventing duplicate keyspace IDs across multiple keyspace groups from disrupting the tests.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/mcs/tso/server/server.go [hunk 1]
```diff
@@ -218,16 +218,6 @@ func (s *Server) IsKeyspaceServingByGroup(keyspaceID, keyspaceGroupID uint32) bo
 	return s.checkKeyspaceGroupLeadership(keyspaceID, keyspaceGroupID)
 }
 
-// IsKeyspaceServing returns whether the keyspace is serving.
```
Comment (rleungx) [inline pkg/mcs/tso/server/server.go:221]: I remember https://github.com/tikv/pd/pull/9460 just split it into two functions /cc @lhy1024

Comment (JmPotato) [reply pkg/mcs/tso/server/server.go:221]: Automatically determining the group ID corresponding to a keyspace ID in integration tests may not be a good idea. Explicitly specifying both values ensures that the expected and actual results match, preventing confusion caused by duplicate keyspace IDs in future test cases.

Comment (lhy1024) [reply pkg/mcs/tso/server/server.go:221]: But `IsKeyspaceServingByGroup` call `FindGroupByKeyspaceID`, and `FindGroupByKeyspaceID` call `getKeyspaceGroupMetaWithCheck`, there are comments `The keyspace doesn't belong to this keyspace group, we should check if it belongs to any other keyspace groups, and return the correct keyspace group meta to the client`, it will also automatically adjust keyspace group id. @JmPotato

**Review by lhy1024 — CHANGES_REQUESTED** [review]
If we want to avoid automatically determining the keyspace group ID, we need a new function.
Or only avoid using the same ID in tests, which is helpful in the PR.

File: pkg/mcs/tso/server/server.go (hunk 1 above)
Comment (JmPotato) [reply pkg/mcs/tso/server/server.go:221]: https://github.com/JmPotato/pd/blob/89a6e5816ef0df2c0c6f12b17b4b32e7bc29e25e/pkg/mcs/tso/server/server.go#L214-L217

But the subsequent logic will check whether the automatically corrected group ID matches the one we passed in, which avoids unexpected issues.

Comment (JmPotato) [reply pkg/mcs/tso/server/server.go:221]: The key point is not to eliminate the automatic correction logic itself, but to ensure that the corrected results meet the expectations set during testing.

**Review by lhy1024 — APPROVED** [review]

**Review by rleungx — APPROVED** [review]
