### PR TITLE
*: fix the gctuner tests

### LINKED ISSUE #5953: *: `make test` is failed about `cgroup`
### What did you do?

make test

### What did you expect to see?

success

### What did you see instead?

failed after https://github.com/tikv/pd/pull/5848 merged

```
--- FAIL: TestGetCgroupCPU (0.00s)
    cgroup_cpu_test.go:45: 
                Error Trace:    /home/lhy1024/pd/pkg/cgroup/cgroup_cpu_test.go:45
                Error:          Received unexpected error:
                                no cpu controller detected
                                github.com/tikv/pd/pkg/cgroup.getCgroupCPUHelper
                                        /home/lhy1024/pd/pkg/cgroup/cgroup_cpu.go:33
                                github.com/tikv/pd/pkg/cgroup.GetCgroupCPU
                                        /home/lhy1024/pd/pkg/cgroup/cgroup_cpu_linux.go:28
                                github.com/tikv/pd/pkg/cgroup.TestGetCgroupCPU
                                        /home/lhy1024/pd/pkg/cgroup/cgroup_cpu_test.go:44
                                testing.tRunner
                                        /usr/local/go/src/testing/testing.go:1446
                                runtime.goexit
                                        /usr/local/go/src/runtime/asm_amd64.s:1594
                Test:           TestGetCgroupCPU
[2023/02/09 14:11:28.732 +08:00] [WARN] [cgroup_memory.go:84] ["no cgroup memory controller detected"]
[2023/02/09 14:11:28.780 +08:00] [WARN] [cgroup_memory.go:55] ["no cgroup memory controller detected"]
[2023/02/09 14:11:28.796 +08:00] [WARN] [cgroup_memory.go:115] ["no cgroup memory controller detected"]
FAIL
coverage: 76.5% of statements
FAIL    github.com/tikv/pd/pkg/cgroup   0.184s
```
```
--- FAIL: TestFinalizer (0.01s)
    finalizer_test.go:40: 
                Error Trace:    /home/lhy1024/pd/pkg/gctuner/finalizer_test.go:40
                Error:          Not equal: 
                                expected: 1
                                actual  : 0
                Test:           TestFinalizer
[2023/02/09 14:18:20.957 +08:00] [INFO] [memory_limit_tuner.go:49] [debug.SetMemoryLimit] [limit=858993459] [ret=9223372036854775807]
[2023/02/09 14:18:21.022 +08:00] [INFO] [memory_limit_tuner.go:49] [debug.SetMemoryLimit] [limit=1181116006] [ret=858993459]
[2023/02/09 14:18:23.825 +08:00] [INFO] [tuner.go:117] ["new gctuner"] [threshold=524288000]
[2023/02/09 14:18:23.826 +08:00] [INFO] [gogc.go:43] [debug.SetGCPercent] [val=500] [result=100]
panic: Fail in goroutine after TestFinalizer has completed

goroutine 20 [running]:
testing.(*common).Fail(0xc000248680)
        /usr/local/go/src/testing/testing.go:824 +0x1a8
testing.(*common).FailNow(0xc000248680)
        /usr/local/go/src/testing/testing.go:847 +0x51
testing.(*common).Fatalf(0xc000248680, {0x93287f, 0x32}, {0x0, 0x0, 0x0})
        /usr/local/go/src/testing/testing.go:955 +0xaf
github.com/tikv/pd/pkg/gctuner.TestFinalizer.func1()
        /home/lhy1024/pd/pkg/gctuner/finalizer_test.go:35 +0x6f
github.com/tikv/pd/pkg/gctuner.finalizerHandler(0xc000216048)
        /home/lhy1024/pd/pkg/gctuner/finalizer.go:40 +0xc2
FAIL    github.com/tikv/pd/pkg/gctuner  2.954s
```

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #5953.

### What is changed and how does it work?
Enable all gctuner-related tests.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by lhy1024** [comment]
still failed
```
--- FAIL: TestTuner (1.35s)
    tuner_test.go:59: 
        	Error Trace:	/home/runner/work/pd/pd/pkg/gctuner/tuner_test.go:59
        	Error:      	Condition never satisfied
        	Test:       	TestTuner
```

File: pkg/gctuner/finalizer_test.go [hunk 1]
```diff
@@ -39,6 +38,7 @@ func TestFinalizer(t *testing.T) {
 	})
 	for i := int32(1); i <= maxCount; i++ {
 		runtime.GC()
+		time.Sleep(10 * time.Millisecond)
```
Comment (bufferflies) [inline pkg/gctuner/finalizer_test.go:41]: It maybe unstable, how about use channel or signal?

File: pkg/gctuner/tuner_test.go [hunk 2]
```diff
@@ -55,23 +54,45 @@ func TestTuner(t *testing.T) {
...
 	for i := 0; i < 100; i++ {
 		runtime.GC()
-		require.Equal(t, minGCPercent.Load(), tn.getGCPercent())
+		require.Eventually(t, func() bool { return minGCPercent.Load() == tn.getGCPercent() },
+			1*time.Second, 50*time.Microsecond)
 	}
 }
+
+func TestCalcGCPercent(t *testing.T) {
+	const gb = 1024 * 1024 * 1024
```
Comment (bufferflies) [inline pkg/gctuner/tuner_test.go:83]:
```suggestion
	const gb = units.GiB 
```

**Review by bufferflies — COMMENTED** [review]
rest LGTM

**Review by JmPotato — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]
