### PR TITLE
operator: fix panic for `WithRangeOption`

### LINKED ISSUE #10293: pd panic in WithRangeOption
## Bug Report
```

[2026/03/04 15:47:06.696 +08:00] [UNKNOWN] [log.go:92] [panic] [recover="\"invalid memory address or nil pointer dereference\""] [stack="github.com/tikv/pd/pkg/utils/logutil.LogPanic\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/utils/logutil/log.go:92\nruntime.gopanic\n\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.12.linux-amd64/src/runtime/panic.go:791\nruntime.panicmem\n\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.12.linux-amd64/src/runtime/panic.go:262\nruntime.sigpanic\n\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.12.linux-amd64/src/runtime/signal_unix.go:917\ngithub.com/tikv/pd/pkg/core.(*RegionInfo).GetStartKey\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/core/region.go:697\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeScheduler).checkJob.WithRangeOption.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/schedule/operator/operator_controller.go:849\ngithub.com/tikv/pd/pkg/schedule/operator.(*Controller).GetOpInfluence.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/schedule/operator/operator_controller.go:877\nsync.(*Map).Range\n\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.12.linux-amd64/src/sync/map.go:501\ngithub.com/tikv/pd/pkg/schedule/operator.(*Controller).GetOpInfluence\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/schedule/operator/operator_controller.go:871\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeScheduler).checkJob\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/schedule/schedulers/balance_range.go:459\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeScheduler).IsScheduleAllowed\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/schedule/schedulers/balance_range.go:423\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*ScheduleController).AllowSchedule\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/schedule/schedulers/scheduler_controller.go:545\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*Controller).runScheduler\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/schedule/schedulers/scheduler_controller.go:372"]
[2026/03/04 15:47:22.607 +08:00] [Info] [meminfo.go:213] ["use physical memory hook"] [cgroupMemorySize=9223372036854775807] [physicalMemorySize=65016676352]

```

### What did you do?
sql: distribute table t 

### What did you expect to see?
no panic
### What did you see instead?
panic
### What version of PD are you using (`pd-server -V`)?
v8.5.4

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #10293

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP APIs changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved stability of operator scheduling by adding nil-safety guards so influence calculations skip missing inputs and apply range-specific influence only when region data is available, preventing runtime errors.

* **Tests**
  * Expanded tests to cover cache invalidation, range-specific influence scenarios, and option handling with nil inputs to prevent regressions.

### CODE REVIEW

File: pkg/schedule/operator/operator_controller.go [hunk 1]
```diff
@@ -897,14 +900,22 @@ func (oc *Controller) GetOpInfluence(cluster *core.BasicCluster, ops ...OpInflue
...
+	}
 	oc.operators.Range(
 		func(_, value any) bool {
 			op := value.(*Operator)
 			if !op.CheckTimeout() && !op.CheckSuccess() {
 				region := cluster.GetRegion(op.RegionID())
-				for _, opt := range ops {
-					if !opt(region) {
-						return true
+				if region != nil {
```
Comment (JmPotato) [inline pkg/schedule/operator/operator_controller.go:911]: Duplicated `if region != nil` with line 921.

Comment (bufferflies) [reply pkg/schedule/operator/operator_controller.go:911]: good catch, done

**Review by okJiang — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]
