### PR TITLE
schedule: `isRegionHealthy` only care pending peer and down peer

### LINKED ISSUE #3896: The behavior of opt.HealthRegion is inconsistent for placement rules disable or enable
## Bug Report

image

When placement rules are disable, `isHealthRegion` will return false when the region has a learner generated by the scheduling intermediate state

When placement rules enable, `isHealthRegion` will return true when the region has a learner generated by the scheduling intermediate state

Perhaps we should also determine whether the learner meets the replica count requirement when placement rules enable.

Maybe we should only determine the down peer and pending peer, and not the learner in `isHealthRegion`

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

close #3896 

### What is changed and how it works?

The current implementation, when using only `isRegionHealthy`, unexpect schedule regions with learners when enabling placement rules.

However, in addition to `isRegionHealthy`, there is also `isReplicated`, which are often used together. When used together, it is actually okay because it will be checked in `isReplicated`.

Only when `isRegionHealthy` is used alone, such as in evict-leader, balance-leader, shuffle-leader, grant-leader and random-merge leaders, only `opt. HealthRegion`, but not `isReplicated`. There is not much difference whether it is allowed or not here.

So, to simplify the semantics and ensure consistent behavior, let `isRegionHealthy` only determine pending peer and down peer.

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

File: server/schedule/opt/healthy.go [hunk 1]
```diff
@@ -21,18 +21,14 @@ import (
...
 // IsRegionHealthy checks if a region is healthy for scheduling. It requires the
-// region does not have any down or pending peers. And when placement rules
-// feature is disabled, it requires the region does not have any learner peer.
+// region does not have any down or pending peers.
 func IsRegionHealthy(cluster Cluster, region *core.RegionInfo) bool {
 	return IsHealthyAllowPending(cluster, region) && len(region.GetPendingPeers()) == 0
 }
 
 // IsHealthyAllowPending checks if a region is healthy for scheduling.
 // Differs from IsRegionHealthy, it allows the region to have pending peers.
```
Comment (rleungx) [inline server/schedule/opt/healthy.go:30]: Prefer to rewrite the comment of this function.

Comment (lhy1024) [reply server/schedule/opt/healthy.go:30]: What would you suggest to add?

**Review by rleungx — APPROVED** [review]
