### PR TITLE
Fix data race, ref #4857

### LINKED ISSUE #4857: Data race in TestSplitPaused test
### Which jobs are failing

FAIL	github.com/tikv/pd/server/cluster	55.402s

### CI link

https://github.com/tikv/pd/runs/6188856882?check_suite_focus=true

### Reason for failure (if possible)

```shell
WARNING: DATA RACE
Write at 0x00c00241a460 by goroutine 45:
  github.com/tikv/pd/server/cluster.(*testUnsafeRecoverSuite).TestSplitPaused()
      /home/runner/work/pd/pd/server/cluster/unsafe_recovery_controller_test.go:672 +0x4cb
  runtime.call16()
      /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:701 +0x48
  reflect.Value.Call()
      /opt/hostedtoolcache/go/1.18.0/x64/src/reflect/value.go:339 +0xd7
  github.com/pingcap/check.(*suiteRunner).forkTest.func1()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/check.go:850 +0xa71
  github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/check.go:739 +0x11e

Previous read at 0x00c00241a460 by goroutine 93:
  github.com/tikv/pd/server/cluster.(*RaftCluster).GetUnsafeRecoveryController()
      /home/runner/work/pd/pd/server/cluster/cluster.go:551 +0xe4
  github.com/tikv/pd/server/cluster.(*scheduleController).AllowSchedule()
      /home/runner/work/pd/pd/server/cluster/coordinator.go:904 +0x38
  github.com/tikv/pd/server/cluster.(*coordinator).runScheduler()
      /home/runner/work/pd/pd/server/cluster/coordinator.go:802 +0x3de
  github.com/tikv/pd/server/cluster.(*coordinator).addScheduler.func2()
      /home/runner/work/pd/pd/server/cluster/coordinator.go:638 +0x47

Goroutine 45 (running) created at:
  github.com/pingcap/check.(*suiteRunner).forkCall()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/check.go:734 +0x5dd
  github.com/pingcap/check.(*suiteRunner).forkTest()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/check.go:832 +0x164
  github.com/pingcap/check.(*suiteRunner).doRun()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/check.go:666 +0x1fa
  github.com/pingcap/check.(*suiteRunner).run()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/check.go:696 +0xe5
  github.com/pingcap/check.Run()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/run.go:150 +0x49
  github.com/pingcap/check.RunAll()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/run.go:113 +0x710
  github.com/pingcap/check.TestingT()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/run.go:99 +0x646
  github.com/tikv/pd/server/cluster.Test()
      /home/runner/work/pd/pd/server/cluster/cluster_test.go:48 +0x2e
  testing.tRunner()
      /opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1486 +0x47

Goroutine 93 (running) created at:
  github.com/tikv/pd/server/cluster.(*coordinator).addScheduler()
      /home/runner/work/pd/pd/server/cluster/coordinator.go:638 +0x35e
  github.com/tikv/pd/server/cluster.(*coordinator).run()
      /home/runner/work/pd/pd/server/cluster/coordinator.go:399 +0x193a
  github.com/tikv/pd/server/cluster.(*testUnsafeRecoverSuite).TestSplitPaused()
      /home/runner/work/pd/pd/server/cluster/unsafe_recovery_controller_test.go:665 +0x2ca
  runtime.call16()
      /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:701 +0x48
  reflect.Value.Call()
      /opt/hostedtoolcache/go/1.18.0/x64/src/reflect/value.go:339 +0xd7
  github.com/pingcap/check.(*suiteRunner).forkTest.func1()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/check.go:850 +0xa71
  github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20211026125417-57bd13f7b5f0/check.go:739 +0x11e
==================
```

### PR DESCRIPTION
**Pull request by v01dstar**
Signed-off-by: v01dstar <yang.zhang@pingcap.com>

### What problem does this PR solve?

Issue Number: Close #4857 

### What is changed and how does it work?

```commit-message
Acquire reader lock while reading the unsafe recovery controller, acquire writer lock while modifying it.
```

### Check List

Tests

- Unit test

Code changes

N/A

Side effects

N/A

Related changes

- PR introduced the bug https://github.com/tikv/pd/pull/4475

### Release note

```release-note
None
```

### CODE REVIEW

File: server/cluster/unsafe_recovery_controller_test.go [hunk 1]
```diff
@@ -669,7 +669,11 @@ func (s *testUnsafeRecoverSuite) TestSplitPaused(c *C) {
 		c.Assert(cluster.PutStore(store.GetMeta()), IsNil)
 	}
 	recoveryController := newUnsafeRecoveryController(cluster)
-	cluster.unsafeRecoveryController = recoveryController
+	{
```
Comment (JmPotato) [inline server/cluster/unsafe_recovery_controller_test.go:672]: This kind of Rust-style block is not common in Go, I prefer not to write like this 😂.

Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller_test.go]: Done

**Review by rleungx — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]
