### PR TITLE
schedule: add scatter operator into OperatorController immediately

### LINKED ISSUE #4703: some operators should not be expired if they belongs same batch.
## Bug Report
There are many expired operator if I scatter 1w region in the cluster.
some log is :
`
[2022/02/16 20:16:31.001 +00:00] [INFO] [operator_controller.go:569] ["operator expired"] [region-id=15792] [lives=5.104098917s] [operator="\"scatter-region {transfer leader: store 266 to 279} (kind:leader, region:15792(5641,47), createAt:2022-02-16 20:16:25.897153267 +0000 UTC m=+533.271882638, startAt:0001-01-01 00:00:00 +0000 UTC, currentStep:0, steps:[])\""] <br>
...

[2022/02/16 20:16:31.131 +00:00] [INFO] [operator_controller.go:569] ["operator expired"] [region-id=9300] [lives=3.000965592s] [operator="\"scatter-region {mv light peer: store [279 266 174] to [257 173 197]} (kind:region,leader, region:9300(5641,47), createAt:2022-02-16 20:16:28.130684491 +0000 UTC m=+535.505413846, startAt:0001-01-01 00:00:00 +0000 UTC, currentStep:0, steps:[])\""]
`
there are 2k+ expired operators in the time(2022/02/16 20:16:31.131 ), so the progress of the scatter will failed.

the create time of the first expired scatter operator is : 2022-02-16 20:16:25.897153267.
the create time of the first expired scatter operator is:  2022-02-16 20:16:28.130684491.

the duration close to 3s.

### What did you do?
split region 1w.

### What did you expect to see?
all the operator should not be expired.
### What did you see instead?
many operators expired.

### LINKED ISSUE #4804: Enlarge the operator expiration time
## Enhancement Task
For now, the expiration threshold of an operator is 3s:
https://github.com/tikv/pd/blob/b7b785fb666544d8cba37f8f8c91fd169979702d/server/schedule/operator/operator.go#L31-L33

But in the batch scatter scene, if the size of the batch is larger, it may cause the operator to be expired since it is created one by one. Only when all operators have been created, PD try to add them to the operator execution list. See
https://github.com/tikv/pd/blob/b7b785fb666544d8cba37f8f8c91fd169979702d/server/grpc_service.go#L1255-L1263

We can enlarge it to reduce the possibility of the following situation:
origin_img_v2_68bd5dad-8da3-447c-bc77-fe03d899160g

### PR DESCRIPTION
**Pull request by CabinfeverB**
Signed-off-by: Cabinfever_B <cabinfeveroier@gmail.com>

### What problem does this PR solve?

Issue Number: Close #4703 Close #4804

### What is changed and how does it work?
After getting an operator, it is immediately added to the queue of the OperatorController.

```commit-message
```

### Check List

Tests

- Unit test
- Manual test 
> 1.split and scatter table by TiDB
> 2. TiDB BR 
image
image

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/api/region.go [hunk 1]
```diff
@@ -876,7 +875,7 @@ func (h *regionsHandler) ScatterRegions(w http.ResponseWriter, r *http.Request)
 			h.rd.JSON(w, http.StatusBadRequest, err.Error())
 			return
 		}
-		ops, failures, err = rc.GetRegionScatter().ScatterRegionsByRange(startKey, endKey, group, retryLimit)
+		opsCount, failures, err = rc.GetRegionScatter().ScatterRegionsByRange(startKey, endKey, group, retryLimit)
```
Comment (bufferflies) [inline server/api/region.go:878]: how about return the success percentage directly? I do not see any where use the failures map?

File: server/schedule/operator/create_operator.go [hunk 2]
```diff
@@ -217,7 +218,7 @@ func CreateScatterRegionOperator(desc string, ci ClusterInformer, origin *core.R
 		EnableLightWeight().
 		// EnableForceTargetLeader in order to ignore the leader schedule limit
 		EnableForceTargetLeader().
-		Build(0)
+		Build(OpAdmin)
```
Comment (bufferflies) [inline server/schedule/operator/create_operator.go:221]: maybe expose one param to set OpKind is better?

File: server/schedule/operator/create_operator.go [hunk 3]
```diff
@@ -16,9 +16,10 @@ package operator
 
 import (
 	"fmt"
-	"github.com/tikv/pd/pkg/logutil"
 	"math/rand"
 
+	"github.com/tikv/pd/pkg/logutil"
+
```
Comment (nolouch) [inline server/schedule/operator/create_operator.go:22]: remove blank line.

File: server/schedule/operator/create_operator.go [hunk 4]
```diff
@@ -217,7 +218,7 @@ func CreateScatterRegionOperator(desc string, ci ClusterInformer, origin *core.R
 		EnableLightWeight().
 		// EnableForceTargetLeader in order to ignore the leader schedule limit
 		EnableForceTargetLeader().
-		Build(0)
```
Comment (nolouch) [inline server/schedule/operator/create_operator.go:220]: 0 means `admin`?

File: server/schedule/region_scatterer.go [hunk 5]
```diff
@@ -238,7 +240,12 @@ func (r *RegionScatterer) scatterRegions(regions map[uint64]*core.RegionInfo, fa
 				continue
 			}
 			if op != nil {
-				ops = append(ops, op)
+				if ok := r.opController.AddOperator(op); !ok {
```
Comment (nolouch) [inline server/schedule/region_scatterer.go:243]: Maybe we can enlarge the expiration time for the scatter region? Do we test it with this change?

File: server/schedule/operator/create_operator.go (hunk 2 above)
Comment (CabinfeverB) [reply server/schedule/operator/create_operator.go:221]: We can regard all scatter operator as admin type in the current scenarios.

File: server/api/region.go (hunk 1 above)
Comment (CabinfeverB) [reply server/api/region.go:878]: In fact, because of the retry mechanism， we need a map in ScatterRegions for count. we can reserve this map.

File: server/schedule/operator/create_operator.go (hunk 4 above)
Comment (CabinfeverB) [reply server/schedule/operator/create_operator.go:220]: 0 does not represent any type

File: server/schedule/region_scatterer.go (hunk 5 above)
Comment (CabinfeverB) [reply server/schedule/region_scatterer.go:243]: Enlarging the expiration time is s an optional solution. But I think it could affect other scheduling operations in a large cluster, so I chose this scheme which would only affect Scatter. I will add a test for my solution soon.

File: pkg/mock/mockcluster/mockcluster.go [hunk 6]
```diff
@@ -345,6 +345,13 @@ func (mc *Cluster) AddLeaderRegion(regionID uint64, leaderStoreID uint64, otherP
 	return region
 }
 
+// AddLightLeaderRegion adds region with specified leader and followers.
```
Comment (rleungx) [inline pkg/mock/mockcluster/mockcluster.go:348]: What is a light leader region?

File: server/schedule/region_scatterer_test.go [hunk 7]
```diff
@@ -433,16 +433,15 @@ func TestScatterForManyRegion(t *testing.T) {
 
 	scatterer := NewRegionScatterer(ctx, tc, oc)
 	regions := make(map[uint64]*core.RegionInfo)
-	for i := 1; i <= 15000; i++ {
-		regions[uint64(i)] = tc.AddLightLeaderRegion(uint64(i), 1, 2, 3)
+	for i := 1; i <= 150; i++ {
```
Comment (rleungx) [inline server/schedule/region_scatterer_test.go:436]: Why change it?

Comment (CabinfeverB) [reply server/schedule/region_scatterer_test.go]: for CI test, had change it back to 15000

**Review by rleungx — APPROVED** [review]

File: Makefile [hunk 8]
```diff
@@ -214,7 +214,7 @@ basic-test: install-tools
 
 ci-test-job: install-tools dashboard-ui
 	@$(FAILPOINT_ENABLE)
-	CGO_ENABLED=1 go test -tags deadlock -race -covermode=atomic -coverprofile=covprofile -coverpkg=./... $(shell ./scripts/ci-subtask.sh $(JOB_COUNT) $(JOB_INDEX))
+	CGO_ENABLED=1 go test -timeout=15m -tags deadlock -race -covermode=atomic -coverprofile=covprofile -coverpkg=./... $(shell ./scripts/ci-subtask.sh $(JOB_COUNT) $(JOB_INDEX))
```
Comment (bufferflies) [inline Makefile:217]: what's the default value of the timeout?

Comment (CabinfeverB) [reply Makefile:217]: 10m

**Comment by bufferflies** [comment]
BTW， Do you have any integration test? If have, please upload the result?

**Review by bufferflies — COMMENTED** [review]
rest LGTM

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by CabinfeverB** [comment]
> BTW， Do you have any integration test with br? If have, please upload the result?

update
