### PR TITLE
client: fix scheme when tls config not match

### LINKED ISSUE #7900: The address of `ServiceClient `does not hold HTTP scheme info when tls config does not match
## Bug Report

h2mMPOXgcl

### LINKED ISSUE #7902: Panic when starting a cse TiDB with TLS config
### What did you do?

Start a cse TiDB with TLS config.

### What did you expect to see?

Everything is ok.

### What did you see instead?
```
start tidb-server ...
/tidb-server --store=tikv --path=serverless-cluster-pd.tidb-serverless.svc:2379 --config=/etc/tidb/tidb.toml --keyspace-activate

config file /etc/tidb/tidb.toml contained invalid configuration options: run-auto-analyze, server-memory-quota; check TiDB manual to make sure this option has not been deprecated and removed from your TiDB version if the option does not appear to be a typo
[2024/03/08 03:20:10.474 +00:00] [INFO] [memory.go:49] ["env NAMESPACE, POD_NAME, NODE_IP not set, skip init memory limits"]
[2024/03/08 03:20:10.474 +00:00] [INFO] [main.go:422] ["serverless cluster info loading..."] [keyspace=4NLo2vmPo3mAFtb]
[2024/03/08 03:20:11.475 +00:00] [WARN] [pd_service_discovery.go:861] ["[pd] failed to get cluster id"] [url=http://serverless-cluster-pd.tidb-serverless.svc:2379/] [error="[PD:client:ErrClientGetMember]error:rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup serverless-cluster-pd.tidb-serverless.svc: i/o timeout\" target:serverless-cluster-pd.tidb-serverless.svc:2379 status:TRANSIENT_FAILURE: error:rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup serverless-cluster-pd.tidb-serverless.svc: i/o timeout\" target:serverless-cluster-pd.tidb-serverless.svc:2379 status:TRANSIENT_FAILURE"]
[2024/03/08 03:20:11.475 +00:00] [WARN] [pd_service_discovery.go:861] ["[pd] failed to get cluster id"] [url=http://serverless-cluster-pd.tidb-serverless.svc:2379/] [error="[PD:client:ErrClientGetMember]error:rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup serverless-cluster-pd.tidb-serverless.svc: i/o timeout\" target:serverless-cluster-pd.tidb-serverless.svc:2379 status:TRANSIENT_FAILURE: error:rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup serverless-cluster-pd.tidb-serverless.svc: i/o timeout\" target:serverless-cluster-pd.tidb-serverless.svc:2379 status:TRANSIENT_FAILURE"]
[2024/03/08 03:20:12.475 +00:00] [WARN] [pd_service_discovery.go:861] ["[pd] failed to get cluster id"] [url=http://serverless-cluster-pd.tidb-serverless.svc:2379/] [error="[PD:client:ErrClientGetMember]error:rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup serverless-cluster-pd.tidb-serverless.svc: i/o timeout\" target:serverless-cluster-pd.tidb-serverless.svc:2379 status:TRANSIENT_FAILURE: error:rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup serverless-cluster-pd.tidb-serverless.svc: i/o timeout\" target:serverless-cluster-pd.tidb-serverless.svc:2379 status:TRANSIENT_FAILURE"]
[2024/03/08 03:20:13.479 +00:00] [INFO] [pd_service_discovery.go:1016] ["[pd] update member urls"] [old-urls="[http://serverless-cluster-pd.tidb-serverless.svc:2379/]"] [new-urls="[http://serverless-cluster-pd-0.serverless-cluster-pd-peer.tidb-serverless.svc:2379,http://serverless-cluster-pd-1.serverless-cluster-pd-peer.tidb-serverless.svc:2379,http://serverless-cluster-pd-2.serverless-cluster-pd-peer.tidb-serverless.svc:2379]"]
[2024/03/08 03:20:13.480 +00:00] [INFO] [pd_service_discovery.go:1043] ["[pd] switch leader"] [new-leader=http://serverless-cluster-pd-0.serverless-cluster-pd-peer.tidb-serverless.svc:2379/] [old-leader=]
[2024/03/08 03:20:13.480 +00:00] [INFO] [pd_service_discovery.go:525] ["[pd] init cluster id"] [cluster-id=7187976276065784319]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x262728c]

goroutine 1 [running]:
[github.com/tikv/pd/client.(*client).LoadKeyspace](http://github.com/tikv/pd/client.(*client).LoadKeyspace)(0x4000ff2bb0, {0x6257fc0, 0x9152080}, {0x400007602e, 0xf})
	/go/cache/[github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/keyspace_client.go:59](http://github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/keyspace_client.go:59) +0x28c
[github.com/tikv/pd/client.(*client).loadKeyspaceMeta](http://github.com/tikv/pd/client.(*client).loadKeyspaceMeta)(0x4000ff2bb0, {0x400007602e?, 0x4000c3d8b0?})
	/go/cache/[github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:558](http://github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:558) +0x3c
[github.com/tikv/pd/client.(*client).initRetry](http://github.com/tikv/pd/client.(*client).initRetry)(0x4000ff2bb0, 0x40013bf278, {0x400007602e, 0xf})
	/go/cache/[github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:545](http://github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:545) +0xbc
[github.com/tikv/pd/client.newClientWithKeyspaceName.func1()](http://github.com/tikv/pd/client.newClientWithKeyspaceName.func1())
	/go/cache/[github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:514](http://github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:514) +0x44
[github.com/tikv/pd/client.(*pdServiceDiscovery).Init(0x4000ab8780)](http://github.com/tikv/pd/client.(*pdServiceDiscovery).Init(0x4000ab8780))
	/go/cache/[github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/pd_service_discovery.go:530](http://github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/pd_service_discovery.go:530) +0x12c
[github.com/tikv/pd/client.(*client).setup(0x4000ff2bb0)](http://github.com/tikv/pd/client.(*client).setup(0x4000ff2bb0))
	/go/cache/[github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:573](http://github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:573) +0x40
[github.com/tikv/pd/client.newClientWithKeyspaceName](http://github.com/tikv/pd/client.newClientWithKeyspaceName)({0x6257f88, 0x9152080}, {0x400007602e, 0xf}, {0x400106bff0, 0x1, 0x1}, {{0x4000f8fa00, 0x18}, {0x4000f8fa40, ...}, ...}, ...)
	/go/cache/[github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:526](http://github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:526) +0x36c
[github.com/tikv/pd/client.NewClientWithAPIContext](http://github.com/tikv/pd/client.NewClientWithAPIContext)({0x6257f88, 0x9152080}, {0x6233050, 0x4001072000}, {0x400106bff0, 0x1, 0x1}, {{0x4000f8fa00, 0x18}, {0x4000f8fa40, ...}, ...}, ...)
	/go/cache/[github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:475](http://github.com/tikv/pd/client@v0.0.0-20240301074832-6cb89172ce73/client.go:475) +0xc4
main.getServerlessInfo()
	/go/src/[github.com/pingcap/tidb/tidb-server/main.go:427](http://github.com/pingcap/tidb/tidb-server/main.go:427) +0x384
main.main()
	/go/src/[github.com/pingcap/tidb/tidb-server/main.go:266](http://github.com/pingcap/tidb/tidb-server/main.go:266) +0x3b0
```

The reason is that we use a sync map to manage the connection between TiDB and PD. If TiDB has TLS config and PD uses HTTP schema, the pd client will trim the HTTP prefix when reading the key from the map. But when writing to the map, the key has a prefix. So it will read nothing about connection.

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by CabinfeverB**
### What problem does this PR solve?

Issue Number: Close #7900 close #7902

### What is changed and how does it work?
1. replace `httpAddr` and `addr` with `url `field which includes scheme info.
2. modify related fields and function name which mix url and address.
3. pick the URL which matches TLS config from member resp.

```commit-message
```

### Check List

Tests

- Unit test

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: client/pd_service_discovery.go [hunk 1]
```diff
@@ -158,34 +156,15 @@ type pdServiceClient struct {
...
-		} else {
-			httpAddress = fmt.Sprintf("%s://%s", httpsScheme, addr)
-		}
-	}
-
+// NOTE: In the current implementation, the address passed in is bound to have an http scheme,
+// because it is processed in `newPDServiceDiscovery`, and the url returned by etcd member is its own.
+// When testing, the address is also bound to have an http scheme.
+func newPDServiceClient(addr, leaderAddr string, conn *grpc.ClientConn, isLeader bool) ServiceClient {
 	cli := &pdServiceClient{
```
Comment (HuSharp) [inline client/pd_service_discovery.go:163]: Do we still need `GetHTTPAddress` function?
[in line ](https://github.com/tikv/pd/pull/7901/files#diff-76173cab783101dc7dfff41befacf2d2a1339ea83eb57ca2b88e6508180cd149R184)

File: client/pd_service_discovery.go [hunk 2]
```diff
@@ -124,10 +124,8 @@ type ServiceDiscovery interface {
 
 // ServiceClient is an interface that defines a set of operations for a raw PD gRPC client to specific PD server.
 type ServiceClient interface {
-	// GetAddress returns the address information of the PD server.
+	// GetAddress returns the address with HTTP scheme of the PD server.
```
Comment (HuSharp) [inline client/pd_service_discovery.go:127]: seems like will return https scheme?

File: client/pd_service_discovery.go [hunk 3]
```diff
@@ -158,34 +156,15 @@ type pdServiceClient struct {
...
-			addr = strings.TrimPrefix(addr, httpScheme)
-			httpAddress = fmt.Sprintf("%s%s", httpsScheme, addr)
-		} else {
-			httpAddress = fmt.Sprintf("%s://%s", httpsScheme, addr)
-		}
-	}
-
+// NOTE: In the current implementation, the address passed in is bound to have an http scheme,
+// because it is processed in `newPDServiceDiscovery`, and the url returned by etcd member is its own.
+// When testing, the address is also bound to have an http scheme.
```
Comment (HuSharp) [inline client/pd_service_discovery.go:161]:
```suggestion
// When testing, the address is also bound to have a http scheme.
```

File: client/pd_service_discovery.go (hunk 2 above)
Comment (iosmanthus) [reply client/pd_service_discovery.go:127]: It should return addresses without the scheme.

File: client/pd_service_discovery.go [hunk 4]
```diff
@@ -1150,15 +1121,28 @@ func (c *pdServiceDiscovery) GetOrCreateGRPCConn(addr string) (*grpc.ClientConn,
...
+
+func addrToUrl(addr string, tlsCfg *tls.Config) string {
+	if tlsCfg == nil {
+		if strings.HasPrefix(addr, httpsScheme) {
+			addr = fmt.Sprintf("%s%s", httpScheme, strings.TrimPrefix(addr, httpsScheme))
+		} else if !strings.HasPrefix(addr, httpScheme) {
+			addr = fmt.Sprintf("%s%s", httpScheme, addr)
+		}
+	} else {
+		if strings.HasPrefix(addr, httpScheme) {
```
Comment (rleungx) [inline client/pd_service_discovery.go:1141]: Shall we according to the etcd member URL change the prefix instead of tlsCfg?

Comment (CabinfeverB) [reply client/pd_service_discovery.go:1141]: This is only used for `url.Parse`. If we don't add scheme, it will return error.
If etcd member URL is not same as this, the connection map will add a new KV pair.

**Review by HuSharp — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

File: client/pd_service_discovery.go [hunk 5]
```diff
@@ -1145,20 +1116,47 @@ func (c *pdServiceDiscovery) switchTSOAllocatorLeaders(allocatorMap map[string]*
...
-// GetOrCreateGRPCConn returns the corresponding grpc client connection of the given addr
-func (c *pdServiceDiscovery) GetOrCreateGRPCConn(addr string) (*grpc.ClientConn, error) {
-	return grpcutil.GetOrCreateGRPCConn(c.ctx, &c.clientConns, addr, c.tlsCfg, c.option.gRPCDialOptions...)
+// GetOrCreateGRPCConn returns the corresponding grpc client connection of the given URL.
+func (c *pdServiceDiscovery) GetOrCreateGRPCConn(url string) (*grpc.ClientConn, error) {
+	return grpcutil.GetOrCreateGRPCConn(c.ctx, &c.clientConns, url, c.tlsCfg, c.option.gRPCDialOptions...)
 }
 
-func addrsToUrls(addrs []string) []string {
+func addrsToUrls(addrs []string, tlsCfg *tls.Config) []string {
```
Comment (rleungx) [inline client/pd_service_discovery.go:1124]:
```suggestion
func addrsToURLs(addrs []string, tlsCfg *tls.Config) []string {
```

File: client/pd_service_discovery.go [hunk 6]
```diff
@@ -1145,20 +1116,47 @@ func (c *pdServiceDiscovery) switchTSOAllocatorLeaders(allocatorMap map[string]*
...
+	for _, url := range urls {
+		if tlsCfg != nil && strings.HasPrefix(url, httpsScheme) {
+			return url
+		}
+		if tlsCfg == nil && strings.HasPrefix(url, httpScheme) {
+			return url
+		}
+	}
+	log.Warn("[pd] no matched url found", zap.Strings("urls", urls), zap.Bool("tls-enabled", tlsCfg != nil))
+	return urls[0]
```
Comment (rleungx) [inline client/pd_service_discovery.go:1161]: Do we need to change the URL according to the tlscfg instead of return [0]?

Comment (CabinfeverB) [reply client/pd_service_discovery.go]: Good catch.
