### PR TITLE
client: use Tracer from Span and fix unfinished `span`

### LINKED ISSUE #7861: PD Client don't record Span of `opentracing`
### What did you do?
image

### PR DESCRIPTION
**Pull request by CabinfeverB**
### What problem does this PR solve?

Issue Number: close #7861

### What is changed and how does it work?
1. using Tracer from Span not global tracer
2. finish Span for GetLocalTSAsync

```commit-message
```

### Check List

Tests

- Unit test
- manual test
image

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/integrations/client/client_test.go [hunk 1]
```diff
@@ -469,6 +471,22 @@ func TestGlobalAndLocalTSO(t *testing.T) {
...
+	spans := recorder.GetSpans()
+	re.Len(spans, 1)
+	_, _, err = future.Wait()
+	re.Error(err)
+	spans = recorder.GetSpans()
+	re.Len(spans, 1)
+	_, _, err = cli.GetTS(ctx)
+	re.NoError(err)
+	spans = recorder.GetSpans()
+	re.Len(spans, 3)
```
Comment (rleungx) [inline tests/integrations/client/client_test.go:488]: There are two GetLocalTSAsync, is it expected?

**Review by rleungx — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Comment by JmPotato** [comment]
@CabinfeverB Please resolve the conflicts.
