### PR TITLE
tests: make TestExpireRegionCache stable

### LINKED ISSUE #6363: TestExpireRegionCache isn't stable
### Which jobs are failing
--- FAIL: TestExpireRegionCache (0.07s)
    cache_test.go:95: 
        	Error Trace:	/home/runner/work/pd/pd/pkg/cache/cache_test.go:95
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestExpireRegionCache

### CI link
https://github.com/tikv/pd/actions/runs/4777183939/jobs/8492711583?pr=6362

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #6363

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Manual test
```
for i in {1..500}
do
    go test -timeout 30s -run ^TestExpireRegionCache$ github.com/tikv/pd/pkg/cache
    go clean -testcache
done
```
Before this pr
image

After this pr
image
		

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

File: pkg/cache/cache_test.go [hunk 1]
```diff
@@ -92,7 +93,10 @@ func TestExpireRegionCache(t *testing.T) {
 	re.True(ok)
 	re.Equal(3.0, value)
 
-	re.Equal(2, cache.Len())
```
Comment (rleungx) [inline pkg/cache/cache_test.go:95]: We have slept 20ms, why is it not expired?

Comment (lhy1024) [reply pkg/cache/cache_test.go:95]: maybe dogc goroutine did not run in time. I try to run test without this pr. I add a log before `re.Equal` and we can see gc is slow than `re.Equal`
```
[2023/08/31 14:38:07.447 +08:00] [INFO] [cache_test.go:98] [count] [cache-len=3]
[2023/08/31 14:38:07.448 +08:00] [INFO] [ttl.go:165] ["TTL GC items"] [count=1]
    cache_test.go:99: 
        	Error Trace:	/home/lhy1024/pd/pkg/cache/cache_test.go:99
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestExpireRegionCache
--- FAIL: TestExpireRegionCache (0.07s)
FAIL
FAIL	github.com/tikv/pd/pkg/cache	0.075s
FAIL
```

**Review by rleungx — APPROVED** [review]
