### PR TITLE
client/retry: only return the latest error in backoffer

### LINKED ISSUE #8142: add index or lightning or import into failed with error “Error 1105 (HY000): request pd http api failed with status: '503 Service Unavailable” when kill pd leader
### What did you do?
1、add index
2、kill pd leader

### What did you expect to see?
add index can success

### What did you see instead?
add index failed with error “Error 1105 (HY000): request pd http api failed with status: '503 Service Unavailable” 

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: 1679dbca25b3483d1375c7e747da27e99ad77360
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time:  2024-04-30 11:39:01

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: ref #8142.

### What is changed and how does it work?

```commit-message
Due to the return of historical errors causing the client's retry logic to fail,
and since we currently do not need to obtain all errors during retries, this PR
removes `multierr` from backoffer and add tests to ensure the correctness of the retry logic.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
Fix the bug where HTTP client retry logic is ineffective.
```

### CODE REVIEW

**Review by HuSharp — APPROVED** [review]

File: client/retry/backoff.go [hunk 1]
```diff
@@ -148,18 +137,25 @@ func InitialBackoffer(base, max, total time.Duration, opts ...Option) *Backoffer
 	return bo
 }
 
-// SetRetryableChecker sets the retryable checker.
-func (bo *Backoffer) SetRetryableChecker(checker func(err error) bool) {
+// SetRetryableChecker sets the retryable checker, `overwrite` flag is used to indicate whether to overwrite the existing checker.
+func (bo *Backoffer) SetRetryableChecker(checker func(err error) bool, overwrite bool) {
```
Comment (okJiang) [inline client/retry/backoff.go:141]: Isn't `overwrite` over-designed? Because now there is only one call to

File: client/retry/backoff.go [hunk 2]
```diff
@@ -69,18 +66,13 @@ func (bo *Backoffer) Exec(
...
 	)
 	fnName := getFunctionName(fn)
 	for {
 		err = fn()
 		bo.attempt++
-		if bo.attempt < maxRecordErrorCount {
-			// multierr.Append will ignore nil error.
-			allErrors = multierr.Append(allErrors, err)
-		}
 		if !bo.isRetryable(err) {
```
Comment (okJiang) [inline client/retry/backoff.go:76]: I think don't need to put `err != nil` into retryable checker function. Just put it before calling `isRetryable` is enough. Each error need to be check `err != nil`.

**Review by okJiang — APPROVED** [review]

**Review by rleungx — APPROVED** [review]
