### PR TITLE
server/grpc_service: make update gc_safepoint concurrently safe

### LINKED ISSUE #5018: server/grpc_service: updateGCSafepoint may lost the max safepoint
## Bug Report
In the function `UpdateGCSafePoint`, if another thread receive and update the safepoint after `LoadGCSafePoint` and before `SaveGCSafePoint`, we may miss the max safepoint . 
[https://github.com/tikv/pd/blob/efb4c9f687620afd0654296bfcd932515fce5a46/server/grpc_service.go#L1339-L1349](https://github.com/tikv/pd/blob/efb4c9f687620afd0654296bfcd932515fce5a46/server/grpc_service.go#L1339-L1349)
### What did you do?
For example:
- client1 LoadGCSafePoint (value=5)
- client2 LoadGCSafePoint (value=5)
- client 2 SaveGCSafePoint with value = 10 since it is bigger than oldValue 5.
- client 1 SaveGCSafePoint with value=7 since it is bigger than the oldValue 5 it get.

Here the max safepoint 10 was lost.

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: shirly <AndreMouche@126.com>

### What problem does this PR solve?

Issue Number: Close #5018 

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/grpc_service.go [hunk 1]
```diff
@@ -1335,22 +1334,17 @@ func (s *GrpcServer) UpdateGCSafePoint(ctx context.Context, request *pdpb.Update
...
-	// Only save the safe point if it's greater than the previous one
+	// safepoint updated
 	if newSafePoint > oldSafePoint {
-		if err := storage.SaveGCSafePoint(newSafePoint); err != nil {
-			return nil, err
-		}
 		log.Info("updated gc safe point",
 			zap.Uint64("safe-point", newSafePoint))
-	} else if newSafePoint < oldSafePoint {
+	} else {
```
Comment (bufferflies) [inline server/grpc_service.go:1347]: what does it do if newSafePoint is eqaul to oldSafePoint?

File: server/server.go [hunk 2]
```diff
@@ -39,6 +39,7 @@ import (
 	"github.com/pingcap/kvproto/pkg/pdpb"
 	"github.com/pingcap/log"
 	"github.com/pingcap/sysutil"
+	gc_server "github.com/tikv/pd/cmd/gc/server"
```
Comment (nolouch) [inline server/server.go:42]: I think server do not relay on `cmd` package, maybe move to `pkg`; see https://github.com/golang-standards/project-layout/blob/master/README_zh.md

File: server/grpc_service.go (hunk 1 above)
Comment (AndreMouche) [reply server/grpc_service.go:1347]: nothing

File: server/server.go (hunk 2 above)
Comment (AndreMouche) [reply server/server.go:42]: ok~

File: server/grpc_service.go [hunk 3]
```diff
@@ -1335,22 +1334,17 @@ func (s *GrpcServer) UpdateGCSafePoint(ctx context.Context, request *pdpb.Update
...
 
-	newSafePoint := request.SafePoint
-
-	// Only save the safe point if it's greater than the previous one
+	// safepoint updated
 	if newSafePoint > oldSafePoint {
-		if err := storage.SaveGCSafePoint(newSafePoint); err != nil {
-			return nil, err
-		}
 		log.Info("updated gc safe point",
```
Comment (rleungx) [inline server/grpc_service.go:1345]: How about putting the log into where the safe point is being updated.

Comment (AndreMouche) [reply server/grpc_service.go:1345]: I try to keep the origin logic Because  I was considering  that if someone or someplace grep the log with the source file's name

File: server/gc/safepoint_test.go [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+package gc
+
+import (
+	"sync"
+	"testing"
+
+	. "github.com/pingcap/check"
```
Comment (JmPotato) [inline server/gc/safepoint_test.go:21]: What about using testify here? Just like https://github.com/tikv/pd/pull/5061.

**Review by bufferflies — COMMENTED** [review]
rest LGTM

File: server/gc/safepoint_test.go [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+	"github.com/tikv/pd/server/storage/endpoint"
+	"github.com/tikv/pd/server/storage/kv"
+)
+
+func newGCStorage() endpoint.GCSafePointStorage {
+	return endpoint.NewStorageEndpoint(kv.NewMemoryKV(), nil)
+}
+
+func TestGCSafePointUpdateSequentially(t *testing.T) {
+	gcSafePointManager := newGCSafePointManager(newGCStorage())
```
Comment (JmPotato) [inline server/gc/safepoint_test.go:31]: We could create a `re := require.New(t)` here and use `re.NoError(err)` later. Just like:

https://github.com/tikv/pd/blob/3362ce2de17945b5ee5466d0b7a3ce00f2420682/pkg/apiutil/apiutil_test.go#L27-L43

File: server/gc/safepoint_test.go [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+	require.NoError(t, err)
+	require.Equal(t, oldSafePoint, safePoint)
+	curSafePoint, err = gcSafePointManager.LoadGCSafePoint()
+	require.NoError(t, err)
+	// current safePoint should not change since the update value was smaller
+	require.Equal(t, curSafePoint, safePoint)
+}
+
+func TestGCSafePointUpdateCurrently(t *testing.T) {
+	gcSafePointManager := newGCSafePointManager(newGCStorage())
```
Comment (JmPotato) [inline server/gc/safepoint_test.go:59]: Ditto.

File: server/gc/safepoint_test.go [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+}
+
+func TestGCSafePointUpdateSequentially(t *testing.T) {
+	gcSafePointManager := newGCSafePointManager(newGCStorage())
+	curSafePoint := uint64(0)
+	// update gc safePoint with asc value.
+	for id := 10; id < 20; id++ {
+		safePoint, err := gcSafePointManager.LoadGCSafePoint()
+		require.NoError(t, err)
+		require.Equal(t, safePoint, curSafePoint)
```
Comment (JmPotato) [inline server/gc/safepoint_test.go:37]: This function's signature is `func Equal(expected interface{}, actual interface{})`, so the expected value should be placed on the first argument.

File: server/gc/safepoint_test.go [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+	"github.com/tikv/pd/server/storage/kv"
+)
+
+func newGCStorage() endpoint.GCSafePointStorage {
+	return endpoint.NewStorageEndpoint(kv.NewMemoryKV(), nil)
+}
+
+func TestGCSafePointUpdateSequentially(t *testing.T) {
+	gcSafePointManager := newGCSafePointManager(newGCStorage())
+	req := require.New(t)
```
Comment (JmPotato) [inline server/gc/safepoint_test.go:32]: Better be consistent with other packages' styles.

```suggestion
	re := require.New(t)
```

File: server/gc/safepoint_test.go [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+	req.NoError(err)
+	// current safePoint should not change since the update value was smaller
+	req.Equal(safePoint, curSafePoint)
+}
+
+func TestGCSafePointUpdateCurrently(t *testing.T) {
+	gcSafePointManager := newGCSafePointManager(newGCStorage())
+	maxSafePoint := uint64(1000)
+	wg := sync.WaitGroup{}
+	req := require.New(t)
```
Comment (JmPotato) [inline server/gc/safepoint_test.go:63]: Ditto.

**Review by nolouch — APPROVED** [review]

File: server/grpc_service.go [hunk 10]
```diff
@@ -1335,19 +1334,13 @@ func (s *GrpcServer) UpdateGCSafePoint(ctx context.Context, request *pdpb.Update
 		return &pdpb.UpdateGCSafePointResponse{Header: s.notBootstrappedHeader()}, nil
 	}
 
-	var storage endpoint.GCSafePointStorage = s.storage
-	oldSafePoint, err := storage.LoadGCSafePoint()
+	newSafePoint := request.SafePoint
```
Comment (JmPotato) [inline server/grpc_service.go:1337]:
```suggestion
	newSafePoint := request.GetSafePoint()
```

**Review by JmPotato — COMMENTED** [review]
The rest LGTM.

**Review by JmPotato — APPROVED** [review]
