### PR TITLE
config: Enlarge max request bytes

### LINKED ISSUE #5008: [Online Recovery] Unsafe online recovery failed
### What did you do?
1、down two tikv
2、execute online unsafe recovery

### What did you expect to see?
Unsafe recovery success

### What did you see instead?
/pd-ctl unsafe remove-failed-stores show
[
  {
    "info": "Unsafe recovery enters collect report stage: failed stores 1, 4",
    "time": "2022-05-21 04:13:49.636"
  },
  {
    "info": "Unsafe recovery enters exit force leader stage",
    "time": "2022-05-21 04:23:54.381",
    "details": [
      "Exceeds timeout 2022-05-21 04:23:49.636075838 +0000 UTC m=+4635.068243220"
    ]
  },
  {
    "info": "Unsafe recovery failed: Exceeds timeout 2022-05-21 04:24:34.381171754 +0000 UTC m=+4679.813339138",
    "time": "2022-05-21 04:24:34.385"
  }
]

### What version of PD are you using (`pd-server -V`)?
./tikv-server -V
 TiKV 
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   1fb8980ccab9ff40c1adc206df52952dab8e8ad8
Git Commit Branch: heads/refs/tags/v6.1.0
UTC Build Time:    2022-05-20 06:30:12
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2022-05-21T12:01:00.468+0800	INFO	k8s/client.go:107	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./pd-server -V
 Release Version: v6.1.0
Edition: Community
Git Commit Hash: aafc77dd7c583a37b9b27821beb59594e1f7ccce
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time:  2022-05-20 06:29:40

### PR DESCRIPTION
**Pull request by Connor1996**
### What problem does this PR solve?

Issue Number: Close #5008 

Too small max request bytes make grpc always fail.
tJwb4zTI7h

### What is changed and how does it work?

Assume that each peer report occupies about 500KB at most, then 150MB can fit for store reports that have 30w regions information. 

```commit-message
Enlarge max request bytes to fit the large store report for unsafe recovery
```

### Check List

Tests

- No code

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
None
```

### CODE REVIEW

File: server/config/config.go [hunk 1]
```diff
@@ -204,7 +204,7 @@ const (
 	defaultCompactionMode          = "periodic"
 	defaultAutoCompactionRetention = "1h"
 	defaultQuotaBackendBytes       = typeutil.ByteSize(8 * 1024 * 1024 * 1024) // 8GB
-	defaultMaxRequestBytes         = uint(1.5 * 1024 * 1024)                   // 1.5MB
+	defaultMaxRequestBytes         = uint(150 * 1024 * 1024)                   // 150MB
```
Comment (rleungx) [inline server/config/config.go:207]: Please add a comment about why we choose the value.

Comment (Connor1996) [reply server/config/config.go]: done

**Review by rleungx — APPROVED** [review]
Basically, LGTM. But this value will print a warning log when starting etcd. It's better to test if this value does not affect the other normal gRPC request latency.
