### PR TITLE
rc: fix group change will meet data race

### LINKED ISSUE #8267: rc: group change will meet data race
## Bug Report

```
==================
WARNING: DATA RACE
Write at 0x00c0014f5b30 by goroutine 513:
  github.com/tikv/pd/pkg/mcs/resourcemanager/server.(*Manager).Init()
      /data/nvme0n1/husharp/proj/pd/pkg/mcs/resourcemanager/server/manager.go:132 +0x5d1
  github.com/tikv/pd/pkg/mcs/resourcemanager/server.(*Manager).Init-fm()
      <autogenerated>:1 +0x47
  github.com/tikv/pd/server.(*Server).campaignLeader()
      /data/nvme0n1/husharp/proj/pd/server/server.go:1772 +0x1742
  github.com/tikv/pd/server.(*Server).leaderLoop()
      /data/nvme0n1/husharp/proj/pd/server/server.go:1699 +0x1444
  github.com/tikv/pd/server.(*Server).startServerLoop.func1()
      /data/nvme0n1/husharp/proj/pd/server/server.go:658 +0x33

Previous read at 0x00c0014f5b30 by goroutine 29900015:
  github.com/tikv/pd/pkg/mcs/resourcemanager/server.(*Manager).backgroundMetricsFlush()
      /data/nvme0n1/husharp/proj/pd/pkg/mcs/resourcemanager/server/manager.go:480 +0x12ed
  github.com/tikv/pd/pkg/mcs/resourcemanager/server.(*Manager).Init.func4()
      /data/nvme0n1/husharp/proj/pd/pkg/mcs/resourcemanager/server/manager.go:180 +0x4f

```

### What did you do?
run pd-server

### What did you expect to see?
no data race

### What did you see instead?
meet data race

### What version of PD are you using (`pd-server -V`)?
494c0e956b622a9b3cec8b98180b942cbbe5a0f3

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Close #8267

### What is changed and how does it work?

Because there is no happens-before guarantee for different goroutine, maybe meet memory reordering

```commit-message
```

### Check List

Tests

- No code(Cannot test it for memory ordering :( )

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/mcs/resourcemanager/server/manager.go [hunk 1]
```diff
@@ -129,7 +129,9 @@ func (m *Manager) Init(ctx context.Context) error {
 		return err
 	}
 	// Load resource group meta info from storage.
+	m.Lock()
```
Comment (lhy1024) [inline pkg/mcs/resourcemanager/server/manager.go:132]: Do it need to be picked to other branches?

**Review by lhy1024 — APPROVED** [review]

File: pkg/mcs/resourcemanager/server/manager.go (hunk 1 above)
Comment (HuSharp) [reply pkg/mcs/resourcemanager/server/manager.go:132]: I think so

**Review by rleungx — APPROVED** [review]

File: pkg/mcs/resourcemanager/server/manager.go [hunk 2]
```diff
@@ -129,7 +129,9 @@ func (m *Manager) Init(ctx context.Context) error {
...
 	m.groups = make(map[string]*ResourceGroup)
+	m.Unlock()
```
Comment (nolouch) [inline pkg/mcs/resourcemanager/server/manager.go:134]: Where will it be called concurrently?

Comment (HuSharp) [reply pkg/mcs/resourcemanager/server/manager.go:134]: I think because there is no happens-before guarantee for different goroutines, maybe meet memory reordering.

**Review by nolouch — APPROVED** [review]
