### PR TITLE
test: stabilize the TSO client tests

### LINKED ISSUE #9412: TestTSONotLeader is unstable
### Which jobs are failing
```
2025-06-17T05:22:56.8356130Z     client_test.go:513: 
2025-06-17T05:22:56.8357911Z         	Error Trace:	/home/runner/work/pd/pd/tests/integrations/tso/client_test.go:513
2025-06-17T05:22:56.8359876Z         	            				/opt/hostedtoolcache/go/1.23.10/x64/src/runtime/asm_amd64.s:1700
2025-06-17T05:22:56.8361242Z         	Error:      	Error "rpc error: code = Canceled desc = context canceled" does not contain "not leader"
2025-06-17T05:22:56.8362101Z         	Test:       	TestTSONotLeader
```

### CI link

https://github.com/tikv/pd/actions/runs/15698835296/job/44229167981?pr=9320

### LINKED ISSUE #9551: TestMoveLeader is unstable
### Which jobs are failing
```
--- FAIL: TestMoveLeader (18.71s)
    member_test.go:334: move etcd leader does not return in 10 seconds
```

### CI link
https://github.com/tikv/pd/actions/runs/16284438006/job/45980322440?pr=9550

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: close #9412, close #9551.

### What is changed and how does it work?

```commit-message
Stabilize TSO client tests by implementing resilient leader resignation with retries and enhancing the tests to accommodate leader change scenarios.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/integrations/tso/client_test.go [hunk 1]
```diff
@@ -495,42 +495,6 @@ func (suite *tsoClientTestSuite) TestGetTSWhileResettingTSOClient() {
 	re.NoError(failpoint.Disable("github.com/tikv/pd/client/clients/tso/delayDispatchTSORequest"))
 }
 
-func TestTSONotLeader(t *testing.T) {
```
Comment (rleungx) [inline tests/integrations/tso/client_test.go:498]: Why remove this case?

Comment (JmPotato) [reply tests/integrations/tso/client_test.go:498]: I believe that `TestRetryGetTSNotLeader` can also cover the code tested by `TestTSONotLeader` now.

Comment (rleungx) [reply tests/integrations/tso/client_test.go:498]: The key point of this test is `rebaseErr`, which might allocate TS even if it is not the leader.

Comment (JmPotato) [reply tests/integrations/tso/client_test.go:498]: Got it. I rewrited `TestTSONotLeader` to `TestTSONotLeaderWhenRebaseErr`. PTAL.

File: tests/integrations/tso/client_test.go [hunk 2]
```diff
@@ -567,19 +566,14 @@ func TestMixedTSODeployment(t *testing.T) {
...
-			err = leaderServer.ResignLeader()
-			re.NoError(err)
-			leaderServer = cluster.GetServer(cluster.WaitLeader())
-			re.NotNil(leaderServer)
-		}
-		cancel1()
-	}()
+	for range 2 {
+		n := r.Intn(2) + 1
+		time.Sleep(time.Duration(n) * time.Second)
```
Comment (okJiang) [inline tests/integrations/tso/client_test.go:572]: What is the purpose of sleep?

Comment (JmPotato) [reply tests/integrations/tso/client_test.go:572]: Maybe it's giving the background `checkTSO` goroutine some time to adopt the change. cc @rleungx

Comment (rleungx) [reply tests/integrations/tso/client_test.go:572]: I cannot remember it. Maybe as @JmPotato said. (

File: tests/cluster.go [hunk 3]
```diff
@@ -167,6 +169,16 @@ func (s *TestServer) ResignLeader() error {
 	return s.server.GetMember().ResignEtcdLeader(s.server.Context(), s.server.Name(), "")
 }
 
+// ResignLeaderWithRetry resigns the leader of the server with retry.
+func (s *TestServer) ResignLeaderWithRetry(re *require.Assertions) {
```
Comment (rleungx) [inline tests/cluster.go]: How about using a for loop to avoid importing testutil

**Review by rleungx — APPROVED** [review]
