### PR TITLE
mcs, etcd: avoid goroutine leak when watcher is failed

### LINKED ISSUE #9966: there maybe goroutine leak when watcher is failed

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #9966

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/mcs/router/server/meta/watcher.go [hunk 1]
```diff
@@ -59,6 +59,7 @@ func NewWatcher(
 	}
 	err := w.initializeStoreWatcher()
 	if err != nil {
+		w.Close()
```
Comment (rleungx) [inline pkg/mcs/router/server/meta/watcher.go:62]: The leak test doesn't cover this issue?

Comment (lhy1024) [reply pkg/mcs/router/server/meta/watcher.go:62]: There is no related test. I added a simple test for it. But only meta watcher.
image

**Comment by lhy1024** [comment]
The new tests will fail in master, and success in this pr
image
image
