### PR TITLE
keyspace: add preconditions for keyspace config update

### LINKED ISSUE #10214: PD: Support CAS-style preconditions for keyspace config updates
## Enhancement Task
PD keyspace config is planned to be used by the TiKV encryption key rotation workflow to store the current and target encryption config version. While the workflow is intended to have a single active actor, unexpected concurrent executions can cause config updates to overwrite each other and break the intended state transition.

PD currently lacks support for conditional (CAS-style) updates, making it impossible to safely express transitions such as setting next_encryption_file_id only if it is absent or advancing current_* only if it matches an expected value.

This issue proposes adding simple preconditions (for example, equal / absent checks) to keyspace config updates so state transitions can be performed safely.

### PR DESCRIPTION
**Pull request by hbisheng**
### What problem does this PR solve?

Issue Number: Close #10214

### What is changed and how does it work?
In the CMEK / encryption key rotation workflow, PD keyspace config is planned to be used to store the current and target encryption config version. Although the workflow is designed to have a single active actor, unexpected concurrent executions (for example, retries or overlapping operations) can lead to config updates overwriting each other and breaking the intended state transition.

This PR adds CAS-style guards to keyspace config updates so that encryption key rotation can advance safely and only when the system is in the expected state. With this, callers can, for example, set `next_encryption_file_id` only if it is absent, or advance `current_encryption_file_id` only if it matches `next_encryption_file_id`.

```commit-message
PD keyspace config updates are extended with optional preconditions that
must be satisfied for the update to succeed. These preconditions act as
lightweight CAS checks.

Changes:
- Extend /pd/api/v2/keyspaces/{name}/config API to accept preconditions
  for CAS-like config updates (equal / absent).
- Add pd-ctl support: keyspace update-config --expect and --expect-absent.
```

### Check List

Tests

- [x] Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

## Summary by CodeRabbit

* **New Features**
  * Conditional keyspace configuration updates via preconditions in the API.
  * CLI flags --expect and --expect-absent to specify preconditions when updating configs.
  * New distinct error code for keyspace config precondition failures.

* **Bug Fixes**
  * Update flow returns HTTP 409 for precondition violations and transactional conflicts.

* **Tests**
  * Added extensive tests (including concurrent scenarios) and a helper to inspect non-OK responses.

### CODE REVIEW

**Comment by hbisheng** [comment]
@coderabbitai review

**Comment by rleungx** [comment]
@ystaticy PTAL

File: pkg/keyspace/keyspace.go [hunk 1]
```diff
@@ -645,6 +645,68 @@ const (
...
+// - key -> "value" means the key must exist and equal "value".
+func (manager *Manager) UpdateKeyspaceConfigWithPreconditions(name string, mutations []*Mutation, preconditions map[string]*string) (*keyspacepb.KeyspaceMeta, error) {
+	if len(preconditions) == 0 {
+		return manager.UpdateKeyspaceConfig(name, mutations)
+	}
+	return manager.updateKeyspaceConfigTxn(name, func(meta *keyspacepb.KeyspaceMeta) error {
+		if err := checkKeyspaceConfigPreconditions(meta.GetConfig(), preconditions); err != nil {
+			return err
+		}
+		for _, mutation := range mutations {
```
Comment (rleungx) [inline pkg/keyspace/keyspace.go]: How about using a function?

Comment (hbisheng) [reply pkg/keyspace/keyspace.go]: Added a `applyKeyspaceConfigMutations` function

Comment (hbisheng) [reply pkg/keyspace/keyspace.go]: Added an `applyKeyspaceConfigMutations` function

**Comment by hbisheng** [comment]
Would appreciate a review when you have time. Thanks! @ystaticy @lhy1024 @rleungx

File: server/apiv2/handlers/keyspace.go [hunk 2]
```diff
@@ -350,8 +355,16 @@ func UpdateKeyspaceConfig(c *gin.Context) {
 		}
 	}
 
-	meta, err := manager.UpdateKeyspaceConfig(name, mutations)
+	meta, err := manager.UpdateKeyspaceConfigWithPreconditions(name, mutations, configParams.Preconditions)
 	if err != nil {
+		if goerrors.Is(err, errs.ErrKeyspaceConfigPreconditionFailed) {
+			c.AbortWithStatusJSON(http.StatusConflict, err.Error())
```
Comment (lhy1024) [inline server/apiv2/handlers/keyspace.go:362]: We also need to update swagger comments for 409.

Comment (hbisheng) [reply server/apiv2/handlers/keyspace.go:362]: Good catch - added a line of comment for it
