### PR TITLE
*: fix potential bug by ai in pkg/schedule/schedulers

### LINKED ISSUE #10449: pkg/schedule/schedulers: avoid panics on malformed scheduler config input
## Development Task

The scheduler config and scheduler-related API paths under `pkg/schedule/schedulers` may panic or return inaccurate HTTP errors when receiving malformed or unexpected input.

Typical risky cases include:
- unsafe type assertions on scheduler config fields parsed from JSON
- unexpected scheduler type casts in transfer witness handling
- incorrect HTTP status codes for invalid user input
- nil-response handling gaps in scheduler API error paths

This task tracks hardening those code paths so that invalid input is rejected safely with clear client-facing errors instead of causing runtime panics or misleading 5xx responses.

Related work:
- ref #10326
- implemented in #10312

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #10449

### What is changed and how does it work?

```commit-message
- It removes several unsafe type assertions on JSON input (like input["x"].(string)), replacing them with checked parsing and clear 400 Bad Request responses, so malformed payloads no longer panic PD.  
  - Key places: pkg/schedule/schedulers/balance_range.go, pkg/schedule/schedulers/evict_leader.go, pkg/schedule/schedulers/grant_hot_region.go, pkg/schedule/schedulers/grant_leader.go
- It fixes a risky type cast in transfer witness handling by making RecvRegionInfo safe (nil on wrong scheduler type) and guarding before channel send.  
  - pkg/schedule/schedulers/transfer_witness_leader.go, pkg/schedule/schedulers/scheduler_controller.go
- It corrects HTTP error behavior in scheduler API paths:
  - invalid user options now return 400 instead of 500
  - avoids nil dereference when delete redirect fails and response is nil
  - handles “handler unavailable” cases explicitly  
  - server/api/scheduler.go
- It adds regression tests specifically asserting no panic and expected status codes for bad/odd inputs.  
  - pkg/schedule/schedulers/balance_range_test.go, pkg/schedule/schedulers/evict_leader_test.go, pkg/schedule/schedulers/grant_hot_region_test.go, pkg/schedule/schedulers/grant_leader_test.go, pkg/schedule/schedulers/transfer_witness_leader_test.go
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP APIs changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Stricter input validation and clearer client-facing errors for scheduler config updates (engine, rule, alias, timeouts, store IDs, ranges), safer control flow to avoid runtime errors and unintended pauses/resumes, and more accurate HTTP status codes for invalid input.

* **Tests**
  * Added tests for invalid field types, malformed ranges, wrong scheduler types, and config update error cases to prevent regressions.

### CODE REVIEW

**Review by liyishuai — APPROVED** [review]
Tesed on my side. The AI review is worth considering. Otherwise LGTM.

File: pkg/schedule/schedulers/evict_leader.go [hunk 1]
```diff
@@ -427,8 +428,28 @@ func (handler *evictLeaderHandler) updateConfig(w http.ResponseWriter, r *http.R
...
+	if hasRanges {
+		switch val := rangesVal.(type) {
+		case []string:
+			ranges = val
+		case []any:
+			ranges = make([]string, 0, len(val))
+			for _, item := range val {
+				s, ok := item.(string)
+				if !ok {
+					handler.config.resumeLeaderTransferIfExist(id)
```
Comment (rleungx) [inline pkg/schedule/schedulers/evict_leader.go]: If there is a wrong request, e.g., an invalid range type, will it resume incorrectly?

Comment (bufferflies) [reply pkg/schedule/schedulers/evict_leader.go]: Good catch. I think the original code is pretty good; we should ignore the other type.

**Comment by rleungx** [comment]
There is still one missing case here: when creating a new balance-range scheduler, `timeout` is still read via `apiutil.CollectStringOption()`, which treats a wrong-typed field the same as a missing one. So a request like `{"timeout":123}` will still silently fall back to the default `30m` instead of returning `400 Bad Request`. Could we distinguish between “not provided” and “wrong type” here, so this path stays consistent with the stricter validation added elsewhere in this PR?

**Comment by bufferflies** [comment]
> CollectStringOption

```
// CollectStringOption is used to collect string using from input map for given option
func CollectStringOption(option string, input map[string]any, collectors ...func(v string)) error {
	if v, ok := input[option].(string); ok {
		for _, c := range collectors {
			c(v)
		}
		return nil
	}
	return errs.ErrOptionNotExist.FastGenByArgs(option)
}
```

It will return ErrOptionNotExist if the key does not exist or is not a string. Do you suggest disguising them?

File: pkg/schedule/schedulers/transfer_witness_leader_test.go [hunk 2]
```diff
@@ -89,3 +89,11 @@ func TestTransferWitnessLeaderWithUnhealthyPeer(t *testing.T) {
 	ops, _ = sl.Schedule(tc, false)
 	re.Empty(ops)
 }
+
+func TestRecvRegionInfoWithWrongSchedulerType(t *testing.T) {
```
Comment (okJiang) [inline pkg/schedule/schedulers/transfer_witness_leader_test.go]: Is this test unnecessary?

Comment (bufferflies) [reply pkg/schedule/schedulers/transfer_witness_leader_test.go]: removed, done

File: server/api/scheduler.go [hunk 3]
```diff
@@ -142,13 +146,13 @@ func (h *schedulerHandler) CreateScheduler(w http.ResponseWriter, r *http.Reques
 			if errors.ErrorEqual(err, errs.ErrOptionNotExist) {
 				collector(defaultTimeout)
 			} else {
-				h.r.JSON(w, http.StatusInternalServerError, err.Error())
+				h.r.JSON(w, http.StatusBadRequest, err.Error())
 				return
 			}
 		}
```
Comment (lhy1024) [inline server/api/scheduler.go:152]: CollectStringOption returns `ErrOptionNotExist` for non-string type and option not exist.

The core issue is that in the create path, {"timeout":123} is still treated as “timeout not provided”, so it silently falls back to the default value instead of returning 400.

Comment (lhy1024) [reply server/api/scheduler.go:152]:
```
func TestCollectStringOptionTypeMismatchMatchesErrOptionNotExist(t *testing.T) {
        input := map[string]any{"timeout": 123}

        err := CollectStringOption("timeout", input)
        require.Error(t, err)
        require.True(t, perrors.ErrorEqual(err, errs.ErrOptionNotExist))
  }
```
```
go test ./pkg/utils/apiutil -run '^TestCollectStringOptionTypeMismatchMatchesErrOptionNotExist$' -count=1
ok    github.com/tikv/pd/pkg/utils/apiutil    0.007s
```

File: pkg/schedule/schedulers/balance_range.go [hunk 4]
```diff
@@ -90,27 +90,52 @@ func (handler *balanceRangeSchedulerHandler) addJob(w http.ResponseWriter, r *ht
...
+			if err != nil {
+				handler.rd.JSON(w, http.StatusBadRequest, fmt.Sprintf("timeout:%s is invalid", timeoutStr))
+				return
+			}
+			if timeout <= 0 {
+				handler.rd.JSON(w, http.StatusBadRequest, "timeout must be positive")
+				return
+			}
+			job.Timeout = timeout
+		}
```
Comment (lhy1024) [inline pkg/schedule/schedulers/balance_range.go:138]: For the initial HTTP create path, timeout: "0s" and negative values are still accepted, because the create decoder only calls time.ParseDuration. It is not consistency with here.

Comment (lhy1024) [reply pkg/schedule/schedulers/balance_range.go:138]:
```
func (suite *scheduleTestSuite) TestBalanceRangeCreateRejectsZeroTimeout() {
	suite.te.RunTest(func(cluster *tests.TestCluster) {
		suite.checkBalanceRangeCreateRejectsNonPositiveTimeout(cluster, "0s")
	})
}

func (suite *scheduleTestSuite) TestBalanceRangeCreateRejectsNegativeTimeout() {
	suite.te.RunTest(func(cluster *tests.TestCluster) {
		suite.checkBalanceRangeCreateRejectsNonPositiveTimeout(cluster, "-1s")
	})
}

func (suite *scheduleTestSuite) checkBalanceRangeCreateRejectsNonPositiveTimeout(cluster *tests.TestCluster, timeout string) {
	re := suite.Require()
	input := map[string]any{
		"alias":     "test.sysbench.partition(p1)",
		"engine":    "tikv",
		"rule":      "leader-scatter",
		"name":      types.BalanceRangeScheduler.String(),
		"timeout":   timeout,
		"start-key": url.QueryEscape("100"),
		"end-key":   url.QueryEscape("200"),
	}
	data, err := json.Marshal(input)
	re.NoError(err)
	leaderAddr := cluster.GetLeaderServer().GetAddr()
	urlPrefix := fmt.Sprintf("%s/pd/api/v1", leaderAddr)
	re.NoError(testutil.CheckPostJSON(
		tests.TestDialClient,
		urlPrefix+"/schedulers",
		data,
		testutil.Status(re, http.StatusBadRequest),
	))
}
```

Comment (lhy1024) [reply pkg/schedule/schedulers/balance_range.go:138]:
```
go test -tags without_dashboard ./tests/server/api -run 'Test(NonMicroservice|Microservice)SchedulingTestSuite/
  TestBalanceRangeCreateRejectsZeroTimeout$' -count=1
  go test -tags without_dashboard ./tests/server/api -run 'Test(NonMicroservice|Microservice)SchedulingTestSuite/
  TestBalanceRangeCreateRejectsNegativeTimeout$' -count=1
```
```
  0s：

  --- FAIL: TestMicroserviceSchedulingTestSuite (18.20s)
      testutil.go:425: start test TestBalanceRangeCreateRejectsZeroTimeout in microservice environment
      --- FAIL: TestMicroserviceSchedulingTestSuite/TestBalanceRangeCreateRejectsZeroTimeout (12.34s)
          api_check.go:30:
               Error:       Not equal:
                            expected: 400
                            actual  : 200
               Messages:    resp: "The scheduler is created."
  FAIL
  FAIL  github.com/tikv/pd/tests/server/api     21.550s
  FAIL

  -1s：

  --- FAIL: TestMicroserviceSchedulingTestSuite (18.19s)
      testutil.go:425: start test TestBalanceRangeCreateRejectsNegativeTimeout in microservice environment
      --- FAIL: TestMicroserviceSchedulingTestSuite/TestBalanceRangeCreateRejectsNegativeTimeout (12.34s)
          api_check.go:30:
               Error:       Not equal:
                            expected: 400
                            actual  : 200
               Messages:    resp: "The scheduler is created."
  FAIL
  FAIL  github.com/tikv/pd/tests/server/api     21.485s
  FAIL
```

File: server/api/scheduler.go
Comment (rleungx) [inline server/api/scheduler.go:251]: If there is a bad rule, it still returns 500, instead of 400.

File: server/api/scheduler.go (hunk 3 above)
Comment (bufferflies) [reply server/api/scheduler.go:152]: It must be string lit, can't be number lit

File: server/api/scheduler.go
Comment (bufferflies) [reply server/api/scheduler.go:251]: good  catch, done

File: pkg/schedule/schedulers/balance_range.go (hunk 4 above)
Comment (bufferflies) [reply pkg/schedule/schedulers/balance_range.go:138]: done,

File: server/api/scheduler.go (hunk 3 above)
Comment (lhy1024) [reply server/api/scheduler.go:152]: Should we distinguish between non-string type and option not exist for timeout?

File: server/api/scheduler.go
Comment (rleungx) [reply server/api/scheduler.go:251]: Actually, AddScheduler can also return 500 sometimes.
