### PR TITLE
schedule/labeler: Optimize locking to fix high-concurrency goroutine surge

### LINKED ISSUE #9854: High goroutine surge and server instability when `SetRegionLabelRule` is called concurrently during Lightning import
## Bug Report
 During TiDB Lightning import tidb call [pauseSchedulerByKeyRangeWithTTL](https://github1s.com/Pingcap/tidb/blob/master/br/pkg/pdutil/pd.go#L799-L800), and the API SetRegionLabelRule is invoked with very high concurrency, triggering heavy [lock contention](https://github.com/tikv/pd/blob/v6.5.4/server/schedule/labeler/labeler.go#L209-L210) inside RegionLabeler and causing a runaway goroutine count and server instability.
Image

Image

### What did you expect to see?
SetRegionLabelRule handles concurrent calls without excessive lock contention or goroutine growth; PD remains stable during Lightning imports.
### What did you see instead?
Goroutines spike to ~2,0M (see profile below)

```
goroutine profile: total 1992996
1977137 @ 0xf6a02e 0xf7bc98 0xf7bc6f 0xf9aba5 0xfad65d 0xfaeb71 0xfaeb52 0x1fc6037 0x270314f 0x26f586b 0x221392d 0x2213a28 0x26f6bac 0x2213a28 0x26f660a 0x2213a28 0x26f5bda 0x2213a28 0x2213d34 0x272c038 0x13547e9 0x1a848e5 0x27212e5 0x221392d 0x2213a28 0x227ec98 0x2213a28 0x227e1b9 0x2213a28 0x2213d34 0x1a848e5 0x1a848e5
#   0xf9aba4    sync.runtime_SemacquireMutex+0x24                                   /usr/local/go/src/runtime/sema.go:77
#   0xfad65c    sync.(*Mutex).lockSlow+0x15c                                        /usr/local/go/src/sync/mutex.go:171
#   0xfaeb70    sync.(*Mutex).Lock+0x30                                         /usr/local/go/src/sync/mutex.go:90
#   0xfaeb51    sync.(*RWMutex).Lock+0x11                                       /usr/local/go/src/sync/rwmutex.go:147
#   0x1fc6036   github.com/tikv/pd/pkg/schedule/labeler.(*RegionLabeler).SetLabelRule+0x56              /pd/pkg/schedule/labeler/labeler.go:212
#   0x270314e   github.com/tikv/pd/server/api.(*regionLabelHandler).SetRegionLabelRule+0xae             /pd/server/api/region_label.go:165
#   0x26f586a   github.com/tikv/pd/server/api.(*serviceMiddlewareBuilder).createHandler.WrapFunc.func1+0x2a     /go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:56
#   0x221392c   github.com/urfave/negroni.HandlerFunc.ServeHTTP+0x2c                            /go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:29
#   0x2213a27   github.com/urfave/negroni.middleware.ServeHTTP+0xa7                         /go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38
#   0x26f6bab   github.com/tikv/pd/server/api.(*rateLimitMiddleware).ServeHTTP+0x32b                    /pd/server/api/middleware.go:170
#   0x2213a27   github.com/urfave/negroni.middleware.ServeHTTP+0xa7                         /go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38
#   0x26f6609   github.com/tikv/pd/server/api.(*auditMiddleware).ServeHTTP+0x569                    /pd/server/api/middleware.go:150
#   0x2213a27   github.com/urfave/negroni.middleware.ServeHTTP+0xa7                         /go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38
#   0x26f5bd9   github.com/tikv/pd/server/api.(*requestInfoMiddleware).ServeHTTP+0x319                  /pd/server/api/middleware.go:76
#   0x2213a27   github.com/urfave/negroni.middleware.ServeHTTP+0xa7                         /go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38
#   0x2213d33   github.com/urfave/negroni.(*Negroni).ServeHTTP+0x113                            /go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:96
#   0x272c037   github.com/tikv/pd/server/api.clusterMiddleware.Middleware-fm.clusterMiddleware.Middleware.func1+0xb7   /pd/server/api/middleware.go:99
#   0x13547e8   net/http.HandlerFunc.ServeHTTP+0x28                                 /usr/local/go/src/net/http/server.go:2136
```

### What version of PD are you using (`pd-server -V`)?
v6.5.4

### PR DESCRIPTION
**Pull request by lhy1024**
…surge

### What problem does this PR solve?

Issue Number: Close #9854

### What is changed and how does it work?

```commit-message
```
1. Remove GC in the get query
2. Reduce lock time for storage and only lock for memory state

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by bufferflies — APPROVED** [review]

File: pkg/schedule/labeler/labeler.go [hunk 1]
```diff
@@ -163,101 +165,140 @@ func (l *RegionLabeler) GetSplitKeys(start, end []byte) [][]byte {
...
+		return err
+	}
+	if err := l.storage.RunInTxn(l.ctx, func(txn kv.Txn) error {
+		return l.storage.SaveRegionRule(txn, rule.ID, rule)
+	}); err != nil {
 		return err
 	}
+
+	// only Lock for in-memory update
+	l.Lock()
```
Comment (HaoW30) [inline pkg/schedule/labeler/labeler.go:257]: In my local experiments, this lock can still experience heavy contention because the range list is built while holding the write lock.
One possible improvement is:
1. Make a copy of the rules under a read lock.
2. Build the range list without holding any lock.
3. Use write lock to set the new range list in RegionLabeler.

This approach avoids holding the write lock for an extended period and should significantly reduce contention.

Comment (HaoW30) [reply pkg/schedule/labeler/labeler.go:257]: Something this 
```
-       // only Lock for in-memory update
+       // Build range list outside the write lock to reduce contention
+       l.RLock()
+       rulesCopy := make(map[string]*LabelRule, len(l.labelRules)+1)
+       for k, v := range l.labelRules {
+               rulesCopy[k] = v
+       }
+       l.RUnlock()
+       rulesCopy[rule.ID] = rule
+
+       // Build the new range list without holding any lock (expensive operation)
+       newRangeList, newMinExpire := buildRangeListFrom(rulesCopy)
+
+       // Quick atomic swap under write lock
        l.Lock()
-       defer l.Unlock()
        l.labelRules[rule.ID] = rule
-       l.buildRangeList()
+       l.rangeList = newRangeList
+       l.minExpire = newMinExpire
+       l.Unlock()
```

Comment (HaoW30) [reply pkg/schedule/labeler/labeler.go:257]: The above code may not be bulletproof — it’s just to show the idea.

Comment (HaoW30) [reply pkg/schedule/labeler/labeler.go:257]: We will need compare and swap to avoid losing updates.

Comment (HaoW30) [reply pkg/schedule/labeler/labeler.go:257]: I’m totally fine with handling the further optimization in a separate PR, since the compare-and-swap part could be a bit tricky.

Comment (lhy1024) [reply pkg/schedule/labeler/labeler.go:257]: Good job. I think it will be helpful and we could do it in another pr.

**Review by okJiang — APPROVED** [review]
