### PR TITLE
fix: fix update-dashboard script not work when target is semver style

### LINKED ISSUE #7637: [bug] Fix scripts/update-dashboard scripts to support dashboard semver style version
## Development Task

When tidb-dashboard become `X.Y.Z-<sha>` style version, running `update-dashboard` scripts meet the following error:

```
❯ scripts/update-dashboard.sh 7.6.0-f7bbcdcf-test
+ Update dashboard version to v7.6.0-f7bbcdcf-test
go: [github.com/pingcap/tidb-dashboard@v7.6.0-f7bbcdcf-test](http://github.com/pingcap/tidb-dashboard@v7.6.0-f7bbcdcf-test): invalid version: module contains a go.mod file, so module path must match major version ("[github.com/pingcap/tidb-dashboard/v7](http://github.com/pingcap/tidb-dashboard/v7)")
```

### PR DESCRIPTION
**Pull request by baurine**
### What problem does this PR solve?

Issue Number: Close #7637 

### What is changed and how does it work?

This PR fix the `scripts/update-dashboard` script can't work with dashboard semver style version format.

```commit-message
none
```

### Test

```
❯ scripts/update-dashboard.sh v7.6.0-f7bbcdcf-test
+ Update dashboard version to v7.6.0-f7bbcdcf-test
go: upgraded github.com/pingcap/tidb-dashboard v0.0.0-20231218095437-aa621ed4de2c => v0.0.0-20231228101154-f7bbcdcf902c
./scripts/embed-dashboard-ui.sh
+ Clean up existing asset file
+ Fetch TiDB Dashboard Go module
  - TiDB Dashboard directory: /home/bao/go/pkg/mod/github.com/pingcap/tidb-dashboard@v0.0.0-20231228101154-f7bbcdcf902c
+ Create download cache directory: /mnt/bao/codes/work/pd/.dashboard_download_cache
+ Discover TiDB Dashboard release version
  - TiDB Dashboard release version: 7.6.0-f7bbcdcf-test
+ Check whether pre-built assets are available
  - Cached archive does not exist
  - Download pre-built embedded assets from GitHub release
  - Download https://github.com/pingcap/tidb-dashboard/releases/download/v7.6.0-f7bbcdcf-test/embedded-assets-golang.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 12.1M  100 12.1M    0     0  2419k      0  0:00:05  0:00:05 --:--:-- 2878k
  - Save archive to cache: /mnt/bao/codes/work/pd/.dashboard_download_cache/embedded-assets-golang-7.6.0-f7bbcdcf-test.zip
+ Unpack embedded asset from archive
Archive:  /mnt/bao/codes/work/pd/.dashboard_download_cache/embedded-assets-golang-7.6.0-f7bbcdcf-test.zip
  inflating: embedded_assets_handler.go  
  - Unpacked /mnt/bao/codes/work/pd/pkg/dashboard/uiserver/embedded_assets_handler.go
GOEXPERIMENT= CGO_ENABLED=1 go build  -gcflags '' -ldflags '-X "github.com/tikv/pd/pkg/versioninfo.PDReleaseVersion=v7.6.0-alpha-157-gc7644be0e-dirty" -X "github.com/tikv/pd/pkg/versioninfo.PDBuildTS=2023-12-29 03:20:07" -X "github.com/tikv/pd/pkg/versioninfo.PDGitHash=c7644be0e86d28719b428f22ceec778ee143696a" -X "github.com/tikv/pd/pkg/versioninfo.PDGitBranch=master" -X "github.com/tikv/pd/pkg/versioninfo.PDEdition=Community" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.InternalVersion=7.6.0-f7bbcdcf-test" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.Standalone=No" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.PDVersion=v7.6.0-alpha-157-gc7644be0e-dirty" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.BuildTime=2023-12-29 03:20:07" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.BuildGitHash=f7bbcdcf902c"' -tags "" -o /mnt/bao/codes/work/pd/bin/pd-server cmd/pd-server/main.go
```

```
❯ scripts/update-dashboard.sh v2023.12.18.1                   
+ Update dashboard version to v2023.12.18.1
go: downgraded github.com/pingcap/tidb-dashboard v0.0.0-20231228101154-f7bbcdcf902c => v0.0.0-20231218095437-aa621ed4de2c
./scripts/embed-dashboard-ui.sh
+ Clean up existing asset file
+ Fetch TiDB Dashboard Go module
  - TiDB Dashboard directory: /home/bao/go/pkg/mod/github.com/pingcap/tidb-dashboard@v0.0.0-20231218095437-aa621ed4de2c
+ Create download cache directory: /mnt/bao/codes/work/pd/.dashboard_download_cache
+ Discover TiDB Dashboard release version
  - TiDB Dashboard release version: 2023.12.18.1
+ Check whether pre-built assets are available
  - Cached archive exists: /mnt/bao/codes/work/pd/.dashboard_download_cache/embedded-assets-golang-2023.12.18.1.zip
+ Unpack embedded asset from archive
Archive:  /mnt/bao/codes/work/pd/.dashboard_download_cache/embedded-assets-golang-2023.12.18.1.zip
  inflating: embedded_assets_handler.go  
  - Unpacked /mnt/bao/codes/work/pd/pkg/dashboard/uiserver/embedded_assets_handler.go
GOEXPERIMENT= CGO_ENABLED=1 go build  -gcflags '' -ldflags '-X "github.com/tikv/pd/pkg/versioninfo.PDReleaseVersion=v7.6.0-alpha-157-gc7644be0e-dirty" -X "github.com/tikv/pd/pkg/versioninfo.PDBuildTS=2023-12-29 03:21:38" -X "github.com/tikv/pd/pkg/versioninfo.PDGitHash=c7644be0e86d28719b428f22ceec778ee143696a" -X "github.com/tikv/pd/pkg/versioninfo.PDGitBranch=master" -X "github.com/tikv/pd/pkg/versioninfo.PDEdition=Community" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.InternalVersion=2023.12.18.1" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.Standalone=No" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.PDVersion=v7.6.0-alpha-157-gc7644be0e-dirty" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.BuildTime=2023-12-29 03:21:38" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.BuildGitHash=aa621ed4de2c"' -tags "" -o /mnt/bao/codes/work/pd/bin/pd-server cmd/pd-server/main.go
```

### Release note

```release-note
None.
```

### CODE REVIEW

File: scripts/update-dashboard.sh [hunk 1]
```diff
@@ -10,16 +10,26 @@ DASHBOARD_VERSION=$(grep -v '^#' "$DASHBOARD_VERSION_FILE")
 # new version
 # Usage: ./scripts/update-dashboard.sh <version>
 # Example: ./scripts/update-dashboard.sh 2023.12.18.1
```
Comment (rleungx) [inline scripts/update-dashboard.sh:12]: Shall remove this one?

Comment (baurine) [reply scripts/update-dashboard.sh:12]: sure, let me update it.

**Review by HuSharp — APPROVED** [review]

File: scripts/dashboard-version [hunk 2]
```diff
@@ -1,3 +1,4 @@
 # This file is updated by running scripts/update-dashboard.sh
 # Don't edit it manullay
+# the version will become X.Y.Z-<commit-short-hash> format later
```
Comment (wuhuizuo) [inline scripts/dashboard-version:3]: It's better support origin tag value, such as:
`v7.6.0-f7bbcdcf-test`.

File: scripts/update-dashboard.sh [hunk 3]
```diff
@@ -9,17 +9,26 @@ DASHBOARD_VERSION=$(grep -v '^#' "$DASHBOARD_VERSION_FILE")
 
 # new version
 # Usage: ./scripts/update-dashboard.sh <version>
-# Example: ./scripts/update-dashboard.sh 2023.12.18.1
+# Example: ./scripts/update-dashboard.sh 7.6.0-f7bbcdcf
```
Comment (wuhuizuo) [inline scripts/update-dashboard.sh:12]:
```suggestion
# Example: 
#     ./scripts/update-dashboard.sh 7.6.0-f7bbcdcf
#     # or
#     ./scripts/update-dashboard.sh v7.6.0-f7bbcdcf
```

File: scripts/update-dashboard.sh [hunk 4]
```diff
@@ -9,17 +9,26 @@ DASHBOARD_VERSION=$(grep -v '^#' "$DASHBOARD_VERSION_FILE")
...
 
 echo "+ Update dashboard version to v$DASHBOARD_VERSION"
 
 cd $BASE_DIR
 
-go get -d github.com/pingcap/tidb-dashboard@v$DASHBOARD_VERSION
+FINAL_VERSION=v$DASHBOARD_VERSION
+# if DASHBOARD_VERSION match X.Y.Z-<commit-short-hash> format,
+# then extract the commit hash as tidb-dashboard target
+if [[ $DASHBOARD_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-[0-9a-f]{7,8} ]]; then
```
Comment (wuhuizuo) [inline scripts/update-dashboard.sh:27]:
```suggestion
if [[ $DASHBOARD_VERSION =~ ^(v)?[0-9]+\.[0-9]+\.[0-9]+-[0-9a-f]{7,8} ]]; then
```

File: scripts/update-dashboard.sh [hunk 5]
```diff
@@ -9,17 +9,26 @@ DASHBOARD_VERSION=$(grep -v '^#' "$DASHBOARD_VERSION_FILE")
...
+  echo $1 >> $DASHBOARD_VERSION_FILE
 fi
 
 echo "+ Update dashboard version to v$DASHBOARD_VERSION"
 
 cd $BASE_DIR
 
-go get -d github.com/pingcap/tidb-dashboard@v$DASHBOARD_VERSION
+FINAL_VERSION=v$DASHBOARD_VERSION
+# if DASHBOARD_VERSION match X.Y.Z-<commit-short-hash> format,
```
Comment (wuhuizuo) [inline scripts/update-dashboard.sh:25]:
```suggestion
# if DASHBOARD_VERSION match "X.Y.Z-<commit-short-hash>" or "vX.Y.Z-<commit-short-hash>" format,
```

File: scripts/dashboard-version (hunk 2 above)
Comment (baurine) [reply scripts/dashboard-version:3]: This file is also used in `Makefile` and `embed-dashboard-ui.sh` to describe the dashboard version without `v` prefix as before, so that why I remove the `v` prefix here, else we need to modify the `Makefile` and `embed-dashboard-ui.sh` logic.

**Review by rleungx — APPROVED** [review]
