### PR TITLE
resource_manager; fix the bug that ru tokens is not limit when available service limit is 0

### LINKED ISSUE #9651: resourcemanager: service limit can be limited occationally
### What did you do?

Image

There is no user configured resource group and the service limit is set to 10k. When running a stable workload that can consume all the ru, I found the ru consumption rate can exceed the service limit sometimes.

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: Close #9651

### What is changed and how does it work?

- Fix the bug that ru tokens is not limit when service limiter's available tokens is 0
- Add a gauge metrics for service limit
- Also track some extended metrics for the default resource group.

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/mcs/resourcemanager/server/manager.go [hunk 1]
```diff
@@ -530,14 +530,12 @@ func (m *Manager) backgroundMetricsFlush(ctx context.Context) {
 				if err != nil {
 					continue
 				}
+				setServiceLimitMetrics(keyspaceName, krgm.getServiceLimiter().GetServiceLimit())
```
Comment (JmPotato) [inline pkg/mcs/resourcemanager/server/manager.go]: Should we only record service limits that are greater than or equal to zero?

File: pkg/mcs/resourcemanager/server/service_limit.go [hunk 2]
```diff
@@ -91,6 +91,13 @@ func (krl *serviceLimiter) setServiceLimit(newServiceLimit float64) {
 	}
 }
 
+// GetServiceLimit return the service limit value of this keyspace.
+func (krl *serviceLimiter) GetServiceLimit() float64 {
```
Comment (JmPotato) [inline pkg/mcs/resourcemanager/server/service_limit.go:95]:
```suggestion
func (krl *serviceLimiter) GetServiceLimit() float64 {
		if krl == nil {
				return 0.0
		}
```

**Review by JmPotato — APPROVED** [review]
LGTM. Please fix the statics check.
