### PR TITLE
test: fix unstable test TestLevelDBBackend

### LINKED ISSUE #7875: Unstable Test In `TestLevelDBBackend`
### Which jobs are failing

https://github.com/tikv/pd/actions/runs/8152116148/job/22281781855?pr=7860

### PR DESCRIPTION
**Pull request by CabinfeverB**
### What problem does this PR solve?

Issue Number: Close #7875

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/storage/leveldb_backend_test.go [hunk 1]
```diff
@@ -86,10 +87,12 @@ func TestLevelDBBackend(t *testing.T) {
 	val, err = backend.Load(key)
 	re.NoError(err)
 	re.Empty(val)
-	time.Sleep(defaultDirtyFlushTick * 2)
-	val, err = backend.Load(key)
-	re.NoError(err)
-	re.Equal(value, val)
+	testutil.Eventually(re, func() bool {
+		time.Sleep(defaultDirtyFlushTick * 2)
```
Comment (rleungx) [inline pkg/storage/leveldb_backend_test.go:91]: Do we still need it?

Comment (CabinfeverB) [reply pkg/storage/leveldb_backend_test.go:91]: forgot to delele it

**Review by rleungx — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]
