### PR TITLE
test/cluster_test: make TestRegionStatistics more stable

### LINKED ISSUE #8319: TestRegionStatistics  is unstable
### Which jobs are failing
```bash
--- FAIL: TestRegionStatistics (14.52s)
    cluster_test.go:262: 
        	Error Trace:	/home/runner/work/pd/pd/tests/server/cluster/cluster_test.go:262
        	Error:      	Not equal: 
        	            	expected: "pd2"
        	            	actual  : "pd1"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-pd2
        	            	+pd1
        	Test:       	TestRegionStatistics
FAIL
```

### CI link
https://github.com/tikv/pd/actions/runs/9611005214/job/26508694960?pr=7756

### Reason for failure (if possible)

Because this test has only 2 pd's and five ResignLeader times, whenever there is a network or disk problem will cause the lease to expire, and result in one more leader resigning. 
There is a high probability of being recognized as frequent campaign times.

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Close #8319

### What is changed and how does it work?

```commit-message
Because this test has only 2 pd's and five ResignLeader times, whenever there is a network or disk problem will cause the lease to expire, and result in one more leader resigning.
And then there is a high probability of being recognized as frequent campaign times to transfer leader failed
```

### Check List

Tests

- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

File: tests/server/cluster/cluster_test.go [hunk 1]
```diff
@@ -186,7 +186,7 @@ func TestRegionStatistics(t *testing.T) {
 	re := require.New(t)
 	ctx, cancel := context.WithCancel(context.Background())
 	defer cancel()
-	tc, err := tests.NewTestCluster(ctx, 2)
+	tc, err := tests.NewTestCluster(ctx, 3)
```
Comment (JmPotato) [inline tests/server/cluster/cluster_test.go:189]: Why add a new server?

Comment (HuSharp) [reply tests/server/cluster/cluster_test.go:189]: Because this test has only 2 pd's and five ResignLeader times, whenever there is a network or disk problem will cause the lease to expire, and result in one more leader resigning.
And then there is a high probability of being recognized as frequent campaign times to transfer leader failed

**Review by nolouch — APPROVED** [review]
