### PR TITLE
server: Auto fix gc_worker's service safepoint for upgraded clusters

### LINKED ISSUE #3366: Service Safepoint with infinite TTL may keep disappearing after upgrading PD
## Bug Report

An extended problem of https://github.com/tikv/pd/issues/3128

### What did you do?

Upgrade from PD from v4.0.8 to v4.0.9.

### What did you expect to see?
PD should contain service_gc_safe_points `gc_worker` in PD etcd key.

Expected:
```
./pd-ctl service-gc-safepoint
{
  "service_gc_safe_points": [
    {
      "service_id": "gc_worker",
      "expired_at": 9223372036854775807,
      "safe_point": 422298434977136640
    }
    ...
}
```

### What did you see instead?

```
./pd-ctl service-gc-safepoint
{
  "service_gc_safe_points": [
    {
      "service_id": "ticdc",
      "expired_at": 1612125548,
      "safe_point": 422298434977136640
    }
  ],
  "gc_safe_point": 422141635726409728
}
```
service_id: "gc_worker" is still lost.

### What version of PD are you using (`pd-server -V`)?
```
Release Version: v4.0.9
Edition: Community
Git Commit Hash: 328752221729cca17b618fca75d161865e4da736
Git Branch: heads/refs/tags/v4.0.9
UTC Build Time:  2020-12-21 03:55:3
```

### PR DESCRIPTION
**Pull request by MyonKeminta**
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

### What problem does this PR solve?

Fixes #3366

Though we did a fix in PR #3146 , there's still a problem for clusters upgraded from older version, where the gc_worker's service safepoint may be invalid or missing and there are other service safepoints in the cluster.

### What is changed and how it works?

Checks if "gc_worker"'s service safepoint exist and has a infinite TTL every time loading safepoints, and tries to fix it if possible.

### Check List

Tests

- Unit test

Code changes

- 

Side effects

- Increased code complexity

Related changes

- Need to cherry-pick to the release branch
  - release-4.0

### Release note

* No release note

### CODE REVIEW

**Comment by MyonKeminta** [comment]
@lichunzhu  @disksing @rleungx PTAL

**Comment by MyonKeminta** [comment]
Ping @lichunzhu @disksing @rleungx PTAL

File: tests/client/client_test.go [hunk 1]
```diff
@@ -911,6 +912,61 @@ func (s *testClientSuite) TestUpdateServiceGCSafePoint(c *C) {
...
+	c.Assert(err, IsNil)
+	_, err = s.client.UpdateServiceGCSafePoint(context.Background(),
+		"b", 1000, 12)
+	c.Assert(err, IsNil)
+	_, err = s.client.UpdateServiceGCSafePoint(context.Background(),
+		"c", 1000, 13)
+	c.Assert(err, IsNil)
+
+	// Force set invalid ttl to gc_worker
+	//err = s.srv.GetStorage().SaveServiceGCSafePoint(&core.ServiceSafePoint{
```
Comment (rleungx) [inline tests/client/client_test.go:928]: Why comment it?

Comment (MyonKeminta) [reply tests/client/client_test.go:928]: Ah sorry. I forgot to remove it.

File: server/core/storage.go [hunk 2]
```diff
@@ -501,10 +503,46 @@ func (s *Storage) RemoveServiceGCSafePoint(serviceID string) error {
...
+// fixGCWorkerServiceSafepoint tries to fix gc_worker's special service safepoint if it's missing or incorrect. An issue
+// in the older version may have invalid TTL for gc_worker's safepoint, and it also might be missing. gc_worker's
+// safepoint may also be missing when the cluster is just bootstrapped. Detect these cases and fix gc_worker's safepoint
+// if necessary.
+func (s *Storage) fixGCWorkerServiceSafePpoint(allServiceSafePoints []*ServiceSafePoint) (modified bool, err error) {
+	if len(allServiceSafePoints) == 0 {
+		// It's a new cluster, or everything is lost so we have no way to recover it. Initialize gc_worker's service
+		// safepoint to zero.
+		_, err = s.initServiceGCSafePointForGCWorker(0)
+		return true, err
```
Comment (rleungx) [inline server/core/storage.go:515]: What if the initialization is wrong, we still return true?

File: server/core/storage.go [hunk 3]
```diff
@@ -501,10 +503,46 @@ func (s *Storage) RemoveServiceGCSafePoint(serviceID string) error {
...
+			return false, nil
+		}
+		if ssp.SafePoint < min {
+			min = ssp.SafePoint
+		}
+	}
+
+	// gc_worker is missing.
+	_, err = s.initServiceGCSafePointForGCWorker(min)
+	return true, err
```
Comment (rleungx) [inline server/core/storage.go:539]: ditto

File: server/core/storage.go (hunk 2 above)
Comment (MyonKeminta) [reply server/core/storage.go:515]: Yes but I thought err will be not nil here so it doesn't matter 🤔 maybe  it doesn't look good. I'll change it.

File: server/core/storage.go [hunk 4]
```diff
@@ -515,25 +553,52 @@ func (s *Storage) initServiceGCSafePointForGCWorker() (*ServiceSafePoint, error)
...
+		return nil, err
 	}
 
-	min := &ServiceSafePoint{SafePoint: math.MaxUint64}
-	for i, key := range keys {
-		ssp := &ServiceSafePoint{}
-		if err := json.Unmarshal([]byte(values[i]), ssp); err != nil {
+	if modified {
+		// Reload the safepoints
+		keys, allServiceSafePoints, err = loadAll()
```
[the remark this answers is not in the document]
Comment (lichunzhu) [reply server/core/storage.go:587]: What's more, it sames that `loadAll()` will not affect the result of `min`... I think we can remove this logic and `modified`.

**Review by lichunzhu — COMMENTED** [review]
I think we can do 1. check whether do we have gc_worker key 2. compute the min safepoint in one loop. After this loop, if 1 is false, we can insert the gc_worker key.

File: server/core/storage.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (MyonKeminta) [reply server/core/storage.go:587]: The user needs the minimum value among all non-expired safepoints, but I want to fix it with the minimum value including expired-but-not-deleted ones. So the final min value may decrease. It's possible to avoid reloading and do all these things in one loop, but trying to make the code more readable, I choose the less-effective way.

**Comment by MyonKeminta** [comment]
@lichunzhu @rleungx PTAL again thx

File: server/core/storage.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (MyonKeminta) [reply server/core/storage.go]: fixed

File: server/core/storage.go [hunk 5]
```diff
@@ -523,25 +523,49 @@ func (s *Storage) LoadMinServiceGCSafePoint(now time.Time) (*ServiceSafePoint, e
...
+		if ssp.SafePoint < validMin.SafePoint {
+			validMin = ssp
 		}
 	}
 
-	return min, nil
+	if !hasGCWorker {
+		// If there exists some service safepoints but gc_worker is missing, init it with the min value among all
+		// safepoints (including expired ones)
+		return s.initServiceGCSafePointForGCWorker(min)
```
Comment (lichunzhu) [inline server/core/storage.go:565]:
```suggestion
		return s.initServiceGCSafePointForGCWorker(validMin.SafePoint)
```

File: server/core/storage.go [hunk 6]
```diff
@@ -523,25 +523,49 @@ func (s *Storage) LoadMinServiceGCSafePoint(now time.Time) (*ServiceSafePoint, e
...
+			if ssp.ExpiredAt != math.MaxInt64 {
+				ssp.ExpiredAt = math.MaxInt64
+				err = s.SaveServiceGCSafePoint(ssp)
+				if err != nil {
+					return nil, errors.Trace(err)
+				}
+			}
+		}
+
+		if ssp.SafePoint < min {
```
Comment (lichunzhu) [inline server/core/storage.go:549]: If ssp is expired, we may get a wrong `min` here. I suggest deleting `min` and keeping only `validMin`.

**Review by lichunzhu — APPROVED** [review]
Rest LGTM

**Comment by MyonKeminta** [comment]
@lichunzhu updated, PTAL again

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by rleungx — APPROVED** [review]

**Comment by MyonKeminta** [comment]
This PR needs to be cherry-picked to release 4.0. I don't have permission to edit the label.
