### PR TITLE
tests/tso: add IDAllocator to make keyspace test stable

### LINKED ISSUE #8099: Flaky Test TestTSOKeyspaceGroupSplitElection
## Flaky Test

TestTSOKeyspaceGroupManager/TestTSOKeyspaceGroupSplitElection

### Which jobs are failing
test13 https://github.com/tikv/pd/actions/runs/8747656441/attempts/1?pr=8097

### CI link
https://productionresultssa13.blob.core.windows.net/actions-results/e5df1eae-f295-4491-85d8-5cf78389c066/workflow-job-run-f70e23af-2346-53b6-e4b5-faf0c1cc06bc/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-19T04%3A10%3A46Z&sig=O1SP%2FjG%2F2k1ADpdwgFX2grPMh7MxSGVezDekHFV4UFc%3D&sp=r&spr=https&sr=b&st=2024-04-19T04%3A00%3A41Z&sv=2021-12-02

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Close #8099

### What is changed and how does it work?
add IDAllocator to make test stable

```commit-message
```

### Check List

Tests

- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/integrations/mcs/tso/keyspace_group_manager_test.go [hunk 1]
```diff
@@ -56,6 +57,13 @@ type tsoKeyspaceGroupManagerTestSuite struct {
 	pdLeaderServer *tests.TestServer
 	// tsoCluster is the TSO service cluster.
 	tsoCluster *tests.TestTSOCluster
+
+	allocator *mockid.IDAllocator
+}
+
+func (suite *tsoKeyspaceGroupManagerTestSuite) alloc() uint32 {
```
Comment (JmPotato) [inline tests/integrations/mcs/tso/keyspace_group_manager_test.go:64]:
```suggestion
func (suite *tsoKeyspaceGroupManagerTestSuite) allocID() uint32 {
```

**Review by JmPotato — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
