### PR TITLE
scheduler: bugfix for slow-trend-scheduler when timestamp of heartbeats are equal

### LINKED ISSUE #6307: scheduler: `evict-slow-trend` not make sense when heartbeatTS keeps same
## Bug Report
When enabling `evict-slow-trend`, there might exists one case that `slowStore.TS` keeps same with other normal Stores'. In this case, the `checkStoresAreUpdated` won't get expect executive result to trigger evicting slow leaders from the slowStore as the following judgement will not make sense.
https://github.com/tikv/pd/blob/3e6ac89b8ec06b7727fa14477b0ce08da4495bb7/pkg/schedule/schedulers/evict_slow_trend.go#L350-L352

### What did you do?
Enable `evict-slow-trend` and testing the abnormal case that there exists io jitters to one TiKV node.

### What did you expect to see?
`evict-slow-trend` makes sense, triggering leaders evicting from the slow node.

### What did you see instead?
image

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What problem does this PR solve?

Issue Number: Close #6307 

### What is changed and how does it work?

```commit-message
Update the strategy on the judgement whether all timestamps have been updated or not when detecting slow stores.
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by LykxSassinator** [comment]
@innerr PTAL, thx

**Comment by LykxSassinator** [comment]
@bufferflies PTAL,thx

File: pkg/schedule/schedulers/evict_slow_trend.go [hunk 1]
```diff
@@ -322,18 +327,17 @@ func chooseEvictCandidate(cluster schedule.Cluster) (slowStore *core.StoreInfo)
 	}
 
 	storeSlowTrendActionStatusGauge.WithLabelValues("cand.add").Inc()
-	log.Info("evict-slow-trend-scheduler canptured candidate", zap.Uint64("store-id", store.GetID()))
+	log.Info("evict-slow-trend-scheduler captured candidate", zap.Uint64("store-id", store.GetID()))
 	return store
 }
 
-func checkStoresAreUpdated(cluster schedule.Cluster, baseline *core.StoreInfo) bool {
+func checkStoresAreUpdated(cluster schedule.Cluster, slowStoreID uint64, baselineTS time.Time) bool {
```
Comment (bufferflies) [inline pkg/schedule/schedulers/evict_slow_trend.go:334]: where the `baselineTS` is used in this function?

Comment (LykxSassinator) [reply pkg/schedule/schedulers/evict_slow_trend.go:334]: The param `baselineTS` is just kept same with previous naming, and used in the following judgement at line 350:
https://github.com/tikv/pd/blob/3779808515edb6362d8f7d28980afca4af687a62/pkg/schedule/schedulers/evict_slow_trend.go#L350

Comment (bufferflies) [reply pkg/schedule/schedulers/evict_slow_trend.go:334]: Btw， the ts has different name such as `baselineTs`,`slowStoreRecordTS`,`captureTS`,  it's a little strange.

Comment (LykxSassinator) [reply pkg/schedule/schedulers/evict_slow_trend.go:334]: `captureTS` represents the TS when the first slowStore has been captured, it's a prerequisite for later processing.

How about renaming `baselineTS` with `slowStoreCapturedTS` ?

Comment (bufferflies) [reply pkg/schedule/schedulers/evict_slow_trend.go:334]: how about `slowStoreRecordTS` ?

**Review by bufferflies — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]
