### PR TITLE
etcdutil, leadership: make more high availability

### LINKED ISSUE #6554: TSO primary election took 14 minutes after PD(API) Pods being deleted at the same time and PD(API) leader being re-elected
## Enhancement Task
What did you do?
In dev env, 

1. kubectl delete pod serverless-cluster-pd-0 serverless-cluster-pd-1 serverless-cluster-pd-2 -n tidb-serverless --force --grace-period=0
2. tso_0 secondary
```
[2023/06/02 03:06:31.612 +00:00] [ERROR] [register.go:82] ["keep alive failed"] [key=/ms/7187976276065784319/tso/registry/http://pd-tso-server-0.tso-service.tidb-serverless.svc:2379]
**repeat the following 4 lines every 1s**
[2023/06/02 03:06:46.624 +00:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] [target=endpoint://client-bf54c660-20ab-44b5-ab7b-5bc8cbf44d8b/serverless-cluster-pd.tidb-serverless.svc:2379] [attempt=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
[2023/06/02 03:06:46.624 +00:00] [WARN] [etcdutil.go:136] ["kv gets too slow"] [request-key=/ms/7187976276065784319/tso/00000/dc-location] [cost=10.000772311s] [error="context deadline exceeded"]
[2023/06/02 03:06:46.624 +00:00] [ERROR] [etcdutil.go:141] ["load from etcd meet error"] [key=/ms/7187976276065784319/tso/00000/dc-location] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:06:46.624 +00:00] [ERROR] [allocator_manager.go:848] ["get cluster dc-locations from etcd failed"] [] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
...
[2023/06/02 03:20:46.623 +00:00] [WARN] [etcdutil.go:136] ["kv gets too slow"] [request-key=/ms/7187976276065784319/tso/00000/dc-location] [cost=10.000127145s] [error="context deadline exceeded"]
[2023/06/02 03:20:46.623 +00:00] [ERROR] [etcdutil.go:141] ["load from etcd meet error"] [key=/ms/7187976276065784319/tso/00000/dc-location] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:20:46.623 +00:00] [ERROR] [allocator_manager.go:848] ["get cluster dc-locations from etcd failed"] [] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:20:46.623 +00:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] [target=endpoint://client-bf54c660-20ab-44b5-ab7b-5bc8cbf44d8b/serverless-cluster-pd.tidb-serverless.svc:2379] [attempt=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
[2023/06/02 03:21:46.624 +00:00] [WARN] [etcdutil.go:136] ["kv gets too slow"] [request-key=/ms/7187976276065784319/tso/00000/dc-location] [cost=10.000692425s] [error="context deadline exceeded"]
[2023/06/02 03:21:46.624 +00:00] [ERROR] [etcdutil.go:141] ["load from etcd meet error"] [key=/ms/7187976276065784319/tso/00000/dc-location] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:21:46.624 +00:00] [ERROR] [allocator_manager.go:848] ["get cluster dc-locations from etcd failed"] [] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:21:46.624 +00:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] [target=endpoint://client-bf54c660-20ab-44b5-ab7b-5bc8cbf44d8b/serverless-cluster-pd.tidb-serverless.svc:2379] [attempt=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
**[2023/06/02 03:21:53.550 +00:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] [target=endpoint://client-bf54c660-20ab-44b5-ab7b-5bc8cbf44d8b/serverless-cluster-pd.tidb-serverless.svc:2379] [attempt=0] [error="rpc error: code = Unavailable desc = transport is closing"]**
[2023/06/02 03:21:53.564 +00:00] [WARN] [leadership.go:194] ["required revision has been compacted, use the compact revision"] [required-revision=1800213] [compact-revision=2353567]
[2023/06/02 03:21:53.804 +00:00] [INFO] [leadership.go:211] ["current leadership is deleted"] [leader-key=/ms/7187976276065784319/tso/00000/primary] [purpose="keyspace group primary election"]
[2023/06/02 03:21:53.804 +00:00] [INFO] [global_allocator.go:553] ["the tso primary has changed, try to re-campaign a primary"] []
[2023/06/02 03:21:53.804 +00:00] [INFO] [global_allocator.go:562] ["start to campaign the primary"] [] [campaign-tso-primary-name=http://pd-tso-server-0.tso-service.tidb-serverless.svc:2379-00000]
[2023/06/02 03:21:53.806 +00:00] [INFO] [lease.go:66] ["lease granted"] [lease-id=7473592164536214571] [lease-timeout=3] [purpose="keyspace group primary election"]
[2023/06/02 03:21:53.809 +00:00] [INFO] [leadership.go:122] ["check campaign resp"] [resp="{\"header\":{\"cluster_id\":10920548605668718190,\"member_id\":13485048042260555703,\"revision\":2481213,\"raft_term\":23},\"succeeded\":true,\"responses\":[{\"Response\":{\"ResponsePut\":{\"header\":{\"revision\":2481213}}}}]}"]
[2023/06/02 03:21:53.809 +00:00] [INFO] [leadership.go:131] ["write leaderData to leaderPath ok"] [leaderPath=/ms/7187976276065784319/tso/00000/primary] [purpose="keyspace group primary election"]
[2023/06/02 03:21:53.809 +00:00] [INFO] [global_allocator.go:595] ["campaign tso primary ok"] [] [campaign-tso-primary-name=http://pd-tso-server-0.tso-service.tidb-serverless.svc:2379-00000]
[2023/06/02 03:21:53.809 +00:00] [INFO] [global_allocator.go:606] ["initializing the global tso allocator"]
[2023/06/02 03:21:53.809 +00:00] [INFO] [lease.go:143] ["start lease keep alive worker"] [interval=1s] [purpose="keyspace group primary election"]
[2023/06/02 03:21:53.931 +00:00] [INFO] [tso.go:185] ["sync and save timestamp"] [last=2023/06/02 03:06:29.715 +00:00] [save=2023/06/02 03:21:56.918 +00:00] [next=2023/06/02 03:21:53.918 +00:00]
[2023/06/02 03:21:53.931 +00:00] [INFO] [global_allocator.go:625] ["tso primary is ready to serve"] [] [tso-primary-name=http://pd-tso-server-0.tso-service.tidb-serverless.svc:2379-00000]
```
3. tso_1 was the primary
```
[2023/06/02 03:06:29.675 +00:00] [INFO] [lease.go:126] ["lease timeout"] [expire=2023/06/02 03:06:31.673 +00:00] [purpose="keyspace group primary election"]
[2023/06/02 03:06:29.675 +00:00] [WARN] [lease.go:158] ["lease keep alive failed"] [purpose="keyspace group primary election"] [error="context canceled"]
[2023/06/02 03:06:29.675 +00:00] [INFO] [lease.go:172] ["stop lease keep alive worker"] [purpose="keyspace group primary election"]
[2023/06/02 03:06:29.675 +00:00] [WARN] [lease.go:158] ["lease keep alive failed"] [purpose="keyspace group primary election"] [error="context canceled"]
[2023/06/02 03:06:29.675 +00:00] [WARN] [lease.go:158] ["lease keep alive failed"] [purpose="keyspace group primary election"] [error="context canceled"]
[2023/06/02 03:06:30.999 +00:00] [ERROR] [register.go:82] ["keep alive failed"] [key=/ms/7187976276065784319/tso/registry/http://pd-tso-server-1.tso-service.tidb-serverless.svc:2379]
[2023/06/02 03:06:31.681 +00:00] [INFO] [global_allocator.go:636] ["no longer a primary because lease has expired, the tso primary will step down"] []
[2023/06/02 03:06:32.682 +00:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] [target=endpoint://client-13874eab-e8c6-4950-b46f-f708fdd4ca9d/serverless-cluster-pd.tidb-serverless.svc:2379] [attempt=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
[2023/06/02 03:06:32.682 +00:00] [INFO] [tso.go:384] ["reset the timestamp in memory"]
[2023/06/02 03:06:39.716 +00:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] [target=endpoint://client-13874eab-e8c6-4950-b46f-f708fdd4ca9d/serverless-cluster-pd.tidb-serverless.svc:2379] [attempt=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
[2023/06/02 03:06:39.716 +00:00] [WARN] [etcdutil.go:136] ["kv gets too slow"] [request-key=/pd/7187976276065784319/timestamp] [cost=10.00049442s] [error="context deadline exceeded"]
[2023/06/02 03:06:39.716 +00:00] [ERROR] [etcdutil.go:141] ["load from etcd meet error"] [key=/pd/7187976276065784319/timestamp] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:06:39.716 +00:00] [WARN] [tso.go:322] ["save timestamp failed"] [dc-location=global] [timestamp-path=timestamp] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:06:39.716 +00:00] [WARN] [allocator_manager.go:801] ["failed to update allocator's timestamp"] [] [dc-location=global] [name=http://pd-tso-server-1.tso-service.tidb-serverless.svc:2379-00000] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:06:39.716 +00:00] [INFO] [tso.go:384] ["reset the timestamp in memory"]
[2023/06/02 03:06:42.683 +00:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] [target=endpoint://client-13874eab-e8c6-4950-b46f-f708fdd4ca9d/serverless-cluster-pd.tidb-serverless.svc:2379] [attempt=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
[2023/06/02 03:06:42.683 +00:00] [WARN] [etcdutil.go:136] ["kv gets too slow"] [request-key=/ms/7187976276065784319/tso/00000/primary] [cost=10.001048119s] [error="context deadline exceeded"]
[2023/06/02 03:06:42.683 +00:00] [ERROR] [etcdutil.go:141] ["load from etcd meet error"] [key=/ms/7187976276065784319/tso/00000/primary] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:06:42.683 +00:00] [ERROR] [participant.go:213] ["getting the leader meets error"] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
...
repeated the 4 log lines every 10 or 11 seconds.
[2023/06/02 03:06:52.885 +00:00] [WARN] [etcdutil.go:136] ["kv gets too slow"] [request-key=/ms/7187976276065784319/tso/00000/primary] [cost=10.001082809s] [error="context deadline exceeded"]
[2023/06/02 03:06:52.885 +00:00] [ERROR] [etcdutil.go:141] ["load from etcd meet error"] [key=/ms/7187976276065784319/tso/00000/primary] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:06:52.885 +00:00] [ERROR] [participant.go:213] ["getting the leader meets error"] [error="[PD:etcd:ErrEtcdKVGet]context deadline exceeded: context deadline exceeded"]
[2023/06/02 03:06:52.885 +00:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] [target=endpoint://client-13874eab-e8c6-4950-b46f-f708fdd4ca9d/serverless-cluster-pd.tidb-serverless.svc:2379] [attempt=0] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"]
...
[2023/06/02 03:22:00.220 +00:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] [target=endpoint://client-13874eab-e8c6-4950-b46f-f708fdd4ca9d/serverless-cluster-pd.tidb-serverless.svc:2379] [attempt=0] [error="rpc error: code = Unavailable desc = transport is closing"]
[2023/06/02 03:22:00.220 +00:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] [target=endpoint://client-13874eab-e8c6-4950-b46f-f708fdd4ca9d/serverless-cluster-pd.tidb-serverless.svc:2379] [attempt=0] [error="rpc error: code = Unavailable desc = transport is closing"]
[2023/06/02 03:22:00.248 +00:00] [WARN] [etcdutil.go:136] ["kv gets too slow"] [request-key=/ms/7187976276065784319/tso/00000/primary] [cost=9.450242803s] []
[2023/06/02 03:22:00.249 +00:00] [INFO] [global_allocator.go:547] ["start to watch the primary"] [] [campaign-tso-primary-name=http://pd-tso-server-1.tso-service.tidb-serverless.svc:2379-00000] [tso-primary="name:\"http://pd-tso-server-0.tso-service.tidb-serverless.svc:2379-00000\" id:10272136419596665458 listen_urls:\"http://pd-tso-server-0.tso-service.tidb-serverless.svc:2379\" "]
```

**What did you expect to see?**
TSO primary election within 15 seconds

**What did you see instead?**
TSO primary election took 14 minutes

**What version of PD are you using (pd-server -V)?**
tidbcloud/pd-cse release-6.6-keyspace 9e1e2de5194655c2e1224ce94057e7f7fb5f7eb4
tikv/pd master

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #6554 https://github.com/tikv/pd/issues/6442

#### leadership

1. make leadership exit watch loop as soon as possible when etcd is unavailable

2. add some other logic similar to loopwatcher, such as `revision++`, `wresp.Err() != nil` and `WithRequireLeader`

#### etcd client

Because the etcd client's keepalive is based on the grpc connection, it can only determine if the network is working properly.

And because etcd client's balancer only supports round-robin policy, it cannot be set to connect only to the leader.

So when the etcd client's original connection is not working for various reasons, such as network isolation, leader-io-hang, or tcp half-open connection, we need to switch the connection to an available node in a more timely manner.

It is easy to think that we can create additional goroutines to check the health of the connections, so for each etcd client, we will create two goroutines, one goroutine to check the health of the node and another goroutine to synchronize the members.

And grpc substream retry policy is exponential rather than linear, which also needs to change it.

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
1. pd-leader-io-hang

   image
   only update pd etcd client, there are two 8027 error
   image
   update pd and tidb etcd client at the same, there is no any 8027 error

2. pd-leader-to-all-network-partition

    image
    only update pd etcd client, there is a warning with 21.7% drop.
    image
    update pd and tidb etcd client at the same, there are some warnings, but all warnings are just a little over 20% and below 25%

3. Manual stop and random restart api server, observe when tso server watch primary
https://github.com/tikv/pd/pull/6577#issuecomment-1597015549
image
image

4. Test 30 times

    Step: `kubectl delete pod serverless-cluster-pd-0 serverless-cluster-pd-1 serverless-cluster-pd-2 -n tidb-serverless --force --grace-period=0`
    note: replace tso server with https://github.com/tikv/pd/pull/6577 use pd-tso-bench https://github.com/tikv/pd/pull/6699
    Result: can recovery in 2 min

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by rleungx** [comment]
Any progress on this PR?

**Comment by lhy1024** [comment]
> Any progress on this PR?

In addition to trying to test with `iptable` and `tcpkill`, I tried to start the server locally and do a kill test.

Test step:
1. `./pd-server services api` ` ./pd-server services tso --listen-addr="http://127.0.0.1:3379/" --backendendpoints="http://127.0.0.1:2379/"` `./pd-server services tso --listen-addr="http://127.0.0.1:3380/" --backend-endpoints="http://127.0.0.1:2379/"`
2. `kill` or `kill -9` with `api server`
3. wait random time to restart `api server`
4. observe when tso server finish election or watch leader.


1. I test with pd-cse and this pr. For one api server, this pr is not better than pd-cse with `keep-alive`
```
client, err := clientv3.New(clientv3.Config{
        Endpoints:            []string{acURL.String()},
        DialTimeout:          defaultEtcdClientTimeout,
        TLS:                  tlsConfig,
        LogConfig:            &lgc,
        DialKeepAliveTime:    defaultDialKeepAliveTime,
        DialKeepAliveTimeout: defaultDialKeepAliveTimeout,
    })
```
image

2. I try use `session` to keep alive, but when I `kill` or `kill -9` api server, there is no any `session` log, which means the code doesn't touch `session.Done`.
```
func (ls *Leadership) Watch(serverCtx context.Context, revision int64) {
    if ls == nil {
        return
    }
    session, err := concurrency.NewSession(
        ls.client, concurrency.WithTTL(180),
    ) // 3 minutes
    if err != nil {
        return
    }
   ...
   for {
   ....
       case <-session.Done():
            // session closed, return
            log.Info("leadership session is done", zap.String("leader-key", ls.leaderKey),
                zap.String("purpose", ls.purpose))
            return
    ....
   }
}
```

**Comment by lhy1024** [comment]
Similarly, I test other ways
image

3. detect unhealthy etcd cluster and exit watch loop
4. pick some etcd pr 
5. use the new client healthy strategy, it is valid for the current test

When creating the client, create two new goroutines, one goroutine synchronizes the endpoint and stores it in a sync.map and periodically checks if it is expired, the other goroutine establishes n connections to check the health of the nodes, the advantage of this is to avoid the failure of other nodes to affect the overall latency, but also to avoid the delay when synchronizing This has the advantage of avoiding the overall latency caused by the failure of other nodes and the latency caused by the lag in synchronization.
If there is no node available, try to reset endpoints to refresh the connection

**Comment by rleungx** [comment]
Is it ready to be reviewed?

File: pkg/election/leadership.go [hunk 1]
```diff
@@ -182,26 +188,67 @@ func (ls *Leadership) Watch(serverCtx context.Context, revision int64) {
...
+	failpoint.Inject("fastTick", func() {
+		timeout = 5 * time.Second
+		interval = 1 * time.Second
+	})
+	ticker := time.NewTicker(interval)
+	defer ticker.Stop()
+	lastHealthyTime := time.Now()
+
 	watcher := clientv3.NewWatcher(ls.client)
 	defer watcher.Close()
```
Comment (binshi-bing) [inline pkg/election/leadership.go:203]: How about adding log when we exits the get leader loop?
```suggestion
	defer watcher.Close()
	defer log.Info("exit ...")
```

File: pkg/election/leadership.go [hunk 2]
```diff
@@ -213,19 +260,15 @@ func (ls *Leadership) Watch(serverCtx context.Context, revision int64) {
...
+			revision = wresp.Header.Revision + 1
 		}
-
-		select {
-		case <-ctx.Done():
-			// server closed, return
-			return
-		default:
-		}
+		watchChanCancel()
```
Comment (binshi-bing) [inline pkg/election/leadership.go:271]: If I'm understanding is right, we cancel the channel here immediately after we process line 242 ~ 269, which mightn't be as expected. Shouldn't it goes back and executes select at 233 after line 268?

File: pkg/utils/etcdutil/etcdutil.go [hunk 3]
```diff
@@ -144,6 +144,20 @@ func EtcdKVGet(c *clientv3.Client, key string, opts ...clientv3.OpOption) (*clie
...
 
+// IsHealthy checks if the etcd is healthy.
+func IsHealthy(ctx context.Context, client *clientv3.Client) bool {
+	timeout := DefaultRequestTimeout
+	failpoint.Inject("fastTick", func() {
+		timeout = 100 * time.Millisecond
+	})
+	ctx, cancel := context.WithTimeout(clientv3.WithRequireLeader(ctx), timeout)
+	defer cancel()
+	_, err := client.Get(ctx, "health")
```
Comment (binshi-bing) [inline pkg/utils/etcdutil/etcdutil.go:155]: Is this etcd standard heartbeat or health check API?

**Review by binshi-bing — COMMENTED** [review]
left few comments. no complete yet.

File: pkg/utils/etcdutil/etcdutil.go [hunk 4]
```diff
@@ -196,72 +210,233 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
+		return client, err
+	}
+
+	checker := &healthyChecker{
+		tlsConfig: tlsConfig,
+	}
+	eps := syncUrls(client)
+	checker.update(eps)
+
+	// Create a goroutine to check the health of etcd endpoints periodically.
```
Comment (binshi-bing) [inline pkg/utils/etcdutil/etcdutil.go:262]: Do we need to add sync.WatchGroup for these two goroutines?

File: pkg/utils/etcdutil/etcdutil.go (hunk 3 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:155]: yes, etcd also use this key to check health https://github.com/etcd-io/etcd/blob/85b640cee793e25f3837c47200089d14a8392dc7/etcdctl/ctlv3/command/ep_command.go#L121

File: pkg/utils/etcdutil/etcdutil.go (hunk 4 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:262]: wait group? I passed in ctx and wg in a previous version and later found that client.ctx could control the exit of these two gotoutines.

File: pkg/election/leadership.go (hunk 2 above)
Comment (lhy1024) [reply pkg/election/leadership.go:271]: it is copied from loopwatcher, where there is a similar problem. I will also fix it.

File: pkg/utils/etcdutil/etcdutil.go [hunk 5]
```diff
@@ -196,72 +210,233 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
+
+	tickerInterval := defaultDialKeepAliveTime
+	failpoint.Inject("fastTick", func() {
+		tickerInterval = 100 * time.Millisecond
+	})
+	failpoint.Inject("closeTick", func() {
+		tickerInterval = 0
+	})
+	if tickerInterval == 0 {
+		return client, err
```
[the remark this answers is not in the document]
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:253]: It only is used to test now.

File: pkg/utils/etcdutil/etcdutil.go (hunk 4 above)
Comment (binshi-bing) [reply pkg/utils/etcdutil/etcdutil.go:262]: Yes, sync.WaitGroup. ok

File: pkg/election/leadership.go [hunk 6]
```diff
@@ -182,26 +188,69 @@ func (ls *Leadership) Watch(serverCtx context.Context, revision int64) {
...
-	// If the revision is compacted, will meet required revision has been compacted error.
-	// In this case, use the compact revision to re-watch the key.
 	for {
 		failpoint.Inject("delayWatcher", nil)
-		rch := watcher.Watch(ctx, ls.leaderKey, clientv3.WithRev(revision))
-		for wresp := range rch {
+		// In order to prevent a watch stream being stuck in a partitioned node,
+		// make sure to wrap context with "WithRequireLeader".
+		watchChanCtx, watchChanCancel := context.WithCancel(clientv3.WithRequireLeader(serverCtx))
+		defer watchChanCancel()
```
Comment (binshi-bing) [inline pkg/election/leadership.go:209]: watchChanCancel() is at places which needs to be handled very carefully and is error prone. We can make it much clearer and easier in the following way (BTW, cancel() can be called multiple times):
```suggestion
func GetLeader(c *clientv3.Client, leaderPath string) (*pdpb.Member, int64, error) {
    var watchChanCancel context.Cancel
    defer func() {
        if watchChanCancel != nil {
	    watchChanCancel()
	}
    } ()
    
    for {
        ...
        if watchChanCancel != nil {
            watchChanCancel()
         }
         watchChanCtx, watchChanCancel := context.WithCancel(clientv3.WithRequireLeader(serverCtx))
         ...
```

File: pkg/election/leadership.go [hunk 7]
```diff
@@ -182,26 +188,69 @@ func (ls *Leadership) Watch(serverCtx context.Context, revision int64) {
...
+
+		watchChan := watcher.Watch(watchChanCtx, ls.leaderKey, clientv3.WithRev(revision))
+		lastHealthyTime = time.Now()
+	WatchChan:
+		select {
+		case <-serverCtx.Done():
+			// server closed, return
+			return
+		case <-ticker.C:
+			if !etcdutil.IsHealthy(serverCtx, ls.client) {
```
Comment (binshi-bing) [inline pkg/election/leadership.go:239]: To avoid temporary failure and false alarm, we'd better to check etcd health status multiple times, if it's unhealthy for a defined period (e.g., check heath 5 times every 1 second and all returned unhealthy status), then we cancel the wach channel and re-watch.

**Review by binshi-bing — COMMENTED** [review]
left few more comments.

File: pkg/election/leadership.go (hunk 6 above)
Comment (rleungx) [reply pkg/election/leadership.go:209]: Agree. Here we might have too many defer.

File: pkg/utils/etcdutil/etcdutil.go [hunk 8]
```diff
@@ -196,72 +210,233 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
+		// check if client exists, if not, create one, if exists, check if it's offline or disconnected.
+		if client, ok := checker.Load(ep); ok {
+			lastHealthy := client.(*healthyClient).lastHealth
+			if time.Since(lastHealthy) > etcdServerOfflineTimeout {
+				log.Info("[etcd client] some etcd server maybe offline", zap.String("endpoint", ep))
+				checker.Delete(ep)
+			}
+			if time.Since(lastHealthy) > etcdServerDisconnectedTimeout {
+				// try to update client to trigger reconnect
+				checker.addClient(ep, lastHealthy)
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil.go:373]: Does the previous one need to be closed?

File: pkg/utils/etcdutil/etcdutil.go [hunk 9]
```diff
@@ -196,72 +210,233 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
+
+	// Create a goroutine to check the health of etcd endpoints periodically.
+	go func(client *clientv3.Client) {
+		defer logutil.LogPanic()
+		ticker := time.NewTicker(tickerInterval)
+		defer ticker.Stop()
+		lastAvailable := time.Now()
+		for {
+			select {
+			case <-client.Ctx().Done():
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil.go:270]: need a log?

File: pkg/utils/etcdutil/etcdutil.go [hunk 10]
```diff
@@ -196,72 +210,233 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
+			case <-ticker.C:
+				usedEps := client.Endpoints()
+				healthyEps := checker.patrol(client.Ctx())
+				if len(healthyEps) == 0 {
+					// when all endpoints are unhealthy, try to reset endpoints to update connect
+					// rather than delete them to avoid there is no any endpoint in client.
+					if time.Since(lastAvailable) > etcdServerDisconnectedTimeout {
+						log.Info("[etcd client] no available endpoint, try to reset endpoints", zap.Strings("last-endpoints", usedEps))
+						client.SetEndpoints([]string{}...)
+						client.SetEndpoints(usedEps...)
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil.go:281]: Why reset will help?

File: pkg/utils/etcdutil/etcdutil.go [hunk 11]
```diff
@@ -196,72 +210,233 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
+	}
+	sort.Strings(a)
+	sort.Strings(b)
+	for i, v := range a {
+		if v != b[i] {
+			return false
+		}
+	}
+	return true
+}
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil.go:427]: use StringsEqual?

Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:427]: `StringsEqual` compares strings one by one, while at `isEqual` we don't care about the order

**Comment by lhy1024** [comment]
5. Resource test

Overall, there is no resource leakage and no particular extra usage. CPU and memory averages have not changed much, but goroutine has increased more than expected, and I will determine if this is expected

|           | pd      | tidb    | cpu max | cpu average | memory max | memory average | goroutine max | goroutine average |  tcms id | 
|-----------|---------|---------|---------|-------------|------------|----------------|---------------|-------------------|---|
| base line | 6.6-cse | 6.6-cse |    36.1%     |   13.1%          |      340MB      |     312MB           |        651       |       528            | 1816501  |  
| case 1     |    + etcd client     |    6.6-cse     |     37.5%    |    13.4%          |    421MB        |   321MB             |       758        |     619              |  1745165 | 
|   case 2         |   + etcd client        |    6.6-cse     |   60.1%      |   13.6%          |    400MB        |   284MB             |      771         |        643           |  1816506  |
|  case 3           |   + etcd client        |  + etcd client         |   55.9%      |     15.1%        |     404MB       |   281MB             |       752        |        608           | 1816607  |

image
image
image
image

File: pkg/utils/etcdutil/etcdutil.go [hunk 12]
```diff
@@ -196,72 +210,237 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
-// FIXME: But it cannot switch etcd endpoints as soon as possible when one of endpoints is with io hang.
-func createEtcdClientWithMultiEndpoint(tlsConfig *tls.Config, acUrls []url.URL) (*clientv3.Client, error) {
-	if len(acUrls) == 0 {
-		return nil, errs.ErrNewEtcdClient.FastGenByArgs("no available etcd address")
-	}
-	endpoints := make([]string, 0, len(acUrls))
-	for _, u := range acUrls {
-		endpoints = append(endpoints, u.String())
-	}
+func newClient(tlsConfig *tls.Config, endpoints ...string) (*clientv3.Client, error) {
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil.go:220]: No need to check the length of endpoints?

File: pkg/utils/etcdutil/etcdutil.go [hunk 13]
```diff
@@ -196,72 +210,237 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
+	client, err := newClient(tlsConfig, urls...)
+	if err != nil {
+		return nil, err
+	}
+
+	tickerInterval := defaultDialKeepAliveTime
+	failpoint.Inject("fastTick", func() {
+		tickerInterval = 100 * time.Millisecond
+	})
+	failpoint.Inject("closeTick", func() {
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil.go:249]: Why not just return?

File: pkg/utils/etcdutil/etcdutil.go [hunk 14]
```diff
@@ -196,72 +210,237 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
+				return
+			case <-ticker.C:
+				usedEps := client.Endpoints()
+				healthyEps := checker.patrol(client.Ctx())
+				if len(healthyEps) == 0 {
+					// when all endpoints are unhealthy, try to reset endpoints to update connect
+					// rather than delete them to avoid there is no any endpoint in client.
+					if time.Since(lastAvailable) > etcdServerDisconnectedTimeout {
+						log.Info("[etcd client] no available endpoint, try to reset endpoints", zap.Strings("last-endpoints", usedEps))
+						client.SetEndpoints([]string{}...)
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil.go:286]: What is it used for?

File: pkg/utils/etcdutil/etcdutil.go [hunk 15]
```diff
@@ -196,72 +210,237 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
+						client.SetEndpoints(usedEps...)
+					}
+				} else {
+					if !isEqual(healthyEps, usedEps) {
+						client.SetEndpoints(healthyEps...)
+						change := fmt.Sprintf("%d->%d", len(usedEps), len(healthyEps))
+						etcdStateGauge.WithLabelValues("endpoints").Set(float64(len(healthyEps)))
+						log.Info("[etcd client] update endpoints", zap.String("num-change", change),
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil.go:294]: I think just printing them is ok?

File: pkg/election/leadership.go [hunk 16]
```diff
@@ -182,26 +188,81 @@ func (ls *Leadership) Watch(serverCtx context.Context, revision int64) {
...
+	lastHealthyTime := time.Now()
+
 	watcher := clientv3.NewWatcher(ls.client)
 	defer watcher.Close()
-	ctx, cancel := context.WithCancel(serverCtx)
-	defer cancel()
-	// The revision is the revision of last modification on this key.
-	// If the revision is compacted, will meet required revision has been compacted error.
-	// In this case, use the compact revision to re-watch the key.
+	var watchChanCancel *context.CancelFunc
```
[the remark this answers is not in the document]
Comment (lhy1024) [reply pkg/election/leadership.go:204]: If not use a pointer, govet will report the error.
18724658-5b12-4f52-978c-cc293d3359a1
81593c4f-0dfc-44e0-9c8f-c0d862a32135

File: pkg/utils/etcdutil/etcdutil.go (hunk 14 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:286]: It will call [resolverGroup.SetEndpoints](https://github.com/etcd-io/etcd/blob/85b640cee793e25f3837c47200089d14a8392dc7/clientv3/client.go) , which will call [cc.NewAddress(addrs)](https://github.com/etcd-io/etcd/blob/85b640cee793e25f3837c47200089d14a8392dc7/clientv3/balancer/resolver/endpoint/endpoint.go#L89), which will call [updateResolverState](https://github.com/grpc/grpc-go/blob/f5b0812e6fe574d90da76b205e9eb51f6ddb1919/resolver_conn_wrapper.go#L183), which will call [updateClientConnState](https://github.com/grpc/grpc-go/blob/f5b0812e6fe574d90da76b205e9eb51f6ddb1919/clientconn.go#L638), which will call [balancer.HandleResolvedAddrs](https://github.com/grpc/grpc-go/blob/f5b0812e6fe574d90da76b205e9eb51f6ddb1919/balancer_conn_wrappers.go#L129)

It will close SubConn in https://github.com/etcd-io/etcd/blob/85b640cee793e25f3837c47200089d14a8392dc7/clientv3/balancer/balancer.go#L175 

If we don't close it manual, it will retry in [resetTransport](https://github.com/grpc/grpc-go/blob/f5b0812e6fe574d90da76b205e9eb51f6ddb1919/clientconn.go#L1082), and grpc use [exponential backoff strategy](https://github.com/grpc/grpc-go/blob/f5b0812e6fe574d90da76b205e9eb51f6ddb1919/internal/backoff/backoff.go#L43) by default, which means etcd client need to wait longer when etcd server is down.

In test, if etcd restart interval is 5min, the backoff interval in resetTransport maybe 2m16.425989119s

File: pkg/utils/etcdutil/etcdutil.go (hunk 15 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:294]: The number of etcd servers is three to five that I don't think printing them all would cause any additional trouble

File: pkg/utils/etcdutil/etcdutil.go (hunk 12 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:220]: I think only adding a check in CreateEtcdClient seems to be enough.

File: pkg/utils/etcdutil/etcdutil.go (hunk 10 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:287]: see https://github.com/tikv/pd/pull/6577#discussion_r1259144016

File: pkg/election/leadership.go (hunk 7 above)
Comment (lhy1024) [reply pkg/election/leadership.go:247]: ok, I have added it in https://github.com/tikv/pd/blob/5b3378404f35b1731845b1ac1253181d414037e4/pkg/election/leadership.go#L247

File: pkg/election/leadership.go (hunk 6 above)
Comment (lhy1024) [reply pkg/election/leadership.go]: ok, I have added it in https://github.com/tikv/pd/blob/5b3378404f35b1731845b1ac1253181d414037e4/pkg/election/leadership.go#L204

File: pkg/election/leadership.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (rleungx) [reply pkg/election/leadership.go:204]: How about just skipping the lint if you are sure about it? It seems a known problem of go analysis.

File: pkg/utils/etcdutil/etcdutil.go (hunk 15 above)
Comment (rleungx) [reply pkg/utils/etcdutil/etcdutil.go:297]: I mean not just print the number but print the addresses?

File: pkg/utils/etcdutil/etcdutil.go (hunk 12 above)
Comment (rleungx) [reply pkg/utils/etcdutil/etcdutil.go:220]: only CreateEtcdClient will call it?

File: pkg/utils/etcdutil/etcdutil.go (hunk 14 above)
Comment (rleungx) [reply pkg/utils/etcdutil/etcdutil.go:289]: Will it break the normal connection?

File: pkg/utils/etcdutil/etcdutil.go (hunk 12 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:220]: another is `healthyChecker.addClient`, it will always pass an endpoint.

File: pkg/utils/etcdutil/etcdutil.go (hunk 14 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:289]: It is triggered only when all endpoints are unavailable for a sustained period of time.

File: pkg/utils/etcdutil/etcdutil.go (hunk 15 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:297]: how about printing diff of addresses rather than all the last addresses and current addresses?

File: pkg/election/leadership.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (lhy1024) [reply pkg/election/leadership.go:204]: I think pointer is acceptable

File: pkg/utils/etcdutil/etcdutil.go (hunk 15 above)
Comment (rleungx) [reply pkg/utils/etcdutil/etcdutil.go:297]: I think it's ok to print them all if the operation is not frequent.

File: pkg/utils/etcdutil/etcdutil.go (hunk 14 above)
Comment (rleungx) [reply pkg/utils/etcdutil/etcdutil.go:289]: https://github.com/tikv/pd/pull/6577/files#diff-bc08534cb4c71e0934cbd39c6cb3fb6a1d5bde0729cd2c81c484ff760ab00b87R317-R318 for this goroutine, are they unavailable?

File: pkg/utils/etcdutil/etcdutil.go (hunk 15 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:297]: ok, it only prints when endpoints changed, for example, network partition and recover, pd leader io hang and recover, etcd scale-in or scale-out.

File: pkg/utils/etcdutil/etcdutil.go (hunk 12 above)
Comment (rleungx) [reply pkg/utils/etcdutil/etcdutil.go:220]: Then what if we have some other functions call it later?

File: pkg/utils/etcdutil/etcdutil.go (hunk 14 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:289]: When all endpoints are unavailable, syncUrls also will be failed to list members, so it cannot help to recover as soon as possible in this case.

And client.SetEndpoints with empty and immediately set endpoints with used endpoints, subconn is removed and created again, it do not affect `syncUrls` when cluster recover.

In a word, L286 and L287 are used to linear retry rather than exponential.

File: pkg/election/leadership.go [hunk 17]
```diff
@@ -182,26 +188,81 @@ func (ls *Leadership) Watch(serverCtx context.Context, revision int64) {
...
+			case <-serverCtx.Done():
+				// server closed, return
+				return
+			case <-ticker.C:
+				// continue to check the etcd availability
+				continue
+			}
+		}
+
+		watchChan := watcher.Watch(watchChanCtx, ls.leaderKey, clientv3.WithRev(revision))
```
Comment (binshi-bing) [inline pkg/election/leadership.go:240]: Regarding #6554 "_TSO primary election took 14 minutes after PD(API) Pods being deleted at the same time and PD(API) leader being re-elected_",  I have two questions:
1. If watch can't exit when etcd isn't available is the main reason, it only explains the seconday, which watches the leader here, can't be re-elected as the new primary, and it can't explain why the old primary can't be re-elected as the new primary. What happened on the old primary? Did the old primary also get stuck in some watch loop?
2. It seems to me what we're thinking is, during the long duration between PD(API) Pods being deleted at the same time and PD(API) leader being re-elected, the watch here won't exit, and even after PD (API) leader is back, the watch here somehow still can't catch the lease lost/expired event. Is my understanding correct? If yes, how long is the unsafe duration of PD(API) leader being offline (once this unsafe duration is exceeded, the watcher here still can't catch the lease lost/expired event)? And the setting value of "unhealthyTimeout" needs to be less than this unsafe duration.

Comment (binshi-bing) [reply pkg/election/leadership.go:240]: I do think the current PR can help to mitigate the situation even without perfect solution or answers to 1 and 2, because with this pr, it seems that the secondary can be elected as the new primary which addressed the question 1 above and the question 2 is a parameter tuning problem.

**Review by binshi-bing — APPROVED** [review]
left a few comments. The rest looks good to me

File: pkg/election/leadership.go (hunk 17 above)
Comment (lhy1024) [reply pkg/election/leadership.go:240]: It's not sure because the watch loop can't exit that it takes fifteen minutes to re-elect, there could be some reasons, stuck on [grpc retry](https://github.com/tikv/pd/pull/6577#discussion_r1259144016), stuck on [tcp retry](https://github.com/tikv/pd/issues/6554#issuecomment-1582790457), or watch stuck on etcd watch.

File: pkg/election/leadership.go [hunk 18]
```diff
@@ -182,26 +188,81 @@ func (ls *Leadership) Watch(serverCtx context.Context, revision int64) {
...
 			// meet compacted error, use the compact revision.
 			if wresp.CompactRevision != 0 {
 				log.Warn("required revision has been compacted, use the compact revision",
 					zap.Int64("required-revision", revision),
 					zap.Int64("compact-revision", wresp.CompactRevision))
 				revision = wresp.CompactRevision
-				break
-			}
-			if wresp.Canceled {
+				continue
```
[the remark this answers is not in the document]
Comment (lhy1024) [reply pkg/election/leadership.go:264]: Yes, we need to recreate watch chan with new revision

**Review by JmPotato — COMMENTED** [review]
LGTM. Please fix `make check` first.

File: pkg/utils/etcdutil/etcdutil.go (hunk 15 above)
Comment (rleungx) [reply pkg/utils/etcdutil/etcdutil.go:297]: Is it necessary now?

File: pkg/utils/etcdutil/etcdutil.go [hunk 19]
```diff
@@ -196,72 +210,240 @@ func EtcdKVPutWithTTL(ctx context.Context, c *clientv3.Client, key string, value
...
+	var eps []string
+	for _, m := range mresp.Members {
+		if len(m.Name) != 0 && !m.IsLearner {
+			eps = append(eps, m.ClientURLs...)
+		}
+	}
+	return eps
+}
+
+func isEqual(a, b []string) bool {
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil.go:422]: move it to typeutil?

File: pkg/election/leadership.go [hunk 20]
```diff
@@ -182,26 +188,82 @@ func (ls *Leadership) Watch(serverCtx context.Context, revision int64) {
...
 		failpoint.Inject("delayWatcher", nil)
-		rch := watcher.Watch(ctx, ls.leaderKey, clientv3.WithRev(revision))
-		for wresp := range rch {
+		if watchChanCancel != nil {
+			watchChanCancel()
+		}
+		// In order to prevent a watch stream being stuck in a partitioned node,
+		// make sure to wrap context with "WithRequireLeader".
+		watchChanCtx, cancel := context.WithCancel(clientv3.WithRequireLeader(serverCtx))
+		watchChanCancel = cancel
```
[the remark this answers is not in the document]
Comment (lhy1024) [reply pkg/election/leadership.go:218]: In previously written, it seems to work without adding the nolint comment.

File: pkg/utils/etcdutil/etcdutil.go (hunk 15 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:297]: yes, it is.

**Review by rleungx — APPROVED** [review]
