### PR TITLE
tests: fix `TestPreparingProgress`

### LINKED ISSUE #8693: TestPreparingProgress is flaky
### Which jobs are failing

TestPreparingProgress

```
    api_test.go:1108: 
        	Error Trace:	/home/runner/work/pd/pd/tests/server/api/api_test.go:1108
        	            				/home/runner/work/pd/pd/tests/server/api/api_test.go:1012
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 200
        	Test:       	TestPreparingProgress
```

### CI link

https://github.com/tikv/pd/actions/runs/11287900664/job/31394644984?pr=8685

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #8693.

### What is changed and how does it work?

The reason is the same as the removing progress testing. As for panic, it is caused by the leader stepping down. So I add a check before put store, which might reduce the possibility of failure.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/server/api/api_test.go [hunk 1]
```diff
@@ -945,9 +945,9 @@ func TestRemovingProgress(t *testing.T) {
 	// store 2: (30-10)/(30+40) ~= 0.285
 	re.Equal("0.29", fmt.Sprintf("%.2f", p.Progress))
 	// store 2: 20/10s = 2
-	re.Equal(2.0, p.CurrentSpeed)
+	re.LessOrEqual(2.0, p.CurrentSpeed)
 	// store 2: (10+40)/2 = 25s
-	re.Equal(25.0, p.LeftSeconds)
+	re.GreaterOrEqual(25.0, p.LeftSeconds)
```
Comment (lhy1024) [inline tests/server/api/api_test.go:950]: Will it change the behavior of test?

Comment (rleungx) [reply tests/server/api/api_test.go:950]: No, the reason is that checkStores is executed more than once.

**Review by lhy1024 — APPROVED** [review]

**Review by okJiang — APPROVED** [review]
