### PR TITLE
schedule: fix rule checker is not expected

### LINKED ISSUE #9440: Rule checker is not expected
### What did you do?

```
SELECT store_id,address,label from INFORMATION_SCHEMA.TIKV_STORE_STATUS;

+----------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| store_id | address             | label                                                                                                                                  |
+----------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------+
|        8 | 172.31.19.203:20161 | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-2"}, {"key": "zone", "value": "z2"}, {"key": "type", "value": "ap"}] |
|        9 | 172.31.29.83:20160  | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-5"}, {"key": "zone", "value": "z2"}, {"key": "type", "value": "ap"}] |
|       10 | 172.31.29.83:20161  | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-6"}, {"key": "zone", "value": "z3"}, {"key": "type", "value": "tp"}] |
|        2 | 172.31.20.170:20161 | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-4"}, {"key": "zone", "value": "z1"}, {"key": "type", "value": "ap"}] |
|        1 | 172.31.20.170:20160 | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-3"}, {"key": "zone", "value": "z3"}, {"key": "type", "value": "tp"}] |
|        7 | 172.31.19.203:20160 | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-1"}, {"key": "zone", "value": "z1"}, {"key": "type", "value": "ap"}] |
+----------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------+
6 rows in set (0.002 sec)
```

The store's distribution is listed as follows:
```
z1
2 type:ap
7 type:ap

z2
8 type:ap
9 type:ap

z3
1  type:tp
10 type:tp
```
And we add a placement policy:
```
create placement policy p leader_constraints="[+type=ap]" follower_constraints="{+type=ap: 1, +type=tp: 1}",
survival_preferences="[zone]";
```

Then we get the right distribution of regions
```
CREATE TABLE `t` (
  `oneid` varchar(128) DEFAULT NULL,
  `tenant_key` varchar(128) DEFAULT NULL,
  `frequent_weekday` varchar(128) DEFAULT NULL,
  `avg_order_value` decimal(18,2) DEFAULT NULL,
  `etl_date` varchar(128) DEFAULT NULL
) SHARD_ROW_ID_BITS=10 PRE_SPLIT_REGIONS=10 placement policy p;


WITH store_labels AS (
    -- 构建 store_id 到 label 的映射表
    SELECT 2 AS store_id, 'z1' AS label
    UNION ALL SELECT 7, 'z1'
    UNION ALL SELECT 8, 'z2'
    UNION ALL SELECT 9, 'z2'
    UNION ALL SELECT 10, 'z3'
    UNION ALL SELECT 1, 'z3'
)
SELECT
    label_combo,
    COUNT(*) AS region_count
FROM (
    SELECT
        trp.region_id,
        GROUP_CONCAT(
            sl.label 
            ORDER BY 
                trp.IS_LEADER DESC,  -- Leader 的 label 排在最前
                trp.store_id ASC      -- 其余按 store_id 升序保证一致性
        ) AS label_combo
    FROM information_schema.tikv_region_peers trp
    JOIN information_schema.tikv_region_status trs 
        ON trs.region_id = trp.region_id
    JOIN store_labels sl 
        ON trp.store_id = sl.store_id  -- 关联映射表
    WHERE 
        trs.table_name = 't' 
        AND trp.IS_LEARNER = 0 
        AND trp.STATUS = 'NORMAL'
    GROUP BY trp.region_id
) AS region_combos
GROUP BY label_combo
ORDER BY region_count DESC, label_combo;


+-------------+--------------+
| label_combo | region_count |
+-------------+--------------+
| z1,z2,z3    |          323 |
| z2,z3,z1    |          262 |
| z1,z3,z2    |          245 |
| z2,z1,z3    |          194 |
+-------------+--------------+
```

But if we change the store label to 
```
+----------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| store_id | address             | label                                                                                                                                  |
+----------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------+
|        2 | 172.31.20.170:20161 | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-4"}, {"key": "zone", "value": "z1"}, {"key": "type", "value": "ap"}] |
|        1 | 172.31.20.170:20160 | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-3"}, {"key": "zone", "value": "z3"}, {"key": "type", "value": "ap"}] |
|        7 | 172.31.19.203:20160 | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-1"}, {"key": "zone", "value": "z1"}, {"key": "type", "value": "ap"}] |
|        8 | 172.31.19.203:20161 | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-2"}, {"key": "zone", "value": "z2"}, {"key": "type", "value": "ap"}] |
|        9 | 172.31.29.83:20160  | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-5"}, {"key": "zone", "value": "z2"}, {"key": "type", "value": "tp"}] |
|       10 | 172.31.29.83:20161  | [{"key": "region", "value": "R1"}, {"key": "host", "value": "host-6"}, {"key": "zone", "value": "z3"}, {"key": "type", "value": "tp"}] |
+----------+---------------------+----------------------------------------------------------------------------------------------------------------------------------------+
6 rows in set (0.002 sec)
```

After the change:
```
[zone]
z1
2 type:ap
7 type:ap

z2
8 type:ap
9 type:tp

z3
1 type:ap
10 type:tp
```

### What did you expect to see?

Regions still have the right distribution.

### What did you see instead?

Then, there will be two peers in the same zone:
```
+-------------+--------------+
| label_combo | region_count |
+-------------+--------------+
| z1,z2,z2    |          300 |
| z2,z1,z3    |          188 |
| z1,z2,z3    |          108 |
| z1,z3,z2    |          108 |
| z2,z3,z3    |          102 |
| z2,z1,z2    |           97 |
| z1,z3,z3    |           83 |
| z3,z1,z3    |           16 |
| z3,z1,z2    |           12 |
| z3,z2,z3    |           10 |
+-------------+--------------+
10 rows in set (0.110 sec)
```

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9440

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

File: pkg/schedule/checker/rule_checker_test.go [hunk 1]
```diff
@@ -743,6 +743,124 @@ func (suite *ruleCheckerTestSuite) TestBetterReplacement2() {
...
+	}
+	suite.ruleManager.SetRule(rule1)
+	suite.ruleManager.SetRule(rule2)
+	suite.ruleManager.SetRule(rule3)
+	suite.ruleManager.DeleteRule(placement.DefaultGroupID, placement.DefaultRuleID)
+	region := suite.cluster.GetRegion(10)
+	op := suite.rc.Check(region)
+	re.NotNil(op)
+	re.Equal("move-to-better-location", op.Desc())
+	if op.Step(0).(operator.AddLearner).ToStore != 4 {
```
Comment (bufferflies) [inline pkg/schedule/checker/rule_checker_test.go:801]: How about removing store 4 to make the operator move 2 to 3 `?
