### PR TITLE
test: reduce redundant code about etcd server and logger

### LINKED ISSUE #6890: Unstable test TestRandomKillEtcd
### Which jobs are failing

```shell
FAIL: TestRandomKillEtcd (1.18s)
    etcdutil_test.go:428: 
        	Error Trace:	/home/runner/work/pd/pd/pkg/utils/etcdutil/etcdutil_test.go:428
        	            				/home/runner/work/pd/pd/pkg/utils/etcdutil/etcdutil_test.go:332
        	Error:      	Received unexpected error:
        	            	error validating peerURLs {ClusterID:5930ec8246e08795 Members:[&{ID:9b8c2306254c08d8 RaftAttributes:{PeerURLs:[http://127.0.0.1:43835] IsLearner:false} Attributes:{Name:test_etcd_7249 ClientURLs:[http://127.0.0.1:45049]}} &{ID:9c475f3ff457c2aa RaftAttributes:{PeerURLs:[http://127.0.0.1:39[823](https://github.com/tikv/pd/actions/runs/5746560238/job/15576225377#step:5:824)] IsLearner:false} Attributes:{Name:test_etcd_9700 ClientURLs:[[http://127.0.0.1:33929]}}](http://127.0.0.1:33929%7D%7D]/)] RemovedMemberIDs:[]}: member count is unequal
        	Test:       	TestRandomKillEtcd
```

### CI link

https://github.com/tikv/pd/actions/runs/5746560238/job/15576225377

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #6890 #6936

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

File: pkg/utils/etcdutil/etcdutil_test.go [hunk 1]
```diff
@@ -48,44 +47,11 @@ func TestMain(m *testing.M) {
...
-
-	<-etcd1.Server.ReadyNotify()
-
-	// Test ListEtcdMembers
-	listResp1, err := ListEtcdMembers(client1)
-	re.NoError(err)
-	re.Len(listResp1.Members, 1)
-	// types.ID is an alias of uint64.
-	re.Equal(uint64(etcd1.Server.ID()), listResp1.Members[0].ID)
+	servers, client1, clean := NewTestEtcdCluster(t, 2)
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil_test.go:50]: Why change it?

File: pkg/utils/etcdutil/testutil.go [hunk 2]
```diff
@@ -50,3 +53,93 @@ func NewTestSingleConfig(t *testing.T) *embed.Config {
...
+	addResp, err := AddEtcdMember(client, []string{peerURL})
+	re.NoError(err)
+	// Check the client can get the new member.
+	members, err := ListEtcdMembers(client)
+	re.NoError(err)
+	re.Len(addResp.Members, len(members.Members))
+	// Start the new etcd member.
+	etcd2, err := embed.StartEtcd(cfg2)
+	if err != nil {
+		re.Contains(err.Error(), "error validating peerURLs")
```
Comment (rleungx) [inline pkg/utils/etcdutil/testutil.go:118]: When will this error happen?

File: pkg/utils/etcdutil/etcdutil_test.go (hunk 1 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil_test.go:50]: NewTestEtcdCluster also checks member num and member id

Comment (rleungx) [reply pkg/utils/etcdutil/etcdutil_test.go:50]: I suggest using add member which is more clear. `NewTestEtcdCluster` looks like an initialization.

File: pkg/utils/etcdutil/testutil.go (hunk 2 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/testutil.go:118]: In #6890, it occurs with "member count is unequal"

Comment (rleungx) [reply pkg/utils/etcdutil/testutil.go:118]: Is the error expected?

Comment (lhy1024) [reply pkg/utils/etcdutil/testutil.go:118]: No, we have sent `MemberAdd` before starting a new etcd server, but it still returns `error validating peerURLs` with `member count is unequal`.

File: pkg/utils/etcdutil/testutil.go [hunk 3]
```diff
@@ -50,3 +53,95 @@ func NewTestSingleConfig(t *testing.T) *embed.Config {
...
+				server.Close()
+			}
+		}
+	}
+
+	return
+}
+
+// MustAddEtcdMember is used to add a new etcd member to the cluster.
+func MustAddEtcdMember(t *testing.T, cfg1 *embed.Config, client *clientv3.Client) *embed.Etcd {
```
Comment (rleungx) [inline pkg/utils/etcdutil/testutil.go:98]: Why call it Mustxxx?

Comment (lhy1024) [reply pkg/utils/etcdutil/testutil.go:98]: Do you have any good ideas about the name of this test function?

Comment (rleungx) [reply pkg/utils/etcdutil/testutil.go:98]: Here is no guarantee that the member is added.

Comment (lhy1024) [reply pkg/utils/etcdutil/testutil.go:98]: It will retry three times, and if it fails all three times, it will report an error `re.NoError(err, "addEtcdMemberWithRetry failed after retry")`

**Comment by lhy1024** [comment]
I tried to run ci 200 times with `CGO_ENABLED=1 go test -timeout=15m -tags deadlock -race github.com/tikv/pd/pkg/election github.com/tikv/pd/pkg/utils/etcdutil` in https://github.com/lhy1024/pd/pull/9

And only met once failure in TestEtcdScaleInAndOut about https://github.com/tikv/pd/issues/6892 and no other error about this pr.

File: pkg/utils/etcdutil/testutil.go (hunk 3 above)
Comment (lhy1024) [reply pkg/utils/etcdutil/testutil.go:99]: I use another way to make the test stable, which is to wait member number to be normal before adding a new node.
