### PR TITLE
cluster: fix tiflash cannot offline

### LINKED ISSUE #9933: TiFlash cannot be deleted if the replica is not enough
## Bug Report

Image

We need to skip TiFlash nodes when `checkReplicaBeforeOfflineStore`.

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9933

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/cluster/cluster.go [hunk 1]
```diff
@@ -1556,7 +1556,9 @@ func (c *RaftCluster) RemoveStore(storeID uint64, physicallyDestroyed bool) erro
 }
 
 func (c *RaftCluster) checkReplicaBeforeOfflineStore(storeID uint64) error {
-	upStores := c.getUpStores()
+	upStores := c.getUpStores(func(store *core.StoreInfo) bool {
```
Comment (lhy1024) [inline server/cluster/cluster.go]:
```suggestion
	upStores := c.getUpStores(/*isExcluded */func(store *core.StoreInfo) bool {
```

File: server/cluster/cluster.go [hunk 2]
```diff
@@ -1590,9 +1592,12 @@ func (c *RaftCluster) checkReplicaBeforeOfflineStore(storeID uint64) error {
 	return nil
 }
 
-func (c *RaftCluster) getUpStores() []uint64 {
+func (c *RaftCluster) getUpStores(isInclude ...func(store *core.StoreInfo) bool) []uint64 {
```
Comment (JmPotato) [inline server/cluster/cluster.go]: It seems that currently there’s only the usage of `IsTiKV()`. How about writing the logic directly inside the function instead of introducing the `isInclude` parameter?

Comment (rleungx) [reply server/cluster/cluster.go]: done

File: server/cluster/cluster.go [hunk 3]
```diff
@@ -1592,10 +1590,11 @@ func (c *RaftCluster) checkReplicaBeforeOfflineStore(storeID uint64) error {
 	return nil
 }
 
-func (c *RaftCluster) getUpStores(isInclude ...func(store *core.StoreInfo) bool) []uint64 {
+// getUpStores gets all up TiKV stores.
+func (c *RaftCluster) getUpStores() []uint64 {
```
Comment (lhy1024) [inline server/cluster/cluster.go:1594]: How about `getUpTiKVs`

Comment (rleungx) [reply server/cluster/cluster.go:1594]: Actually, I prefer not to introduce the TiKV/TiFlash concept as much as possible.
