### PR TITLE
mcs: fix /config and /admin scheduling forward logic

### LINKED ISSUE #9825: There are also forward problems in scheduling, resource manager and pd
It is similiar to https://github.com/tikv/pd/issues/9797

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #9825

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/mcs/scheduling/server/apis/v1/api.go [hunk 1]
```diff
@@ -133,13 +134,16 @@ func NewService(srv *scheserver.Service) *Service {
 func (s *Service) RegisterAdminRouter() {
 	router := s.root.Group("admin")
 	router.PUT("/log", changeLogLevel)
-	router.DELETE("cache/regions", deleteAllRegionCache)
-	router.DELETE("cache/regions/:id", deleteRegionCacheByID)
+	redirector := multiservicesapi.ServiceRedirector()
+	router.DELETE("cache/regions", redirector, deleteAllRegionCache)
```
Comment (rleungx) [inline pkg/mcs/scheduling/server/apis/v1/api.go:138]: Only primary may have a cache?

Comment (lhy1024) [reply pkg/mcs/scheduling/server/apis/v1/api.go:138]: Yes, it is.

File: tests/integrations/mcs/scheduling/api_test.go [hunk 2]
```diff
@@ -760,3 +761,116 @@ func (suite *apiTestSuite) checkHealth(cluster *tests.TestCluster) {
...
+	level := "debug"
+	logPayload, err := json.Marshal(level)
+	re.NoError(err)
+	req, err := http.NewRequest(http.MethodPut, logURL, bytes.NewBuffer(logPayload))
+	re.NoError(err)
+	req.Header.Set("Content-Type", "application/json")
+	resp, err := tests.TestDialClient.Do(req)
+	re.NoError(err)
+	defer resp.Body.Close()
+	re.Equal(http.StatusOK, resp.StatusCode)
```
Comment (rleungx) [inline tests/integrations/mcs/scheduling/api_test.go:841]: Do we need to check the result after setting?

Comment (lhy1024) [reply tests/integrations/mcs/scheduling/api_test.go:841]: Yes, it is checked in L852

**Review by rleungx — APPROVED** [review]

File: tests/integrations/mcs/scheduling/api_test.go [hunk 3]
```diff
@@ -760,3 +761,116 @@ func (suite *apiTestSuite) checkHealth(cluster *tests.TestCluster) {
 	defer resp.Body.Close()
 	re.Equal(http.StatusOK, resp.StatusCode)
 }
+
+// schedulingForwardingTestSuite is a test suite for testing the forwarding behavior of Scheduling APIs.
+type schedulingForwardingTestSuite struct {
```
Comment (okJiang) [inline tests/integrations/mcs/scheduling/api_test.go:766]: How about creating a new file?

File: pkg/mcs/scheduling/server/apis/v1/api.go [hunk 4]
```diff
@@ -281,11 +300,47 @@ func changeLogLevel(c *gin.Context) {
...
 // @Router   /config [get]
 func getConfig(c *gin.Context) {
-	var config *config.Config
 	svr := c.MustGet(multiservicesapi.ServiceContextKey).(*scheserver.Server)
-	config = svr.GetConfig()
-	config.Schedule.MaxMergeRegionKeys = config.Schedule.GetMaxMergeRegionKeys()
-	c.IndentedJSON(http.StatusOK, config)
+	localCfg := svr.GetConfig()
+	if svr.IsServing() {
+		localCfg.Schedule.MaxMergeRegionKeys = localCfg.Schedule.GetMaxMergeRegionKeys()
```
Comment (okJiang) [inline pkg/mcs/scheduling/server/apis/v1/api.go]: Should we move this line into `GetConfig`?

File: pkg/mcs/scheduling/server/apis/v1/api.go [hunk 5]
```diff
@@ -281,11 +300,47 @@ func changeLogLevel(c *gin.Context) {
...
+		return
+	}
+	var primaryCfg config.Config
+	if err := json.NewDecoder(resp.Body).Decode(&primaryCfg); err != nil {
+		c.String(http.StatusInternalServerError, "failed to decode primary's config: "+err.Error())
+		return
+	}
+
+	mergedCfg := localCfg
+	mergedCfg.Schedule = primaryCfg.Schedule
```
Comment (okJiang) [inline pkg/mcs/scheduling/server/apis/v1/api.go:345]: please add some comments to explain why `Schedule` and `Replication` need to be replaced with primary's config.

File: pkg/mcs/scheduling/server/apis/v1/api.go [hunk 6]
```diff
@@ -281,11 +300,47 @@ func changeLogLevel(c *gin.Context) {
...
 	svr := c.MustGet(multiservicesapi.ServiceContextKey).(*scheserver.Server)
-	config = svr.GetConfig()
-	config.Schedule.MaxMergeRegionKeys = config.Schedule.GetMaxMergeRegionKeys()
-	c.IndentedJSON(http.StatusOK, config)
+	localCfg := svr.GetConfig()
+	if svr.IsServing() {
+		localCfg.Schedule.MaxMergeRegionKeys = localCfg.Schedule.GetMaxMergeRegionKeys()
+		c.IndentedJSON(http.StatusOK, localCfg)
+		return
+	}
```
Comment (okJiang) [inline pkg/mcs/scheduling/server/apis/v1/api.go:308]: Maybe we need check primary here. Otherwise, there could be an infinite loop

File: tests/integrations/mcs/scheduling/api_test.go (hunk 3 above)
Comment (lhy1024) [reply tests/integrations/mcs/scheduling/api_test.go:766]: I think it is not necessary

File: pkg/mcs/scheduling/server/apis/v1/api.go (hunk 6 above)
Comment (lhy1024) [reply pkg/mcs/scheduling/server/apis/v1/api.go:308]: why?

Comment (okJiang) [reply pkg/mcs/scheduling/server/apis/v1/api.go:308]: If the primary is also `!serving` all the time, the primary will keep sending requests to the primary. It is dangerous

Comment (lhy1024) [reply pkg/mcs/scheduling/server/apis/v1/api.go:308]: done
