### PR TITLE
Fix tso server close stuck issue

### LINKED ISSUE #6304: TestMixedTSODeployment timeout sometimes
### Which jobs are failing
TestMixedTSODeployment 

### CI link
https://github.com/tikv/pd/actions/runs/4655922619/jobs/8239044048
https://github.com/tikv/pd/actions/runs/4667209181/jobs/8263220385
https://github.com/tikv/pd/actions/runs/4654377314/jobs/8236052896
https://github.com/tikv/pd/actions/runs/4637756863/jobs/8206938196

### PR DESCRIPTION
**Pull request by binshi-bing**
### What problem does this PR solve?

Issue Number: Close #6304
Issue Number: Ref #5895 

### What is changed and how does it work?

```commit-message
Rewrite TSO gPRC/HTTP server Close().
```

### Check List

Tests

- Unit test
Reran TestMixedTSODeployment test cases 30 times, the issue wasn't reproed. Previously, it was reproed every 3 ~ 5 times.

-->

```release-note
None.
```

### CODE REVIEW

File: pkg/mcs/tso/server/server.go [hunk 1]
```diff
@@ -389,83 +394,128 @@ func (s *Server) startGRPCServer(l net.Listener) {
...
-	}
-
+	log.Info("[tso] grpc server starts serving", zap.String("address", l.Addr().String()))
+	err := s.grpcServer.Serve(l)
 	if s.IsClosed() {
-		log.Info("grpc server stopped")
+		log.Info("[tso] grpc server stopped")
 	} else {
-		log.Fatal("grpc server stopped unexpectedly", errs.ZapError(serverr))
+		log.Fatal("[tso] grpc server stopped unexpectedly", errs.ZapError(err))
```
Comment (rleungx) [inline pkg/mcs/tso/server/server.go:402]: We don't need to change it because [xxx] is mainly used for the client.

File: pkg/mcs/tso/server/server.go [hunk 2]
```diff
@@ -389,83 +394,128 @@ func (s *Server) startGRPCServer(l net.Listener) {
...
-			log.Info("mux stop serving", errs.ZapError(err))
+			log.Info("[tso] mux stopped serving", errs.ZapError(err))
 		} else {
-			log.Panic("mux stop serving unexpectedly", errs.ZapError(err))
+			log.Fatal("[tso] mux stopped serving unexpectedly", errs.ZapError(err))
 		}
 	}
 }
 
+func (s *Server) stopHTTPServer() {
```
Comment (lhy1024) [inline pkg/mcs/tso/server/server.go:457]: it is similar to stopGRPCServer. And we could use them in other micro services.

File: pkg/mcs/tso/server/server.go [hunk 3]
```diff
@@ -510,8 +561,11 @@ func (s *Server) startServer() (err error) {
 		return err
 	}
 
+	serverReadyChan := make(chan struct{})
```
Comment (lhy1024) [inline pkg/mcs/tso/server/server.go:564]: why add it?

File: pkg/mcs/tso/server/server.go (hunk 2 above)
Comment (binshi-bing) [reply pkg/mcs/tso/server/server.go:457]: Yes, stopHTTPServer and stopGRPCServer are similar, but there is no need to write a general function, because there are still a few differences between these two functions. stopHTTPServer and stopGRPCServer can be used in outher micro services.

File: pkg/mcs/tso/server/server.go (hunk 1 above)
Comment (binshi-bing) [reply pkg/mcs/tso/server/server.go:402]: removed all

File: pkg/mcs/tso/server/server.go (hunk 3 above)
Comment (binshi-bing) [reply pkg/mcs/tso/server/server.go:564]: To ensure tso.Server.StartServer() successfully exits right before cmux.CMux.Serve() is called. Without this, the TestServerRegisterTestSuite.TestServerPrimaryChange will fail, because it starts tso server then call tso.Server.Close() immediately. Generally, it's better to shorten the distance between tso.Server.StartServer() successfully returned and cmux.CMux.Serve() being called.

**Review by rleungx — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]
