### PR TITLE
test: fix data race for `balance-range-scheduler`

### LINKED ISSUE #9837: Data race in `TestSchedulers`
### Which jobs are failing
```
==================
WARNING: DATA RACE
Write at 0x00c0083f90f8 by goroutine 31469:
  github.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeSchedulerConfig).deleteJob.func1()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/balance_range.go:191 +0x64
  github.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeSchedulerConfig).persistLocked()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/balance_range.go:228 +0x798
  github.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeSchedulerConfig).deleteJob()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/balance_range.go:190 +0x4ee
  github.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeSchedulerHandler).deleteJob()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/balance_range.go:146 +0x204
  github.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeSchedulerHandler).deleteJob-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:2220 +0x47
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x371
  github.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeScheduler).ServeHTTP()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/balance_range.go:399 +0xbe
  github.com/tikv/pd/server.(*Handler).GetSchedulerConfigHandler.StripPrefix.func1()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:2282 +0x471
  net/http.HandlerFunc.ServeHTTP()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:2220 +0x47
  net/http.(*ServeMux).ServeHTTP()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:2747 +0x255
  github.com/tikv/pd/server/api.(*schedulerConfigHandler).handleSchedulerConfig()
      /home/runner/work/pd/pd/server/api/scheduler.go:369 +0x1c1
  github.com/tikv/pd/server/api.(*schedulerConfigHandler).handleSchedulerConfig-fm()
      <autogenerated>:1 +0x51
  github.com/tikv/pd/server/api.(*serviceMiddlewareBuilder).createHandler.WrapFunc.func1()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:69 +0x50
  github.com/urfave/negroni/v3.HandlerFunc.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:33 +0x51
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/tikv/pd/server/api.(*rateLimitMiddleware).ServeHTTP()
      /home/runner/work/pd/pd/server/api/middleware.go:184 +0x676
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/tikv/pd/server/api.(*auditMiddleware).ServeHTTP()
      /home/runner/work/pd/pd/server/api/middleware.go:152 +0xc04
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/tikv/pd/server/api.(*requestInfoMiddleware).ServeHTTP()
      /home/runner/work/pd/pd/server/api/middleware.go:78 +0x1132
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x128
  github.com/urfave/negroni/v3.(*Negroni).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:111 +0x12
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x371
  github.com/tikv/pd/server/api.NewHandler.Wrap.func21()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:59 +0x66
  github.com/urfave/negroni/v3.HandlerFunc.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:33 +0x51
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/tikv/pd/pkg/utils/apiutil/serverapi.(*redirector).ServeHTTP()
      /home/runner/work/pd/pd/pkg/utils/apiutil/serverapi/middleware.go:186 +0x2be
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/tikv/pd/pkg/utils/apiutil/serverapi.(*runtimeServiceValidator).ServeHTTP()
      /home/runner/work/pd/pd/pkg/utils/apiutil/serverapi/middleware.go:48 +0x163
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x128
  github.com/urfave/negroni/v3.(*Negroni).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:111 +0x12
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x371
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x371
  github.com/urfave/negroni/v3.(*Negroni).UseHandler.Wrap.func1()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:59 +0x66
  github.com/urfave/negroni/v3.HandlerFunc.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:33 +0x51
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/urfave/negroni/v3.(*Recovery).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/recovery.go:210 +0x101
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x128
  github.com/urfave/negroni/v3.(*Negroni).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:111 +0x12
  net/http.(*ServeMux).ServeHTTP()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:2747 +0x255
  go.etcd.io/etcd/server/v3/embed.(*accessController).ServeHTTP()
      /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.15/embed/serve.go:427 +0x8cd
  net/http.serverHandler.ServeHTTP()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:3210 +0x2a1
  net/http.(*conn).serve()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:2092 +0x12a4
  net/http.(*Server).Serve.gowrap3()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:3360 +0x4f

Previous read at 0x00c0083f90f8 by goroutine 59647:
  github.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeScheduler).checkJob()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/balance_range.go:442 +0x350
  github.com/tikv/pd/pkg/schedule/schedulers.(*balanceRangeScheduler).IsScheduleAllowed()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/balance_range.go:423 +0x178
  github.com/tikv/pd/pkg/schedule/schedulers.(*ScheduleController).AllowSchedule()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/scheduler_controller.go:552 +0xc8
  github.com/tikv/pd/pkg/schedule/schedulers.(*Controller).runScheduler()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/scheduler_controller.go:379 +0x61c
  github.com/tikv/pd/pkg/schedule/schedulers.(*Controller).AddScheduler.gowrap2()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/scheduler_controller.go:216 +0x44

Goroutine 31469 (running) created at:
  net/http.(*Server).Serve()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:3360 +0x8ec
  go.etcd.io/etcd/server/v3/embed.(*serveCtx).serve.func3()
      /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.15/embed/serve.go:175 +0x44
  go.etcd.io/etcd/server/v3/embed.(*serveCtx).serve.gowrap3()
      /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.15/embed/serve.go:176 +0x61

Goroutine 59647 (running) created at:
  github.com/tikv/pd/pkg/schedule/schedulers.(*Controller).AddScheduler()
      /home/runner/work/pd/pd/pkg/schedule/schedulers/scheduler_controller.go:216 +0x41e
  github.com/tikv/pd/server/cluster.(*schedulingController).AddScheduler()
      /home/runner/work/pd/pd/server/cluster/scheduling_controller.go:380 +0x25d
  github.com/tikv/pd/server.(*Handler).AddScheduler()
      /home/runner/work/pd/pd/server/handler.go:216 +0xf9d
  github.com/tikv/pd/server/api.(*schedulerHandler).CreateScheduler()
      /home/runner/work/pd/pd/server/api/scheduler.go:245 +0x2008
  github.com/tikv/pd/server/api.(*schedulerHandler).CreateScheduler-fm()
      <autogenerated>:1 +0x51
  github.com/tikv/pd/server/api.(*serviceMiddlewareBuilder).createHandler.WrapFunc.func1()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:69 +0x50
  github.com/urfave/negroni/v3.HandlerFunc.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:33 +0x51
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/tikv/pd/server/api.(*rateLimitMiddleware).ServeHTTP()
      /home/runner/work/pd/pd/server/api/middleware.go:184 +0x676
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/tikv/pd/server/api.(*auditMiddleware).ServeHTTP()
      /home/runner/work/pd/pd/server/api/middleware.go:152 +0xc04
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/tikv/pd/server/api.(*requestInfoMiddleware).ServeHTTP()
      /home/runner/work/pd/pd/server/api/middleware.go:78 +0x1132
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x128
  github.com/urfave/negroni/v3.(*Negroni).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:111 +0x12
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x371
  github.com/tikv/pd/server/api.NewHandler.Wrap.func21()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:59 +0x66
  github.com/urfave/negroni/v3.HandlerFunc.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:33 +0x51
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/tikv/pd/pkg/utils/apiutil/serverapi.(*redirector).ServeHTTP()
      /home/runner/work/pd/pd/pkg/utils/apiutil/serverapi/middleware.go:186 +0x2be
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/tikv/pd/pkg/utils/apiutil/serverapi.(*runtimeServiceValidator).ServeHTTP()
      /home/runner/work/pd/pd/pkg/utils/apiutil/serverapi/middleware.go:48 +0x163
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x128
  github.com/urfave/negroni/v3.(*Negroni).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:111 +0x12
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x371
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x371
  github.com/urfave/negroni/v3.(*Negroni).UseHandler.Wrap.func1()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:59 +0x66
  github.com/urfave/negroni/v3.HandlerFunc.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:33 +0x51
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x75
  github.com/urfave/negroni/v3.middleware.ServeHTTP-fm()
      <autogenerated>:1 +0x1b
  github.com/urfave/negroni/v3.(*Recovery).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/recovery.go:210 +0x101
  github.com/urfave/negroni/v3.middleware.ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:51 +0x128
  github.com/urfave/negroni/v3.(*Negroni).ServeHTTP()
      /home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.1.1/negroni.go:111 +0x12
  net/http.(*ServeMux).ServeHTTP()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:2747 +0x255
  go.etcd.io/etcd/server/v3/embed.(*accessController).ServeHTTP()
      /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.15/embed/serve.go:427 +0x8cd
  net/http.serverHandler.ServeHTTP()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:3210 +0x2a1
  net/http.(*conn).serve()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:2092 +0x12a4
  net/http.(*Server).Serve.gowrap3()
      /opt/hostedtoolcache/go/1.23.12/x64/src/net/http/server.go:3360 +0x4f
==================
```

### CI link
https://github.com/tikv/pd/actions/runs/18516698974/job/52768520485

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #9837

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- No code

Code changes

Side effects

Related changes

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/schedule/schedulers/balance_range.go [hunk 1]
```diff
@@ -151,8 +151,8 @@ func (handler *balanceRangeSchedulerHandler) deleteJob(w http.ResponseWriter, r
 }
 
 type balanceRangeSchedulerConfig struct {
-	syncutil.RWMutex
 	schedulerConfig
+	sync.Mutex
```
Comment (lhy1024) [inline pkg/schedule/schedulers/balance_range.go]: how about syncutil

Comment (bufferflies) [reply pkg/schedule/schedulers/balance_range.go]: done

File: pkg/schedule/schedulers/balance_range.go [hunk 2]
```diff
@@ -513,11 +510,7 @@ func newBalanceRangeScheduler(opController *operator.Controller, conf *balanceRa
 // Schedule schedules the balance key range operator.
 func (s *balanceRangeScheduler) Schedule(cluster sche.SchedulerCluster, _ bool) ([]*operator.Operator, []plan.Plan) {
 	balanceRangeCounter.Inc()
-	_, job := s.conf.peek()
-	if job == nil {
-		balanceRangeNoJobCounter.Inc()
-		return nil, nil
-	}
```
Comment (rleungx) [inline pkg/schedule/schedulers/balance_range.go:520]: no need anymore?

Comment (bufferflies) [reply pkg/schedule/schedulers/balance_range.go:520]: Yes, it has been set in preparation.

**Review by lhy1024 — APPROVED** [review]
