### PR TITLE
scheduler: fix batch compatibility issue

### LINKED ISSUE #9416: Evict leader could be paused after upgrading
### What did you do?

Use the version before v8.5.x:
```
tiup playground v8.1.0 --tiflash 0 --pd 1 --kv 4 --host 10.2.8.101 --tag test

» scheduler add evict-leader-scheduler 1
Success! The scheduler is created.
» scheduler config evict-leader-scheduler
{
  "store-id-ranges": {
    "1": [
      {
        "start-key": "",
        "end-key": ""
      }
    ]
  }
}
```

Upgrade to v8.5.x:
```
tiup playground v8.5.2 --tiflash 0 --pd 1 --kv 4 --host 10.2.8.101 --tag test

» scheduler config evict-leader-scheduler
{
  "store-id-ranges": {
    "1": [
      {
        "start-key": "",
        "end-key": ""
      }
    ]
  },
  "batch": 0
}
```

The `batch` will be changed to `0`, which leads to the evict-leader-scheduler not work.

Workaound:
1. delete the scheduler and add it again
2. or pd-ctl `scheduler config evict-leader-scheduler set batch 3`

### What version of PD are you using (`pd-server -V`)?
v8.5.x

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9416.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Manual test

```
tiup playground v8.1.0 --tiflash 0 --pd 1 --kv 4 --tag test

$ ./pd-ctl -u http://127.0.0.1:2379 -i
» scheduler add evict-leader-scheduler 1
Success! The scheduler is created.
» scheduler config evict-leader-scheduler
{
  "store-id-ranges": {
    "1": [
      {
        "start-key": "",
        "end-key": ""
      }
    ]
  }
}
```
After replacing nightly with this branch and upgrading PD to nightly:
```
tiup playground nightly --tiflash 0 --pd 1 --kv 4 --tag test

$ ./pd-ctl -u http://127.0.0.1:2379 -i
» scheduler config evict-leader-scheduler
{
  "store-id-ranges": {
    "1": [
      {
        "end-key": "",
        "start-key": ""
      }
    ]
  },
  "batch": 3
}
```

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/schedule/schedulers/evict_leader.go [hunk 1]
```diff
@@ -142,6 +142,9 @@ func (conf *evictLeaderSchedulerConfig) reloadConfig() error {
 	if err := conf.load(newCfg); err != nil {
 		return err
 	}
+	if newCfg.Batch == 0 {
```
Comment (lhy1024) [inline pkg/schedule/schedulers/evict_leader.go:145]: Do we need to add a unit test?

**Review by lhy1024 — APPROVED** [review]

File: pkg/schedule/schedulers/evict_leader.go (hunk 1 above)
Comment (rleungx) [reply pkg/schedule/schedulers/evict_leader.go:145]: done
