### PR TITLE
step: fix merge region failed caused by mismatch confver

### LINKED ISSUE #5656: merge check match witness
## Development Task

Consider witness merge in merge scheduler

ref https://github.com/tikv/tikv/issues/12876

### PR DESCRIPTION
**Pull request by ethercflow**
ref tikv/pd#5656

Signed-off-by: Wenbo Zhang <ethercflow@gmail.com>

### What problem does this PR solve?

Issue Number: Close #5656

### What is changed and how does it work?

When region A's witness and region B's witness not on the same store. It will gen the op with

step1:  Demote witness voter -> witness learner
step2: switch witness learner -> non-witness leaner
step3: Promote non-witness learner -> voter

When calculating the conf ver change, after the third step is executed, the conf ver change condition of the first step is not satisfied, resulting in the difference between the actual region conf ver change and the calculated one.

So add witness change as a condition to solve this.

```commit-message
step: fix merge region failed caused by mismatch confver
```

### Check List

Tests

- Manual test 
   - test with sysbench prepare

Code changes

- None

Side effects

- None

Related changes

- None

### Release note

```release-note
None
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

File: server/schedule/operator/step.go [hunk 1]
```diff
@@ -415,7 +415,7 @@ func (bsw BatchSwitchWitness) Influence(opInfluence OpInfluence, region *core.Re
 // Timeout returns duration that current step may take.
 func (bsw BatchSwitchWitness) Timeout(regionSize int64) time.Duration {
 	count := uint64(len(bsw.ToWitnesses)+len(bsw.ToNonWitnesses)) + 1
-	return fastStepWaitDuration(regionSize) * time.Duration(count)
+	return slowStepWaitDuration(regionSize) * time.Duration(count)
```
Comment (bufferflies) [inline server/schedule/operator/step.go:418]: how about only use `ToNonWitness`?

**Review by bufferflies — COMMENTED** [review]
rest lgtm

**Review by bufferflies — APPROVED** [review]
