### PR TITLE
pd-ctl: fix keyspace group split hang when pd is in pd-mode

### LINKED ISSUE #6906: pd-ctl: there is no resp when sending a `keyspace-group split` to a pd in non-api mode
### send `keyspace-group split`

pd-ctl send once:
`[2023/08/08 10:40:32.222 +08:00] [INFO] [pdutil.go:214] ["stdout:Failed! Post \"http://127.0.0.1:2379/pd/api/v2/tso/keyspace-groups/
0/split\": EOF\n stderr:\n exitCode:0\n"]`
pd-ctl send twice, hang: 
image

pd:
9a364a1d-8b10-4ba1-a983-3b335a38eee1

### send `keyspace-group`
75477e07-3a48-4d37-af1c-aac8131d3e6d

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #6906

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Manual test
image

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

File: server/apiv2/handlers/tso_keyspace_group.go [hunk 1]
```diff
@@ -243,12 +243,19 @@ func SplitKeyspaceGroupByID(c *gin.Context) {
...
+
 	patrolKeyspaceAssignmentState.Lock()
 	if !patrolKeyspaceAssignmentState.patrolled {
 		// Patrol keyspace assignment before splitting keyspace group.
 		manager := svr.GetKeyspaceManager()
 		if manager == nil {
 			c.AbortWithStatusJSON(http.StatusInternalServerError, managerUninitializedErr)
+			patrolKeyspaceAssignmentState.Unlock()
 			return
 		}
```
Comment (JmPotato) [inline server/apiv2/handlers/tso_keyspace_group.go:260]: What about moving this check to the front also?

**Review by JmPotato — APPROVED** [review]
