### PR TITLE
test: make TestSplitKeyspaceGroup and TestMergeKeyspaceGroup stable

### LINKED ISSUE #9363: TestSplitKeyspaceGroup is flaky, etcd transaction failed
### Which jobs are failing

```
    keyspace_group_test.go:122: 
        	Error Trace:	/home/runner/work/pd/pd/tools/pd-ctl/tests/keyspace/keyspace_group_test.go:122
        	Error:      	Received unexpected error:
        	            	[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back
        	Test:       	TestSplitKeyspaceGroup
```

### CI link

https://github.com/tikv/pd/actions/runs/15290784728/job/43009730359?pr=9117

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #9363 #9316

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by okJiang** [comment]
Can you explain why? Or add some comments.

**Review by okJiang — APPROVED** [review]

File: tools/pd-ctl/tests/keyspace/keyspace_group_test.go [hunk 1]
```diff
@@ -322,8 +330,14 @@ func TestMergeKeyspaceGroup(t *testing.T) {
 
 	tc.WaitLeader()
 	leaderServer := tc.GetLeaderServer()
-	re.NoError(leaderServer.BootstrapCluster())
-
+	testutil.Eventually(re, func() bool {
```
Comment (rleungx) [inline tools/pd-ctl/tests/keyspace/keyspace_group_test.go]: Why do only these two tests have this issue? We use `re.NoError(leaderServer.BootstrapCluster())` in many places

Comment (lhy1024) [reply tools/pd-ctl/tests/keyspace/keyspace_group_test.go]: Because they preallocate keyspaces, I guess.

Comment (rleungx) [reply tools/pd-ctl/tests/keyspace/keyspace_group_test.go]: Seems we need to find the reason for the conflicts instead of retrying.

Comment (lhy1024) [reply tools/pd-ctl/tests/keyspace/keyspace_group_test.go]: I added some logs and found that the error is from `LoadKeyspace` in `waitPreAllocKeyspaces`.  We pre alloc keyspace in `Manager.Bootstrap` with different goroutines and try to call `LoadKeyspace` in `waitPreAllocKeyspaces` in another goroutine.
