### PR TITLE
tests: fix `TestTSONotLeader`

### LINKED ISSUE #9412: TestTSONotLeader is unstable
### Which jobs are failing
```
2025-06-17T05:22:56.8356130Z     client_test.go:513: 
2025-06-17T05:22:56.8357911Z         	Error Trace:	/home/runner/work/pd/pd/tests/integrations/tso/client_test.go:513
2025-06-17T05:22:56.8359876Z         	            				/opt/hostedtoolcache/go/1.23.10/x64/src/runtime/asm_amd64.s:1700
2025-06-17T05:22:56.8361242Z         	Error:      	Error "rpc error: code = Canceled desc = context canceled" does not contain "not leader"
2025-06-17T05:22:56.8362101Z         	Test:       	TestTSONotLeader
```

### CI link

https://github.com/tikv/pd/actions/runs/15698835296/job/44229167981?pr=9320

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9412.

### What is changed and how does it work?

The test won't return `not leader` because of the retry. So we add a failpoint to skip the retry.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: client/client.go [hunk 1]
```diff
@@ -532,6 +532,10 @@ func (c *client) GetTS(ctx context.Context) (physical int64, logical int64, err
 	for retryCount = range maxTSORetryTimes {
 		resp := c.GetTSAsync(ctx)
 		if physical, logical, err = resp.Wait(); err != nil {
```
Comment (lhy1024) [inline client/client.go:534]: but new test fail `TestRetryGetTSNotLeader`

Comment (rleungx) [reply client/client.go:534]: not related

**Review by JmPotato — APPROVED** [review]
