### PR TITLE
keyspace: refine the split and merge details

### LINKED ISSUE #6686: timestamp fallback after spliting followed by merging immediately
## Enhancement Task
**// split keyspace 1 from group 0 to group 1** 
root@serverless-cluster-pd-0:/# ./pd-ctl keyspace-group split 0 1 1
Success!
root@serverless-cluster-pd-0:/# ./pd-ctl keyspace-group merge 0 1
Failed! [500] "keyspace group is in split state"

**// Send traffic to keyspace 1 to trigger finish split for group 1**
root@tso-bench:/# ./pd-tso-bench -v -duration 250000s -pd "http://serverless-cluster-pd-0.serverless-cluster-pd-peer.tidb-serverless.svc:2379" -client 10 -c 3 -interval 30s -keyspace 1

**// Now we can merge 1 to 0**
root@serverless-cluster-pd-0:/# ./pd-ctl keyspace-group merge 0 1
Success!

**// But pd-tso-bench reported time fallback immediately after above merging.**
panic: global timestamp fallback, new ts (1687812834954, 1003) <= the last one (1687812834975, 50). keyspace: 1, keyspace group: 0

goroutine 693 [running]:
github.com/tikv/pd/client.(*tsoClient).compareAndSwapTS(0x4000439d40, {0x93f24b, 0x6}, 0x188f97c068a, 0x3eb, 0x0, 0x2)
        /go/src/github.com/tikv/pd/client/tso_dispatcher.go:742 +0x244
github.com/tikv/pd/client.(*tsoClient).processRequests(0x4000439d40, {0xa6e3e0, 0x4000f94bd0}, {0x93f24b, 0x6}, 0x40000c50e0, {0x0?, 0x0, 0x4000160280?})
        /go/src/github.com/tikv/pd/client/tso_dispatcher.go:720 +0x250
github.com/tikv/pd/client.(*tsoClient).handleDispatcher(0x4000439d40, {0xa79090?, 0x4000538040}, {0x93f24b, 0x6}, 0x40000c50e0)
        /go/src/github.com/tikv/pd/client/tso_dispatcher.go:445 +0xde4
created by github.com/tikv/pd/client.(*tsoClient).createTSODispatcher
        /go/src/github.com/tikv/pd/client/tso_dispatcher.go:290 +0x264

**Here is the PD client log.**
https://gist.githubusercontent.com/binshi-bing/68fadbf399dc5991e9c65341d7375636/raw/05de99538b8a5dc9d65ace1ddf8462928541c05a/gistfile1.txt

All Client/TSO log can be found https://gist.github.com/binshi-bing/68fadbf399dc5991e9c65341d7375636/edit

### LINKED ISSUE #6698: timestamp fallback in default keyspace group
### What did you do?

only stop and restart server `kubectl delete pod serverless-cluster-pd-0 serverless-cluster-pd-1 serverless-cluster-pd-2 -n tidb-serverless --force --grace-period=0 && kubectl delete po pd-tso-server-0 pd-tso-server-1 -n tidb-serverless --force --grace-period=0`

### What did you expect to see?
normal
### What did you see instead?

```
[2023/06/27 09:16:58.476 +00:00] [INFO] [tso_dispatcher.go:746] ["[tso] keyspace group changed"] [dc-location=global] [old-group-id=1] [new-group-id=0]
[2023/06/27 09:16:58.476 +00:00] [INFO] [tso_dispatcher.go:313] ["[tso] exit tso dispatcher"] [dc-location=global]
panic: global timestamp fallback, new ts (1687857418453, 1) <= the last one (1687857418453, 57). last keyspace group: 1, keyspace in request: 0, keyspace group in request: 1, keyspace group in response: 0

goroutine 71 [running]:
github.com/tikv/pd/client.(*tsoClient).compareAndSwapTS(0x4000000120, {0x93f68b, 0x6}, 0x0, 0x188fc2450d5, 0x1, 0x0, 0x1)
	/go/src/github.com/tikv/pd/client/tso_dispatcher.go:756 +0x454
github.com/tikv/pd/client.(*tsoClient).processRequests(0x4000000120, {0xa6ea40, 0x4000cfb210}, {0x93f68b, 0x6}, 0x40004fa050, {0x0?, 0x0, 0x400099ee40?})
	/go/src/github.com/tikv/pd/client/tso_dispatcher.go:721 +0x254
github.com/tikv/pd/client.(*tsoClient).handleDispatcher(0x4000000120, {0xa796f0?, 0x4000265600}, {0x93f68b, 0x6}, 0x40004fa050)
	/go/src/github.com/tikv/pd/client/tso_dispatcher.go:446 +0xde4
created by github.com/tikv/pd/client.(*tsoClient).createTSODispatcher
	/go/src/github.com/tikv/pd/client/tso_dispatcher.go:291 +0x264

```

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: Close #6686, close #6698.

### What is changed and how does it work?

```commit-message
- Adjust the merge operation order.
- Add some logs.
- Refine the code.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/keyspace/tso_keyspace_group.go [hunk 1]
```diff
@@ -536,6 +536,16 @@ func (m *GroupManager) SplitKeyspaceGroupByID(
...
+		// Build the new keyspace groups for split source and target.
+		var startKeyspaceID, endKeyspaceID uint32
+		if len(keyspaceIDRange) >= 2 {
+			startKeyspaceID, endKeyspaceID = keyspaceIDRange[0], keyspaceIDRange[1]
+		}
+		splitSourceKeyspaces, splitTargetKeyspaces, err := buildSplitKeyspaces(
+			splitSourceKg.Keyspaces, keyspaces, startKeyspaceID, endKeyspaceID)
+		if err != nil {
+			return err
+		}
```
Comment (lhy1024) [inline pkg/keyspace/tso_keyspace_group.go:548]: why move this block?

File: pkg/keyspace/tso_keyspace_group.go [hunk 2]
```diff
@@ -618,15 +622,7 @@ func buildSplitKeyspaces(
 				oldSplit = append(oldSplit, keyspace)
 			}
 		}
-		// Dedup new keyspaces if it's necessary.
```
Comment (lhy1024) [inline pkg/keyspace/tso_keyspace_group.go:621]: we don't need this check?

**Review by lhy1024 — APPROVED** [review]
the rest LGTM

File: pkg/keyspace/tso_keyspace_group.go (hunk 2 above)
Comment (JmPotato) [reply pkg/keyspace/tso_keyspace_group.go:621]: I found that `newNum` is always equal to `len(newKeyspaceMap)`,  so we can directly return `new` as the result here.

**Review by lhy1024 — APPROVED** [review]

File: pkg/keyspace/tso_keyspace_group.go (hunk 2 above)
Comment (binshi-bing) [reply pkg/keyspace/tso_keyspace_group.go:621]: We can't remove this check. I specifically add this block to fix issue https://github.com/tikv/pd/issues/6687. 

root@serverless-cluster-pd-0:/# ./pd-ctl keyspace-group split 0 2 **2 2**
Success!

{"id":2,"user-kind":"basic","members":[{"address":"http://pd-tso-server-0.tso-service.tidb-serverless.svc:2379","priority":200},{"address":"http://pd-tso-server-1.tso-service.tidb-serverless.svc:2379","priority":300}],"keyspaces":**[2,2]**}

Comment (binshi-bing) [reply pkg/keyspace/tso_keyspace_group.go:621]: It's my fault, since I signed off this change and previous change didn't add unittest.

File: pkg/keyspace/tso_keyspace_group.go [hunk 3]
```diff
@@ -637,6 +633,9 @@ func buildSplitKeyspaces(
 		newKeyspaceMap = make(map[uint32]struct{}, newNum)
 	)
 	for _, keyspace := range old {
+		if keyspace == utils.DefaultKeyspaceID {
```
Comment (binshi-bing) [inline pkg/keyspace/tso_keyspace_group.go:636]: We can't add this check, because it means that we can't split default keyspace group now.

File: pkg/keyspace/tso_keyspace_group.go (hunk 2 above)
Comment (binshi-bing) [reply pkg/keyspace/tso_keyspace_group.go:621]: I'll reopen #6687.

**Review by binshi-bing — COMMENTED** [review]
found two bugs.
