### PR TITLE
etcdutil: fix ctx in watch loop

### LINKED ISSUE #6439: PD OOM when doing HA tests
### What did you do?

Run HA test plan

### What did you expect to see?

All test pass

### What did you see instead?

Screenshot 2023-05-11 at 14 30 15
Screenshot 2023-05-11 at 14 32 27
Screenshot 2023-05-11 at 14 34 33

### What version of PD are you using (`pd-server -V`)?
pd-cse

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #6439

### What is changed and how does it work?

```commit-message
```

Before this pr, the goroutine of watch chan will exist until the watcher is closed, which means it will leak in for-loop.

We need to cancel ctx when watch chan is not needed.

And I found that `withRequireLeader` is necessary for `watch`, so I also added it.

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
memory and goroutine is enough stable
image

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by binshi-bing — APPROVED** [review]
@rleungx @lhy1024 should add more details about the feature. It will be even better with short analysis and solution explanation.

File: pkg/utils/etcdutil/etcdutil.go [hunk 1]
```diff
@@ -461,6 +461,8 @@ func (lw *LoopWatcher) initFromEtcd(ctx context.Context) int64 {
 		watchStartRevision int64
 		err                error
 	)
+	ctx, cancel := context.WithTimeout(ctx, lw.loadTimeout)
+	defer cancel()
 	ticker := time.NewTicker(defaultLoadFromEtcdRetryInterval)
 	defer ticker.Stop()
```
Comment (JmPotato) [inline pkg/utils/etcdutil/etcdutil.go:467]: Since it has a timeout, we better initialize it later.

```suggestion
	ticker := time.NewTicker(defaultLoadFromEtcdRetryInterval)
	defer ticker.Stop()
	ctx, cancel := context.WithTimeout(ctx, lw.loadTimeout)
	defer cancel()
```

File: pkg/utils/etcdutil/etcdutil.go [hunk 2]
```diff
@@ -532,11 +542,16 @@ func (lw *LoopWatcher) watch(ctx context.Context, revision int64) (nextRevision
 						log.Error("put failed in watch loop", zap.String("name", lw.name),
 							zap.String("key", lw.key), zap.Error(err))
 					}
+					log.Debug("put in watch loop", zap.String("name", lw.name),
+						zap.ByteString("key", event.Kv.Key),
```
Comment (rleungx) [inline pkg/utils/etcdutil/etcdutil.go:546]:
```suggestion
						zap.String("key", string(event.Kv.Key)),
```

Comment (lhy1024) [reply pkg/utils/etcdutil/etcdutil.go:546]: Why? What is the difference between them?

Comment (rleungx) [reply pkg/utils/etcdutil/etcdutil.go:546]: Oh, they are the same.

**Review by rleungx — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Comment by lhy1024** [comment]
I will add a test for it to check memory
