### PR TITLE
resource_manager: Fix for delayed deletion of created groups in TestWatchResourceGroup

### LINKED ISSUE #7144: Unstable TestWatchResourceGroup
### Which jobs are failing

`TestResourceManagerClientTestSuite/TestWatchResourceGroup`

### CI link

https://github.com/tikv/pd/actions/runs/6295573039/job/17089629197?pr=7139

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Close #7144

### What is changed and how does it work?

```commit-message
```
- When the test is complete `cleanupResourceGroups` will be executed. However, the watch mechanism in ci is not immediately available due to machine performance.
aa6b2607-e2f8-4d94-93d0-209e78335f87
For `TestWatchResourceGroups` that have groups created at begin, deletions (the delayed deletions mentioned above which result from last Test finished) may be encountered after creation, causing creation to not work.
- refine all tests
- run this change many times https://github.com/HuSharp/pd/pull/2
- remove redundant code

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by HuSharp** [comment]
I have run `resource_manager_test.go` many times and don't meet an error.
https://github.com/HuSharp/pd/pull/2

File: tests/integrations/mcs/resourcemanager/resource_manager_test.go [hunk 1]
```diff
@@ -191,19 +177,16 @@ func (suite *resourceManagerClientTestSuite) resignAndWaitLeader() {
 }
 
 func (suite *resourceManagerClientTestSuite) TestWatchResourceGroup() {
-	// TODO: fix the unstable part at line 248.
-	suite.T().Skip()
 	re := suite.Require()
 	cli := suite.client
 	group := &rmpb.ResourceGroup{
-		Name: "test",
+		Name: "watch_test",
```
Comment (JmPotato) [inline tests/integrations/mcs/resourcemanager/resource_manager_test.go:183]: What about using a const?

File: tests/integrations/mcs/resourcemanager/resource_manager_test.go [hunk 2]
```diff
@@ -1265,14 +1288,14 @@ func (suite *resourceManagerClientTestSuite) TestCheckBackgroundJobs() {
 		return false
 	}, testutil.WithTickInterval(50*time.Millisecond))
 
-	resourceGroupName = suite.initGroups[0].Name
+	resourceGroupName = "background_unable"
```
Comment (JmPotato) [inline tests/integrations/mcs/resourcemanager/resource_manager_test.go:1291]: Ditto.

**Review by JmPotato — COMMENTED** [review]
The reset LGTM.

File: tests/integrations/mcs/resourcemanager/resource_manager_test.go (hunk 2 above)
Comment (HuSharp) [reply tests/integrations/mcs/resourcemanager/resource_manager_test.go]: use a func to distinguish

File: tests/integrations/mcs/resourcemanager/resource_manager_test.go (hunk 1 above)
Comment (HuSharp) [reply tests/integrations/mcs/resourcemanager/resource_manager_test.go]: done

File: tests/integrations/mcs/resourcemanager/resource_manager_test.go [hunk 3]
```diff
@@ -129,20 +129,6 @@ func (suite *resourceManagerClientTestSuite) SetupSuite() {
 				},
 			},
 		},
-		{
```
Comment (nolouch) [inline tests/integrations/mcs/resourcemanager/resource_manager_test.go:132]: why remove this case?

File: tests/integrations/mcs/resourcemanager/resource_manager_test.go [hunk 4]
```diff
@@ -1210,47 +1236,52 @@ func (suite *resourceManagerClientTestSuite) TestCheckBackgroundJobs() {
...
-		resp, err := cli.AddResourceGroup(suite.ctx, group)
-		re.NoError(err)
-		re.Contains(resp, "Success!")
+	enableBackgroundGroup := func(enable bool) string {
+		if enable {
+			return "background_enable"
+		} else {
+			return "background_unable"
+		}
 	}
```
Comment (HuSharp) [inline tests/integrations/mcs/resourcemanager/resource_manager_test.go:1245]: used `enableBackgroundGroup` instead of unnecessary using `initGroups` cc @nolouch

**Review by nolouch — APPROVED** [review]
lgtm

**Review by CabinfeverB — APPROVED** [review]
