### PR TITLE
tso: fix tso proxy error propagation

### LINKED ISSUE #9188: tidb_enable_tso_follower_proxy causes 10s unavailability during graceful leader transfer
### What did you do?

1. Enable PD proxy:
```
mysql> SET GLOBAL tidb_enable_tso_follower_proxy = ON;
Query OK, 0 rows affected (0.11 sec)
```

2. Start write intensive benchmark:

```
sysbench oltp_update_non_index --non_index_updates=1 --mysql-ignore-errors=1105 --skip_trx=true --tables=1 --table_size=16384  --threads=64 --mysql-host=${HOST} --mysql-user=root --mysql-db=test --mysql-port=4000 --report-interval=1 --time=300 run
...
[ 1s ] thds: 64 tps: 1944.84 qps: 1944.84 (r/w/o: 0.00/1944.84/0.00) lat (ms,95%): 112.67 err/s: 0.00 reconn/s: 0.00
[ 2s ] thds: 64 tps: 1934.00 qps: 1934.00 (r/w/o: 0.00/1934.00/0.00) lat (ms,95%): 121.08 err/s: 0.00 reconn/s: 0.00
...
```

3. Resign the leader:
```
pd-ctl >> » member leader resign
Success!
```

### What did you expect to see?

No or minimal subsecond impact like in the case of resigning leader with `tidb_enable_tso_follower_proxy=OFF`
```
[ 139s ] thds: 64 tps: 1976.67 qps: 1976.67 (r/w/o: 0.00/1976.67/0.00) lat (ms,95%): 123.28 err/s: 0.00 reconn/s: 0.00
[ 140s ] thds: 64 tps: 1701.14 qps: 1701.14 (r/w/o: 0.00/1701.14/0.00) lat (ms,95%): 137.35 err/s: 2.00 reconn/s: 0.00
[ 141s ] thds: 64 tps: 1968.29 qps: 1968.29 (r/w/o: 0.00/1968.29/0.00) lat (ms,95%): 121.08 err/s: 0.00 reconn/s: 0.00
```
Above I observe negligible 10% QPS drop recovered within 1 second.

### What did you see instead?

Observe 10 seconds down time:
```
[ 19s ] thds: 64 tps: 1957.00 qps: 1957.00 (r/w/o: 0.00/1957.00/0.00) lat (ms,95%): 123.28 err/s: 0.00 reconn/s: 0.00
[ 20s ] thds: 64 tps: 689.90 qps: 689.90 (r/w/o: 0.00/689.90/0.00) lat (ms,95%): 112.67 err/s: 0.00 reconn/s: 0.00
[ 21s ] thds: 64 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 22s ] thds: 64 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 23s ] thds: 64 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 24s ] thds: 64 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 25s ] thds: 64 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 26s ] thds: 64 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 27s ] thds: 64 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 28s ] thds: 64 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 29s ] thds: 64 tps: 994.03 qps: 994.03 (r/w/o: 0.00/994.03/0.00) lat (ms,95%): 9118.47 err/s: 0.00 reconn/s: 0.00
[ 30s ] thds: 64 tps: 1926.30 qps: 1926.30 (r/w/o: 0.00/1926.30/0.00) lat (ms,95%): 114.72 err/s: 0.00 reconn/s: 0.00
```

### What version of PD are you using (`pd-server -V`)?
Both TiDB and PD are at LTS 8.5.1

### PR DESCRIPTION
**Pull request by Tema**
### What problem does this PR solve?

Issue Number: Close #9188

### What is changed and how does it work?

The change fixes the problems outlined in https://github.com/tikv/pd/issues/9188#issuecomment-2806773456
* Don't block client stream on receiving next request and allow to return error from proxy
* Allow to return proxy error to all clients served by the proxy error
* Don't cancel proxy stream after original client stream is closed

Tested using the same way as reported in the issue and observe subsecond impact only now:
```
[ 67s ] thds: 64 tps: 2007.63 qps: 2007.63 (r/w/o: 0.00/2007.63/0.00) lat (ms,95%): 116.80 err/s: 0.00 reconn/s: 0.00
[ 68s ] thds: 64 tps: 1962.21 qps: 1962.21 (r/w/o: 0.00/1962.21/0.00) lat (ms,95%): 121.08 err/s: 0.00 reconn/s: 0.00
[ 69s ] thds: 64 tps: 1984.16 qps: 1984.16 (r/w/o: 0.00/1984.16/0.00) lat (ms,95%): 116.80 err/s: 0.00 reconn/s: 0.00
[ 70s ] thds: 64 tps: 504.00 qps: 504.00 (r/w/o: 0.00/504.00/0.00) lat (ms,95%): 646.19 err/s: 0.00 reconn/s: 0.00
[ 71s ] thds: 64 tps: 1607.99 qps: 1607.99 (r/w/o: 0.00/1607.99/0.00) lat (ms,95%): 125.52 err/s: 0.00 reconn/s: 0.00
[ 72s ] thds: 64 tps: 2010.98 qps: 2010.98 (r/w/o: 0.00/2010.98/0.00) lat (ms,95%): 116.80 err/s: 0.00 reconn/s: 0.00
[ 73s ] thds: 64 tps: 1965.68 qps: 1965.68 (r/w/o: 0.00/1965.68/0.00) lat (ms,95%): 123.28 err/s: 0.00 reconn/s: 0.00
```

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/grpc_service.go [hunk 1]
```diff
@@ -539,18 +560,14 @@ func (s *GrpcServer) Tso(stream pdpb.PD_TsoServer) error {
...
 
-			if errCh == nil {
-				doneCh = make(chan struct{})
-				defer close(doneCh) // nolint
-				errCh = make(chan error)
-			}
-
 			tsoRequest := tsoutil.NewPDProtoRequest(forwardedHost, clientConn, request, stream)
-			s.tsoDispatcher.DispatchRequest(ctx, tsoRequest, s.pdProtoFactory, doneCh, errCh, s.tsoPrimaryWatcher)
+			// don't pass a stream context here as dispatcher serves multiple streams
```
Comment (rleungx) [inline server/grpc_service.go:564]: Will these be closed if we disable the proxy?

Comment (rleungx) [reply server/grpc_service.go:564]: I was thinking whether there is a resource leak after scaling in and out repeatedly.

File: server/grpc_service.go [hunk 2]
```diff
@@ -539,18 +560,14 @@ func (s *GrpcServer) Tso(stream pdpb.PD_TsoServer) error {
...
+			tsoRequestProxyQueue = s.tsoDispatcher.DispatchRequest(s.ctx, tsoRequest, s.pdProtoFactory, s.tsoPrimaryWatcher)
 			continue
 		}
 
 		if s.IsServiceIndependent(constant.TSOServiceName) {
+			var err error
```
Comment (bufferflies) [inline server/grpc_service.go:570]: Why use a new error here?

File: server/grpc_service.go (hunk 1 above)
Comment (bufferflies) [reply server/grpc_service.go:564]: > No, but it is at most one connection to each PD, which won't be re-open after restrat. 
Every client stream is independent, so the stream may have count(TIDB X PD)

File: pkg/utils/tsoutil/tso_dispatcher.go [hunk 3]
```diff
@@ -42,6 +43,41 @@ type tsoResp interface {
 	GetTimestamp() *pdpb.Timestamp
 }
 
+// TsoRequestProxyQueue contains request channel and allows to communicate error back to client
+// There are multiple streams associated with a single TSO request proxy queue, so we can't use a single channel to
+// communicate it back to all streams and store error in a separate variable
+type TsoRequestProxyQueue struct {
+	request chan Request
+	done    chan struct{}
```
Comment (bufferflies) [inline pkg/utils/tsoutil/tso_dispatcher.go:51]: How about renaming ' doneCh`? The done indicates the boolean variables

File: pkg/utils/tsoutil/tso_dispatcher.go [hunk 4]
```diff
@@ -42,6 +43,41 @@ type tsoResp interface {
...
+	err     atomic.Pointer[error]
```
Comment (bufferflies) [inline pkg/utils/tsoutil/tso_dispatcher.go:52]: Why use `atomic.Pointer`? Is this error single-thread safe?

**Review by bufferflies — COMMENTED** [review]
BTW, Maybe need to add intergrate test?

File: pkg/utils/tsoutil/tso_dispatcher.go [hunk 5]
```diff
@@ -36,12 +37,20 @@ const (
 	maxMergeRequests = 10000
 	// DefaultTSOProxyTimeout defines the default timeout value of TSP Proxying
 	DefaultTSOProxyTimeout = 3 * time.Second
+	// TSOProxyStreamIdleTimeout defines how long Proxy stream will live if no request is received
+	TSOProxyStreamIdleTimeout = 5 * time.Minute
```
Comment (JmPotato) [inline pkg/utils/tsoutil/tso_dispatcher.go:41]: This const doesn't need to be exported.

File: pkg/utils/tsoutil/tso_dispatcher.go [hunk 6]
```diff
@@ -65,75 +74,62 @@ func (s *TSODispatcher) DispatchRequest(
...
-		}
+		tsoQueue.cancel(err)
+		return
 	}
 	defer cancel()
 
 	requests := make([]Request, maxMergeRequests+1)
 	needUpdateServicePrimaryAddr := len(tsoPrimaryWatchers) > 0 && tsoPrimaryWatchers[0] != nil
 	for {
+		noProxyRequestsTimer := time.NewTimer(TSOProxyStreamIdleTimeout)
```
Comment (JmPotato) [inline pkg/utils/tsoutil/tso_dispatcher.go:121]: Do we need to create a timer inside the loop? Is it possible to reuse the same timer always?

**Review by bufferflies — APPROVED** [review]

**Comment by bufferflies** [comment]
> @JmPotato @bufferflies I've done addressing all the comments, but it lacks test coverage and I'm afraid #9243 won't be enough, so I'm working on bringing a more comprehensive tso proxy server test suite.

You can copy the PR#9243 into this PR and add some unit tests for the new struct, I think it's enough.

**Review by JmPotato — APPROVED** [review]

**Comment by bufferflies** [comment]
> @JmPotato @bufferflies I'm still working on comprehensive unit tests for tso proxy server and cut a separate PR soon.

Great, thanks for your contributions for PD.
