### PR TITLE
*: fix `startWatchLoop` leak

### LINKED ISSUE #6351: Data race caused by `watchServiceAddrs`
### Which jobs are failing
```
==================
WARNING: DATA RACE
Read at 0x00c00364e8d0 by goroutine 73881:
  runtime.mapaccess2_faststr()
      /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/map_faststr.go:108 +0x0
  github.com/tikv/pd/pkg/keyspace.(*GroupManager).watchServiceAddrs()
      /home/runner/work/pd/pd/pkg/keyspace/tso_keyspace_group.go:238 +0xd92
  github.com/tikv/pd/pkg/keyspace.(*GroupManager).startWatchLoop()
      /home/runner/work/pd/pd/pkg/keyspace/tso_keyspace_group.go:190 +0x85d
  github.com/tikv/pd/pkg/keyspace.(*GroupManager).Bootstrap.func2()
      /home/runner/work/pd/pd/pkg/keyspace/tso_keyspace_group.go:138 +0x39

Previous write at 0x00c00364e8d0 by goroutine 67981:
  runtime.mapdelete_faststr()
      /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/map_faststr.go:301 +0x0
  github.com/tikv/pd/pkg/keyspace.(*GroupManager).watchServiceAddrs()
      /home/runner/work/pd/pd/pkg/keyspace/tso_keyspace_group.go:239 +0xe1b
  github.com/tikv/pd/pkg/keyspace.(*GroupManager).startWatchLoop()
      /home/runner/work/pd/pd/pkg/keyspace/tso_keyspace_group.go:190 +0x85d
  github.com/tikv/pd/pkg/keyspace.(*GroupManager).Bootstrap.func2()
      /home/runner/work/pd/pd/pkg/keyspace/tso_keyspace_group.go:138 +0x39

Goroutine 73881 (running) created at:
  github.com/tikv/pd/pkg/keyspace.(*GroupManager).Bootstrap()
      /home/runner/work/pd/pd/pkg/keyspace/tso_keyspace_group.go:138 +0xa39
  github.com/tikv/pd/server/cluster.(*RaftCluster).Start()
      /home/runner/work/pd/pd/server/cluster/cluster.go:278 +0x384
  github.com/tikv/pd/server.(*Server).createRaftCluster()
      /home/runner/work/pd/pd/server/server.go:706 +0x153
  github.com/tikv/pd/server.(*Server).campaignLeader()
      /home/runner/work/pd/pd/server/server.go:1519 +0x1d86
  github.com/tikv/pd/server.(*Server).leaderLoop()
      /home/runner/work/pd/pd/server/server.go:1445 +0x1184
  github.com/tikv/pd/server.(*Server).startServerLoop.func1()
      /home/runner/work/pd/pd/server/server.go:565 +0x39

Goroutine 67981 (running) created at:
  github.com/tikv/pd/pkg/keyspace.(*GroupManager).Bootstrap()
      /home/runner/work/pd/pd/pkg/keyspace/tso_keyspace_group.go:138 +0xa39
  github.com/tikv/pd/server/cluster.(*RaftCluster).Start()
      /home/runner/work/pd/pd/server/cluster/cluster.go:278 +0x384
  github.com/tikv/pd/server.(*Server).bootstrapCluster()
      /home/runner/work/pd/pd/server/server.go:688 +0x1ba4
  github.com/tikv/pd/server.(*GrpcServer).Bootstrap()
      /home/runner/work/pd/pd/server/grpc_service.go:291 +0x4be
  github.com/tikv/pd/tests.(*TestServer).BootstrapCluster()
      /home/runner/work/pd/pd/tests/cluster.go:396 +0x644
  github.com/tikv/pd/tests/integrations/mcs/tso.(*CommonTestSuite).SetupSuite()
      /home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:350 +0x484
  github.com/stretchr/testify/suite.Run()
      /home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:154 +0x5d7
  github.com/tikv/pd/tests/integrations/mcs/tso.TestCommonTestSuite()
      /home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:334 +0x44
  testing.tRunner()
      /opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:1629 +0x47
==================
```

### CI link
https://github.com/tikv/pd/actions/runs/4751210932/jobs/8440122477

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Ref #6351.

### What is changed and how does it work?

Use the cluster's context instead of the keyspace group manager's context.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Review by binshi-bing — COMMENTED** [review]
left one comment

File: pkg/keyspace/tso_keyspace_group.go [hunk 1]
```diff
@@ -101,7 +101,7 @@ func NewKeyspaceGroupManager(ctx context.Context, store endpoint.KeyspaceGroupSt
 }
 
 // Bootstrap saves default keyspace group info and init group mapping in the memory.
-func (m *GroupManager) Bootstrap() error {
+func (m *GroupManager) Bootstrap(ctx context.Context) error {
```
Comment (binshi-bing) [inline pkg/keyspace/tso_keyspace_group.go:104]: I have understood the problem, and I feel this fix could be cleaner, though it can fix the problem. The GroupManage still holds the context directly inherited from pd server, but the resources are under RaftCluster's context.

With the current logic, keyspaceGroupManager's state is leader instance specific, can we new KeyspaceGroupManager inside of RaftCluster.Start with RaftCluster's context, just as NewRuleManager/NewRegionLabeler/NewReplicationModeManager does. We'll naturally avoid the bug.

Even better, can every API node, including leader and follower, keep and track keyspace group's membership/tso service registry/distribution change to serve keyspace group meta query, but only leader can serve membership/distribution write requests?

Comment (rleungx) [reply pkg/keyspace/tso_keyspace_group.go:104]: When we new a keyspaceManger, we need to pass keyspaceGroupManager as a parameter.

**Review by CabinfeverB — APPROVED** [review]

**Review by binshi-bing — APPROVED** [review]
