### PR TITLE
config: fix precheck blocking the change of other PD configurations

### LINKED ISSUE #10114: Dashboard precheck blocks the change of other PD configurations
## Bug Report

If the dashboard uses an old PD address, which could have been offline already, the pd server config cannot be changed due to the precheck. One workaround is to disable the dashboard first before making the change.

Image

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #10114.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error messages for dashboard address validation, providing clearer feedback when an invalid address is configured.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

File: server/server.go [hunk 1]
```diff
@@ -1289,22 +1289,23 @@ func (s *Server) GetPDServerConfig() *config.PDServerConfig {
...
-			return errors.Errorf("%s is not the client url of any member", cfg.DashboardAddress)
-		}
-	}
 	if err := cfg.Validate(); err != nil {
 		return err
 	}
-
 	old := s.persistOptions.GetPDServerConfig()
+	if old.DashboardAddress != cfg.DashboardAddress {
+		switch cfg.DashboardAddress {
```
Comment (HunDunDM) [inline server/server.go:1298]: May add a link to the relevant issue in the comments? rest LGTM

Comment (rleungx) [reply server/server.go:1298]: done

**Review by HunDunDM — APPROVED** [review]
