### PR TITLE
mcs: fix the compatibility issue of batch allocating IDs

### LINKED ISSUE #9138: ID will be duplicated if the scheduling service upgrade first
## Bug Report

Previously, we only ensured compatibility issues when PD was upgraded first. If the scheduling server completed the upgrade first but PD has not been upgraded yet, there will be duplicate IDs.

1. Assume that the current PD base ID is 10. 
2. The upgraded scheduling server receives the `AskBatchSplit` request. Assume that the request count is 1. 
3. But the PD server has not been upgraded at this time, it is sent to the PD server for processing as a non-batch request. The base ID returned to the caller is 11, the region ID is 11, and the peer IDs are 12, 13, and 14 respectively.
4. After the PD server upgrade is completed, the scheduling server receives the `AskBatchSplit` request again. 
5. Assuming that the request count is 1, it is processed as a batch request. And the base ID returned to the caller is `15-4=11`, the region ID is 11, and the peer IDs are 12, 13, and 14. 

So the bug is triggered that the region ID is the same but the range is different.

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9138.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/integrations/mcs/scheduling/server_test.go [hunk 1]
```diff
@@ -833,3 +833,101 @@ func (suite *serverTestSuite) TestBatchSplit() {
...
+	re.Len(allocatedIDs, 40)
+
+	// simulate the new version of PD
+	re.NoError(failpoint.Disable("github.com/tikv/pd/server/allocIDOnce"))
+
+	resp, err = grpcPDClient.AskBatchSplit(suite.ctx, req)
+	re.NoError(err)
+	re.Empty(resp.GetHeader().GetError())
+	for _, id := range resp.GetIds() {
+		_, ok := allocatedIDs[id.NewRegionId]
```
Comment (okJiang) [inline tests/integrations/mcs/scheduling/server_test.go:922]: How about checking `NewRegionId > all allocatedIDs`?

Comment (rleungx) [reply tests/integrations/mcs/scheduling/server_test.go:940]: add a check in grpc_service.go

File: pkg/mcs/scheduling/server/grpc_service.go [hunk 2]
```diff
@@ -298,47 +299,39 @@ func (s *Service) AskBatchSplit(_ context.Context, request *schedulingpb.AskBatc
 	// PD doesn't support allocating IDs in batch. We need to allocate IDs
 	// for each region.
 	if requestIDCount != count {
-		// use old way to split region
-		for range splitCount {
-			newRegionID, _, err := c.AllocID(1)
+		for range requestIDCount - 1 {
+			id, _, err = c.AllocID(1)
```
Comment (okJiang) [inline pkg/mcs/scheduling/server/grpc_service.go:303]: Can we guarantee that the IDs returned from consecutive requests are sequential? What if another client makes an ID request in the meantime?

Comment (okJiang) [reply pkg/mcs/scheduling/server/grpc_service.go:303]: Maybe we can save these ids and handle them together later.

Comment (rleungx) [reply pkg/mcs/scheduling/server/grpc_service.go:303]: I plan to revert to the original implementation. /cc @bufferflies

Comment (rleungx) [reply pkg/mcs/scheduling/server/grpc_service.go]: I have added a concurrency test.

**Review by bufferflies — APPROVED** [review]

**Review by okJiang — APPROVED** [review]
