### PR TITLE
Handle compatibility issue in GetClusterInfo RPC

### LINKED ISSUE #6448: PD (Client) in TiDB seems to have tso service discovery failure
### What did you do?

Hanyang is running TiUP with multiple-group tso cherry-pick

### What did you expect to see?
no suspicious error log, which indicates tso service discovery failure, printed periodically

### What did you see instead?
"failed to find the keyspace group" log is printed periodically

### What version of PD are you using (`pd-server -V`)?
pd-cse

### PR DESCRIPTION
**Pull request by binshi-bing**
### What problem does this PR solve?
 If the server has lower version than the client and returns no tso addrs in the GetClusterInfo RPC, the client then falls back to the legacy path to discover TSO servers from etcd directly.

Issue Number: Ref #5895
Issue Number: Close #6448 

### What is changed and how does it work?

```commit-message
Handle the compatibility issue in the GetClusterInfo RPC
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: client/tso_service_discovery.go [hunk 1]
```diff
@@ -526,3 +503,83 @@ func (c *tsoServiceDiscovery) findGroupByKeyspaceID(
...
+			// There is no error but no tso server address found, which means
+			// either the server side is experiencing some problems to get the
+			// tso primary addresses or the server hasn't been upgraded to the
+			// version which processes and returns GetClusterInfoResponse.TsoUrls.
+			// In this case, we fall back to the old way of discovering the tso
+			// primary addresses from etcd directly.
+			log.Warn("[tso] no tso server address found,"+
+				" fallback to the legacy path to discover from etcd directly",
+				zap.String("discovery-key", c.defaultDiscoveryKey))
+			addrs, err = c.discoverWithLegacyPath()
```
Comment (lhy1024) [inline client/tso_service_discovery.go:534]: if api server has been ready without tso service, but tso server is starting, what will happen? return error "not found"?

Comment (binshi-bing) [reply client/tso_service_discovery.go:534]: It returns communication error or "not started" or "not served" for this case.

Comment (binshi-bing) [reply client/tso_service_discovery.go:534]: "no error and tso_urls is nil" indicates the server version is behind and doesn't return tso_urls.

**Review by lhy1024 — APPROVED** [review]

File: tests/integrations/tso/client_test.go [hunk 2]
```diff
@@ -197,6 +197,32 @@ func (suite *tsoClientTestSuite) TestGetTSAsync() {
...
+	re := suite.Require()
+	var wg sync.WaitGroup
+	wg.Add(tsoRequestConcurrencyNumber)
+	for i := 0; i < tsoRequestConcurrencyNumber; i++ {
+		go func() {
+			defer wg.Done()
+			// Simulate the case that the server has lower version than the client and returns no tso addrs
+			// in the GetClusterInfo RPC.
+			re.NoError(failpoint.Enable("github.com/tikv/pd/client/serverReturnsNoTSOAddrs", "return(true)"))
+			defer re.NoError(failpoint.Disable("github.com/tikv/pd/client/serverReturnsNoTSOAddrs"))
```
Comment (JmPotato) [inline tests/integrations/tso/client_test.go:210]: No need to enable the failpoint in each goroutine?

Comment (rleungx) [reply tests/integrations/tso/client_test.go:210]: need to use 
```
defer func() {
      re.NoError(failpoint.Disable("github.com/tikv/pd/client/serverReturnsNoTSOAddrs"))
}
```
or disable it in the end of the goroutine

File: client/client.go [hunk 3]
```diff
@@ -429,16 +429,14 @@ func (c *client) loadKeyspaceMeta(keyspace string) error {
...
+	// Init the metrics.
+	initAndRegisterMetrics(c.option.metricsLabels)
+
 	// Init the client base.
 	if err := c.pdSvcDiscovery.Init(); err != nil {
 		return err
 	}
 
-	// Init the metrics.
-	if c.option.initMetrics {
```
Comment (rleungx) [inline client/client.go:438]: Why remove it?

Comment (binshi-bing) [reply client/client.go:438]: It shouldn't add c.option.initMetrics, because it will cause panic.

Comment (binshi-bing) [reply client/client.go:438]: Hi Zheming, regarding ​[client: add a option to control whether to initialize the metric when… · tikv/pd@b159dd2](https://github.com/tikv/pd/commit/b159dd2df37c8da4c001ec176b4df706a78ea2bb)
```
        // Init the metrics.
        if c.option.initMetrics {
                initAndRegisterMetrics(c.option.metricsLabels)
        }
```
We added "c.option.initMetrics" to call initAndRegisterMetrics conditionally, but Cmd Durations are always used without checking if it is initialized or not, will it cause null reference panic if the caller turns off c.option.initMetrics when creating a pd client?

Comment (binshi-bing) [reply client/client.go:438]: Zheming, confirmed "It will panic, I revert this PR first." and has a follow-up to fix it. https://github.com/tikv/pd/pull/6441

File: tests/integrations/tso/client_test.go (hunk 2 above)
Comment (binshi-bing) [reply tests/integrations/tso/client_test.go]: figured out. failpoint isn't goroutine isolated.

File: client/client.go (hunk 3 above)
Comment (binshi-bing) [reply client/client.go:438]: I added back so that my pr is independent of Zheming's fix

File: client/tso_service_discovery.go [hunk 4]
```diff
@@ -526,3 +503,84 @@ func (c *tsoServiceDiscovery) findGroupByKeyspaceID(
...
+			addrs = nil
+		})
+		if len(addrs) == 0 {
+			// There is no error but no tso server address found, which means
+			// either the server side is experiencing some problems to get the
+			// tso primary addresses or the server hasn't been upgraded to the
+			// version which processes and returns GetClusterInfoResponse.TsoUrls.
+			// In this case, we fall back to the old way of discovering the tso
+			// primary addresses from etcd directly.
+			log.Warn("[tso] no tso server address found,"+
```
Comment (rleungx) [inline client/tso_service_discovery.go:532]: This file permission has changed to 0755, need to change it back.

Comment (binshi-bing) [reply client/tso_service_discovery.go:532]: changed back.

File: client/tso_service_discovery.go [hunk 5]
```diff
@@ -526,3 +503,84 @@ func (c *tsoServiceDiscovery) findGroupByKeyspaceID(
...
+	t.selectIdx++
+	t.selectIdx %= len(t.addrs)
+
+	return tsoServerAddr, nil
+}
+
+func (c *tsoServiceDiscovery) discoverWithLegacyPath() ([]string, error) {
+	resp, err := c.metacli.Get(c.ctx, []byte(c.defaultDiscoveryKey))
+	if err != nil {
+		log.Error("[tso] failed to get the kesypace serving endpoint",
```
Comment (rleungx) [inline client/tso_service_discovery.go:562]:
```suggestion
		log.Error("[tso] failed to get the keyspace serving endpoint",
```

**Review by rleungx — APPROVED** [review]

File: client/tso_service_discovery.go (hunk 5 above)
Comment (binshi-bing) [reply client/tso_service_discovery.go:562]: good catch.

Comment (binshi-bing) [reply client/tso_service_discovery.go]: fixed
