### PR TITLE
client: updating keyspace group must check the previous version

### LINKED ISSUE #6770: Round-robin updateMember may cause the timestamp to fallback
## Bug Report

We use a round-robin way to request the TSO server with `FindGroupByKeyspaceID` gRPC call.

https://github.com/tikv/pd/blob/b176a0a573a6633f0185cc8e2225af6b6371485c/client/tso_service_discovery.go#L418-L441

However, if the requested TSO server satisfies this kind of case, it may cause the timestamp to fallback.

- TSO node A initialized group 1.
- TSO node B has not initialized group 1 yet.

If we do `updateMember` quickly while requesting the TSO, it may cause the keyspace group in the request to change between the default group and group 1, resulting in the timestamp fallback.

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #6770

[Merged]kv proto: [#1361](https://github.com/pingcap/kvproto/pull/1361)

### What is changed and how does it work?

```commit-message
'FindGroupByKeyspaceID' must carry the current keyspace group version, and the server needs to check the memory
state isn't stale, and then return the server keyspace group info.
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

Side effects

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: client/servicediscovery/tso_service_discovery.go [hunk 1]
```diff
@@ -66,16 +66,27 @@ type keyspaceGroupSvcDiscovery struct {
 	secondaryURLs []string
 	// urls are the primary/secondary serving URL
 	urls []string
+
+	// version is used to avoid updating stale info
```
Comment (ystaticy) [inline client/servicediscovery/tso_service_discovery.go]: How about adding a comment to clarify where the version is sourced from and briefly explain its usage?

File: client/servicediscovery/tso_service_discovery.go [hunk 2]
```diff
@@ -160,6 +171,7 @@ func NewTSOServiceDiscovery(
 		primaryURL:    "",
 		secondaryURLs: make([]string, 0),
 		urls:          make([]string, 0),
+		version:       0,
```
Comment (ystaticy) [inline client/servicediscovery/tso_service_discovery.go]: When the TSO client starts up, does it use version=0 for the initial request?

Furthermore, if this initial request is routed to a TSO service with a lower version, is that behavior expected?

File: client/servicediscovery/tso_service_discovery.go (hunk 1 above)
Comment (bufferflies) [reply client/servicediscovery/tso_service_discovery.go]: done

File: client/servicediscovery/tso_service_discovery.go (hunk 2 above)
Comment (bufferflies) [reply client/servicediscovery/tso_service_discovery.go]: No, this version just works for requesting the keyspace group. Most updates don't relate to this client's keyspace ID, so it doesn't need to be updated.

Comment (bufferflies) [reply client/servicediscovery/tso_service_discovery.go]: The higher version of the server side doesn't mean that the client's keyspace group has changed.

File: client/servicediscovery/tso_service_discovery.go [hunk 3]
```diff
@@ -66,16 +66,31 @@ type keyspaceGroupSvcDiscovery struct {
 	secondaryURLs []string
 	// urls are the primary/secondary serving URL
 	urls []string
+
+	// version is used to avoid updating stale info
+	// this version is provided by etcd watcher on the server side
+	// and increases monotonically.
+	// If the new version is less than the current version, it means that the requested tso service hasn't applied the
```
Comment (ystaticy) [inline client/servicediscovery/tso_service_discovery.go]: How about clarifying the source of both `the new version` and `the current version`?

File: pkg/tso/keyspace_group_manager.go [hunk 4]
```diff
@@ -91,6 +91,8 @@ type state struct {
 	// Once a group receives its first TSO request and pass the certain check, it will be added to this map.
 	// Being merged will cause the group to be removed from this map eventually if the merge is successful.
 	requestedGroups map[uint32]struct{}
+
+	modVersion uint64
```
Comment (ystaticy) [inline pkg/tso/keyspace_group_manager.go]: Please add comments for `modVersion uint64`.

File: client/servicediscovery/tso_service_discovery.go (hunk 3 above)
Comment (bufferflies) [reply client/servicediscovery/tso_service_discovery.go]: done

File: pkg/tso/keyspace_group_manager.go (hunk 4 above)
Comment (bufferflies) [reply pkg/tso/keyspace_group_manager.go]: done

File: pkg/tso/keyspace_group_manager.go [hunk 5]
```diff
@@ -515,12 +538,22 @@ func (kgm *KeyspaceGroupManager) InitializeGroupWatchLoop() error {
...
 		}
+		failpoint.Inject("SkipKeyspaceWatch", func(val failpoint.Value) {
+			addr, ok := val.(string)
+			if ok && addr == kgm.electionNamePrefix {
+				failpoint.Return(nil)
+			}
+		})
+		if len(event) > 0 {
+			last := event[len(event)-1]
+			kgm.SetModVersion(uint64(last.Kv.ModRevision))
```
Comment (rleungx) [inline pkg/tso/keyspace_group_manager.go]: Shall we use the kv mod revision or the revision in the response?

Comment (bufferflies) [reply pkg/tso/keyspace_group_manager.go]: No, the response header revision is the latest version of the global KV. It may bring some probs: 
1. It updates stale if it lists all keyspaces and updates the cache one by one; the revision between the first kv and last kv is the same. If we update the revision at first and the second kv does not update. The cache is stale.
2. if no update in the etcd key, the header revision is always the same, we can't know the kv is the latest.

File: client/servicediscovery/tso_service_discovery.go [hunk 6]
```diff
@@ -413,12 +428,16 @@ func (c *tsoServiceDiscovery) updateMember() error {
 
 	keyspaceID := c.GetKeyspaceID()
 	var keyspaceGroup *tsopb.KeyspaceGroup
+	var version uint64
```
Comment (rleungx) [inline client/servicediscovery/tso_service_discovery.go]: How about unifying the naming, using modRevision and curModRevision?
