### PR TITLE
replication mode: fix wrong available store list

### LINKED ISSUE #7221: replication mode: `available_stores` is wrongly calculated
### What did you do?
when some stores are configured to be used to schedule learners, they should be contained in `available stores` list.

### What did you expect to see?
`available stores` list contains stores that only have raft learners.

### What did you see instead?
`available stores` list does not contain stores that only have raft learners.

### What version of PD are you using (`pd-server -V`)?
master/v6.5.5

### PR DESCRIPTION
**Pull request by disksing**
### What problem does this PR solve?
Issue Number: Close #7221 #7218

### What is changed and how does it work?
As now `canSync` and `hasMajority` are calculated using placement rules, we can contain stores that have only learners in avalable stores list.

This PR also fix a minor bug that relates to available stores id comparsion.

```commit-message
```

### Check List

Tests
- Unit test

Related changes
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

File: pkg/replication/replication_mode.go [hunk 1]
```diff
@@ -489,7 +489,7 @@ func (m *ModeManager) tickUpdateState() {
 			m.drSwitchToSyncRecover()
 			break
 		}
-		if !reflect.DeepEqual(m.drGetAvailableStores(), stores[primaryUp]) && m.drCheckStoreStateUpdated(storeIDs(stores[primaryUp])) {
+		if !reflect.DeepEqual(m.drGetAvailableStores(), storeIDs(stores[primaryUp])) && m.drCheckStoreStateUpdated(storeIDs(stores[primaryUp])) {
```
Comment (CabinfeverB) [inline pkg/replication/replication_mode.go:492]: How about `checkStoreStatus` returns `[][]*core.StoreInfo` and `[][]uint64`

**Review by CabinfeverB — APPROVED** [review]
rest LGTM

File: pkg/replication/replication_mode.go (hunk 1 above)
Comment (lhy1024) [reply pkg/replication/replication_mode.go:492]: BTW, it may be more readable ` primaryUpStores := storeIDs(stores[primaryUp]` https://github.com/lhy1024/pd/blob/2452a4de9440d2c5d5c098c0555a003ee928260a/pkg/replication/replication_mode.go#L469
