### PR TITLE
tests: make TestSplitKeyspaceGroup stable

### LINKED ISSUE #6571: TestSplitKeyspaceGroup "Condition never satisfied" randomly
### Which jobs are failing
--- FAIL: TestSplitKeyspaceGroup (44.24s)
    testutil.go:63: 
        	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/testutil.go:63
        	            				/home/runner/work/pd/pd/tests/pdctl/keyspace/keyspace_group_test.go:124
        	Error:      	Condition never satisfied
        	Test:       	TestSplitKeyspaceGroup

### CI link
https://github.com/tikv/pd/actions/runs/5203268375/jobs/9385886991?pr=6565

### Reason for failure (if possible)
unknown

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #6571

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by lhy1024** [comment]
it is stable enough.

https://github.com/tikv/pd/actions/runs/5224016809/jobs/9431687002
https://github.com/tikv/pd/actions/runs/5224016809/jobs/9431895862
https://github.com/tikv/pd/actions/runs/5224016809/jobs/9432183860
https://github.com/tikv/pd/actions/runs/5224016809/jobs/9432369885
https://github.com/tikv/pd/actions/runs/5224016809/jobs/9432369885
https://github.com/tikv/pd/actions/runs/5224016809/jobs/9432557465
https://github.com/tikv/pd/actions/runs/5224016809/jobs/9432742936
https://github.com/tikv/pd/actions/runs/5224583895/jobs/9432950984

File: tests/pdctl/keyspace/keyspace_group_test.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ func TestSplitKeyspaceGroup(t *testing.T) {
 	re.NoError(failpoint.Enable("github.com/tikv/pd/pkg/keyspace/acceleratedAllocNodes", `return(true)`))
 	re.NoError(failpoint.Enable("github.com/tikv/pd/server/delayStartServerLoop", `return(true)`))
 	keyspaces := make([]string, 0)
-	for i := 0; i < 500; i++ {
+	for i := 0; i < 129; i++ { // 128 is the default max txn ops limit in etcd.
```
Comment (binshi-bing) [inline tests/pdctl/keyspace/keyspace_group_test.go:99]: If we use 129 here, we'll add 129 txn ops instead of 128, right?

Comment (binshi-bing) [reply tests/pdctl/keyspace/keyspace_group_test.go:99]: you add 0, 1, ..., 128 keypsace here, 129 in total which will exceed the default max txn ops limit in etcd.

File: pkg/keyspace/tso_keyspace_group.go [hunk 2]
```diff
@@ -352,6 +360,32 @@ func (m *GroupManager) saveKeyspaceGroups(keyspaceGroups []*endpoint.KeyspaceGro
...
+		oldKG, err := m.store.LoadKeyspaceGroup(txn, keyspaceGroup.ID)
+		if err != nil {
+			return err
+		}
+		if oldKG.IsSplitting() {
+			return ErrKeyspaceGroupInSplit
+		}
+		newKG := oldKG
+		newKG.Keyspaces = keyspaceGroup.Keyspaces
+		if oldKG.IsSplitting() {
```
Comment (binshi-bing) [inline pkg/keyspace/tso_keyspace_group.go:376]: It has already checked that "if oldKG.IsSplitting() is true and exit on condition met" at line 371 above.
So the check here is always true.

Comment (binshi-bing) [reply pkg/keyspace/tso_keyspace_group.go:376]: It looks like we have conflict logic here -- if oldKG.IsSplitting() is true, do we want to return ErrKeyspaceGroupInSplit, or want to set newKG.SplitState and proceed?

Comment (binshi-bing) [reply pkg/keyspace/tso_keyspace_group.go:376]: The whole function doesn't provide CAS semantics, which is my real concern. 
Before the caller calls saveGroupWithUpdateKeyspace, the caller must have loaded the keyspace group info from the etcd, then do some calculation and update keyspace list in the memory, finally call saveGroupWithUpdateKeyspace here. If somehow the latest keyspace list loaded here is different from the original one, it will overwrite something and cause inconsistency. Two ways to solve it:
1. saveGroupWithUpdateKeyspace should check if the latest keyspace group info loaded here has the same keypace list as the original one which can pass to this function.
2. Just pass two lists to saveGroupWithUpdateKeyspace -- one keyspace list to add and one keyspace list to delete, and this function just needs to add if it doesn't exist or delete if it exists based on the latest loaded keyspace list here.

**Review by binshi-bing — CHANGES_REQUESTED** [review]
left some comments.

File: tests/pdctl/keyspace/keyspace_group_test.go (hunk 1 above)
Comment (lhy1024) [reply tests/pdctl/keyspace/keyspace_group_test.go:99]: yes, test the case which exceed the default max txn ops limit in etcd

File: pkg/keyspace/tso_keyspace_group.go (hunk 2 above)
Comment (lhy1024) [reply pkg/keyspace/tso_keyspace_group.go:376]: saveGroupWithUpdateKeyspace is a part of saveKeyspaceGroups, and only update keyspace list param

Comment (lhy1024) [reply pkg/keyspace/tso_keyspace_group.go:376]: because updateKeyspaceForGroupLocked load kg from memory rather than etcd, so we should not update other params besides keyspace list.

Comment (lhy1024) [reply pkg/keyspace/tso_keyspace_group.go:376]: keyspace check is in updateKeyspaceForGroupLocked

**Comment by lhy1024** [comment]
cc @binshi-bing @JmPotato

**Review by JmPotato — APPROVED** [review]

File: pkg/keyspace/tso_keyspace_group.go [hunk 3]
```diff
@@ -352,6 +355,27 @@ func (m *GroupManager) saveKeyspaceGroups(keyspaceGroups []*endpoint.KeyspaceGro
 	})
 }
 
+// saveGroupWithUpdateKeyspace will try to save the given keyspace groups into the storage.
+// It only update the keyspace field for the keyspace group.
+func (m *GroupManager) saveGroupWithUpdateKeyspace(keyspaceGroup *endpoint.KeyspaceGroup) error {
```
Comment (rleungx) [inline pkg/keyspace/tso_keyspace_group.go:360]: If we only run it on the leader node, do we still need it?

Comment (lhy1024) [reply pkg/keyspace/tso_keyspace_group.go:360]: I think it is still necessary because we provide an external interface to set node for keyspace groups.

Comment (rleungx) [reply pkg/keyspace/tso_keyspace_group.go:360]: But it can be only executed by the leader?

Comment (lhy1024) [reply pkg/keyspace/tso_keyspace_group.go:360]: Yes, but `UpdateKeyspaceForGroup` is called by manager of keyspace. 

For example, when manager of keyspace call `UpdateKeyspaceForGroup`, but we exec `set node` before `updateKeyspaceForGroupLocked`, which is similiar with [failpoint.Inject](https://github.com/tikv/pd/blob/fe58ed103afc060b97f6884c71085d78b12fe5bc/pkg/keyspace/tso_keyspace_group.go#L418).

File: pkg/keyspace/tso_keyspace_group.go [hunk 4]
```diff
@@ -137,6 +140,11 @@ func (m *GroupManager) Bootstrap() error {
 		m.groups[userKind].Put(group)
 	}
 
+	// It will only alloc node when the group manager is on API leader.
+	if m.client != nil {
+		m.wg.Add(1)
+		go m.allocNodesToAllKeyspaceGroups()
```
Comment (rleungx) [inline pkg/keyspace/tso_keyspace_group.go:146]: If we transfer the leader, will it exit?

File: pkg/keyspace/tso_keyspace_group.go (hunk 3 above)
Comment (rleungx) [reply pkg/keyspace/tso_keyspace_group.go:360]: We have a lock. Does it prevent this thing from happening?

File: tests/pdctl/keyspace/keyspace_group_test.go (hunk 1 above)
Comment (binshi-bing) [reply tests/pdctl/keyspace/keyspace_group_test.go:99]: oh, could add this statement in comment? Without this statement, the code looks like have bug.

**Review by binshi-bing — APPROVED** [review]
LGTM

File: pkg/keyspace/tso_keyspace_group.go (hunk 3 above)
Comment (lhy1024) [reply pkg/keyspace/tso_keyspace_group.go]: yes, updated, PTAL

File: pkg/keyspace/tso_keyspace_group.go (hunk 4 above)
Comment (lhy1024) [reply pkg/keyspace/tso_keyspace_group.go]: Thanks, added ctx

**Comment by lhy1024** [comment]
@rleungx PTAL

File: pkg/keyspace/tso_keyspace_group.go [hunk 5]
```diff
@@ -158,6 +166,9 @@ func (m *GroupManager) allocNodesToAllKeyspaceGroups() {
 	log.Info("start to alloc nodes to all keyspace groups")
 	for {
 		select {
+		case <-ctx.Done():
+			log.Info("stop to alloc nodes to all keyspace groups")
+			return
 		case <-m.ctx.Done():
```
Comment (rleungx) [inline pkg/keyspace/tso_keyspace_group.go:172]: Do we still need it?

**Review by rleungx — APPROVED** [review]
