### PR TITLE
schedule: fix tiflash hot scheduling

### LINKED ISSUE #9924: TiFlash expectation of hot scheduling is wrong
## Bug Report

Image

The expectation is lower than all TiFlash nodes.

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9924

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/statistics/store_load.go [hunk 1]
```diff
@@ -109,8 +109,10 @@ func SummaryStoreInfos(stores []*core.StoreInfo) map[uint64]*StoreSummaryInfo {
 	infos := make(map[uint64]*StoreSummaryInfo, len(stores))
 	for _, store := range stores {
 		info := &StoreSummaryInfo{
-			StoreInfo:  store,
-			isTiFlash:  store.IsTiFlash(),
+			StoreInfo: store,
+			// Only mark TiFlash write nodes, not compute nodes.
+			// Compute nodes don't store data and shouldn't be included in hot region scheduling.
+			isTiFlash:  store.IsTiFlashWrite(),
```
Comment (lhy1024) [inline pkg/statistics/store_load.go]:
```suggestion
			isTiFlashWrite:  store.IsTiFlashWrite(),
```

Comment (lhy1024) [reply pkg/statistics/store_load.go]: Will it affect the exp of tikv?

Comment (lhy1024) [reply pkg/statistics/store_load.go]: Perhaps we need to modify `IsTiFlash()` to change it from a Boolean value to an enum variable for `TiKV`, `TiFlashWrite`, and `TiFlashCompute`.

Comment (rleungx) [reply pkg/statistics/store_load.go]: I have removed this flag and use the store label to check.

File: pkg/statistics/collector.go [hunk 2]
```diff
@@ -41,6 +41,7 @@ func (tikvCollector) engine() string {
 }
 
 func (tikvCollector) filter(info *StoreSummaryInfo, kind constant.ResourceKind) bool {
+	// Exclude all TiFlash nodes (both Write and Compute)
 	if info.IsTiFlash() {
```
Comment (lhy1024) [inline pkg/statistics/collector.go]: Do we need to remove `IsTiFlash()` in `StoreSummaryInfo`?

Comment (rleungx) [reply pkg/statistics/collector.go]: Why?

File: pkg/schedule/handler/handler.go [hunk 3]
```diff
@@ -1017,7 +1017,7 @@ func (h *Handler) GetHotStores() (*HotStoreStats, error) {
 	for _, store := range stores {
 		id := store.GetID()
 		if loads, ok := storesLoads[id]; ok {
-			if store.IsTiFlash() {
+			if store.IsTiFlashWrite() {
```
Comment (JmPotato) [inline pkg/schedule/handler/handler.go:1023]: Will this change affect the legacy architecture?

File: pkg/statistics/collector.go (hunk 2 above)
Comment (lhy1024) [reply pkg/statistics/collector.go]: Only concern whether need to modify for other `IsTiFlash()`

File: pkg/schedule/handler/handler.go (hunk 3 above)
Comment (rleungx) [reply pkg/schedule/handler/handler.go:1023]: IsTiFlashWrite returns true if the store is TiFlash write node or TiFlash classic node.

**Review by lhy1024 — APPROVED** [review]
