### PR TITLE
ttl: Trying to get float64 after get uint64 fails.

### LINKED ISSUE #7980: ttl: get uint64 value fails because passing `uint64(math.MaxInt32)`
### What did you do?
set `schedule.max-pending-peer-count` as `uint64(math.MaxInt32)`

### What did you expect to see?
parse value success

### What did you see instead?
`[2024/03/25 06:55:50.799 +00:00] [WARN] [persist_options.go:887] ["failed to parse schedule.max-pending-peer-count from PersistOptions's ttl storage"] [error="strconv.ParseUint: parsing \"2.147483647e+09\": invalid syntax"]`
and get default value

### Error Stack
json unmarshal will convert number(such as `uint64(math.MaxInt32)`) to float64

and then set float64 into TTL config
https://github.com/tikv/pd/blob/6ee25f9f8177067957b0932f1be7e2cace0202d0/server/server.go#L1955

will transfer `fmt.Sprint(math.MaxInt32)` to `2.147483647e+09` which will meet error 

`[2024/03/25 06:55:50.799 +00:00] [WARN] [persist_options.go:887] ["failed to parse schedule.max-pending-peer-count from PersistOptions's ttl storage"] [error="strconv.ParseUint: parsing \"2.147483647e+09\": invalid syntax"]`

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Close #7980

### What is changed and how does it work?

when set `schedule.max-pending-peer-count` as `uint64(math.MaxInt32)`

json unmarshal will convert number(`uint64(math.MaxInt32)`) to float64

and then set float64 into TTL config
https://github.com/tikv/pd/blob/6ee25f9f8177067957b0932f1be7e2cace0202d0/server/server.go#L1955

and then `fmt.Sprint(float(math.MaxInt32))` will transfer `float(math.MaxInt32)` to `2.147483647e+09` which will meet error when try to get TTL config

`[2024/03/25 06:55:50.799 +00:00] [WARN] [persist_options.go:887] ["failed to parse schedule.max-pending-peer-count from PersistOptions's ttl storage"] [error="strconv.ParseUint: parsing \"2.147483647e+09\": invalid syntax"]`

and then get default value 64 which is not equal `math.MaxInt32`

```commit-message
```

### Check List

Tests

- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

File: server/config/persist_options.go [hunk 1]
```diff
@@ -876,7 +876,16 @@ func (o *PersistOptions) getTTLUint(key string) (uint64, bool, error) {
 		return 0, false, nil
 	}
 	r, err := strconv.ParseUint(stringForm, 10, 64)
-	return r, true, err
+	if err == nil {
```
Comment (lhy1024) [inline server/config/persist_options.go:879]: maybe we need to provide a util about it

Comment (HuSharp) [reply server/config/persist_options.go:880]: transfer function name `getTTLUint` to `getTTLNumber` and add more comment

**Review by CabinfeverB — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]
