### PR TITLE
ctl: refactor by url values

### LINKED ISSUE #9385: pd-ctl: `keyspace list` may not work properly when `limit` not specified but `page_token` specified.
## Bug Report

*[This issue was written with the help of Claude]*

### What did you do?

Used the `pd-ctl keyspace list` command with the `--page_token` flag, either alone or in combination with the `--limit` flag.

Example commands that trigger the issue:
```bash
pd-ctl keyspace list --page_token=2
pd-ctl keyspace list --limit=10 --page_token=2
```

### What did you expect to see?

The command should construct a valid URL and successfully make the API request to list keyspaces.

Expected URLs:
- `http://127.0.0.1:2379/pd/api/v2/keyspaces?page_token=2`
- `http://127.0.0.1:2379/pd/api/v2/keyspaces?limit=10&page_token=2`

### What did you see instead?

The command fails with a malformed URL when using `--page_token` without `--limit`:

```
Get "http://127.0.0.1:2379/pd/api/v2/keyspaces&page_token=2"
```

Which results in a 404 not found:

```
tiup ctl:nightly pd keyspace list --page_token "2" -u '127.0.0.1:35657'
Starting component ctl: /DATA/disk3/juncen/.tiup/components/ctl/v9.0.0-beta.1.pre-nightly/ctl pd keyspace list --page_token 2 -u 127.0.0.1:35657
Failed to list keyspace:  [404] 404 page not found
```

The URL is malformed because it uses `&page_token=2` instead of `?page_token=2` when no other query parameters are present.

### Root Cause

In the `listKeyspaceCommandFunc` function in `tools/pd-ctl/pdctl/command/keyspace_command.go`, the URL construction logic is flawed:

```go
if limit != "" {
    url += fmt.Sprintf("?limit=%s", limit)
}
// ...
if pageToken != "" {
    url += fmt.Sprintf("&page_token=%s", pageToken)  // Always uses &, even when no ? exists
}
```

The code always uses `&` for the `page_token` parameter, but it should use `?` when it's the first query parameter.

### What version of PD are you using (`pd-server -V`)?

Current development version (based on the source code in the repository).

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #9385

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by okJiang — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

File: tools/pd-ctl/pdctl/command/label_command.go [hunk 1]
```diff
@@ -75,9 +75,13 @@ func showLabelListStoresCommandFunc(cmd *cobra.Command, args []string) {
 		cmd.Println("Usage: label store name [value]")
 		return
 	}
-	namePrefix := fmt.Sprintf("name=%s", getValue(args, 0))
-	valuePrefix := fmt.Sprintf("value=%s", getValue(args, 1))
-	prefix := fmt.Sprintf("%s?%s&%s", labelsStorePrefix, namePrefix, valuePrefix)
+	query := make(url.Values)
+	query.Set("name", getValue(args, 0))
+	query.Set("value", args[1])
```
Comment (rleungx) [inline tools/pd-ctl/pdctl/command/label_command.go]: Shall we use getValue?

File: tools/pd-ctl/pdctl/command/region_command.go [hunk 2]
```diff
@@ -421,25 +426,26 @@ func showRegionWithCheckCommandFunc(cmd *cobra.Command, args []string) {
...
+			query.Set("bound", "10")
 		}
 	} else if strings.EqualFold(state, "hist-keys") {
 		if len(args) == 2 {
 			if _, err := strconv.Atoi(args[1]); err != nil {
 				cmd.Println("region keys histogram bound should be a number")
 				return
 			}
-			prefix += "?bound=" + args[1]
+			query.Set("bound", args[1])
```
Comment (rleungx) [inline tools/pd-ctl/pdctl/command/region_command.go:446]: Where do we use it?

File: tools/pd-ctl/pdctl/command/label_command.go (hunk 1 above)
Comment (bufferflies) [reply tools/pd-ctl/pdctl/command/label_command.go]: yes, fixed

File: tools/pd-ctl/pdctl/command/region_command.go (hunk 2 above)
Comment (bufferflies) [reply tools/pd-ctl/pdctl/command/region_command.go:446]: fixed
