### PR TITLE
mcs: avoid stuck goroutine when raftcluster failed to create

### LINKED ISSUE #7001: TestResignAPIPrimaryForward is unstable
### Which jobs are failing
```
2023-08-29T02:24:03.1901281Z panic: test timed out after 15m0s
2023-08-29T02:24:03.1901409Z running tests:
2023-08-29T02:24:03.1901628Z 	TestAPIServerForwardTestSuite (10m30s)
2023-08-29T02:24:03.1901947Z 	TestAPIServerForwardTestSuite/TestResignAPIPrimaryForward (8m21s)
2023-08-29T02:24:03.1902048Z 
2023-08-29T02:24:03.1902195Z goroutine 2571455 [running]:
2023-08-29T02:24:03.1902412Z testing.(*M).startAlarm.func1()
2023-08-29T02:24:03.1902691Z 	/opt/hostedtoolcache/go/1.21.0/x64/src/testing/testing.go:2259 +0x1fc
2023-08-29T02:24:03.1902827Z created by time.goFunc
2023-08-29T02:24:03.1903074Z 	/opt/hostedtoolcache/go/1.21.0/x64/src/time/sleep.go:176 +0x45
2023-08-29T02:24:03.1903084Z 
2023-08-29T02:24:03.1903251Z goroutine 1 [chan receive, 10 minutes]:
2023-08-29T02:24:03.1903448Z testing.(*T).Run(0xc0001861a0, {0x42f441f, 0x1d}, 0x4daf520)
2023-08-29T02:24:03.1903696Z 	/opt/hostedtoolcache/go/1.21.0/x64/src/testing/testing.go:1649 +0x856
2023-08-29T02:24:03.1903856Z testing.runTests.func1(0x0?)
2023-08-29T02:24:03.1904130Z 	/opt/hostedtoolcache/go/1.21.0/x64/src/testing/testing.go:2054 +0x85
2023-08-29T02:24:03.1904302Z testing.tRunner(0xc0001861a0, 0xc000665a30)
2023-08-29T02:24:03.1904566Z 	/opt/hostedtoolcache/go/1.21.0/x64/src/testing/testing.go:1595 +0x239
2023-08-29T02:24:03.1904821Z testing.runTests(0xc0002ed400?, {0x65a6b00, 0xc, 0xc}, {0x105c733?, 0x4?, 0x6676d60?})
2023-08-29T02:24:03.1905086Z 	/opt/hostedtoolcache/go/1.21.0/x64/src/testing/testing.go:2052 +0x897
2023-08-29T02:24:03.1905226Z testing.(*M).Run(0xc0002ed400)
2023-08-29T02:24:03.1905479Z 	/opt/hostedtoolcache/go/1.21.0/x64/src/testing/testing.go:1925 +0xb58
2023-08-29T02:24:03.1905744Z go.uber.org/goleak.VerifyTestMain({0x51e3a80, 0xc0002ed400}, {0x66787e0, 0x8, 0x8})
2023-08-29T02:24:03.1906054Z 	/home/runner/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x58
2023-08-29T02:24:03.1906279Z github.com/tikv/pd/tests/integrations/mcs/tso.TestMain(...)
2023-08-29T02:24:03.1906549Z 	/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:51
2023-08-29T02:24:03.1906664Z main.main()
2023-08-29T02:24:03.1906826Z 	_testmain.go:111 +0x359
2023-08-29T02:24:03.1906839Z 
2023-08-29T02:24:03.1906984Z goroutine 41 [chan receive]:
2023-08-29T02:24:03.1907228Z go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc000013bd8)
2023-08-29T02:24:03.1907771Z 	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20220915004622-85b640cee793/pkg/logutil/merge_logger.go:173 +0xa7
2023-08-29T02:24:03.1908037Z created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger in goroutine 1
2023-08-29T02:24:03.1908567Z 	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20220915004622-85b640cee793/pkg/logutil/merge_logger.go:91 +0x167
2023-08-29T02:24:03.1908576Z 
2023-08-29T02:24:03.1908710Z goroutine 1018 [select]:
```

### CI link
https://github.com/tikv/pd/actions/runs/6006223367/job/16292464207?pr=6996

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #7001

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/cluster/cluster.go [hunk 1]
```diff
@@ -327,6 +320,15 @@ func (c *RaftCluster) Start(s Server) error {
 		log.Error("load external timestamp meets error", zap.Error(err))
 	}
 
+	// bootstrap keyspace group manager after starting other parts successfully.
```
Comment (rleungx) [inline server/cluster/cluster.go:323]: Why change the order?

Comment (lhy1024) [reply server/cluster/cluster.go:323]: This and `m.ctx.Done()` are a double insurance measure.

Comment (lhy1024) [reply server/cluster/cluster.go:323]: If the `keyspaceGroupManager` has started a goroutine according to the previous sequence, when the raft cluster creation fails, it will return without running `s.stopRaftCluster()` https://github.com/tikv/pd/issues/7001#issuecomment-1701550466

Comment (rleungx) [reply server/cluster/cluster.go:323]: Shall we cancel it?

Comment (lhy1024) [reply server/cluster/cluster.go:323]: Do you think to check `m.ctx.Done()` is enough?

Comment (rleungx) [reply server/cluster/cluster.go:323]: I mean we need to use a separate context to handle the case you mentioned.

Comment (lhy1024) [reply server/cluster/cluster.go:323]: I got it, but I don't think it's necessary. The goroutines below don't use another context either, but since they're at the tail of the order, they're not stuck.

**Review by JmPotato — APPROVED** [review]

**Review by rleungx — APPROVED** [review]
