### PR TITLE
*: make `TestForwardTSOUnexpectedToFollower` stable

### LINKED ISSUE #8397: TestForwardTSOUnexpectedToFollower2 is unstable
### Which jobs are failing

```
--- FAIL: TestForwardTSOUnexpectedToFollower2 (8.36s)
    server_test.go:446: 
        	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:446
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:485
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:440
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster
        	Test:       	TestForwardTSOUnexpectedToFollower2
    server_test.go:313: 
        	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:313
        	            				/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:541
        	            				/opt/hostedtoolcache/go/1.21.12/x64/src/testing/testing.go:999
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:446
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:485
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:440
        	Error:      	Should be empty, but was [{"service-addr":"http://127.0.0.1:36189/","version":"None","git-hash":"None","deploy-path":"/home/runner/work/pd/pd/tests/integrations/mcs/tso","start-timestamp":1721034672} {"service-addr":"http://127.0.0.1:46735/","version":"None","git-hash":"None","deploy-path":"/home/runner/work/pd/pd/tests/integrations/mcs/tso","start-timestamp":1721034673}]
        	Test:       	TestForwardTSOUnexpectedToFollower2
FAIL
```

### CI link

https://github.com/tikv/pd/actions/runs/9936654996/job/27445363927?pr=8396

### LINKED ISSUE #8589: TestForwardTSOUnexpectedToFollower1 is unstable
### Which jobs are failing
```
    server_test.go:378: 
        	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:378
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:432
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:374
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster
        	            	github.com/tikv/pd/client.(*client).respForErr
        	            		/home/runner/work/pd/pd/client/client.go:1734
        	            	github.com/tikv/pd/client.(*client).UpdateServiceGCSafePoint
        	            		/home/runner/work/pd/pd/client/client.go:1413
        	            	github.com/tikv/pd/tests/integrations/mcs/tso.TestForwardTSOUnexpectedToFollower1.func1
        	            		/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:377
        	            	github.com/tikv/pd/tests/integrations/mcs/tso.(*APIServerForward).checkForwardTSOUnexpectedToFollower
        	            		/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:432
        	            	github.com/tikv/pd/tests/integrations/mcs/tso.TestForwardTSOUnexpectedToFollower1
        	            		/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:374
        	            	testing.tRunner
        	            		/opt/hostedtoolcache/go/1.21.13/x64/src/testing/testing.go:1595
        	            	runtime.goexit
        	            		/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/asm_amd64.s:1650
        	Test:       	TestForwardTSOUnexpectedToFollower1

```
```
server_test.go:260: 
        	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:260
        	            				/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:541
        	            				/opt/hostedtoolcache/go/1.21.13/x64/src/testing/testing.go:999
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:378
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:432
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:374
        	Error:      	Should be empty, but was [{"name":"http://127.0.0.1:34769/","service-addr":"http://127.0.0.1:34769/","version":"None","git-hash":"None","deploy-path":"/home/runner/work/pd/pd/tests/integrations/mcs/tso","start-timestamp":1725337222} {"name":"http://127.0.0.1:35031/","service-addr":"http://127.0.0.1:35031/","version":"None","git-hash":"None","deploy-path":"/home/runner/work/pd/pd/tests/integrations/mcs/tso","start-timestamp":1725337222}]
        	Test:       	TestForwardTSOUnexpectedToFollower1
--- FAIL: TestForwardTSOUnexpectedToFollower1 (8.48s)
```
### CI link
https://github.com/tikv/pd/actions/runs/10676453491/job/29590029940?pr=8518

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #8589, close #8397.

### What is changed and how does it work?

Increase the retry times to make sure that force load should happen at least once. 

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/grpc_service.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ import (
 
 const (
 	heartbeatSendTimeout          = 5 * time.Second
-	maxRetryTimesRequestTSOServer = 3
+	maxRetryTimesRequestTSOServer = 6
```
Comment (lhy1024) [inline server/grpc_service.go:60]: Is it enough?

**Review by HuSharp — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]
