### PR TITLE
*: fix the split problem caused by no enough replicas

### LINKED ISSUE #6550: "Not enough replicas" caused keyspace group split to fail randomly
### What did you do?
QA team ran keyspace group split with pd-ctl

### What did you expect to see?
keyspace group split should successfully complete

### What did you see instead?
Randomly failed because of "Not enough replicas" 

### What version of PD are you using (`pd-server -V`)?
tidbcloud/pd-cse release-6.6-keyspace 9e1e2de5194655c2e1224ce94057e7f7fb5f7eb4

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #6550.

### What is changed and how does it work?

This PR is going to fix the above problem and adds more logs and unit tests for splitting the keyspace group.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

File: pkg/mcs/discovery/registry_entry.go [hunk 1]
```diff
@@ -23,7 +23,7 @@ import (
 
 // ServiceRegistryEntry is the registry entry of a service
 type ServiceRegistryEntry struct {
-	ServiceAddr string `json:"serviceAddr"`
+	ServiceAddr string `json:"service-addr"`
```
Comment (rleungx) [inline pkg/mcs/discovery/registry_entry.go:26]: Please pay attention to it.

File: pkg/keyspace/tso_keyspace_group.go [hunk 2]
```diff
@@ -184,14 +190,15 @@ func (m *GroupManager) allocNodesToAllKeyspaceGroups() {
 		}
 		if !withError {
 			// all keyspace groups have equal or more than default replica count
+			log.Info("all keyspace groups have equal or more than default replica count, stop to alloc node")
```
Comment (JmPotato) [inline pkg/keyspace/tso_keyspace_group.go:193]: Will this be noisy?

**Comment by lhy1024** [comment]
Do we need to cherry-pick it to pd-cse?
