### PR TITLE
keyspace, id: fix alloc range and add reserved keyspaces for next-gen

### LINKED ISSUE #9417: The keyspace id will be allocated over the uint32 max

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #9417 Ref https://github.com/tikv/pd/issues/9414

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/id/id.go [hunk 1]
```diff
@@ -27,15 +29,28 @@ import (
...
 const (
+	// ReservedKeyspaceIDCount is the reserved count for keyspace id.
+	ReservedKeyspaceIDCount = uint64(1024)
+	// ReservedKeyspaceIDStart is the start id for reserved keyspace id.
+	// The reserved keyspace id range is [uint32.Max - 1024, uint32.Max)
+	ReservedKeyspaceIDStart = uint64(math.MaxUint32) - ReservedKeyspaceIDCount
+	// NonNextGenKeyspaceIDLimit is the upper limit for keyspace IDs when not in NextGen mode.
+	// NullKeyspaceID is math.MaxUint32
+	// IDs should be less than or equal to math.MaxUint32 -1 .
+	NonNextGenKeyspaceIDLimit = uint64(math.MaxUint32) - 1
```
Comment (JmPotato) [inline pkg/id/id.go]: None of the constants need to be exported.

**Review by JmPotato — APPROVED** [review]
