### PR TITLE
apiutil, middleware: strengthen the robustness of GetIPPortFromHTTPRequest function

### LINKED ISSUE #6957: Port is not truncated correctly when getting IP from HTTP request
## Bug Report

#6622 added `X-Forwarded-For` into the header for the forwarded request. However, `GetIPAddrFromHTTPRequest` directly returns the IP address from `X-Forwarded-For` without truncating the port as handling `X-Real-Ip` down below.

https://github.com/tikv/pd/blob/54981d1b89563547e321dbfcee24edef8a6c7a1c/pkg/utils/apiutil/apiutil.go#L104-L124

When the forwarded request uses a random port and the QPS is high, the metrics may record a large number of records, which affects indicator observation or downstream monitoring services.

img_v2_876bd46c-4f4b-40fa-8ed0-e2638bf1571g

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: Close #6957.

### What is changed and how does it work?

```commit-message
- Improve `GetIPPortFromHTTPRequest` to ensure it could handle different host addresses.
- Make middleware set the forwarded header correctly.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
Ensure the HTTP middleware set the forwarded header correctly.
```

### CODE REVIEW

File: pkg/utils/apiutil/serverapi/middleware.go [hunk 1]
```diff
@@ -130,22 +124,27 @@ func (h *redirector) matchMicroServiceRedirectRules(r *http.Request) (bool, stri
...
 	}
 
-	r.Header.Set(PDRedirectorHeader, h.s.Name())
-	r.Header.Add(ForwardedForHeader, r.RemoteAddr)
+	r.Header.Set(apiutil.PDRedirectorHeader, h.s.Name())
+	if forwardedIP, forwardedPort, err := net.SplitHostPort(r.RemoteAddr); err == nil {
+		r.Header.Add(apiutil.XForwardedForHeader, forwardedIP)
+		r.Header.Add(apiutil.XForwardedPortHeader, forwardedPort)
+	} else {
+		r.Header.Add(apiutil.XForwardedForHeader, r.RemoteAddr)
```
Comment (rleungx) [inline pkg/utils/apiutil/serverapi/middleware.go:146]: Do we need else here?

Comment (JmPotato) [reply pkg/utils/apiutil/serverapi/middleware.go:146]: Just in case if the remote address is illegal, we can still get it passed down through the middleware.

**Review by rleungx — APPROVED** [review]

File: pkg/utils/apiutil/serverapi/middleware.go [hunk 2]
```diff
@@ -130,22 +124,27 @@ func (h *redirector) matchMicroServiceRedirectRules(r *http.Request) (bool, stri
...
+	if name := r.Header.Get(apiutil.PDRedirectorHeader); len(name) != 0 {
 		log.Error("redirect but server is not leader", zap.String("from", name), zap.String("server", h.s.Name()), errs.ZapError(errs.ErrRedirect))
 		http.Error(w, apiutil.ErrRedirectToNotLeader, http.StatusInternalServerError)
 		return
 	}
 
-	r.Header.Set(PDRedirectorHeader, h.s.Name())
-	r.Header.Add(ForwardedForHeader, r.RemoteAddr)
+	r.Header.Set(apiutil.PDRedirectorHeader, h.s.Name())
+	if forwardedIP, forwardedPort, err := net.SplitHostPort(r.RemoteAddr); err == nil {
```
Comment (CabinfeverB) [inline pkg/utils/apiutil/serverapi/middleware.go:142]: IMO, we should also use `GetIPPortFromHTTPRequest` to get real source IP and port.

**Review by CabinfeverB — APPROVED** [review]
