### PR TITLE
cmd, server: check the release version before starting the pd-server

### LINKED ISSUE #7978: move the version check from leader campaign to startup
## Enhancement Task

This is the propose to move the version check from leader campaign to startup 

we have a case when we lost the leader.
1. the pd binary is built without version tag
2. upgrade the 3 pd node to the wrong pd build
3. after the upgrade completes, all the 3 pd nodes are into the crash loop during compaign leader, and the cluster lost the pd leader and no longer function.

Here is the pd log for panic during leader campaign
```
{"level":"INFO","time":"2024/03/26 00:12:16.368 +00:00","caller":"versioninfo.go:89","message":"Welcome to Placement Driver (PD)"}
{"level":"INFO","time":"2024/03/26 00:12:16.368 +00:00","caller":"versioninfo.go:90","message":"PD","release-version":"62227fb4c"}
...
{"level":"INFO","time":"2024/03/26 00:43:45.706 +00:00","caller":"server.go:1670","message":"campaign PD leader ok","campaign-leader-name":"pd-1"}
{"level":"FATAL","time":"2024/03/26 00:43:46.950 +00:00","caller":"versioninfo.go:61","message":"version string is illegal","error":"[PD:semver:ErrSemverNewVersion]62227fb4c is not in dotted-tri format: 62227fb4c is not in dotted-tri format","errorVerbose":"[PD:semver:E
rrSemverNewVersion]62227fb4c is not in dotted-tri format: 62227fb4c is not in dotted-tri format\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithSt
ackByCause\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:307\ngithub.com/tikv/pd/pkg/versioninfo.ParseVersion\n\t/mnt/tidb/pd/pkg/versioninfo/versioninfo.go:52\ngithub.com/tikv/pd/pkg/versioninfo.MustParseVersion\n\t/mnt/tid
b/pd/pkg/versioninfo/versioninfo.go:59\ngithub.com/tikv/pd/server.CheckPDVersion\n\t/mnt/tidb/pd/server/util.go:40\ngithub.com/tikv/pd/server.(*Server).campaignLeader\n\t/mnt/tidb/pd/server/server.go:1743\ngithub.com/tikv/pd/server.(*Server).leaderLoop\n\t/mnt/tidb/pd/s
erver/server.go:1639\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650","stack":"github.com/tikv/pd/pkg/versioninfo.MustParseVersion\n\t/mnt/tidb/pd/pkg/versioninfo/versioninfo.go:61\ngithub.com/tikv/pd/server.CheckPDVersion\n\t/mnt/tidb/pd/server/util.go:40
\ngithub.com/tikv/pd/server.(*Server).campaignLeader\n\t/mnt/tidb/pd/server/server.go:1743\ngithub.com/tikv/pd/server.(*Server).leaderLoop\n\t/mnt/tidb/pd/server/server.go:1639"}
{"level":"WARN","time":"2024/03/26 00:43:51.984 +00:00","caller":"member.go:250","message":"the pd leader has not changed, delete and campaign again","old-pd-leader":"name:\"pd-1\" member_id:1438954984562261702 peer_urls:\"http
s://infra-tidb-pd-shopping-catalog-prod-0a019086.ec2.pin220.com:2380\" client_urls:\"https://infra-tidb-pd-shopping-catalog-prod-0a019086.ec2.pin220.com:2379\" "}
{"level":"INFO","time":"2024/03/26 00:43:51.986 +00:00","caller":"server.go:1632","message":"skip campaigning of pd leader and check later","server-name":"pd-1","etcd-leader-id":626574301973153734,"member-id":143895498456226170
2}
{"level":"INFO","time":"2024/03/26 00:43:52.187 +00:00","caller":"server.go:1632","message":"skip campaigning of pd leader and check later","server-name":"pd-1","etcd-leader-id":626574301973153734,"member-id":143895498456226170
2}
{"level":"INFO","time":"2024/03/26 00:43:52.388 +00:00","caller":"server.go:1632","message":"skip campaigning of pd leader and check later","server-name":"pd-1","etcd-leader-id":626574301973153734,"member-id":143895498456226170
2}
{"level":"INFO","time":"2024/03/26 00:43:58.012 +00:00","caller":"server.go:1607","message":"pd leader has changed, try to re-campaign a pd leader"}
{"level":"INFO","time":"2024/03/26 00:43:58.012 +00:00","caller":"server.go:1632","message":"skip campaigning of pd leader and check later","server-name":"pd-1","etcd-leader-id":626574301973153734,"member-id":143895498456226170
2}
{"level":"INFO","time":"2024/03/26 00:44:04.477 +00:00","caller":"server.go:1607","message":"pd leader has changed, try to re-campaign a pd leader"}
{"level":"INFO","time":"2024/03/26 00:44:04.477 +00:00","caller":"server.go:1644","message":"start to campaign PD leader","campaign-leader-name":"pd-1"}
{"level":"INFO","time":"2024/03/26 00:44:04.481 +00:00","caller":"leadership.go:181","message":"check campaign resp","resp":{"header":{"cluster_id":8850434198915930927,"member_id":16443876602637797343,"revision":55937640,"raft_term":342},"succeeded":true,"responses":[{"
Response":{"ResponsePut":{"header":{"revision":55937640}}}}]}}
{"level":"INFO","time":"2024/03/26 00:44:04.481 +00:00","caller":"server.go:1670","message":"campaign PD leader ok","campaign-leader-name":"pd-1"}

```

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: Close #7978.

### What is changed and how does it work?

```commit-message
Move the release version check before the startup to ensure we can know it as soon as possible.
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

```shell
> GOEXPERIMENT= CGO_ENABLED=1 go build  -gcflags '' -ldflags '-X "github.com/tikv/pd/pkg/versioninfo.PDReleaseVersion=g39108f7be" -X "github.com/tikv/pd/pkg/versioninfo.PDBuildTS=2024-03-26 06:12:55" -X "github.com/tikv/pd/pkg/versioninfo.PDGitHash=39108f7be343368ed7487848d81d4528734dc02a" -X "github.com/tikv/pd/pkg/versioninfo.PDGitBranch=fix_release_version_check" -X "github.com/tikv/pd/pkg/versioninfo.PDEdition=Community" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.InternalVersion=8.0.0-ab48e09f" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.Standalone=No" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.PDVersion=v8.0.0-alpha-114-g39108f7be-dirty" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.BuildTime=2024-03-26 06:12:56" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.BuildGitHash=ab48e09f7762"' -tags "" -o /Users/jmpotato/go/src/github.com/JmPotato/pd/bin/pd-server cmd/pd-server/main.go
> ./bin/pd-server
[2024/03/26 14:13:47.423 +08:00] [FATAL] [versioninfo.go:70] ["version string is illegal"] [error="[PD:semver:ErrSemverNewVersion]g39108f7be is not in dotted-tri format: g39108f7be is not in dotted-tri format"] [errorVerbose="[PD:semver:ErrSemverNewVersion]g39108f7be is not in dotted-tri format: g39108f7be is not in dotted-tri format\ngithub.com/pingcap/errors.AddStack\n\t/Users/jmpotato/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByCause\n\t/Users/jmpotato/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:307\ngithub.com/tikv/pd/pkg/versioninfo.ParseVersion\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/pkg/versioninfo/versioninfo.go:61\ngithub.com/tikv/pd/pkg/versioninfo.MustParseVersion\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/pkg/versioninfo/versioninfo.go:68\ngithub.com/tikv/pd/server.CheckAndGetPDVersion\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/server/util.go:41\nmain.start\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/cmd/pd-server/main.go:225\nmain.createServerWrapper\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/cmd/pd-server/main.go:191\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/jmpotato/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/jmpotato/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/jmpotato/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\nmain.main\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/cmd/pd-server/main.go:71\nruntime.main\n\t/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/proc.go:271\nruntime.goexit\n\t/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/asm_arm64.s:1222"] [stack="github.com/tikv/pd/pkg/versioninfo.MustParseVersion\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/pkg/versioninfo/versioninfo.go:70\ngithub.com/tikv/pd/server.CheckAndGetPDVersion\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/server/util.go:41\nmain.start\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/cmd/pd-server/main.go:225\nmain.createServerWrapper\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/cmd/pd-server/main.go:191\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/jmpotato/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/jmpotato/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/jmpotato/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\nmain.main\n\t/Users/jmpotato/go/src/github.com/JmPotato/pd/cmd/pd-server/main.go:71\nruntime.main\n\t/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/proc.go:271"]
```

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/util.go [hunk 1]
```diff
@@ -33,14 +34,21 @@ import (
...
+func CheckAndGetPDVersion() *semver.Version {
 	pdVersion := versioninfo.MinSupportedVersion(versioninfo.Base)
 	if versioninfo.PDReleaseVersion != "None" {
 		pdVersion = versioninfo.MustParseVersion(versioninfo.PDReleaseVersion)
 	}
+	return pdVersion
+}
+
+// CheckPDVersionWithClusterVersion checks if PD needs to be upgraded by comparing the PD version with the cluster version.
+func CheckPDVersionWithClusterVersion(opt *config.PersistOptions) {
```
Comment (HuSharp) [inline server/util.go:47]: Can we remove the `CheckAndGetPDVersion` function by passing `GetClusterVersion`?

Comment (HuSharp) [reply server/util.go:47]: Oh, for the first time, it seems no need to check cluster version 0 0

**Review by HuSharp — APPROVED** [review]

File: cmd/pd-server/main.go [hunk 2]
```diff
@@ -221,6 +221,8 @@ func start(cmd *cobra.Command, args []string, services ...string) {
 		exit(0)
 	}
 
+	// Check the PD version first before running.
+	server.CheckAndGetPDVersion()
```
Comment (CabinfeverB) [inline cmd/pd-server/main.go:225]: Is the purpose of the modification to print warning logs to help debug?

Comment (JmPotato) [reply cmd/pd-server/main.go:225]: No, it should directly panic here.

Comment (CabinfeverB) [reply cmd/pd-server/main.go:225]: Will panic in MustParseVersion ?

Comment (JmPotato) [reply cmd/pd-server/main.go:225]: Yes, otherwise it will panic during the leader campaign which might be too late to let the user be aware of the problem.

**Review by CabinfeverB — APPROVED** [review]
