### PR TITLE
mcs: fix micro-service topo's display

### LINKED ISSUE #7957: mcs: micro-service topo's display is wrong
### What did you do?
run dashboard and find deploy path is wrong
img_v3_0296_970e14bc-de8f-4433-9215-9cd6cc8209eg

### What did you expect to see?
display directory rather than bin package

### What did you see instead?
display directory

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Close #7957

### What is changed and how does it work?
before
img_v3_0296_67eef215-0035-4a4f-b929-7b3b050e555g
after
image

```commit-message
```

### Check List

Tests

- Manual test (add detailed scripts or steps below)

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/mcs/scheduling/server/server.go [hunk 1]
```diff
@@ -413,7 +414,8 @@ func (s *Server) startServer() (err error) {
 	// different service modes provided by the same pd-server binary
 	bs.ServerInfoGauge.WithLabelValues(versioninfo.PDReleaseVersion, versioninfo.PDGitHash).Set(float64(time.Now().Unix()))
 	bs.ServerMaxProcsGauge.Set(float64(runtime.GOMAXPROCS(0)))
-	deployPath, err := os.Executable()
+	execPath, err := os.Executable()
```
Comment (lhy1024) [inline pkg/mcs/scheduling/server/server.go:417]: tso and resource manager also need to update

Comment (HuSharp) [reply pkg/mcs/scheduling/server/server.go:417]: get it. only tso and scheduling have it

**Review by lhy1024 — APPROVED** [review]

File: pkg/mcs/scheduling/server/server.go (hunk 1 above)
Comment (lhy1024) [reply pkg/mcs/scheduling/server/server.go:417]: Do we also need to pick it to release-8.0?

Comment (HuSharp) [reply pkg/mcs/scheduling/server/server.go:417]: added

**Review by CabinfeverB — APPROVED** [review]
