### PR TITLE
etcdutil: check if the endpoint has been removed before evicting

### LINKED ISSUE #8286: The removed member should no longer appear in the list of evicted endpoints
## Bug Report

```go
[2024/06/04 15:07:36.180 +05:30] [INFO] [health_checker.go:386] ["remove stale etcd client"] [endpoint=http://{pd_addr_a}:2379] [source=election-etcd-client]
...
[2024/06/04 15:07:45.167 +05:30] [INFO] [health_checker.go:294] ["evicted etcd endpoint found"] [endpoint=http://{pd_addr_a}:2379] [source=election-etcd-client]
```

Once a member is removed from the cluster, its endpoint should no longer exist in the health checker.

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: close #8286.

### What is changed and how does it work?

```commit-message
Once a member is removed from the cluster, its endpoint should no longer exist in the health checker.
This PR adds a check to prevent the removed endpoint from being evicted again unexpectedly.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]

File: pkg/utils/etcdutil/health_checker.go [hunk 1]
```diff
@@ -286,18 +286,21 @@ func (checker *healthChecker) updateEvictedEps(lastEps, pickedEps []string) {
...
 	})
-	// Find all endpoints which are in the lastEps but not in the pickedEps,
-	// and add them to the evictedEps.
+	// Find all endpoints which are in `lastEps` and `healthyClients` but not in `pickedEps`,
+	// and add them to the `evictedEps`.
 	for _, ep := range lastEps {
 		if pickedSet[ep] {
 			continue
 		}
+		if hc := checker.loadClient(ep); hc == nil {
```
Comment (okJiang) [inline pkg/utils/etcdutil/health_checker.go:295]: This PR seems to be trying to solve the issue of non-atomic updates between `evictedEps` and the `client`. However, this PR doesn't fully address the problem.

For example: Do we need to check `if hc := checker.loadClient(ep); hc ==` for other `checker.evictedEps.Store(ep, 0)`?

Comment (okJiang) [reply pkg/utils/etcdutil/health_checker.go:295]: If the passed-in `lastEps` can be modified, is the returned `lastEps` also possibly inaccurate?

https://github.com/tikv/pd/blob/13174b5d4cab4d958f0b4ea2718ea7bb74992bc7/pkg/utils/etcdutil/health_checker.go#L210-L218

**Review by okJiang — APPROVED** [review]

**Review by HuSharp — APPROVED** [review]
