### PR TITLE
mcs/resourcemanager: delete expire tokenSlot

### LINKED ISSUE #7346: remove legacy tokenSlot of resource group bucket
## Enhancement Task
Normally when node step out gracefully(got SIGTERM etc), it will send last acquire grpc, so PD will cleanup its slot token.

But when node crash unexpctedly or got SIGKILL(which cannot be handled), it will have no chance to send last acquire grpc, so its corresponding slot token will leave here forever, which makes fillrate/burstLimit be less.

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?
If tidb/tiflash crash unexpectly or killed by signal which cannot be handled, there will be a useless slot, which will cause fillrate/burstlimit become less than expected for other alive ones.
So add a expire timeout(10min).

Issue Number: Close #7346

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/mcs/resourcemanager/server/token_buckets.go [hunk 1]
```diff
@@ -139,6 +147,13 @@ func (gts *GroupTokenBucketState) balanceSlotTokens(
 		}
 	}
 
+	for clientUniqueID, slot := range gts.tokenSlots {
```
Comment (CabinfeverB) [inline pkg/mcs/resourcemanager/server/token_buckets.go:150]: Do we need check this every handling request?

Comment (guo-shaoge) [reply pkg/mcs/resourcemanager/server/token_buckets.go:150]: should refine so we can check every 10mins

Comment (guo-shaoge) [reply pkg/mcs/resourcemanager/server/token_buckets.go]: Add `gts.lastCheckExpireSlot` as a guard

File: pkg/mcs/resourcemanager/server/token_buckets.go [hunk 2]
```diff
@@ -108,17 +114,21 @@ func (gts *GroupTokenBucketState) resetLoan() {
 	}
 
 	evenTokens := gts.Tokens * evenRatio
+	now := time.Now()
+	gts.lastCheckExpireSlot = now
```
Comment (HuSharp) [inline pkg/mcs/resourcemanager/server/token_buckets.go:118]: Do we need to check expiration here first?

Comment (guo-shaoge) [reply pkg/mcs/resourcemanager/server/token_buckets.go]: deleted, no need to update here

**Review by CabinfeverB — APPROVED** [review]

File: pkg/mcs/resourcemanager/server/token_buckets.go [hunk 3]
```diff
@@ -139,6 +148,16 @@ func (gts *GroupTokenBucketState) balanceSlotTokens(
 		}
 	}
 
+	if time.Since(gts.lastCheckExpireSlot) >= slotExpireTimeout {
+		gts.lastCheckExpireSlot = now
+		for clientUniqueID, slot := range gts.tokenSlots {
+			if time.Since(slot.lastReqTime) >= slotExpireTimeout {
+				delete(gts.tokenSlots, clientUniqueID)
+				log.Info("delete resource group slot because expire", zap.Any("last req time", slot.lastReqTime),
```
Comment (HuSharp) [inline pkg/mcs/resourcemanager/server/token_buckets.go:156]:
```suggestion
				log.Info("delete resource group slot because expire", zap.Time("last-req-time", slot.lastReqTime),
```

File: pkg/mcs/resourcemanager/server/token_buckets.go [hunk 4]
```diff
@@ -127,8 +134,10 @@ func (gts *GroupTokenBucketState) balanceSlotTokens(
 			slot = &TokenSlot{}
 			gts.tokenSlots[clientUniqueID] = slot
 			gts.clientConsumptionTokensSum = 0
+			slot.lastReqTime = now
```
Comment (HuSharp) [inline pkg/mcs/resourcemanager/server/token_buckets.go:137]: seems like slots cannot be updated?
```suggestion
			slot = &TokenSlot{lastReqTime: now}
			gts.tokenSlots[clientUniqueID] = slot
			gts.clientConsumptionTokensSum = 0
```

Comment (HuSharp) [inline pkg/mcs/resourcemanager/server/token_buckets.go:137]: seems like slots can not be updated
```suggestion
			slot = &TokenSlot{lastReqTime: now}
			gts.tokenSlots[clientUniqueID] = slot
			gts.clientConsumptionTokensSum = 0
```

**Review by HuSharp — APPROVED** [review]
rest LGTM!

**Comment by HuSharp** [comment]
seems like DCO is wrong  :) @guo-shaoge 
```
Commit sha: [6122ee9](https://github.com/tikv/pd/pull/7344/commits/6122ee9c413627d4027da7dc0e80b1e6a9c3dd70), Author: guo-shaoge, Committer: GitHub; The sign-off is missing.
Commit sha: [7201cce](https://github.com/tikv/pd/pull/7344/commits/7201cce1cfabad5d42c2f87efac6510fe2453356), Author: guo-shaoge, Committer: GitHub; The sign-off is missing.
```

**Comment by guo-shaoge** [comment]
> seems like DCO is wrong with `sign-off is missing` :) @guo-shaoge
> 
> ```
> Commit sha: [6122ee9](https://github.com/tikv/pd/pull/7344/commits/6122ee9c413627d4027da7dc0e80b1e6a9c3dd70), Author: guo-shaoge, Committer: GitHub; The sign-off is missing.
> Commit sha: [7201cce](https://github.com/tikv/pd/pull/7344/commits/7201cce1cfabad5d42c2f87efac6510fe2453356), Author: guo-shaoge, Committer: GitHub; The sign-off is missing.
> ```

fixed

**Comment by CabinfeverB** [comment]
No test in this PR, can u do a manual test? @guo-shaoge

**Comment by guo-shaoge** [comment]
> No test in this PR, can u do a manual test? @guo-shaoge I also agree to merge first and make up later

tested last night.
1. setup cluster
2. kill -9 tiflash
3. wait 10mins and check pd log

image
