### PR TITLE
tests: fix `TestStoreDelete`

### LINKED ISSUE #9840: Data race in `TestStoreDelete`
### Which jobs are failing
```
==================
WARNING: DATA RACE
Write at 0x00c003a1e330 by goroutine 271:
  runtime.mapdelete_fast64()
      /opt/hostedtoolcache/go/1.23.12/x64/src/runtime/map_fast64.go:304 +0x0
  github.com/tikv/pd/server/cluster.(*RaftCluster).BuryStoreLocked()
      /home/runner/work/pd/pd/server/cluster/cluster.go:1646 +0xd73
  github.com/tikv/pd/server/cluster.(*RaftCluster).BuryStore()
      /home/runner/work/pd/pd/server/cluster/cluster.go:1609 +0x17b
  github.com/tikv/pd/tests/server/api.(*storeTestSuite).TearDownTest.(*SchedulingTestEnvironment).Reset.func1()
      /home/runner/work/pd/pd/tests/testutil.go:470 +0xf2b
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).runFuncInMicroserviceEnv()
      /home/runner/work/pd/pd/tests/testutil.go:592 +0x290
  github.com/pingcap/failpoint.parseTerm()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:149 +0x233
  github.com/pingcap/failpoint.parse()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:126 +0xa5
  github.com/pingcap/failpoint.newTerms()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:98 +0x3e
  github.com/pingcap/failpoint.(*Failpoint).Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoint.go:58 +0x3e
  github.com/pingcap/failpoint.(*Failpoints).Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoints.go:105 +0x296
  github.com/pingcap/failpoint.Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoints.go:255 +0x13a
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).runFuncInMicroserviceEnv()
      /home/runner/work/pd/pd/tests/testutil.go:584 +0x13b
  github.com/pingcap/failpoint.parseTerm()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:149 +0x233
  github.com/pingcap/failpoint.parse()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:126 +0xa5
  github.com/pingcap/failpoint.newTerms()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:98 +0x3e
  github.com/pingcap/failpoint.(*Failpoint).Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoint.go:58 +0x3e
  github.com/pingcap/failpoint.(*Failpoints).Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoints.go:105 +0x296
  github.com/pingcap/failpoint.Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoints.go:255 +0xfc
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).runFuncInMicroserviceEnv()
      /home/runner/work/pd/pd/tests/testutil.go:583 +0xfd
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).RunFunc()
      /home/runner/work/pd/pd/tests/testutil.go:398 +0xf6
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).Reset()
      /home/runner/work/pd/pd/tests/testutil.go:561 +0xf6
  github.com/tikv/pd/tests/server/api.(*storeTestSuite).TearDownTest()
      /home/runner/work/pd/pd/tests/server/api/store_test.go:60 +0x36
  github.com/stretchr/testify/suite.Run.func1.1()
      /home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:184 +0x335
  runtime.deferreturn()
      /opt/hostedtoolcache/go/1.23.12/x64/src/runtime/panic.go:611 +0x5d
  github.com/pingcap/failpoint.parseTerm()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:149 +0x233
  github.com/pingcap/failpoint.parse()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:126 +0xa5
  github.com/pingcap/failpoint.newTerms()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:98 +0x3e
  github.com/pingcap/failpoint.(*Failpoint).Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoint.go:58 +0x3e
  github.com/pingcap/failpoint.(*Failpoints).Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoints.go:105 +0x296
  github.com/pingcap/failpoint.Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoints.go:255 +0xfc
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).runFuncInMicroserviceEnv()
      /home/runner/work/pd/pd/tests/testutil.go:583 +0xfd
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).RunTestInMicroserviceEnv()
      /home/runner/work/pd/pd/tests/testutil.go:411 +0xf3
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).RunTest()
      /home/runner/work/pd/pd/tests/testutil.go:383 +0xf6
  github.com/tikv/pd/tests/server/api.(*storeTestSuite).TestStoreDelete()
      /home/runner/work/pd/pd/tests/server/api/store_test.go:378 +0x6f
  runtime.call16()
      /opt/hostedtoolcache/go/1.23.12/x64/src/runtime/asm_amd64.s:775 +0x42
  reflect.Value.Call()
      /opt/hostedtoolcache/go/1.23.12/x64/src/reflect/value.go:368 +0xb5
  github.com/stretchr/testify/suite.Run.func1()
      /home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:202 +0x6f1
  testing.tRunner()
      /opt/hostedtoolcache/go/1.23.12/x64/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.23.12/x64/src/testing/testing.go:1743 +0x44

Previous write at 0x00c003a1e330 by goroutine 6514:
  runtime.mapdelete_fast64()
      /opt/hostedtoolcache/go/1.23.12/x64/src/runtime/map_fast64.go:304 +0x0
  github.com/tikv/pd/server/cluster.(*RaftCluster).BuryStoreLocked()
      /home/runner/work/pd/pd/server/cluster/cluster.go:1646 +0xd73
  github.com/tikv/pd/server/cluster.(*RaftCluster).checkStore()
      /home/runner/work/pd/pd/server/cluster/cluster.go:1865 +0x168c
  github.com/tikv/pd/server/cluster.(*RaftCluster).checkStores()
      /home/runner/work/pd/pd/server/cluster/cluster.go:1812 +0x195
  github.com/tikv/pd/server/cluster.(*RaftCluster).runNodeStateCheckJob()
      /home/runner/work/pd/pd/server/cluster/cluster.go:860 +0x39d
  github.com/tikv/pd/server/cluster.(*RaftCluster).Start.gowrap4()
      /home/runner/work/pd/pd/server/cluster/cluster.go:411 +0x33

Goroutine 271 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.23.12/x64/src/testing/testing.go:1743 +0x825
  github.com/stretchr/testify/suite.runTests()
      /home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:247 +0x17e
  github.com/stretchr/testify/suite.Run()
      /home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:220 +0xa2e
  github.com/tikv/pd/tests/server/api.TestStoreTestSuite()
      /home/runner/work/pd/pd/tests/server/api/store_test.go:48 +0x3c
  testing.tRunner()
      /opt/hostedtoolcache/go/1.23.12/x64/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.23.12/x64/src/testing/testing.go:1743 +0x44

Goroutine 6514 (running) created at:
  github.com/tikv/pd/server/cluster.(*RaftCluster).Start()
      /home/runner/work/pd/pd/server/cluster/cluster.go:411 +0x17b3
  github.com/tikv/pd/server.(*Server).bootstrapCluster()
      /home/runner/work/pd/pd/server/server.go:775 +0x1789
  github.com/tikv/pd/server.(*GrpcServer).Bootstrap()
      /home/runner/work/pd/pd/server/grpc_service.go:637 +0x4d1
  github.com/tikv/pd/tests.(*TestServer).BootstrapCluster()
      /home/runner/work/pd/pd/tests/cluster.go:412 +0x66e
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).startCluster()
      /home/runner/work/pd/pd/tests/testutil.go:621 +0xbc4
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).runFuncInMicroserviceEnv()
      /home/runner/work/pd/pd/tests/testutil.go:590 +0x239
  github.com/pingcap/failpoint.parseTerm()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:149 +0x233
  github.com/pingcap/failpoint.parse()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:126 +0xa5
  github.com/pingcap/failpoint.newTerms()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:98 +0x3e
  github.com/pingcap/failpoint.(*Failpoint).Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoint.go:58 +0x3e
  github.com/pingcap/failpoint.(*Failpoints).Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoints.go:105 +0x296
  github.com/pingcap/failpoint.Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoints.go:255 +0x13a
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).runFuncInMicroserviceEnv()
      /home/runner/work/pd/pd/tests/testutil.go:584 +0x13b
  github.com/pingcap/failpoint.parseTerm()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:149 +0x233
  github.com/pingcap/failpoint.parse()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:126 +0xa5
  github.com/pingcap/failpoint.newTerms()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/terms.go:98 +0x3e
  github.com/pingcap/failpoint.(*Failpoint).Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoint.go:58 +0x3e
  github.com/pingcap/failpoint.(*Failpoints).Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoints.go:105 +0x296
  github.com/pingcap/failpoint.Enable()
      /home/runner/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20240528011301-b51a646c7c86/failpoints.go:255 +0xfc
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).runFuncInMicroserviceEnv()
      /home/runner/work/pd/pd/tests/testutil.go:583 +0xfd
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).RunTestInMicroserviceEnv()
      /home/runner/work/pd/pd/tests/testutil.go:411 +0xf3
  github.com/tikv/pd/tests.(*SchedulingTestEnvironment).RunTest()
      /home/runner/work/pd/pd/tests/testutil.go:383 +0xf6
  github.com/tikv/pd/tests/server/api.(*storeTestSuite).TestStoreDelete()
      /home/runner/work/pd/pd/tests/server/api/store_test.go:378 +0x6f
  runtime.call16()
      /opt/hostedtoolcache/go/1.23.12/x64/src/runtime/asm_amd64.s:775 +0x42
  reflect.Value.Call()
      /opt/hostedtoolcache/go/1.23.12/x64/src/reflect/value.go:368 +0xb5
  github.com/stretchr/testify/suite.Run.func1()
      /home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:202 +0x6f1
  testing.tRunner()
      /opt/hostedtoolcache/go/1.23.12/x64/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.23.12/x64/src/testing/testing.go:1743 +0x44
==================
```

### CI link
https://github.com/tikv/pd/actions/runs/18518714312/job/52774808231?pr=9819

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9840.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/cluster/cluster.go [hunk 1]
```diff
@@ -172,7 +172,7 @@ type RaftCluster struct {
 	externalTS             atomic.Value // Store as uint64
 
 	// Keep the previous store limit settings when removing a store.
-	prevStoreLimit map[uint64]map[storelimit.Type]float64
+	prevStoreLimit sync.Map // map[uint64]map[storelimit.Type]float64
```
Comment (lhy1024) [inline server/cluster/cluster.go:175]: Do we need to add a new unit test for it?

Comment (rleungx) [reply server/cluster/cluster.go:175]: no need?
