### PR TITLE
tso: use less interval when waiting api service

### LINKED ISSUE #6449: TiKV failed to new PD(TSO) client
### What did you do?

Hanyang is running TiUP with multiple-group tso cherry-pick

### What did you expect to see?
TiKV can successfully and consistently new PD(TSO) client

### What did you see instead?
had random failures. The root cause is that the cherry-pick contains a mistake which overwrites the default retry interval 1s with 3s which results in timeout 2s set by TiKV for creating TSO(PD) client.

### What version of PD are you using (`pd-server -V`)?
pd-cse

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #6449

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by binshi-bing — APPROVED** [review]
LGTM

File: pkg/mcs/tso/server/server.go [hunk 1]
```diff
@@ -71,9 +71,10 @@ const (
 	tsoSvcRootPathFormat = msServiceRootPath + "/%d/" + mcsutils.TSOServiceName
 
 	// maxRetryTimesWaitAPIService is the max retry times for initializing the cluster ID.
-	maxRetryTimesWaitAPIService = 60
+	maxRetryTimesWaitAPIService = 360
 	// retryIntervalWaitAPIService is the interval to retry.
-	retryIntervalWaitAPIService = 3 * time.Second
+	// Note: the interval must be less than the timeout of tidb and tikv, which is 2s by default in tikv.
+	retryIntervalWaitAPIService = 500 * time.Millisecond
```
Comment (rleungx) [inline pkg/mcs/tso/server/server.go:77]: Will it print more logs?

Comment (lhy1024) [reply pkg/mcs/tso/server/server.go:77]: the log level is only debug.

Comment (lhy1024) [reply pkg/mcs/tso/server/server.go:77]: https://github.com/tikv/pd/blob/19f5bd531d3f09de6cda6c4ab0391eae79b3fd96/pkg/mcs/tso/server/server.go#L551

Comment (rleungx) [reply pkg/mcs/tso/server/server.go:77]: No, there is a warning log instead.

**Review by rleungx — APPROVED** [review]

**Comment by rleungx** [comment]
Do we really need these debug logs?
