### PR TITLE
resource_control: fix consumption less zero

### LINKED ISSUE #6973: master: pd panic during running workload with multiple resource groups
### What did you do?
1. create 1000 resource groups and assign them to 1000 different users.
2. run workload with 32 different users.

### What did you expect to see?
No errors report.

### What did you see instead?
One pd panic.

```
{"namespace":"e2e-oltp-multiple-resource-group-tps-2071148-1-37","level":"FATAL","container":"pd","log":"[log.go:87] [panic] [recover={}] [stack=\"[github.com/tikv/pd/pkg/utils/logutil.LogPanic\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/utils/logutil/log.go:87\\nruntime.gopanic\\n\\t/usr/local/go/src/runtime/panic.go:914\\ngithub.com/prometheus/client_golang/prometheus.(*counter).Add\\n\\t/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/counter.go:109\\ngithub.com/tikv/pd/pkg/mcs/resourcemanager/server.(*Manager).backgroundMetricsFlush\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/mcs/resourcemanager/server/manager.go:327](http://github.com/tikv/pd/pkg/utils/logutil.LogPanic//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/utils/logutil/log.go:87//nruntime.gopanic//n//t/usr/local/go/src/runtime/panic.go:914//ngithub.com/prometheus/client_golang/prometheus.(*counter).Add//n//t/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/counter.go:109//ngithub.com/tikv/pd/pkg/mcs/resourcemanager/server.(*Manager).backgroundMetricsFlush//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/mcs/resourcemanager/server/manager.go:327)\"]","pod":"tc-pd-0"}
```

### What version of PD are you using (`pd-server -V`)?
```
./pd-server -V
 Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: 346e7716e2598dfba2db6afa73c3731e15449f49
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time:  2023-08-16 11:36:22
```

### PR DESCRIPTION
**Pull request by CabinfeverB**
### What problem does this PR solve?

Issue Number: Close #6973

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: client/resource_group/controller/model.go [hunk 1]
```diff
@@ -237,6 +237,43 @@ func add(custom1 *rmpb.Consumption, custom2 *rmpb.Consumption) {
...
+	}
+	if now.WRU >= last.WRU {
+		delta.WRU = now.WRU - last.WRU
+		last.WRU = now.WRU
+	}
+	if now.ReadBytes >= last.ReadBytes {
+		delta.ReadBytes = now.ReadBytes - last.ReadBytes
+		last.ReadBytes = now.ReadBytes
+	}
+	if now.WriteBytes >= last.WriteBytes {
```
Comment (HuSharp) [inline client/resource_group/controller/model.go:254]: if now with {ReadBytes: 100, WriteBytes: 0}, last is {ReadBytes: 50, WriteBytes: 50}
Maybe make last's parms not consistent, does it make sense?

Comment (CabinfeverB) [reply client/resource_group/controller/model.go:254]: We can assume that the various consumption stored in 'last' is monotonically increasing, and the inconsistency problem is not a big problem, I want to make sure that there are no more statistics RU. If the workload is ongoing and we are counting real consumption, then this discrepancy will be quickly eliminated as well.

**Review by HuSharp — APPROVED** [review]
LGTM!
