### PR TITLE
errs: remove redundant `FastGenWithCause` in `ZapError`

### LINKED ISSUE #7496: The error log  of TSO doesn't print the cause
## Bug Report

```
[2023/12/06 10:46:41.796 +08:00] [ERROR] [tso_dispatcher.go:498] ["[tso] getTS error"] [dc-location=global] [stream-addr=http://127.0.0.1:49408] [error="[PD:client:ErrClientGetTSO]get TSO failed, after processing requests"]
```
but 
https://github.com/tikv/pd/blob/ef6ba8551e525a700546d6bdb7ad6766115209cc/client/tso_dispatcher.go#L493-L496

And more, I do a test for `ZapError`
```
err1 := errors.New("test")
	log.Error("[pd] failed to close grpc clientConn", errs.ZapError(errs.ErrCloseGRPCConn, err1))
```
It prints
```
[2023/12/06 10:53:11.164 +08:00] [ERROR] [client_test.go:505] ["[pd] failed to close grpc clientConn"] [error="[PD:grpc:ErrCloseGRPCConn]test: test"] [stack="github.com/tikv/pd/tests/integrations/client_test.TestCustomTimeout\n\t/Users/jiangyongbo/github/pd/tests/integrations/client/client_test.go:505\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1595"]
```
"close gRPC connection failed" is overwritten by "test"

### PR DESCRIPTION
**Pull request by CabinfeverB**
### What problem does this PR solve?

Issue Number: Close #7496

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Manual test (add detailed scripts or steps below)
after  
```
[2023/12/06 10:43:25.636 +08:00] [ERROR] [tso_dispatcher.go:498] ["[tso] getTS error after processing requests"] [dc-location=global] [stream-addr=http://127.0.0.1:64317] [error="[PD:client:ErrClientGetTSO]get TSO failed, rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster"]
```

some example
```
[2023/12/06 11:16:43.550 +08:00] [ERROR] [client_test.go:506] ["[pd] failed to close grpc clientConn"] [error="[PD:grpc:ErrCloseGRPCConn]close gRPC connection failed: test"] [stack="github.com/tikv/pd/tests/integrations/client_test.TestCustomTimeout\n\t/Users/jiangyongbo/github/pd/tests/integrations/client/client_test.go:506\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1595"]
[2023/12/06 11:16:43.551 +08:00] [ERROR] [client_test.go:507] ["[tso] fetch pending tso requests error"] [error="[PD:client:ErrClientGetTSO]get TSO failed: test"] [stack="github.com/tikv/pd/tests/integrations/client_test.TestCustomTimeout\n\t/Users/jiangyongbo/github/pd/tests/integrations/client/client_test.go:507\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1595"]
[2023/12/06 11:16:43.551 +08:00] [ERROR] [client_test.go:508] ["send heartbeat message fail"] [error="[PD:grpc:ErrGRPCSend]send request error: test"] [stack="github.com/tikv/pd/tests/integrations/client_test.TestCustomTimeout\n\t/Users/jiangyongbo/github/pd/tests/integrations/client/client_test.go:508\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1595"]
[2023/12/06 11:16:43.551 +08:00] [ERROR] [client_test.go:509] ["watch gc safe point v2 error"] [error="[PD:client:ErrClientWatchGCSafePointV2Stream]watch gc safe point v2 stream failed: test"] [stack="github.com/tikv/pd/tests/integrations/client_test.TestCustomTimeout\n\t/Users/jiangyongbo/github/pd/tests/integrations/client/client_test.go:509\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1595"]
```

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: client/errs/errs.go [hunk 1]
```diff
@@ -27,7 +27,7 @@ func ZapError(err error, causeError ...error) zap.Field {
 	}
 	if e, ok := err.(*errors.Error); ok {
 		if len(causeError) >= 1 {
-			err = e.Wrap(causeError[0]).FastGenWithCause()
```
Comment (lhy1024) [inline client/errs/errs.go:30]: Do we need to check other `FastGenWithCause`?

**Review by lhy1024 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm
