### PR TITLE
Fix "non-default keyspace groups use the same timestamp path by mistake"

### LINKED ISSUE #6453: `TestGetMinTS` is flaky
### Which jobs are failing
```
--- FAIL: TestMicroserviceTSOClient (70.53s)
    --- FAIL: TestMicroserviceTSOClient/TestGetMinTS (7.89s)
        client_test.go:267: 
            	Error Trace:	/home/runner/work/pd/pd/tests/integrations/tso/client_test.go:267
            	            				/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/asm_amd64.s:1598
            	Error:      	Received unexpected error:
            	            	rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster
            	            	github.com/tikv/pd/client.(*tsoTSOStream).processRequests
            	            		/home/runner/work/pd/pd/client/tso_stream.go:190
            	            	github.com/tikv/pd/client.(*tsoClient).processRequests
            	            		/home/runner/work/pd/pd/client/tso_dispatcher.go:711
            	            	github.com/tikv/pd/client.(*tsoClient).handleDispatcher
            	            		/home/runner/work/pd/pd/client/tso_dispatcher.go:445
            	            	runtime.goexit
            	            		/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/asm_amd64.s:1598
            	            	github.com/tikv/pd/client.(*tsoRequest).Wait
            	            		/home/runner/work/pd/pd/client/tso_dispatcher.go:94
            	            	github.com/tikv/pd/client.(*client).GetTS
            	            		/home/runner/work/pd/pd/client/client.go:717
            	            	github.com/tikv/pd/tests/integrations/tso.(*tsoClientTestSuite).TestGetMinTS.func1
            	            		/home/runner/work/pd/pd/tests/integrations/tso/client_test.go:266
            	            	runtime.goexit
            	            		/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/asm_amd64.s:1598
            	Test:       	TestMicroserviceTSOClient/TestGetMinTS
        client_test.go:269: 
            	Error Trace:	/home/runner/work/pd/pd/tests/integrations/tso/client_test.go:269
            	            				/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/asm_amd64.s:1598
            	Error:      	"441418138665353238" is not less than "0"
            	Test:       	TestMicroserviceTSOClient/TestGetMinTS
```

### CI link
https://github.com/tikv/pd/actions/runs/4956285469/jobs/8866547918?pr=6409

### LINKED ISSUE #6465: non-default keyspace groups use the same timestamp path by mistake
### What did you do?
Added TestGetMinTS test but it had random failure. The root cause is that non-default keyspace groups use the same timestamp path by mistake, which caused random failure when saving timestamp in etcd due to transaction conflict thus caused keyspace group primary to be reset unexpectedly.

### What did you expect to see?
No random test failure in TestGetMinTS.

### What did you see instead?
There were random failures due to the root cause described above.

2023-05-15T00:29:19.5492594Z [2023/05/15 00:29:19.548 +00:00] [WARN] [tso.go:289] ["clock offset"] [jet-lag=221.789286ms] [prev-physical=2023/05/15 00:29:19.326 +00:00] [now=2023/05/15 00:29:19.548 +00:00] [update-physical-interval=50ms]
2023-05-15T00:29:19.5600840Z [2023/05/15 00:29:19.559 +00:00] [WARN] [tso.go:289] ["clock offset"] [jet-lag=169.907035ms] [prev-physical=2023/05/15 00:29:19.389 +00:00] [now=2023/05/15 00:29:19.559 +00:00] [update-physical-interval=50ms]
2023-05-15T00:29:19.5651800Z [2023/05/15 00:29:19.564 +00:00] [WARN] [allocator_manager.go:752] ["failed to update allocator's timestamp"] [dc-location=global] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
2023-05-15T00:29:19.5668265Z [2023/05/15 00:29:19.566 +00:00] [INFO] [tso.go:375] ["reset the timestamp in memory"]
2023-05-15T00:29:19.5675787Z [2023/05/15 00:29:19.567 +00:00] [INFO] [lease.go:172] ["stop lease keep alive worker"] [purpose="keyspace group primary election"]
2023-05-15T00:29:19.5726002Z [2023/05/15 00:29:19.572 +00:00] [INFO] [leadership.go:211] ["current leadership is deleted"] [leader-key=/ms/7233199744956437750/tso/00001/primary] [purpose="keyspace group primary election"]
2023-05-15T00:29:19.5733101Z [2023/05/15 00:29:19.573 +00:00] [INFO] [leadership.go:211] ["current leadership is deleted"] [leader-key=/ms/7233199744956437750/tso/00001/primary] [purpose="keyspace group primary election"]
2023-05-15T00:29:19.5746233Z [2023/05/15 00:29:19.574 +00:00] [INFO] [global_allocator.go:499] ["the tso primary has changed, try to re-campaign a primary"]
2023-05-15T00:29:19.5750728Z [2023/05/15 00:29:19.574 +00:00] [INFO] [global_allocator.go:507] ["start to campaign the primary"] [campaign-tso-primary-name=http://127.0.0.1:44687-00001]

### PR DESCRIPTION
**Pull request by binshi-bing**
### What problem does this PR solve?

Issue Number: Close #6453
Issue Number: Close #6465

### What is changed and how does it work?

```commit-message
The tso servers are loading keyspace groups asynchronously. Make sure all keyspace groups
are available for serving tso requests from corresponding keyspaces by querying
IsKeyspaceServing(keyspaceID, the Desired KeyspaceGroupID). if use default keyspace group id
in the query, it will always return true as the keyspace will be served by default keyspace group
before the keyspace groups are loaded.
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/integrations/tso/testutil.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ import (
 const (
 	serverCount                 = 3
 	tsoRequestConcurrencyNumber = 5
-	tsoRequestRound             = 30
+	tsoRequestRound             = 300
```
Comment (binshi-bing) [inline tests/integrations/tso/testutil.go:25]: having more rounds to ensure SaveTimestamp() to etcd is covered.

File: tests/integrations/tso/Makefile [hunk 2]
```diff
@@ -32,7 +32,7 @@ test: failpoint-enable
 	$(MAKE) failpoint-disable
 
 ci-test-job:
-	CGO_ENABLED=1 go test -tags deadlock -race -covermode=atomic -coverprofile=covprofile -coverpkg=$(ROOT_PATH)/... github.com/tikv/pd/tests/integrations/tso
+	CGO_ENABLED=1 go test -v -tags deadlock -race -covermode=atomic -coverprofile=covprofile -coverpkg=$(ROOT_PATH)/... github.com/tikv/pd/tests/integrations/tso
```
Comment (binshi-bing) [inline tests/integrations/tso/Makefile:35]: will remove it in the final commit.

File: tests/integrations/mcs/tso/keyspace_group_manager_test.go [hunk 3]
```diff
@@ -248,26 +269,27 @@ func (suite *tsoKeyspaceGroupManagerTestSuite) TestTSOKeyspaceGroupSplit() {
...
 	// Check the split TSO from keyspace group 2.
 	var splitTS pdpb.Timestamp
 	testutil.Eventually(re, func() bool {
 		splitTS, err = suite.requestTSO(re, 1, 222, 2)
 		return err == nil && tsoutil.CompareTimestamp(&splitTS, &pdpb.Timestamp{}) > 0
 	})
+	splitTS, err = suite.requestTSO(re, 1, 222, 2)
 	re.Greater(tsoutil.CompareTimestamp(&splitTS, &ts), 0)
-	// Finish the split.
-	handlersutil.MustFinishSplitKeyspaceGroup(re, suite.pdLeaderServer, 2)
```
Comment (binshi-bing) [inline tests/integrations/mcs/tso/keyspace_group_manager_test.go:259]: No need to explicitly to call this line, because the keyspace group manager will automatically finish the split when it's first time serving the tso request for the split target group.

File: tests/integrations/mcs/tso/keyspace_group_manager_test.go [hunk 4]
```diff
@@ -248,26 +269,27 @@ func (suite *tsoKeyspaceGroupManagerTestSuite) TestTSOKeyspaceGroupSplit() {
...
 
 func (suite *tsoKeyspaceGroupManagerTestSuite) requestTSO(
 	re *require.Assertions,
 	count, keyspaceID, keyspaceGroupID uint32,
 ) (pdpb.Timestamp, error) {
 	primary := suite.tsoCluster.WaitForPrimaryServing(re, keyspaceID, keyspaceGroupID)
-	tam, err := primary.GetTSOAllocatorManager(keyspaceGroupID)
+	kgm := primary.GetKeyspaceGroupManager()
+	re.NotNil(kgm)
+	ts, _, err := kgm.HandleTSORequest(keyspaceID, keyspaceGroupID, tsopkg.GlobalDCLocation, count)
```
Comment (binshi-bing) [inline tests/integrations/mcs/tso/keyspace_group_manager_test.go:290]: Call keyspace group manager's HandleTSORequest() instead of primary.GetTSOAllocatorManager(keyspaceGroupID) to trigger split process.

File: tests/integrations/mcs/tso/keyspace_group_manager_test.go [hunk 5]
```diff
@@ -176,15 +181,29 @@ func (suite *tsoKeyspaceGroupManagerTestSuite) TestKeyspacesServedByNonDefaultKe
...
 
+	// Wait until all keyspace groups are ready.
 	testutil.Eventually(re, func() bool {
 		for _, param := range params {
 			for _, keyspaceID := range param.keyspaceIDs {
 				served := false
 				for _, server := range suite.tsoCluster.GetServers() {
 					if server.IsKeyspaceServing(keyspaceID, param.keyspaceGroupID) {
-						tam, err := server.GetTSOAllocatorManager(param.keyspaceGroupID)
+						am, err := server.GetTSOAllocatorManager(param.keyspaceGroupID)
```
Comment (binshi-bing) [inline tests/integrations/mcs/tso/keyspace_group_manager_test.go:191]: Here we test the correct timestamp paths are used for all keyspace groups.

File: pkg/tso/local_allocator.go [hunk 6]
```diff
@@ -73,6 +86,14 @@ func NewLocalTSOAllocator(
 	}
 }
 
+// GetTimestampPath returns the timestamp path in etcd.
+func (lta *LocalTSOAllocator) GetTimestampPath() string {
+	if lta == nil || lta.timestampOracle == nil {
+		return ""
```
Comment (rleungx) [inline pkg/tso/local_allocator.go:92]: Should we return the default one?

File: tests/integrations/mcs/tso/keyspace_group_manager_test.go [hunk 7]
```diff
@@ -248,26 +269,27 @@ func (suite *tsoKeyspaceGroupManagerTestSuite) TestTSOKeyspaceGroupSplit() {
 	re.Equal(uint32(2), kg2.ID)
 	re.Equal([]uint32{222, 333}, kg2.Keyspaces)
 	re.True(kg2.IsSplitTarget())
+	time.Sleep(3 * time.Second)
```
Comment (rleungx) [inline tests/integrations/mcs/tso/keyspace_group_manager_test.go:272]: Why do we need sleep here, we can use `Eventually` to do the same thing.

Comment (binshi-bing) [reply tests/integrations/mcs/tso/keyspace_group_manager_test.go:272]: good catch. It's added for debugging. It should be removed.

File: pkg/tso/local_allocator.go (hunk 6 above)
Comment (binshi-bing) [reply pkg/tso/local_allocator.go:92]: nope. returning "" to indicate error.

File: pkg/tso/local_allocator.go [hunk 8]
```diff
@@ -36,14 +37,15 @@ import (
 // which is only used to allocate TSO in one DC each.
 // One PD server may hold multiple Local TSO Allocators.
 type LocalTSOAllocator struct {
+	// kgID is the keyspace group ID
```
[the remark this answers is not in the document]
Comment (binshi-bing) [reply pkg/tso/local_allocator.go:40]: removed

**Review by JmPotato — APPROVED** [review]
