### PR TITLE
server/grpc_service: make the lock for `UpdateServiceGCSafePoint` smaller

### LINKED ISSUE #5019: server/grpc_service: could we make the lock for the func `UpdateServiceGCSafepoint` smaller?
## Bug Report
It seems the function `UpdateServiceGCSafepoint` should only save a safepoint bigger than the `minServiceGCSafepoint`, So that we can make sure that the `minServiceGCSafepoint` is always increasing. However, there exist corner case that it may store a safepoint smaller than the minServiceGCSafepoint.
[https://github.com/tikv/pd/blob/efb4c9f687620afd0654296bfcd932515fce5a46/server/grpc_service.go#L1395-L1430](https://github.com/tikv/pd/blob/efb4c9f687620afd0654296bfcd932515fce5a46/server/grpc_service.go#L1395-L1430)

### What did you do?
Here is the case we may store a safepoint smaller than the minServiceGCSafepoint.
assume that there is only one service safepoint in PD:(cdc,safepoint=5)
1.  br-client: got min=(cdc,safepoint=5) from `LoadMinServiceGCSafePoint`.
2.  cdc-client: got min=(cdc,safepoint=5) from `LoadMinServiceGCSafePoint`.
3.  cdc-client: set (cdc,safepoint=10) with `SaveServiceGCSafePoint` should success since  the safepoint 10 > min.safepoint 5
4. cdc-client: get min = (cdc,safepoint=10) success from `LoadMinServiceGCSafePoint` and returns to the client.
5.  br-client: set (br,safepoint=7) success since the safepoint 7 > min.safepoint 5(got from step1)
6.  br-client: get min = (br,safepoint=7) success from `LoadMinServiceGCSafePoint` and returns to the client.

### What did you expect to see?
step 5 shouldn't happen and br-client should got response  `min = (cdc,safepoint=10)`

### What did you see instead?
step 5-6 happens.
### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: shirly <AndreMouche@126.com>

### What problem does this PR solve?

Issue Number: Close #5019 

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by rleungx** [comment]
CI failed.

File: server/gc/safepoint.go [hunk 1]
```diff
@@ -62,3 +55,31 @@ func (manager *gcSafePointManager) UpdateGCSafePoint(newSafePoint uint64) (oldSa
...
+		SafePoint: newSafePoint,
+	}
+	if math.MaxInt64-now.Unix() <= ttl {
+		ssp.ExpiredAt = math.MaxInt64
+	}
+	if err := manager.store.SaveServiceGCSafePoint(ssp); err != nil {
+		return nil, false, err
+	}
+
+	// If the min safepoint is updated, load the next one
```
Comment (bufferflies) [inline server/gc/safepoint.go:80]:
```suggestion
	// If the min safe point is updated, load the next one
```

**Review by bufferflies — APPROVED** [review]
rest LGTM

File: server/gc/safepoint_test.go [hunk 2]
```diff
@@ -78,3 +80,87 @@ func TestGCSafePointUpdateCurrently(t *testing.T) {
...
+	manager := NewSafePointManager(newGCStorage())
+	gcworkerServiceID := "gc_worker"
+	cdcServiceID := "cdc"
+	brServiceID := "br"
+	cdcServiceSafePoint := uint64(10)
+	gcWorkerSafePoint := uint64(8)
+	brSafePoint := uint64(15)
+
+	wg := sync.WaitGroup{}
+	wg.Add(1)
```
Comment (rleungx) [inline server/gc/safepoint_test.go:95]: How about:
```suggestion
	wg.Add(5)
```

File: server/gc/safepoint_test.go [hunk 3]
```diff
@@ -78,3 +80,87 @@ func TestGCSafePointUpdateCurrently(t *testing.T) {
...
+	// update the safepoint for cdc to 10 should success
+	go func() {
+		min, updated, err := manager.UpdateServiceGCSafePoint(cdcServiceID, cdcServiceSafePoint, 10000, time.Now())
+		re.NoError(err)
+		re.True(updated)
+		// the service will init the service safepoint to 0(<10 for cdc) for gc_worker.
+		re.Equal(gcworkerServiceID, min.ServiceID)
+		wg.Done()
```
Comment (rleungx) [inline server/gc/safepoint_test.go:103]: defer wg.Done()

**Review by rleungx — APPROVED** [review]
The rest LGTM
