### PR TITLE
fix ci failed in api package

### LINKED ISSUE #2823: Test in api is unstable
## Bug Report

```
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:55.765 +08:00] [INFO] [raft.go:923] ["831b306120d34f9d is starting a new election at term 3"]
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:55.766 +08:00] [INFO] [raft.go:729] ["831b306120d34f9d became pre-candidate at term 3"]
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:55.766 +08:00] [INFO] [raft.go:824] ["831b306120d34f9d received MsgPreVoteResp from 831b306120d34f9d at term 3"]
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:55.766 +08:00] [INFO] [raft.go:811] ["831b306120d34f9d [logterm: 3, index: 177] sent MsgPreVote request to 976239f155150dc3 at term 3"]
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:55.766 +08:00] [INFO] [raft.go:811] ["831b306120d34f9d [logterm: 3, index: 177] sent MsgPreVote request to aa912e71d9b93f32 at term 3"]
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:56.368 +08:00] [WARN] [v3_server.go:750] ["timed out waiting for read index response (local node might have slow network)"] [timeout=11s]
[2020-08-24T04:52:10.131Z] {"level":"warn","ts":"2020-08-24T12:51:57.377+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-026b2f2f-0a61-4ebd-8c9e-40221e536a7c/127.0.0.1:13272","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:57.377 +08:00] [ERROR] [etcdutil.go:109] ["load from etcd meet error"] [error="[PD:etcdutil:ErrLoadValue] context deadline exceeded"]
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:57.377 +08:00] [WARN] [etcdutil.go:112] ["kv gets too slow"] [request-key=/pd/6864408351241973623/scheduler_config/] [cost=10.000810878s] [error="context deadline exceeded"]
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:57.377 +08:00] [WARN] [util.go:144] ["apply request took too long"] [took=9.999357644s] [expected-duration=100ms] [prefix="read-only range "] [request="key:\"/pd/6864408351241973623/scheduler_config/\" range_end:\"/pd/6864408351241973623/scheduler_config0\" limit:1000 "] [response=] [error="context canceled"]
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:57.377 +08:00] [ERROR] [coordinator.go:238] ["cannot load schedulers' config"] [retry-times=9] [error="context deadline exceeded"]
[2020-08-24T04:52:10.131Z] [2020/08/24 12:51:57.377 +08:00] [FATAL] [coordinator.go:241] ["cannot load schedulers' config"] [error="context deadline exceeded"] [stack="github.com/pingcap/log.Fatal\n\t/home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200511115504-543df19646ad/global.go:59\ngithub.com/tikv/pd/server/cluster.(*coordinator).run\n\t/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/cluster/coordinator.go:241\ngithub.com/tikv/pd/server/cluster.(*RaftCluster).runCoordinator\n\t/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/cluster/cluster.go:334"]
[2020-08-24T04:52:10.131Z] FAIL	github.com/tikv/pd/server/api	110.294s
```
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/pd_test/runs/7161/nodes/38/steps/107/log/?start=0

### PR DESCRIPTION
**Pull request by HunDunDM**
### What problem does this PR solve?

fix #2823 

### What is changed and how it works?

check ctx when loading schedule config

### Check List

Tests

- Unit test

Related changes

- Need to cherry-pick to the release branch

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -405,12 +405,18 @@ func (s *Server) Close() {
...
+	}
 
 	if s.client != nil {
-		s.client.Close()
+		if err := s.client.Close(); err != nil {
+			log.Error("close etcd client meet error", zap.Error(err))
+		}
 	}
 
+	s.stopServerLoop()
```
Comment (lhy1024) [inline server/server.go:418]: why move this line?

Comment (HunDunDM) [reply server/server.go]: Seems to cause some problems, has been reverted

**Review by lhy1024 — APPROVED** [review]

File: pkg/errs/errno.go [hunk 2]
```diff
@@ -93,3 +93,8 @@ var (
 	ErrLoadValue  = errors.Normalize("load value from etcd failed", errors.RFCCodeText("PD:etcdutil:ErrLoadValue"))
 	ErrGetCluster = errors.Normalize("get cluster from remote peer failed", errors.RFCCodeText("PD:etcdutil:ErrGetCluster"))
 )
+
+// etcd errors
```
Comment (JmPotato) [inline pkg/errs/errno.go:97]: Do we need to classify this error as a server error?

Comment (HunDunDM) [reply pkg/errs/errno.go:97]: @rleungx What do you think?

Comment (lhy1024) [reply pkg/errs/errno.go:97]: I think we may talk with the issue in new pr, we should merge it as soon as possible to improve ci

Comment (rleungx) [reply pkg/errs/errno.go:97]: For the error which is generated from the third-party project, we can use the project name instead of our package name.

**Review by rleungx — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
