### PR TITLE
ci-subtask: exit ci-subtask.sh when execute ci failed

### LINKED ISSUE #7770: ci didn't report an error
### What did you do?
run master ci

### What did you expect to see?
export error when failed

### What did you see instead?
not report error when failed

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Close #7770

### What is changed and how does it work?

```commit-message
need to exit when execute failed
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by HuSharp** [comment]
error can be checked in https://github.com/tikv/pd/actions/runs/7690098188/job/20953445255?pr=7766

**Review by bufferflies — APPROVED** [review]

File: tests/integrations/client/http_client_test.go [hunk 1]
```diff
@@ -520,14 +526,14 @@ func (suite *httpClientTestSuite) checkScheduleConfig(mode mode, client pd.Clien
 
 	config, err := client.GetScheduleConfig(env.ctx)
 	re.NoError(err)
-	re.Equal(float64(4), config["leader-schedule-limit"])
+	re.Equal(float64(4), config["hot-region-schedule-limit"])
```
Comment (JmPotato) [inline tests/integrations/client/http_client_test.go:529]: Why change the scheduler?

Comment (HuSharp) [reply tests/integrations/client/http_client_test.go:529]: To avoid the effects of other tests, such as testConfig above.

File: scripts/ci-subtask.sh [hunk 2]
```diff
@@ -8,20 +8,14 @@ if [[ $2 -gt 10 ]]; then
     integrations_dir=./tests/integrations
     integrations_tasks=($(find "$integrations_dir" -mindepth 1 -maxdepth 1 -type d))
     # Currently, we only have 3 integration tests, so we can hardcode the task index.
-    for t in ${integrations_tasks[@]}; do
-        if [[ "$t" = "$integrations_dir/client" && "$2" = 11 ]]; then
+    for t in "${integrations_tasks[@]}"; do
+        if [[ "$t" = "$integrations_dir/client" && $2 -eq 11 ]]; then
             cd ./client && make ci-test-job && cd .. && cat ./client/covprofile >> covprofile
```
Comment (CabinfeverB) [inline scripts/ci-subtask.sh:13]: Does this line need `exit 1`?

**Review by CabinfeverB — COMMENTED** [review]
REST LGTM

**Review by JmPotato — APPROVED** [review]

File: tests/integrations/mcs/scheduling/api_test.go [hunk 3]
```diff
@@ -397,13 +403,11 @@ func (suite *apiTestSuite) checkConfig(cluster *tests.TestCluster) {
 	re.Equal(cfg.DataDir, s.GetConfig().DataDir)
 	testutil.Eventually(re, func() bool {
 		// wait for all schedulers to be loaded in scheduling server.
-		return len(cfg.Schedule.SchedulersPayload) == 6
+		return len(cfg.Schedule.SchedulersPayload) == 4
```
Comment (HuSharp) [inline tests/integrations/mcs/scheduling/api_test.go:406]: fixed as https://github.com/tikv/pd/pull/7765, PTAL, thx! @rleungx

File: pkg/mcs/scheduling/server/cluster.go [hunk 4]
```diff
@@ -454,7 +455,11 @@ func (c *Cluster) runCoordinator() {
 	defer logutil.LogPanic()
 	defer c.wg.Done()
 	// force wait for 1 minute to make prepare checker won't be directly skipped
-	c.coordinator.RunUntilStop(collectWaitTime)
+	runCollectWaitTime := collectWaitTime
```
Comment (HuSharp) [inline pkg/mcs/scheduling/server/cluster.go:458]: added a failpoint here as https://github.com/tikv/pd/pull/7678 @rleungx PTAL as well, thx!

File: scripts/ci-subtask.sh (hunk 2 above)
Comment (HuSharp) [reply scripts/ci-subtask.sh]: good catch:) added.

**Review by CabinfeverB — APPROVED** [review]

**Review by rleungx — APPROVED** [review]
