### PR TITLE
*: fix scheduling can not immediately start after transfer leader

### LINKED ISSUE #4769: Scheduling is blocked for around 5 mins after transferring the PD leader
### What did you do?

Transfer PD leader manually.

### What did you expect to see?

The scheduling can run immediately after the leader is transferred.

### What did you see instead?
```
:34.066 +08:00] [INFO] [coordinator.go:302] ["coordinator starts to collect cluster information"]
[2022/03/29 14:29:34.068 +08:00] [INFO] [id.go:122] ["idAllocator allocates a new id"] [alloc-id=2000]
[2022/03/29 14:29:34.068 +08:00] [INFO] [util.go:77] ["load cluster version"] [cluster-version=6.0.0-alpha]
[2022/03/29 14:29:34.068 +08:00] [INFO] [server.go:1381] ["PD cluster leader is ready to serve"] [pd-leader-name=pd-0]
[2022/03/29 14:34:29.850 +08:00] [INFO] [grpc_service.go:1375] ["update service GC safe point"] [service-id=gc_worker] [expire-at=9223372036854775807] [safepoint=432153577346301952]
[2022/03/29 14:34:34.067 +08:00] [INFO] [coordinator.go:305] ["coordinator has finished cluster information preparation"]
[2022/03/29 14:34:34.067 +08:00] [INFO] [coordinator.go:315] ["coordinator starts to run schedulers"]
[2022/03/29 14:34:34.068 +08:00] [INFO] [coordinator.go:363] ["create scheduler with independent configuration"] [scheduler-name=balance-hot-region-scheduler]
[2022/03/29 14:34:34.069 +08:00] [INFO] [coordinator.go:363] ["create scheduler with independent configuration"] [scheduler-name=balance-leader-scheduler]
[2022/03/29 14:34:34.070 +08:00] [INFO] [coordinator.go:363] ["create scheduler with independent configuration"] [scheduler-name=balance-region-scheduler]
[2022/03/29 14:34:34.070 +08:00] [INFO] [coordinator.go:385] ["create scheduler"] [scheduler-name=balance-region-scheduler] [scheduler-args="[]"]
[2022/03/29 14:34:34.071 +08:00] [INFO] [coordinator.go:385] ["create scheduler"] [scheduler-name=balance-leader-scheduler] [scheduler-args="[]"]
[2022/03/29 14:34:34.071 +08:00] [INFO] [coordinator.go:385] ["create scheduler"] [scheduler-name=balance-hot-region-scheduler] [scheduler-args="[]"]
[2022/03/29 14:34:34.072 +08:00] [INFO] [coordinator.go:285] ["coordinator begins to actively drive push operator"]
[2022/03/29 14:34:34.072 +08:00] [INFO] [coordinator.go:220] ["coordinator begins to check suspect key ranges"]
```

It is blocked for around 5 minutes to prepare.

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Issue Number: Close #4769.

### What is changed and how does it work?

This PR uses the flag to distinguish if the region's heartbeat is new when transferring the PD leader.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
Fix the issue that scheduling cannot immediately start after PD leader transfers
```

### CODE REVIEW

File: server/cluster/cluster.go [hunk 1]
```diff
@@ -737,7 +742,7 @@ func (c *RaftCluster) processRegionHeartbeat(region *core.RegionInfo) error {
 		regionEventCounter.WithLabelValues("update_cache").Inc()
 	}
 
-	if isNew {
+	if !c.IsPreapred() || isNew {
```
Comment (JmPotato) [inline server/cluster/cluster.go:745]: Why add `IsPreapred` check here? Just controlling the `isNew` flag should be enough to fix this issue 🤔

Comment (rleungx) [reply server/cluster/cluster.go:745]: Yes, but when we have collected enough regions, there is no need to collect the rest anymore.

Comment (JmPotato) [reply server/cluster/cluster.go:745]: Will this cause the region which is not new actually to be prepared here?

File: server/cluster/cluster.go [hunk 2]
```diff
@@ -671,6 +671,11 @@ func (c *RaftCluster) processReportBuckets(buckets *metapb.Buckets) error {
 	return nil
 }
 
+// IsPreapred return if the prepare checker is ready.
+func (c *RaftCluster) IsPreapred() bool {
```
Comment (JmPotato) [inline server/cluster/cluster.go:675]:
```suggestion
func (c *RaftCluster) IsPrepared() bool {
```

File: server/cluster/cluster.go (hunk 1 above)
Comment (rleungx) [reply server/cluster/cluster.go:745]: Oh, it should be `!c.IsPreapred() && isNew`

Comment (rleungx) [reply server/cluster/cluster.go]: nice catch!

**Review by JmPotato — APPROVED** [review]
LGTM. BTW, do we need to triage this issue first to see which version it affects before merging it?

**Comment by rleungx** [comment]
> LGTM. BTW, do we need to triage this issue first to see which version it affects before merging it?

Done

File: server/cluster/cluster.go [hunk 3]
```diff
@@ -812,7 +817,7 @@ func (c *RaftCluster) processRegionHeartbeat(region *core.RegionInfo) error {
 		regionEventCounter.WithLabelValues("update_cache").Inc()
 	}
 
-	if isNew {
+	if !c.IsPrepared() && isNew {
```
Comment (AndreMouche) [inline server/cluster/cluster.go:820]: Could we check the condition in the function `collect` directly?

File: server/cluster/coordinator.go [hunk 4]
```diff
@@ -310,6 +311,9 @@ func (c *coordinator) runUntilStop() {
 }
 
 func (c *coordinator) run() {
+	failpoint.Inject("runSchedulerCheckInterval", func() {
```
Comment (AndreMouche) [inline server/cluster/coordinator.go:314]: Could we change the `Ticker` instead of `runSchedulerCheckInterval`? So we can keep `runSchedulerCheckInterval` as a constant.
For example , re define the ticker after L317
```
	failpoint.Inject("runSchedulerCheckInterval", func() {
		ticker = time.NewTicker(100 * time.Millisecond)
	})
```

File: server/core/region.go [hunk 5]
```diff
@@ -622,6 +628,9 @@ func GenerateRegionGuideFunc(enableLog bool) RegionGuideFunc {
 					region.GetReplicationStatus().GetStateId() != origin.GetReplicationStatus().GetStateId()) {
 				saveCache = true
 			}
+			if !origin.IsFromHeartbeat() {
+				isNew = true
```
Comment (AndreMouche) [inline server/core/region.go:632]: Should we set `saveKV`, `saveCache`, `needSync` to `true` if it is from heartbeat?

File: server/region_syncer/client.go [hunk 6]
```diff
@@ -204,9 +204,10 @@ func (s *RegionSyncer) StartSyncWithLeader(addr string) {
 							core.SetWrittenKeys(stats[i].KeysWritten),
 							core.SetReadBytes(stats[i].BytesRead),
 							core.SetReadKeys(stats[i].KeysRead),
+							core.SetFromHeartbeat(false),
 						)
 					} else {
-						region = core.NewRegionInfo(r, regionLeader)
+						region = core.NewRegionInfo(r, regionLeader, core.SetFromHeartbeat(false))
```
Comment (AndreMouche) [inline server/region_syncer/client.go:210]: It seems we do not need to `SetFromHeartbeat(fase)` because we do not process the value if `IsNew` on L218
```
_, saveKV, _, _ := regionGuide(region, origin)
```

**Review by AndreMouche — COMMENTED** [review]
Could we remove the value of `fromHeartbeat` in `RegionInfo`, it seems we do not need it.

File: server/cluster/prepare_checker.go [hunk 7]
```diff
@@ -40,7 +40,7 @@ func newPrepareChecker() *prepareChecker {
 func (checker *prepareChecker) check(c *core.BasicCluster) bool {
 	checker.RLock()
 	defer checker.RUnlock()
-	if checker.isPrepared || time.Since(checker.start) > collectTimeout {
+	if checker.prepared || time.Since(checker.start) > collectTimeout {
```
Comment (AndreMouche) [inline server/cluster/prepare_checker.go:43]: Is it possible that the condition `time.Since(checker.start) > collectTimeout` comes true before `prepared`?  What will happen if `checker.prepared` never comes true?

**Review by AndreMouche — COMMENTED** [review]
Rest LGTM

**Review by AndreMouche — APPROVED** [review]
LGTM
