### PR TITLE
server: fix the bug that causes wrong statistics for over/undersized regions

### LINKED ISSUE #5107: [Dynamic Region]undersized-region-count display is not accurate on grafana after modify the configuration repeatedly
### What did you do?
modify the dynamic region region configuration repeatedly（modified every 1 hour）
var regionSplitSizes = []string{"128MiB", "256MiB", "512MiB", "1024MiB", "5120MiB", "10240MiB"}
func getTargetDynamicRegionConfigsValue(regionSplitSize string) (map[string]string, error) {
	configsValue := make(map[string]string)
	sizeStr := regionSplitSize[0 : len(regionSplitSize)-3]
	unit := regionSplitSize[len(regionSplitSize)-3:]
	sizeValue, _ := strconv.ParseFloat(sizeStr, 64)
	if unit != "MiB" && unit != "GiB" {
		return configsValue, errors.New("unsupported region split size")
	}
	// convert it to MiB
	if unit == "GiB" {
		sizeValue = sizeValue * 1024
	}
	configsValue["coprocessor.enable-region-bucket"] = "true"
	configsValue["coprocessor.region-bucket-size"] = "96MiB"
	configsValue["coprocessor.region-split-size"] = regionSplitSize
	configsValue["coprocessor.region-split-keys"] = strconv.Itoa(int(math.Ceil(sizeValue * 10000)))
	configsValue["coprocessor.region-max-size"] = strconv.Itoa(int(math.Ceil(sizeValue*1.5))) + "MiB"
	configsValue["coprocessor.region-max-keys"] = strconv.Itoa(int(math.Ceil(sizeValue * 1.5 * 10000)))
	configsValue["schedule.max-merge-region-size"] = strconv.Itoa(int(math.Ceil(sizeValue * 0.2)))
	configsValue["schedule.max-merge-region-keys"] = strconv.Itoa(int(math.Ceil(sizeValue * 0.2 * 10000)))

	return configsValue, nil
}

### What did you expect to see?
after stop workload，undersized-region-count can reduce to zero

### What did you see instead?
image
after restart pd，undersized-region-count recover to zero
middle_img_v2_7e4c37ea-1bd6-404c-a326-4dc57fd4bb8g

### What version of PD are you using (`pd-server -V`)?
./tikv-server -V
 TiKV 
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   5c6018e5711bec3d13f9cdf39d3a84ed9de27809
Git Commit Branch: heads/refs/tags/v6.1.0
UTC Build Time:    2022-06-02 13:53:59
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
./pd-server -V
 Release Version: v6.1.0
Edition: Community
Git Commit Hash: d82f4fab6cf37cd1eca9c3574984e12a7ae27c42
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time:  2022-06-01 01:44:08
./tidb-server -V
 Release Version: v6.1.0
Edition: Community
Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:15:11
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Issue Number: Close #5107.

### What is changed and how does it work?

```commit-message
Fix the bug that causes wrong statistics for over/undersized regions.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/statistics/region_collection.go [hunk 1]
```diff
@@ -101,6 +101,18 @@ func (r *RegionStatistics) GetRegionStatsByType(typ RegionStatisticType) []*core
 	return res
 }
 
+// IsRegionStatsType returns whether the status of the region is the given type.
+func (r *RegionStatistics) IsRegionStatsType(regionID uint64, typ RegionStatisticType) bool {
+	r.RLock()
+	defer r.RUnlock()
+	for _, r := range r.stats[typ] {
+		if r.GetID() == regionID {
```
Comment (nolouch) [inline server/statistics/region_collection.go:109]: Better directly use `map` the improve the performance. do not iterator in here.

File: server/statistics/region_collection.go [hunk 2]
```diff
@@ -128,6 +140,20 @@ func (r *RegionStatistics) deleteOfflineEntry(deleteIndex RegionStatisticType, r
 	}
 }
 
+// RegionStatsNeedUpdate checks whether the region's status need to be updated
+// due to some special state types.
+func (r *RegionStatistics) RegionStatsNeedUpdate(region *core.RegionInfo) bool {
+	regionID := region.GetID()
+	maxSize := int64(r.storeConfigManager.GetStoreConfig().GetRegionMaxSize())
+	maxKeys := int64(r.storeConfigManager.GetStoreConfig().GetRegionMaxKeys())
+	if r.IsRegionStatsType(regionID, OversizedRegion) != region.IsOversized(maxSize, maxKeys) {
```
Comment (nolouch) [inline server/statistics/region_collection.go:149]: I wonder `IsRegionStatsType` can be removed.

File: server/statistics/region_collection.go [hunk 3]
```diff
@@ -128,6 +140,20 @@ func (r *RegionStatistics) deleteOfflineEntry(deleteIndex RegionStatisticType, r
...
+		return true
+	}
+	minSize := int64(r.opt.GetMaxMergeRegionSize())
+	minKeys := int64(r.opt.GetMaxMergeRegionKeys())
+	return r.IsRegionStatsType(regionID, UndersizedRegion) != region.IsUndersized(minSize, minKeys)
```
Comment (nolouch) [inline server/statistics/region_collection.go:154]: I wonder `IsRegionStatsType` can be removed.

File: server/statistics/region_collection.go (hunk 2 above)
Comment (JmPotato) [reply server/statistics/region_collection.go:145]: We need to put a read lock inside `IsRegionStatsType` and it's also used in the test. I want to keep it.

Comment (nolouch) [reply server/statistics/region_collection.go:145]: why cannot directly use `region.IsOversized(maxSize, maxKeys)`?

Comment (JmPotato) [reply server/statistics/region_collection.go:145]: I write this check to make sure the `RegionStatistics` will only be updated when it's necessary:

* The region is not oversized before.
* The region is not oversized anymore.

File: server/statistics/region_collection.go [hunk 4]
```diff
@@ -169,17 +191,24 @@ func (r *RegionStatistics) Observe(region *core.RegionInfo, stores []*core.Store
...
 		EmptyRegion: region.GetApproximateSize() <= core.EmptyRegionApproximateSize,
-		OversizedRegion: region.GetApproximateSize() >= int64(r.storeConfigManager.GetStoreConfig().GetRegionMaxSize()) ||
-			region.GetApproximateKeys() >= int64(r.storeConfigManager.GetStoreConfig().GetRegionMaxKeys()),
-		UndersizedRegion: region.NeedMerge(int64(r.opt.GetScheduleConfig().MaxMergeRegionSize),
-			int64(r.opt.GetScheduleConfig().MaxMergeRegionKeys)),
+		OversizedRegion: region.IsOversized(
+			int64(r.storeConfigManager.GetStoreConfig().GetRegionMaxSize()),
+			int64(r.storeConfigManager.GetStoreConfig().GetRegionMaxKeys()),
+		),
+		UndersizedRegion: region.IsUndersized(
```
Comment (rleungx) [inline server/statistics/region_collection.go:208]: When the TTL config exists, I'm not sure whether the original config or TTL config should be used.

Comment (JmPotato) [reply server/statistics/region_collection.go:208]: Since the TTL config will affect the actual merge behavior, I think the statistical info should be consistent with it.

**Review by nolouch — APPROVED** [review]
lgtm

File: server/core/region.go [hunk 5]
```diff
@@ -229,6 +229,17 @@ func (r *RegionInfo) NeedMerge(mergeSize int64, mergeKeys int64) bool {
...
 }
 
+// IsOversized indicates whether the region is oversized.
+func (r *RegionInfo) IsOversized(maxSize int64, maxKeys int64) bool {
+	return r.GetApproximateSize() >= maxSize || r.GetApproximateKeys() >= maxKeys
+}
+
+// IsUndersized indicates whether the region is undersized.
+// PS: This is an alias of `NeedMerge`.
+func (r *RegionInfo) IsUndersized(minSize int64, minKeys int64) bool {
```
Comment (bufferflies) [inline server/core/region.go:239]: why not rename  `NeedMerge`

Comment (JmPotato) [reply server/core/region.go:239]: In the `MergeChecker`, `NeedMerge` is a more clear name. So I want to keep both to use in different contexts.

**Review by bufferflies — APPROVED** [review]
