### PR TITLE
scheduler: add approximateSize property to operator struct

### LINKED ISSUE #4457: Operator add region size properties
## Enhancement Task
In past, it will bury operator if it's running duration  exceeds  than 10 minutes, it can not work well if region size is big like 10GB. The timeout should depend on operator step and region's size. It is the first step to solve operator life cycle.
More detail is described at #4456

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?
Operator timeout will depend on region size not fixed value and close #4457.

### Check List

Tests

- Unit test

Code changes

Side effects

Related changes

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by nolouch** [comment]
plz describe you issue and PR clearly.

**Comment by disksing** [comment]
better to change title to `scheduler: add approximateSize property to operator struct`

**Review by disksing — APPROVED** [review]

**Review by lhy1024 — COMMENTED** [review]
Would you like to add more descriptions?

**Review by lhy1024 — COMMENTED** [review]
LGTM

**Review by lhy1024 — APPROVED** [review]

**Comment by rleungx** [comment]
We need more information before this PR is merged.

File: server/schedule/operator/operator.go [hunk 1]
```diff
@@ -363,3 +367,11 @@ func (o *Operator) GetAdditionalInfo() string {
 	}
 	return ""
 }
+
+// mock region default region size is 96Mb.
+const mockRegionSize = 96 * (1 << 20)
+
+// NewTestOperator creates a test operator.
+func NewTestOperator(desc, brief string, regionID uint64, regionEpoch *metapb.RegionEpoch, kind OpKind, steps ...OpStep) *Operator {
```
Comment (rleungx) [inline server/schedule/operator/operator.go:375]: Why do we need it?

File: server/schedule/operator/operator.go [hunk 2]
```diff
@@ -81,7 +83,9 @@ func (o *Operator) String() string {
 	for i := range o.steps {
 		stepStrs[i] = o.steps[i].String()
 	}
-	s := fmt.Sprintf("%s {%s} (kind:%s, region:%v(%v,%v), createAt:%s, startAt:%s, currentStep:%v, steps:[%s])", o.desc, o.brief, o.kind, o.regionID, o.regionEpoch.GetVersion(), o.regionEpoch.GetConfVer(), o.GetCreateTime(), o.GetStartTime(), atomic.LoadInt32(&o.currentStep), strings.Join(stepStrs, ", "))
+	s := fmt.Sprintf("%s {%s} (kind:%s, region:%v(%v,%v), createAt:%s, startAt:%s, currentStep:%v, size:%v，steps:[%s])",
```
Comment (rleungx) [inline server/schedule/operator/operator.go:86]:
```suggestion
	s := fmt.Sprintf("%s {%s} (kind:%s, region:%v(%v,%v), createAt:%s, startAt:%s, currentStep:%v, size:%v, steps:[%s])",
```

File: server/schedule/operator/operator.go (hunk 1 above)
Comment (bufferflies) [reply server/schedule/operator/operator.go:375]: This constructor of the operator is used for unit test, it will decrease works for unit test.

File: server/schedule/operator/operator.go [hunk 3]
```diff
@@ -363,3 +367,15 @@ func (o *Operator) GetAdditionalInfo() string {
 	}
 	return ""
 }
+
+// mock region default region size is 96Mb.
```
Comment (rleungx) [inline server/schedule/operator/operator.go:371]: MB?

File: server/schedule/operator/operator.go [hunk 4]
```diff
@@ -363,3 +367,15 @@ func (o *Operator) GetAdditionalInfo() string {
 	}
 	return ""
 }
+
+const (
```
Comment (rleungx) [inline server/schedule/operator/operator.go:371]: Please add a comment to emphasize these constants are only used for unit test.

**Review by rleungx — APPROVED** [review]
The rest LGTM.
