### PR TITLE
cache: lazy gc in ttl

### LINKED ISSUE #9047: goroutine leak: goroutine increase during the long-term operation
## Bug Report
The count of pd goroutine continue increase in long-term cluster

### What did you do?
Trigger condition: remove scheduler 

 ```
#/bin/bash

for i in $(seq 1 50); do
tiup ctl:v6.5.6 pd -u  http://127.0.0.1:2379 scheduler remove balance-leader-scheduler
sleep 10
tiup ctl:v6.5.6 pd -u  http://127.0.0.1:2379 scheduler add balance-leader-scheduler
sleep 20
done
```

Image

root cause: https://github.com/tikv/pd/blob/77d6f5b6785eb4e153495bf1c32b165019ae119e/server/cluster/coordinator.go#L696-L700

### What did you expect to see?

The count of goroutine is steady

### What version of PD are you using (`pd-server -V`)?
v6.5.6

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #9047  

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Manual test (add detailed scripts or steps below)

6.5.6 fixed 
image

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/cache/ttl.go [hunk 1]
```diff
@@ -63,7 +61,9 @@ func (c *ttlCache) put(key any, value any) {
 func (c *ttlCache) putWithTTL(key any, value any, ttl time.Duration) {
 	c.Lock()
 	defer c.Unlock()
-
+	if len(c.items) == 0 {
+		go c.doGC()
```
Comment (okJiang) [inline pkg/cache/ttl.go:65]: There is a possibility that when `len(items) == 0`, the old goroutine has not exited, but a new put request arrives, which can lead to multiple `goGC()` goroutines existing for the same structure.

Comment (bufferflies) [reply pkg/cache/ttl.go:65]: there is one lock，the previous must exit when the item queue is empty

Comment (okJiang) [reply pkg/cache/ttl.go:65]: It is possible during the gaps in gcInterval.

Comment (okJiang) [reply pkg/cache/ttl.go:65]: I understand now. The deletion can only be done through goGC, and the situation I mentioned will not occur.

**Review by okJiang — APPROVED** [review]

File: pkg/cache/ttl.go (hunk 1 above)
Comment (bufferflies) [reply pkg/cache/ttl.go:65]: you mean that the previous gc has deleted all items but not exit?

File: pkg/cache/ttl.go [hunk 2]
```diff
@@ -163,6 +163,11 @@ func (c *ttlCache) doGC() {
 					}
 				}
 			}
+			if len(c.items) == 0 {
```
Comment (rleungx) [inline pkg/cache/ttl.go:166]: How about `remove`?

Comment (bufferflies) [reply pkg/cache/ttl.go:166]: it doesn't matter, one gc interval will exit.

File: pkg/cache/ttl.go (hunk 1 above)
Comment (okJiang) [reply pkg/cache/ttl.go:65]: 1. remove all items(not through goGC)
2. put one item(a new goGC())
3. old goGC() tick

This situation can lead to unexpected goroutines.

File: pkg/cache/ttl.go (hunk 2 above)
Comment (bufferflies) [reply pkg/cache/ttl.go]: good catch, I have added one atomic flag to check the goroutine exist.

**Review by rleungx — APPROVED** [review]
