### PR TITLE
client: fix pd client panic

### LINKED ISSUE #6440: PD client panic if turnsing off c.option.initMetrics when creating a pd client?
### What did you do?
1. call `WithInitMetrics(false)` when creating pd client in tidb
2. start tidb

### What did you expect to see?
1. no panic

### What did you see instead?
1. panic

### PR DESCRIPTION
**Pull request by zeminzhou**
### What problem does this PR solve?

Issue Number: Close #6440

### What is changed and how does it work?

Initialize metrics, but do not register

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
1. change tidb code: call `WithInitMetrics(false)` when creating pd client.
2. start tidb cluster
3. curl http://127.0.0.1:10080/metrics
image

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: client/metrics.go [hunk 1]
```diff
@@ -23,6 +23,11 @@ import (
 // make sure register metrics only once
 var initialized int32
 
+func init() {
+	initMetrics(prometheus.Labels{})
+	initCmdDurations()
```
Comment (rleungx) [inline client/metrics.go:28]: Do we still need to call it inside `initAndRegisterMetrics`?

Comment (zeminzhou) [reply client/metrics.go:28]: yesh, if callers want to add const labels, we should reinitialize variables.

**Review by rleungx — APPROVED** [review]
