### PR TITLE
*: fix concurrent merge issue

### LINKED ISSUE #9332: Flaky TestOperatorControllerTestSuite/TestConcurrentMergeConflict
### Which jobs are failing

`TestOperatorControllerTestSuite/TestConcurrentMergeConflict`

### CI link

https://github.com/tikv/pd/actions/runs/15109152175/job/42464467110?pr=9331

### Reason for failure (if possible)

```shell
    operator_controller_test.go:541: 
        	Error Trace:	/home/runner/work/pd/pd/pkg/schedule/operator/operator_controller_test.go:541
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestOperatorControllerTestSuite/TestConcurrentMergeConflict
```

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9332. 

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/schedule/operator/operator_controller.go [hunk 1]
```diff
@@ -512,16 +512,43 @@ func isHigherPriorityOperator(new, old *Operator) bool {
...
+			return false
+		}
+		oc.counts.dec(oldOp.SchedulerKind())
+		oc.counts.inc(op.SchedulerKind())
+		oc.ack(oldOp)
+		if oldOp.Kind()&OpMerge != 0 {
+			oc.removeRelatedMergeOperator(oldOp)
+		}
+		_ = oldOp.Replace()
+		oc.buryOperator(oldOp)
```
Comment (lhy1024) [inline pkg/schedule/operator/operator_controller.go:545]: Do we need to call op.Start() for new op here?

Comment (rleungx) [reply pkg/schedule/operator/operator_controller.go:545]: nice catch

File: pkg/schedule/operator/operator_controller.go [hunk 2]
```diff
@@ -512,16 +512,41 @@ func isHigherPriorityOperator(new, old *Operator) bool {
...
+		if !isHigherPriorityOperator(op, oldOp) {
+			log.Debug("operator already exists with higher or equal priority",
+				zap.Uint64("region-id", regionID),
+				zap.Reflect("old", oldOp),
+				zap.Reflect("new", op))
+			operatorCounter.WithLabelValues(op.Desc(), "redundant").Inc()
+			return false
+		}
+		// replace old operator
+		if !oc.operators.CompareAndSwap(regionID, oldOp, op) {
```
Comment (lhy1024) [inline pkg/schedule/operator/operator_controller.go:530]: Time | Thread A (Mid Priority) | Thread B (High Priority) | Map State (regionID) | Explanation
-- | -- | -- | -- | --
T0 | (Not started) | (Not started) | OldOp (Low) | Initial state.
T1 |   | Calls addOperatorInner(HighOp) | OldOp | Thread B starts.
T2 |   | Calls LoadOrStore. Returns OldOp. | OldOp | Thread B sees the old operator.
T3 |   | Checks: HighOp > OldOp? YES. | OldOp | Thread B prepares to replace OldOp.
T4 | Calls addOperatorInner(MidOp) | (Paused / Context Switch) | OldOp | Thread A starts running concurrently.
T5 | Calls LoadOrStore. Returns OldOp. |   | OldOp | Thread A also sees the old operator.
T6 | Checks: MidOp > OldOp? YES. |   | OldOp | Thread A prepares to replace OldOp.
T7 | Executes CompareAndSwap  (OldOp, MidOp) -> Success |   | MidOp (Medium) | CRITICAL: Thread A wins the race. Map is updated.
T8 |   | Executes CompareAndSwap  (OldOp, HighOp) -> Fail | MidOp | Thread B tries to swap, but current value is MidOp, not OldOp.
T9 |   | Enters if !CAS block. | MidOp | Thread B detects the change.
T10 |   | Logs "operator changed" and Returns false. | MidOp | The Bug: Thread B gives up.
T11 | (Running MidOp) | HighOp is Leaked | MidOp |

Comment (rleungx) [reply pkg/schedule/operator/operator_controller.go:530]: add remove logic

File: pkg/schedule/operator/operator_controller.go [hunk 3]
```diff
@@ -651,10 +667,6 @@ func (oc *Controller) RemoveOperator(op *Operator, reasons ...CancelReasonType)
 }
 
 func (oc *Controller) removeOperatorWithoutBury(op *Operator) bool {
-	return oc.removeOperatorInner(op)
-}
-
-func (oc *Controller) removeOperatorInner(op *Operator) bool {
 	regionID := op.RegionID()
 	if cur, ok := oc.operators.Load(regionID); ok && cur.(*Operator) == op {
 		oc.operators.Delete(regionID)
```
Comment (lhy1024) [inline pkg/schedule/operator/operator_controller.go]: How about using CompareAndDelete to avoid delete other op

File: pkg/schedule/operator/operator_controller.go [hunk 4]
```diff
@@ -512,16 +512,43 @@ func isHigherPriorityOperator(new, old *Operator) bool {
...
+	if loaded {
+		// If there is an old operator and it has lower priority, replace it
+		oldOp := old.(*Operator)
+		if !isHigherPriorityOperator(op, oldOp) {
+			log.Debug("operator already exists with higher or equal priority",
+				zap.Uint64("region-id", regionID),
+				zap.Reflect("old", oldOp),
+				zap.Reflect("new", op))
+			operatorCounter.WithLabelValues(op.Desc(), "redundant").Inc()
+			return false
```
Comment (lhy1024) [inline pkg/schedule/operator/operator_controller.go:527]: Do we also need to remove op here? Since it's not added to the map, it might be leaked if we just return false

Comment (rleungx) [reply pkg/schedule/operator/operator_controller.go:527]: Done

File: pkg/schedule/operator/operator_controller.go [hunk 5]
```diff
@@ -512,16 +512,45 @@ func isHigherPriorityOperator(new, old *Operator) bool {
...
+				zap.Reflect("old", oldOp),
+				zap.Reflect("new", op))
+			_ = op.Cancel(AlreadyExist)
+			oc.buryOperator(op)
+			operatorCounter.WithLabelValues(op.Desc(), "redundant").Inc()
+			return false
+		}
+		// replace old operator
+		if !oc.operators.CompareAndSwap(regionID, oldOp, op) {
+			_ = op.Cancel()
```
Comment (lhy1024) [inline pkg/schedule/operator/operator_controller.go:531]:
```suggestion
			_ = op.Cancel(AlreadyExist)
```
How about adding a reason?

**Review by lhy1024 — COMMENTED** [review]
the rest LGTM

File: pkg/schedule/operator/operator_controller.go (hunk 5 above)
Comment (rleungx) [reply pkg/schedule/operator/operator_controller.go:531]: not belong to AlreadyExist?

Comment (lhy1024) [reply pkg/schedule/operator/operator_controller.go:531]: Do we need to add other reason for it?

Comment (lhy1024) [reply pkg/schedule/operator/operator_controller.go:531]: Do we need to add other reason for it?

Comment (rleungx) [reply pkg/schedule/operator/operator_controller.go:531]: Yes we can, maybe later?

**Review by lhy1024 — APPROVED** [review]

File: pkg/schedule/operator/operator_controller.go [hunk 6]
```diff
@@ -512,16 +512,45 @@ func isHigherPriorityOperator(new, old *Operator) bool {
...
+		}
+		_ = oldOp.Replace()
+		oc.buryOperator(oldOp)
 	}
 
+	oc.counts.inc(op.SchedulerKind())
+	// Now start the operator after successfully adding it to the map
 	if !op.Start() {
+		_ = oc.removeOperatorWithoutBury(op)
+		_ = op.Cancel(Unknown)
```
Comment (bufferflies) [inline pkg/schedule/operator/operator_controller.go]: How about creating a new reason for the start to fail?

File: pkg/schedule/operator/operator_controller.go [hunk 7]
```diff
@@ -512,16 +512,45 @@ func isHigherPriorityOperator(new, old *Operator) bool {
...
+		oc.counts.dec(oldOp.SchedulerKind())
+		oc.ack(oldOp)
+		if oldOp.Kind()&OpMerge != 0 {
+			oc.removeRelatedMergeOperator(oldOp)
+		}
+		_ = oldOp.Replace()
+		oc.buryOperator(oldOp)
 	}
 
+	oc.counts.inc(op.SchedulerKind())
```
Comment (bufferflies) [inline pkg/schedule/operator/operator_controller.go:548]: Is it done after starting success?

File: pkg/schedule/operator/operator_controller.go [hunk 8]
```diff
@@ -512,16 +512,45 @@ func isHigherPriorityOperator(new, old *Operator) bool {
...
+	// Now start the operator after successfully adding it to the map
 	if !op.Start() {
+		_ = oc.removeOperatorWithoutBury(op)
+		_ = op.Cancel(Unknown)
+		oc.buryOperator(op)
 		log.Error("adding operator with unexpected status",
```
Comment (bufferflies) [inline pkg/schedule/operator/operator_controller.go]: I think the log level should be warn

File: pkg/schedule/operator/operator_controller.go (hunk 7 above)
Comment (rleungx) [reply pkg/schedule/operator/operator_controller.go:548]: What do you mean?
