### PR TITLE
election, tso: fix data race in lease.go

### LINKED ISSUE #6378: TestMixedTSODeployment has random failures due to data race in lease
### Which jobs are failing
TestMixedTSODeployment
==================
WARNING: DATA RACE
Write at 0x00c008ac3838 by goroutine 482457:
  github.com/tikv/pd/pkg/election.(*lease).Grant()
      /Users/binshi/code/pingcap/my-pd/pkg/election/lease.go:67 +0x4b8
  github.com/tikv/pd/pkg/election.(*Leadership).Campaign()
      /Users/binshi/code/pingcap/my-pd/pkg/election/leadership.go:111 +0x214
  github.com/tikv/pd/pkg/member.(*EmbeddedEtcdMember).CampaignLeader()
      /Users/binshi/code/pingcap/my-pd/pkg/member/member.go:168 +0x228
  github.com/tikv/pd/server.(*Server).campaignLeader()
      /Users/binshi/code/pingcap/my-pd/server/server.go:1451 +0x198
  github.com/tikv/pd/server.(*Server).leaderLoop()
      /Users/binshi/code/pingcap/my-pd/server/server.go:1445 +0x9c0
  github.com/tikv/pd/server.(*Server).startServerLoop.func1()
      /Users/binshi/code/pingcap/my-pd/server/server.go:565 +0x34

Previous read at 0x00c008ac3838 by goroutine 488107:
  github.com/tikv/pd/pkg/election.(*lease).Close()
      /Users/binshi/code/pingcap/my-pd/pkg/election/lease.go:83 +0xc8
  github.com/tikv/pd/pkg/election.(*Leadership).Reset()
      /Users/binshi/code/pingcap/my-pd/pkg/election/leadership.go:236 +0xd0
  github.com/tikv/pd/pkg/member.(*EmbeddedEtcdMember).ResetLeader()
      /Users/binshi/code/pingcap/my-pd/pkg/member/member.go:249 +0x38
  github.com/tikv/pd/tests.(*TestServer).ResignLeader()
      /Users/binshi/code/pingcap/my-pd/tests/cluster.go:155 +0x9c
  github.com/tikv/pd/tests/integrations/tso.TestMixedTSODeployment.func1()
      /Users/binshi/code/pingcap/my-pd/tests/integrations/tso/client_test.go:270 +0xe8

### CI link
local run: 
under pd/tests/integrations/tso, run "make test"

### Reason for failure (if possible)
data race in lease.go. The log shown above is clear.

### PR DESCRIPTION
**Pull request by binshi-bing**
The data race happens when we call leadership.ResignLeader in test.

### What problem does this PR solve?

Issue Number: Close #6378

### What is changed and how does it work?

```commit-message
fix data race in lease.go
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/election/lease.go [hunk 1]
```diff
@@ -80,7 +80,11 @@ func (l *lease) Close() error {
 	// Try to revoke lease to make subsequent elections faster.
 	ctx, cancel := context.WithTimeout(l.client.Ctx(), revokeLeaseTimeout)
 	defer cancel()
-	l.lease.Revoke(ctx, l.ID)
+	var leaseID clientv3.LeaseID
+	if l.ID.Load() != nil {
+		leaseID = l.ID.Load().(clientv3.LeaseID)
+	}
```
Comment (lhy1024) [inline pkg/election/lease.go:86]: if l.ID is nil, what will happen? Do we need to add some tests about it?

Comment (binshi-bing) [reply pkg/election/lease.go:86]: if l.ID.Load() is nil, leaseID is initialized with the default value. Since clientv3.LeaseID is int64, so the initialized value is 0, which keeps exact the same as the existing logic.

**Review by lhy1024 — APPROVED** [review]

File: pkg/election/lease.go (hunk 1 above)
Comment (lhy1024) [reply pkg/election/lease.go:86]: ok, I see

**Review by nolouch — APPROVED** [review]
lgtm
