### PR TITLE
cluster: fix tso fallback due raft cluster did not stop tso service (part2)

### LINKED ISSUE #8889: pd client panics with "[tso] timestamp fallback"
### What did you do?

run jepson test

### What did you expect to see?

no panic

### What did you see instead?

pd client panics with "[tso] timestamp fallback"

### What version of PD are you using (`pd-server -V`)?

8.5

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #8889 ref #8477

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/cluster/cluster.go [hunk 1]
```diff
@@ -329,6 +329,19 @@ func (c *RaftCluster) Start(s Server) error {
 		return err
 	}
 	c.checkTSOService()
+	defer func() {
+		// We need to try to stop tso jobs when the cluster is not running.
+		// Ref: https://github.com/tikv/pd/issues/8836
+		if !c.running {
+			c.stopTSOJobsIfNeeded()
```
Comment (rleungx) [inline server/cluster/cluster.go:336]: Shall we check the error instead of running?

File: server/cluster/cluster.go [hunk 2]
```diff
@@ -329,6 +329,19 @@ func (c *RaftCluster) Start(s Server) error {
 		return err
 	}
 	c.checkTSOService()
+	defer func() {
+		// We need to try to stop tso jobs when the cluster is not running.
+		// Ref: https://github.com/tikv/pd/issues/8836
+		if !c.running {
```
Comment (lhy1024) [inline server/cluster/cluster.go:335]: I think it is better to check `runing` rather than error. Firstly,  we need to call `stopTSOJobsIfNeeded` whenever we return early, regardless of whether error is nil or not. Secondly, it prevents us from modifying the code later to return the error without assigning a value to it.

**Review by rleungx — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Comment by lhy1024** [comment]
/cherry-pick-release-8.5
