### PR TITLE
schedule: Add leader filter for scatter

### LINKED ISSUE #5622: Scatter can‘t work if the learner peer is not tiflash.
## Bug Report
In auto-dr scene , there are six replica for each region include 5 voter and 1 learner,.Then I use split region ,  all the operators are failed. 

The pd log:
```
[2022/10/19 13:55:38.529 +08:00] [DEBUG] [region_scatterer.go:349] ["fail to create scatter region operator"] [error="cannot transfer leader to 30: not voter"]
```

The root cause is that the select leade only consider the tiflash but the learner peer store may be tikv by placment rule. It should skip the peer that's learner and check the leader is satisfy the placement rule.

some related code:

https://github.com/tikv/pd/blob/7efef3170b4edecc9c0debe895753e5ffaff6986/server/schedule/region_scatterer.go#L437-L461

### What did you do?
split region

### What did you expect to see?
region peer and learner can be balanced in the cluster
### What did you see instead?
all scatter operator failed 
image

### What version of PD are you using (`pd-server -V`)?
master, 6.1.1,6.2.0

### PR DESCRIPTION
**Pull request by CabinfeverB**
Signed-off-by: Cabinfever_B <cabinfeveroier@gmail.com>

### What problem does this PR solve?

Issue Number: Close #5622

### What is changed and how does it work?
Add leader filter

```commit-message
schedule: Add leader filter for scatter
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/schedule/region_scatterer.go [hunk 1]
```diff
@@ -457,16 +457,22 @@ func (r *RegionScatterer) selectStore(group string, peer *metapb.Peer, sourceSto
...
+// the existed peers store depended on the leader counts in the group level. Please use this func before scatter spacial engines.
+func (r *RegionScatterer) selectAvailableLeaderStore(group string, region *core.RegionInfo, peers map[uint64]*metapb.Peer, context engineContext) uint64 {
+	sourceStore := r.cluster.GetStore(region.GetLeader().GetStoreId())
+	if sourceStore == nil {
+		log.Error("failed to get the store", zap.Uint64("store-id", region.GetLeader().GetStoreId()), errs.ZapError(errs.ErrGetSourceStore))
+		return 0
+	}
 	leaderCandidateStores := make([]uint64, 0)
+	// use PlacementLeaderSafeguard for con follower and learner in rule
+	filter := filter.NewPlacementLeaderSafeguard(r.name, r.cluster.GetOpts(), r.cluster.GetBasicCluster(), r.cluster.GetRuleManager(), region, sourceStore, false /*allowMoveLeader*/)
```
Comment (bufferflies) [inline server/schedule/region_scatterer.go:469]: I think the leader can move.

File: server/schedule/region_scatterer.go [hunk 2]
```diff
@@ -457,16 +457,22 @@ func (r *RegionScatterer) selectStore(group string, peer *metapb.Peer, sourceSto
...
 	for storeID := range peers {
 		store := r.cluster.GetStore(storeID)
 		if store == nil {
 			return 0
 		}
-		engine := store.GetLabelValue(core.EngineKey)
-		if len(engine) < 1 {
+		if filter == nil || filter.Target(r.cluster.GetOpts(), store).IsOK() {
```
Comment (bufferflies) [inline server/schedule/region_scatterer.go:475]: why check the filter is nil?

Comment (CabinfeverB) [reply server/schedule/region_scatterer.go:475]: because if placementrule is disabled, filter will be nil.

File: server/schedule/region_scatterer_test.go [hunk 3]
```diff
@@ -569,6 +569,75 @@ func TestRegionFromDifferentGroups(t *testing.T) {
...
+				Key:    "zone",
+				Op:     placement.In,
+				Values: []string{"z2"},
+			},
+		},
+	})
+	scatterer := NewRegionScatterer(ctx, tc, oc)
+	regionCount := 50
+	for i := 1; i <= regionCount; i++ {
+		scatterer.Scatter(tc.AddRegionWithLearner(uint64(i), uint64(1), []uint64{uint64(2), uint64(3)}, []uint64{7}), fmt.Sprintf("t%d", i))
```
[the remark this answers is not in the document]
Comment (CabinfeverB) [reply server/schedule/region_scatterer_test.go:618]: I can' check whether the operator is nil, if `isSameDistribution` is true, it will return nil.

[the remark this answers is not in the document]
Comment (CabinfeverB) [reply server/schedule/region_scatterer_test.go:618]: I can the check function, PTAL

**Review by bufferflies — APPROVED** [review]

File: server/schedule/region_scatterer.go [hunk 4]
```diff
@@ -337,9 +337,10 @@ func (r *RegionScatterer) scatterRegion(region *core.RegionInfo, group string) *
 	// FIXME: target leader only considers the ordinary stores, maybe we need to consider the
 	// special engine stores if the engine supports to become a leader. But now there is only
 	// one engine, tiflash, which does not support the leader, so don't consider it for now.
-	targetLeader := r.selectAvailableLeaderStore(group, targetPeers, r.ordinaryEngine)
+	targetLeader := r.selectAvailableLeaderStore(group, region, targetPeers, r.ordinaryEngine)
 	if targetLeader == 0 {
 		scatterCounter.WithLabelValues("no-leader", "").Inc()
+		fmt.Println("no-leader")
```
Comment (nolouch) [inline server/schedule/region_scatterer.go:343]: remove it

**Review by rleungx — APPROVED** [review]
