### PR TITLE
tso: sync timestamp once before the first serving

### LINKED ISSUE #7015: TestMixedTSODeployment failed again
### CI link
https://github.com/tikv/pd/actions/runs/6023573258/job/16340590837
https://github.com/tikv/pd/actions/runs/6022180459/job/16336412853

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: Close #7015.

### What is changed and how does it work?

```commit-message
Sync the timestamp once before the first serving to make sure that the TSO is the latest one from the storage,
which could prevent the potential fallback caused by the rolling update of the mixed PD and TSO service.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Review by lhy1024 — COMMENTED** [review]
TestTSOProxyTestSuite failed

File: pkg/tso/keyspace_group_manager.go [hunk 1]
```diff
@@ -146,6 +153,43 @@ func (s *state) getDeletedGroupNum() int {
...
+	s.RLock()
+	_, ok := s.requestedGroups[groupID]
+	s.RUnlock()
+	if ok {
+		return nil
+	}
+	s.Lock()
+	defer s.Unlock()
+	// Double check if the keyspace group has been marked as requested.
+	if _, ok := s.requestedGroups[groupID]; ok {
```
Comment (rleungx) [inline pkg/tso/keyspace_group_manager.go:183]: Is it necessary to double check it?

File: tests/integrations/tso/client_test.go [hunk 2]
```diff
@@ -436,7 +436,7 @@ func TestMixedTSODeployment(t *testing.T) {
 
 	ctx1, cancel1 := context.WithCancel(context.Background())
 	var wg sync.WaitGroup
-	checkTSO(ctx1, re, &wg, backendEndpoints, pd.WithAllowTSOFallback() /* It's expected that the timestamp fallback happens here */)
```
Comment (rleungx) [inline tests/integrations/tso/client_test.go:439]: Do we still need WithAllowTSOFallback?

Comment (JmPotato) [reply tests/integrations/tso/client_test.go:439]: Removed.

File: pkg/tso/keyspace_group_manager.go (hunk 1 above)
Comment (JmPotato) [reply pkg/tso/keyspace_group_manager.go:183]: I think this may happen in the case of high concurrency. Double checking can reduce the possibility of etcd transaction conflicts in sync timestamp.

Comment (JmPotato) [reply pkg/tso/keyspace_group_manager.go:183]: Just to avoid the unnecessary operation as much as possible on the TSO hot path.

**Review by rleungx — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]
