### PR TITLE
resource_manager/client: Don't set token as `-1` in burstable mode 

### LINKED ISSUE #6209: Exceeded resource group quota limitation when switching burstable twice
## Bug Report

ref https://github.com/pingcap/tidb/issues/42492

### What did you do?
Enable BURSTABLE of resource group, run workload for this resource group. Stop the workload and wait a while. Disable BURSTABLE, and run workload again.

### What did you expect to see?
Run workload normally.
### What did you see instead?
mysql_stmt_execute() returned error 8252 (Exceeded resource group quota limitation)

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by CabinfeverB**
### What problem does this PR solve?

Issue Number: Close #6209

### What is changed and how does it work?
Before this PR, the token of limiter is set to `-1` in burst mode. But ref #6209, after stopping workload, the avg will be zore. So the required token will be zero. If we disable burstable, the token and fillratre are both zero, so workload can not run.
This PR block token refill when in burstable mode and keep the token as FillRate.

```commit-message
```

### Check List

Tests

- Integration test
- Manual test (add detailed scripts or steps below)
1.  mysql> alter resource group rg1 RU_PER_SEC=10000 BURSTABLE;
image
2. run sysbench and kill it.
image
3. wait 1 minute and alter resource group rg1 RU_PER_SEC=1000;
image
4. run sysbench again.

### Release note

```release-note
None.
```

### CODE REVIEW

File: client/resource_group/controller/controller.go [hunk 1]
```diff
@@ -798,9 +806,9 @@ func (gc *groupCostController) applyBasicConfigForRUTokenCounters() {
 		counter.inDegradedMode = true
 		initCounterNotify(counter)
 		var cfg tokenBucketReconfigureArgs
-		fillRate := getRUTokenBucketSetting(gc.ResourceGroup, typ)
-		cfg.NewBurst = int64(fillRate.Settings.FillRate)
-		cfg.NewRate = float64(fillRate.Settings.FillRate)
+		tb := counter.getTokenBucketFunc()
```
Comment (HuSharp) [inline client/resource_group/controller/controller.go:809]: maybe can directly get fillrate?

File: client/resource_group/controller/controller.go [hunk 2]
```diff
@@ -810,15 +818,15 @@ func (gc *groupCostController) applyBasicConfigForRUTokenCounters() {
...
+	for _, counter := range gc.run.resourceTokens {
 		if !counter.limiter.IsLowTokens() {
 			continue
 		}
 		initCounterNotify(counter)
 		var cfg tokenBucketReconfigureArgs
-		fillRate := getRawResourceTokenBucketSetting(gc.ResourceGroup, typ)
-		cfg.NewBurst = int64(fillRate.Settings.FillRate)
-		cfg.NewRate = float64(fillRate.Settings.FillRate)
+		tb := counter.getTokenBucketFunc()
```
Comment (HuSharp) [inline client/resource_group/controller/controller.go:827]: ditto

File: client/resource_group/controller/limiter.go [hunk 3]
```diff
@@ -296,18 +298,23 @@ func (lim *Limiter) Reconfigure(now time.Time,
...
+	if args.NewBurst < 0 {
+		lim.tokens = args.NewTokens
+	} else {
+		now, _, tokens := lim.advance(now)
+		lim.last = now
+		lim.tokens = tokens + args.NewTokens
+	}
 	lim.limit = Limit(args.NewRate)
 	lim.burst = args.NewBurst
+	_, _, lim.tokens = lim.advance(now)
```
Comment (nolouch) [inline client/resource_group/controller/limiter.go:311]: why not advance before `lim.last = now`?

Comment (CabinfeverB) [reply client/resource_group/controller/limiter.go:311]: I was trying to avoid accumulating too many tokens when burst is -1. Because the first `advance` was before the burst changes, we want to `advance` after the burst changes.
But I feel this worry is unnecessary, I will delete this line

File: client/resource_group/controller/controller.go (hunk 1 above)
Comment (CabinfeverB) [reply client/resource_group/controller/controller.go]: fix

File: client/resource_group/controller/controller.go [hunk 4]
```diff
@@ -843,10 +861,9 @@ func (gc *groupCostController) modifyTokenCounter(counter *tokenCounter, bucket
 		cfg.NewTokens = granted
 		cfg.NewRate = float64(bucket.GetSettings().FillRate)
 		counter.lastDeadline = time.Time{}
-		cfg.NotifyThreshold = math.Min(granted+counter.limiter.AvailableTokens(gc.run.now), counter.avgRUPerSec*float64(defaultTargetPeriod)) * notifyFraction
-		// In the non-trickle case, clients can be allowed to accumulate more tokens.
-		if cfg.NewBurst >= 0 {
-			cfg.NewBurst = 0
+		cfg.NotifyThreshold = math.Min((granted+counter.limiter.AvailableTokens(gc.run.now)), counter.avgRUPerSec*defaultTargetPeriod.Seconds()) * notifyFraction
+		if cfg.NewBurst < 0 {
```
Comment (nolouch) [inline client/resource_group/controller/controller.go:865]:
```suggestion
		if cfg.NewBurst <= 0 {
```
if NewBurst is zero, is it reasonable to reset the tokens  in client side?

**Review by nolouch — APPROVED** [review]
lgtm

File: client/resource_group/controller/controller.go (hunk 4 above)
Comment (CabinfeverB) [reply client/resource_group/controller/controller.go:865]: It's not reasonable. if NewBurst is zero, the tokens of the client should be allocated by the server

File: tests/mcs/resource_manager/resource_manager_test.go [hunk 5]
```diff
@@ -334,6 +334,114 @@ func (suite *resourceManagerClientTestSuite) TestResourceGroupController() {
 	controller.Stop()
 }
 
+// TestSwitchBurst is used to test https://github.com/tikv/pd/issue/6209
```
Comment (HuSharp) [inline tests/mcs/resource_manager/resource_manager_test.go:337]: https://github.com/tikv/pd/issues/6209
`issues` miss a `s` :)

File: client/resource_group/controller/controller.go [hunk 6]
```diff
@@ -843,10 +861,9 @@ func (gc *groupCostController) modifyTokenCounter(counter *tokenCounter, bucket
 		cfg.NewTokens = granted
 		cfg.NewRate = float64(bucket.GetSettings().FillRate)
 		counter.lastDeadline = time.Time{}
-		cfg.NotifyThreshold = math.Min(granted+counter.limiter.AvailableTokens(gc.run.now), counter.avgRUPerSec*float64(defaultTargetPeriod)) * notifyFraction
-		// In the non-trickle case, clients can be allowed to accumulate more tokens.
-		if cfg.NewBurst >= 0 {
-			cfg.NewBurst = 0
+		cfg.NotifyThreshold = math.Min((granted+counter.limiter.AvailableTokens(gc.run.now)), counter.avgRUPerSec*defaultTargetPeriod.Seconds()) * notifyFraction
```
Comment (HuSharp) [inline client/resource_group/controller/controller.go:864]: redundant braket

File: client/resource_group/controller/limiter.go [hunk 7]
```diff
@@ -296,18 +298,22 @@ func (lim *Limiter) Reconfigure(now time.Time,
 ) {
 	lim.mu.Lock()
 	defer lim.mu.Unlock()
-	log.Debug("[resource group controller] before reconfigure", zap.Float64("NewTokens", lim.tokens), zap.Float64("NewRate", float64(lim.limit)), zap.Float64("NotifyThreshold", args.NotifyThreshold))
-	now, _, tokens := lim.advance(now)
-	lim.last = now
-	lim.tokens = tokens + args.NewTokens
+	log.Debug("[resource group controller] before reconfigure", zap.Float64("NewTokens", lim.tokens), zap.Float64("NewRate", float64(lim.limit)), zap.Float64("NotifyThreshold", args.NotifyThreshold), zap.Int64("burst", lim.burst))
+	if args.NewBurst < 0 {
+		lim.tokens = args.NewTokens
```
Comment (HuSharp) [inline client/resource_group/controller/limiter.go:303]: The annotation for the limiter field `now` is `last is the last time the token field of the limiter was updated`
So for this change do we need to update comment or  Will this cause some unexpect behavior?

**Review by HuSharp — APPROVED** [review]
REST LGTM!

File: client/resource_group/controller/limiter.go (hunk 7 above)
Comment (CabinfeverB) [reply client/resource_group/controller/limiter.go:303]: I changed it and will update `last` here as well

**Review by JmPotato — APPROVED** [review]
