### PR TITLE
tests: retry when address already in use

### LINKED ISSUE #8511: test: tests fail because bind address already in use
### Which jobs are failing
```
2024-08-09T10:13:43.8843538Z     member_test.go:339: 
2024-08-09T10:13:43.8844726Z         	Error Trace:	/home/runner/work/pd/pd/tests/server/member/member_test.go:339
2024-08-09T10:13:43.8845893Z         	Error:      	Received unexpected error:
2024-08-09T10:13:43.8848471Z         	            	[PD:etcd:ErrStartEtcd]listen tcp 127.0.0.1:41903: bind: address already in use: listen tcp 127.0.0.1:41903: bind: address already in use
2024-08-09T10:13:43.8850327Z         	            	github.com/pingcap/errors.AddStack
2024-08-09T10:13:43.8853049Z         	            		/home/runner/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174
2024-08-09T10:13:43.8855194Z         	            	github.com/pingcap/errors.(*Error).GenWithStackByCause
2024-08-09T10:13:43.8857807Z         	            		/home/runner/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:307
2024-08-09T10:13:43.8859576Z         	            	github.com/tikv/pd/server.(*Server).startEtcd
2024-08-09T10:13:43.8861027Z         	            		/home/runner/work/pd/pd/server/server.go:331
2024-08-09T10:13:43.8862268Z         	            	github.com/tikv/pd/server.(*Server).Run
2024-08-09T10:13:43.8863652Z         	            		/home/runner/work/pd/pd/server/server.go:620
2024-08-09T10:13:43.8864960Z         	            	github.com/tikv/pd/tests.(*TestServer).Run
2024-08-09T10:13:43.8866351Z         	            		/home/runner/work/pd/pd/tests/cluster.go:127
2024-08-09T10:13:43.8867570Z         	            	github.com/tikv/pd/tests.RunServer.func1
2024-08-09T10:13:43.8868949Z         	            		/home/runner/work/pd/pd/tests/cluster.go:577
2024-08-09T10:13:43.8869927Z         	            	runtime.goexit
2024-08-09T10:13:43.8871403Z         	            		/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/asm_amd64.s:1650
2024-08-09T10:13:43.8872714Z         	            	github.com/tikv/pd/tests.RunServers
2024-08-09T10:13:43.8874084Z         	            		/home/runner/work/pd/pd/tests/cluster.go:589
2024-08-09T10:13:43.8875673Z         	            	github.com/tikv/pd/tests.(*TestCluster).RunInitialServers
2024-08-09T10:13:43.8877146Z         	            		/home/runner/work/pd/pd/tests/cluster.go:601
2024-08-09T10:13:43.8878866Z         	            	github.com/tikv/pd/tests/server/member_test.TestCampaignLeaderFrequently
2024-08-09T10:13:43.8880777Z         	            		/home/runner/work/pd/pd/tests/server/member/member_test.go:338
2024-08-09T10:13:43.8881875Z         	            	testing.tRunner
2024-08-09T10:13:43.8883380Z         	            		/opt/hostedtoolcache/go/1.21.12/x64/src/testing/testing.go:1595
2024-08-09T10:13:43.8884428Z         	            	runtime.goexit
2024-08-09T10:13:43.8885826Z         	            		/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/asm_amd64.s:1650
2024-08-09T10:13:43.8886856Z         	Test:       	TestCampaignLeaderFrequently
```

### CI link
https://github.com/tikv/pd/actions/runs/10317426723/job/28561957825?pr=8510

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #8511.

### What is changed and how does it work?

```
[2026/01/19 10:39:07.054 +08:00] [WARN] [cluster.go:665] ["etcd start failed, will retry"] [error="[PD:etcd:ErrStartEtcd]listen tcp 127.0.0.1:43255: bind: address already in use: listen tcp 127.0.0.1:43255: bind: address already in use"]
[2026/01/19 10:39:07.055 +08:00] [WARN] [cluster.go:665] ["etcd start failed, will retry"] [error="[PD:etcd:ErrStartEtcd]listen tcp 127.0.0.1:43255: bind: address already in use: listen tcp 127.0.0.1:43255: bind: address already in use"]
    client_test.go:896: 
        	Error Trace:	/home/prow/go/src/github.com/tikv/pd/tests/integrations/client/client_test.go:896
        	            				/home/prow/go/src/github.com/tikv/pd/tests/integrations/client/router_client_test.go:73
        	            				/home/prow/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:157
        	            				/home/prow/go/src/github.com/tikv/pd/tests/integrations/client/router_client_test.go:46
        	Error:      	Received unexpected error:
        	            	[PD:etcd:ErrStartEtcd]listen tcp 127.0.0.1:43255: bind: address already in use: listen tcp 127.0.0.1:43255: bind: address already in use
```

We do have a retry when the address is already in use, but we use the same port, which is useless.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

## Summary by CodeRabbit

* **New Features**
  * Test cluster startup now retries on port/address conflicts: ports are reallocated and servers recreated to recover while preserving original services and options.
  * Added configurable retry limits and backoff to improve automated recovery when startup conflicts occur.

* **Chores**
  * Test infrastructure now retains startup context and initial configuration to support reliable restart flows and clearer errors when retries are exhausted.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: tests/cluster.go [hunk 1]
```diff
@@ -643,11 +649,91 @@ func RunServers(servers []*TestServer) error {
 
 // RunInitialServers starts to run servers in InitialServers.
 func (c *TestCluster) RunInitialServers() error {
-	servers := make([]*TestServer, 0, len(c.config.InitialServers))
-	for _, conf := range c.config.InitialServers {
-		servers = append(servers, c.GetServer(conf.Name))
+	return c.RunInitialServersWithRetry(3)
```
Comment (JmPotato) [inline tests/cluster.go]: How about defining a constant to make it easier to locate and adjust the retry times later?

File: tests/cluster.go [hunk 2]
```diff
@@ -643,11 +649,91 @@ func RunServers(servers []*TestServer) error {
...
+			backoff := time.Duration(i+1) * 500 * time.Millisecond
+			if backoff > 3*time.Second {
+				backoff = 3 * time.Second
+			}
+			time.Sleep(backoff)
+			continue
+		}
+
+		// For non-port-conflict errors, use regular retry
+		if strings.Contains(lastErr.Error(), "ErrStartEtcd") {
```
Comment (JmPotato) [inline tests/cluster.go]: Using a `switch` statement for different `lastErr` values seems clearer.

File: tests/cluster.go (hunk 1 above)
Comment (rleungx) [reply tests/cluster.go]: done

File: tests/cluster.go [hunk 3]
```diff
@@ -643,11 +652,87 @@ func RunServers(servers []*TestServer) error {
...
+
+				// Use the original opts passed during cluster creation
+				allOpts := append([]ConfigOption{WithGCTuner(false)}, c.opts...)
+				serverConf, err := conf.Generate(allOpts...)
+				if err != nil {
+					return err
+				}
+
+				// Use the original services passed during cluster creation
+				s, err := NewTestServer(context.Background(), serverConf, c.services)
```
Comment (lhy1024) [inline tests/cluster.go]: how about using c.ctx?

Comment (rleungx) [reply tests/cluster.go]: done

File: tests/cluster.go
Comment (JmPotato) [inline tests/cluster.go:744]: This function is no longer used, we should removed it then.

File: tests/cluster.go [hunk 4]
```diff
@@ -643,11 +654,87 @@ func RunServers(servers []*TestServer) error {
...
 // RunInitialServers starts to run servers in InitialServers.
 func (c *TestCluster) RunInitialServers() error {
-	servers := make([]*TestServer, 0, len(c.config.InitialServers))
-	for _, conf := range c.config.InitialServers {
-		servers = append(servers, c.GetServer(conf.Name))
+	return c.RunInitialServersWithRetry(defaultMaxRetryTimes)
+}
+
+// RunInitialServersWithRetry starts to run servers with port conflict handling.
+func (c *TestCluster) RunInitialServersWithRetry(maxRetries int) error {
```
Comment (JmPotato) [inline tests/cluster.go]:
```suggestion
func (c *TestCluster) runInitialServersWithRetry(maxRetries int) error {
```

File: tests/cluster.go
Comment (rleungx) [reply tests/cluster.go:744]: There is another test still relying on it.

**Review by JmPotato — APPROVED** [review]
