### PR TITLE
api: stop forwarding /ready to the leader

### LINKED ISSUE #9286: /ready API should never be forwarded to the leader
## Bug Report

`/ready` API was added to return whether pd follower is ready to became leader: https://github.com/tikv/pd/blob/7c3b9a35139dc404f0782f8300d8d3f04c65aa17/server/apiv2/handlers/ready.go#L36 It should never be forwarded to the leader. 

Right now it returns `true` even if regions are not loaded and it won't be ready to serve regions if promoted to the leader.

### What did you do?

Restart a follower and issue `/ready` request right away while regions were still not loaded by the follower.

### What did you expect to see?

Follower should always evaluate readiness locally w/o forwarding it to the leader. `/ready` should return `false` until regions are loaded.

### What did you see instead?

Follower forwarded `/ready` request to leader and returned `true`.

### What version of PD are you using (`pd-server -V`)?

```
Release Version: v9.0.0-beta.1.pre-99-gde4bc50f
Edition: Community
Git Commit Hash: de4bc50fa42d4d54aff2d76d66ded08f41f62492
```

### PR DESCRIPTION
**Pull request by Tema**
### What problem does this PR solve?

Issue Number: Close #9286

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/apiv2/router.go [hunk 1]
```diff
@@ -51,9 +51,9 @@ func NewV2Handler(_ context.Context, svr *server.Server) (http.Handler, apiutil.
 		c.Set(middlewares.ServerContextKey, svr)
 		c.Next()
 	})
-	router.Use(middlewares.Redirector())
 	root := router.Group(apiV2Prefix)
 	root.GET("ready", handlers.Ready)
+	root.Use(middlewares.Redirector())
```
Comment (lhy1024) [inline server/apiv2/router.go:56]: How about adding a comment such as `Register /ready endpoint before Redirector middleware to exclude it from redirection logic?

**Review by lhy1024 — APPROVED** [review]
LGTM

**Review by rleungx — APPROVED** [review]
