### PR TITLE
region_scatter: fix a bug that PD may panic when scatter region if region is unhealthy

### LINKED ISSUE #6099: v6.5.1 lightning import data to master fail for pd reset the connection
### What did you do?

tidb cluster upgrade from 6.0.0 to 6.5.1-pre
import data to 6.0.0 cluster using 6.5.1 lightning

### What did you expect to see?
import success
### What did you see instead?
import fail
print many warning:
{"level":"warn","ts":"2023-03-07T03:08:03.956Z","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000c22380/src-tidb-pd.fb-testbed-comp-2nrpj:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = "transport: Error while dialing dial tcp 10.244.7.55:2379: connect: connection refused""}

### What version of PD are you using (`pd-server -V`)?
v6.5.1-pre

### PR DESCRIPTION
**Pull request by HunDunDM**
### What problem does this PR solve?

Issue Number: Close #6099 

### What is changed and how does it work?

region_scatter: fix a bug that PD may panic when scatter region if region is unhealthy

### Check List

Tests

- Unit test

Code changes

Side effects

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
Fix a bug that PD may panic when scatter region if region is unhealthy
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

File: server/schedule/region_scatterer.go [hunk 1]
```diff
@@ -406,12 +406,14 @@ func allowLeader(fit *placement.RegionFit, peer *metapb.Peer) bool {
 	if peer.IsWitness {
 		return false
 	}
-
-	rule := fit.GetRuleFit(peer.GetId()).Rule
-	if rule.IsWitness {
+	peerFit := fit.GetRuleFit(peer.GetId())
+	if peerFit == nil || peerFit.Rule == nil {
```
Comment (bufferflies) [inline server/schedule/region_scatterer.go:410]: why not add one condition `peerFit.Rule.IsWitness`?
