### PR TITLE
scheduler: fix panic in grant hot region scheduler

### LINKED ISSUE #8933: pd meet panic after adding grant-hot-region-scheduler
### What did you do?

add grant-hot-region-scheduler

### What did you expect to see?

work normal

### What did you see instead?

meet panic

```
[2024/12/18 10:10:46.625 +00:00] [FATAL] [log.go:87] [panic] [recover="\"invalid memory address or nil pointer dereference\""] [stack="github.com/tikv/pd/pkg/utils/logutil.LogPanic\n\t/workspace/source/pd/pkg/utils/logutil/log.go:87\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:914\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:861\ngithub.com/tikv/pd/pkg/schedule/operator.(*Operator).SetPriorityLevel\n\t/workspace/source/pd/pkg/schedule/operator/operator.go:407\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*grantHotRegionScheduler).transfer\n\t/workspace/source/pd/pkg/schedule/schedulers/grant_hot_region.go:359\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*grantHotRegionScheduler).randomSchedule\n\t/workspace/source/pd/pkg/schedule/schedulers/grant_hot_region.go:298\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*grantHotRegionScheduler).dispatch\n\t/workspace/source/pd/pkg/schedule/schedulers/grant_hot_region.go:277\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*grantHotRegionScheduler).Schedule\n\t/workspace/source/pd/pkg/schedule/schedulers/grant_hot_region.go:263\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*ScheduleController).Schedule\n\t/workspace/source/pd/pkg/schedule/schedulers/scheduler_controller.go:469\ngithub.com/tikv/pd/pkg/schedule/schedulers.(*Controller).runScheduler\n\t/workspace/source/pd/pkg/schedule/schedulers/scheduler_controller.go:356"]
```

### What version of PD are you using (`pd-server -V`)?
release-8.1

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #8933

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by okJiang — APPROVED** [review]

File: pkg/schedule/schedulers/grant_hot_region.go [hunk 1]
```diff
@@ -318,6 +318,10 @@ func (s *grantHotRegionScheduler) transfer(cluster sche.SchedulerCluster, region
 	} else {
 		op, err = operator.CreateMovePeerOperator(s.GetName()+"-move", cluster, srcRegion, operator.OpRegion|operator.OpLeader, srcStore.GetID(), dstStore)
 	}
+	if err != nil {
+		log.Error("fail to create grant hot leader operator", errs.ZapError(err))
```
Comment (rleungx) [inline pkg/schedule/schedulers/grant_hot_region.go:322]: use debug level?

**Review by rleungx — APPROVED** [review]
