### PR TITLE
scheduler: fix evict leader scheduler remains

### LINKED ISSUE #9908: Evict leader scheduler may remain
### What did you do?

Execute add/remove multiple times.

### What did you expect to see?

evict leader scheduler is removed

### What did you see instead?

```
pd-ctl -u https://127.0.0.1:2379 scheduler config evict-leader-scheduler
{
  "store-id-ranges": {},
  "batch": 3
}
```

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9908

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/schedule/schedulers/evict_leader_test.go [hunk 1]
```diff
@@ -19,6 +19,8 @@ import (
 	"encoding/json"
 	"testing"
 
+	"github.com/pingcap/errors"
```
Comment (lhy1024) [inline pkg/schedule/schedulers/evict_leader_test.go]: please fix ci

**Review by lhy1024 — APPROVED** [review]
