### PR TITLE
tests: fix `TestPreparingProgress`

### LINKED ISSUE #9607: Panic in TestPreparingProgress
### Which jobs are failing

TestPreparingProgress

### CI link

https://github.com/tikv/pd/actions/runs/16645458912/job/47104946875?pr=9606

### Reason for failure (if possible)

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x44c0365]

goroutine 460356 [running]:
github.com/tikv/pd/tests/server/api.TestPreparingProgress.func7()
	/home/runner/work/pd/pd/tests/server/api/api_test.go:1189 +0xa5
github.com/stretchr/testify/assert.Eventually.func1()
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x34
created by github.com/stretchr/testify/assert.Eventually in goroutine 254
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x3d6
run all tasks takes 4m49.115057088s
make: *** [Makefile:266: ci-test-job] Error 1
```

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9607.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/server/api/api_test.go [hunk 1]
```diff
@@ -1159,8 +1164,16 @@ func TestPreparingProgress(t *testing.T) {
 		tests.MustPutStore(re, cluster, store)
 	}
 
+	re.NotEmpty(cluster.WaitLeader())
+	leader = cluster.GetLeaderServer()
```
Comment (lhy1024) [inline tests/server/api/api_test.go:1168]: Is it necessary? We have checked the leader in L1144-1148

Comment (rleungx) [reply tests/server/api/api_test.go:1168]: The leader may be dropped due to the environmental issue.
