### PR TITLE
mcs: fix panic of GetMinTS

### LINKED ISSUE #7528: GetMinTS panic when there is a network problem
## Bug Report

Screen Shot 2023-12-12 at 11 28 30 AM

https://github.com/tikv/pd/blob/fcdeec42aa9a9033c576083c1571dcd264d068c8/server/grpc_service.go#L345
If there is some problem that causes index 0 to fail to receive the response, but index 1 receives it. https://github.com/tikv/pd/blob/fcdeec42aa9a9033c576083c1571dcd264d068c8/server/grpc_service.go#L362 
It might panic.

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #7528.

### What is changed and how does it work?

Revert part changes of #7014.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/grpc_service.go [hunk 1]
```diff
@@ -328,11 +328,11 @@ func (s *GrpcServer) GetMinTSFromTSOService(dcLocation string) (*pdpb.Timestamp,
 
 	// Get the minimal timestamp from the TSO servers/pods
 	var mutex syncutil.Mutex
-	resps := make([]*tsopb.GetMinTSResponse, len(addrs))
+	resps := make([]*tsopb.GetMinTSResponse, 0)
```
Comment (lhy1024) [inline server/grpc_service.go:331]: How about adding some comments to avoid similar modify?

**Review by lhy1024 — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]
