### PR TITLE
*: fix panic that region may not exist

### LINKED ISSUE #6456: pd panicked during jepsen tests
### What did you do?

run jepsen test

### What did you expect to see?

No panic.

### What did you see instead?

```
[2023/05/12 04:48:33.834 +00:00] [FATAL] [log.go:87] [panic] [recover="\"invalid memory address or nil pointer dereference\""] [stack="github.com/tikv/pd/pkg/utils/logutil.LogPanic\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/utils/logutil/log.go:87\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:260\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:837\ngithub.com/tikv/pd/pkg/core.(*RegionInfo).GetStartKey\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/core/region.go:605\ngithub.com/tikv/pd/pkg/schedule/labeler.(*RegionLabeler).GetRegionLabel\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/schedule/labeler/labeler.go:279\ngithub.com/tikv/pd/pkg/schedule/labeler.(*RegionLabeler).ScheduleDisabled\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/pkg/schedule/labeler/labeler.go:300\ngithub.com/tikv/pd/server/cluster.(*scheduleController).Schedule\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/cluster/coordinator.go:907\ngithub.com/tikv/pd/server/cluster.(*coordinator).runScheduler\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/cluster/coordinator.go:809"]
```

The full logs can be found [here](https://test-infra-minio.pingcap.net:30009/argo/2023-05-12/plan-exec-1710308-re0/plan-exec-1710308-re0-1548184512/archive.tgz).

### What version of PD are you using (`pd-server -V`)?

master b159dd2df37c8da4c001ec176b4df706a78ea2bb

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #6456.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: server/cluster/coordinator.go [hunk 1]
```diff
@@ -902,9 +902,14 @@ func (s *scheduleController) Schedule(diagnosable bool) []*operator.Operator {
 			s.diagnosticRecorder.setResultFromPlans(ops, plans)
 		}
 		foundDisabled := false
-		for _, op := range ops {
+		for i, op := range ops {
 			if labelMgr := s.cluster.GetRegionLabeler(); labelMgr != nil {
-				if labelMgr.ScheduleDisabled(s.cluster.GetRegion(op.RegionID())) {
+				region := s.cluster.GetRegion(op.RegionID())
+				if region == nil {
+					ops = append(ops[:i], ops[i+1:]...)
```
Comment (nolouch) [inline server/cluster/coordinator.go:909]:
```
 runtime error: slice bounds out of range [2:1] [recovered]
 ```
it will out bounds after deleting a item if there len(ops) >= 2.

**Review by lhy1024 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
