### PR TITLE
hotfix: add failed_regions_id for scatter regions response (#9167) 

### LINKED ISSUE #9088: `ScatterRegions` not returning which region(s) are failed to scatter
### What did you do?

`ScatterRegions` not returning which region(s) are failed to scatter. br/lightning now will prefer `ScatterRegions` to do  region scatter for performance reason, but if some regions failed to scatter for reasons like `region %d is not fully replicated`, it will also return success and only give a percentage of success regions, but doesn't tell client which failed. currently br/lightning will take this as success, and will move on, and cause region/data skew.

br/lightning have retry on scatter, but need PD returns which regions have failed

https://github.com/tikv/pd/blob/2bbeb9c97141c0f16d99d407b97c2d2366adfd38/pkg/mcs/scheduling/server/grpc_service.go#L219-L232

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #9088
cp：https://github.com/tikv/pd/pull/10022/files

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/schedule/scatter/region_scatterer.go [hunk 1]
```diff
@@ -272,6 +273,12 @@ func (r *RegionScatterer) Scatter(region *core.RegionInfo, group string, skipSto
 		return nil, errors.Errorf("region %d is not fully replicated", region.GetID())
 	}
 
+	if op := r.opController.GetOperator(region.GetID()); op != nil {
+		scatterOperatorExistedCounter.Inc()
+		log.Info("region not replicated during scatter", zap.Uint64("region-id", region.GetID()))
```
Comment (rleungx) [inline pkg/schedule/scatter/region_scatterer.go]: The log doesn't match.

File: pkg/schedule/scatter/region_scatterer.go [hunk 2]
```diff
@@ -272,6 +276,25 @@ func (r *RegionScatterer) Scatter(region *core.RegionInfo, group string, skipSto
 		return nil, errors.Errorf("region %d is not fully replicated", region.GetID())
 	}
 
+	if op := r.opController.GetOperator(region.GetID()); op != nil {
+		val, ok := op.AdditionalInfos["group"]
+		// If the existing operator is created by the same group scatterer, just skip creating a new one.
+		if strings.Contains(op.Desc(), scatterOperatorDes) && ok && val == group {
+			scatterOperatorRunningCounter.Inc()
+			log.Info("scatter operator is running, just think it success", zap.Uint64("region-id", region.GetID()))
```
Comment (rleungx) [inline pkg/schedule/scatter/region_scatterer.go]: It might fail, but we can skip it.

File: pkg/schedule/scatter/region_scatterer.go [hunk 3]
```diff
@@ -272,6 +276,25 @@ func (r *RegionScatterer) Scatter(region *core.RegionInfo, group string, skipSto
...
+			return nil, nil
+		} else {
+			scatterOperatorExistedCounter.Inc()
```
Comment (rleungx) [inline pkg/schedule/scatter/region_scatterer.go]: As for others, we may need to retry.

File: pkg/schedule/scatter/region_scatterer.go [hunk 4]
```diff
@@ -53,12 +54,15 @@ var (
 	scatterUnnecessaryCounter       = scatterCounter.WithLabelValues("unnecessary", "")
 	scatterFailCounter              = scatterCounter.WithLabelValues("fail", "")
 	scatterSuccessCounter           = scatterCounter.WithLabelValues("success", "")
+	scatterOperatorRunningCounter   = scatterCounter.WithLabelValues("success", "scatter-operator-running")
```
Comment (rleungx) [inline pkg/schedule/scatter/region_scatterer.go]:
```suggestion
	scatterOperatorRunningCounter   = scatterCounter.WithLabelValues("skip", "running")
```

File: pkg/schedule/scatter/region_scatterer.go [hunk 5]
```diff
@@ -53,12 +54,15 @@ var (
...
+	scatterOperatorExistedCounter   = scatterCounter.WithLabelValues("skip", "operator-existed")
```
Comment (rleungx) [inline pkg/schedule/scatter/region_scatterer.go]:
```suggestion
	scatterOperatorExistedCounter   = scatterCounter.WithLabelValues("skip", "other-operator-existed")
```

File: pkg/schedule/scatter/region_scatterer.go [hunk 6]
```diff
@@ -272,6 +276,25 @@ func (r *RegionScatterer) Scatter(region *core.RegionInfo, group string, skipSto
 		return nil, errors.Errorf("region %d is not fully replicated", region.GetID())
 	}
 
+	if op := r.opController.GetOperator(region.GetID()); op != nil {
+		val, ok := op.AdditionalInfos["group"]
+		// If the existing operator is created by the same group scatterer, just skip creating a new one.
+		if strings.Contains(op.Desc(), scatterOperatorDes) && ok && val == group {
```
Comment (lhy1024) [inline pkg/schedule/scatter/region_scatterer.go:282]: They are not in 10022?

File: pkg/schedule/scatter/region_scatterer.go (hunk 5 above)
Comment (bufferflies) [reply pkg/schedule/scatter/region_scatterer.go]: done

File: pkg/schedule/scatter/region_scatterer.go (hunk 4 above)
Comment (bufferflies) [reply pkg/schedule/scatter/region_scatterer.go]: done

File: pkg/schedule/scatter/region_scatterer.go (hunk 1 above)
Comment (bufferflies) [reply pkg/schedule/scatter/region_scatterer.go]: done

File: pkg/schedule/scatter/region_scatterer.go (hunk 6 above)
Comment (lhy1024) [reply pkg/schedule/scatter/region_scatterer.go:282]: Contains is safe?

Comment (bufferflies) [reply pkg/schedule/scatter/region_scatterer.go:282]: Yes，but this hotfix needs it to ensure not create too many operator in retry

**Review by lhy1024 — APPROVED** [review]

File: pkg/schedule/scatter/region_scatterer.go (hunk 6 above)
Comment (lhy1024) [reply pkg/schedule/scatter/region_scatterer.go:282]: We should add comments to indicate it is from another pr?

**Review by rleungx — APPROVED** [review]
