### PR TITLE
Prevent PD from crashing due to epoch comparison error

### LINKED ISSUE #5418: pd crashed during unsafe remove-failed-stores
### What did you do?

when execute pd-ctl unsafe remove-failed-stores, the pd crashes with

```
[2022/08/10 16:32:01.142 +00:00] [INFO] [unsafe_recovery_controller.go:505] ["{\"info\":\"Unsafe recovery enters exit force leader stage\",\"time\":\"2022-08-10 16:32:01.142\",\"details\":[\"triggered by error: region \\u0026{0xc06ac4c980 14048}'s epoch shouldn't be staler than old ones \\u0026{0xc0658f71c0 14039}\"]}"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b599d4]

goroutine 834457685 [running]:
github.com/tikv/pd/server/cluster.(*unsafeRecoveryController).generateExitForceLeaderPlan(...)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/cluster/unsafe_recovery_controller.go:1154
github.com/tikv/pd/server/cluster.(*unsafeRecoveryController).HandleStoreHeartbeat(0xc01e88bce0, 0x1?, 0x0?)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/cluster/unsafe_recovery_controller.go:343 +0x514
github.com/tikv/pd/server.(*GrpcServer).StoreHeartbeat(0xc009d9d760, {0x33acbc0?, 0xc0b8efbad0?}, 0xc0b8eff000)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/grpc_service.go:624 +0x5c5
github.com/pingcap/kvproto/pkg/pdpb._PD_StoreHeartbeat_Handler.func1({0x33acbc0, 0xc0b8efbad0}, {0x2685c00?, 0xc0b8eff000})
        /go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220510035547-0e2f26c0a46a/pkg/pdpb/pdpb.pb.go:7467 +0x7b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1({0x33acbc0?, 0xc0b8efbad0?}, {0x2685c00?, 0xc0b8eff000?})
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:31 +0x89
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x33acbc0, 0xc0b8efbad0}, {0x2685c00, 0xc0b8eff000}, 0x24ac200?, 0xc0358f6f00)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1({0x33acbc0?, 0xc0b8efbad0?}, {0x2685c00?, 0xc0b8eff000?})
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x6f
go.etcd.io/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1({0x33acbc0, 0xc0b8efbad0}, {0x2685c00?, 0xc0b8eff000}, 0x0?, 0xc0358f6f00)
        /go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/api/v3rpc/interceptor.go:64 +0x1b6
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1({0x33acbc0?, 0xc0b8efbad0?}, {0x2685c00?, 0xc0b8eff000?})
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x6f
go.etcd.io/etcd/etcdserver/api/v3rpc.newLogUnaryInterceptor.func1({0x33acbc0, 0xc0b8efbad0}, {0x2685c00, 0xc0b8eff000}, 0xc0bcf2a140, 0xc0358f6f00)
        /go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/api/v3rpc/interceptor.go:71 +0xc3
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x33acbc0, 0xc0b8efbad0}, {0x2685c00, 0xc0b8eff000}, 0xc0bcf2a140, 0xc050ccfae8)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39 +0x1a3
github.com/pingcap/kvproto/pkg/pdpb._PD_StoreHeartbeat_Handler({0x2700f60?, 0xc009d9d760}, {0x33acbc0, 0xc0b8efbad0}, 0xc08afe4720, 0xc001f8d350)
        /go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220510035547-0e2f26c0a46a/pkg/pdpb/pdpb.pb.go:7469 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00067e480, {0x33b7950, 0xc0676b1b90}, 0xc028e50c00, 0xc000907d10, 0x433d028, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc00067e480, {0x33b7950, 0xc0676b1b90}, 0xc028e50c00, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xa05
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xea
```
however, retry the command could succeed

### What did you expect to see?

the command doesn't crash pd, either succeed or fail gracefully with meaningful error message

### What did you see instead?

pd crashed

### What version of PD are you using (`pd-server -V`)?
v6.1.0

### PR DESCRIPTION
**Pull request by v01dstar**
Signed-off-by: v01dstar <yang.zhang@pingcap.com>

### What problem does this PR solve?

Issue Number: Close #5418 

### What is changed and how does it work?

```commit-message
PD crashed because:
1. Region 1 and region 2 are ordered differently while creating the newest peer map and the newest region tree, since r1.Ver < r2.Ver but r1.ConfVer > r2.ConfVer. So, an error was reported while building the tree.
2. While handling the error, previous implementation cleans up the reports and then tries to read it again which results in seg fault.

To fix it:
1. Give Epoch.Ver and Epoch.ConfVer different priorities.
2. Do not clean up reports if PD is exiting force leader due to failures.

```

### Check List

Tests

- Unit test

Code changes

N/A

Side effects

No

Related changes

N/A

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
In which case, r1.Ver < r2.Ver but r1.ConfVer > r2.ConfVer

File: server/cluster/unsafe_recovery_controller.go [hunk 1]
```diff
@@ -43,51 +43,51 @@ const (
...
-//                                                    |           |
-//                                                    v           |
-//                      +-----------+           +-----------+     |
-//  +-----------+       |           |           |           |     |
-//  |           |       | exitForce |           |  create   |     |
-//  | finished  |<------|  Leader   |<----------|  Region   |-----+
-//  |           |       |           |           |           |
-//  +-----------+       +-----------+           +-----------+
 //
+//	                    +-----------+           +-----------+
```
Comment (Connor1996) [inline server/cluster/unsafe_recovery_controller.go:47]: why change

Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go:47]: This is auto formatted by `go fmt` I think

**Comment by v01dstar** [comment]
> In which case, r1.Ver < r2.Ver but r1.ConfVer > r2.ConfVer

I am not exactly sure why it happened last time, but from the log this is the only explanation, one possible scenario I can think of is:

1. r1 splits into r1 and r2
2. r1 merges with r0 become a new r1
3. r2 moves by applyin a conf change

File: server/cluster/unsafe_recovery_controller_test.go [hunk 2]
```diff
@@ -1650,3 +1650,95 @@ func TestSplitPaused(t *testing.T) {
...
+	req := newStoreHeartbeat(1, reports[1])
+	req.StoreReport.Step = 1
+	resp := &pdpb.StoreHeartbeatResponse{}
+	recoveryController.HandleStoreHeartbeat(req, resp)
+
+	req = newStoreHeartbeat(4, reports[4])
+	req.StoreReport.Step = 1
+	resp = &pdpb.StoreHeartbeatResponse{}
+	recoveryController.HandleStoreHeartbeat(req, resp)
+	// enter force leader stage
```
Comment (Connor1996) [inline server/cluster/unsafe_recovery_controller_test.go:1708]: why not use `advanceUntilFinished(re, recoveryController, reports)`

File: server/cluster/unsafe_recovery_controller.go [hunk 3]
```diff
@@ -485,6 +486,7 @@ func (u *unsafeRecoveryController) changeStage(stage unsafeRecoveryStage) {
 		output.Info = "Unsafe recovery enters exit force leader stage"
 		if u.err != nil {
 			output.Details = append(output.Details, fmt.Sprintf("triggered by error: %v", u.err.Error()))
+			exitForceLeaderDueToFailure = true
```
Comment (Connor1996) [inline server/cluster/unsafe_recovery_controller.go:489]: how about not calling `changeStage(exitForceLeader)` in `handleErr`, and set stage with `exitForceLeader`
``` go
var stage Stage
if u.err == nil {
  stage = u.stage
} else {
  stage = exitForceLeader
}

reCheck := false
for {
	switch stage {
	case collectReport:
		fallthrough
	case tombstoneTiFlashLearner:
		.....
````

File: server/cluster/unsafe_recovery_controller.go [hunk 4]
```diff
@@ -485,6 +486,7 @@ func (u *unsafeRecoveryController) changeStage(stage unsafeRecoveryStage) {
 		output.Info = "Unsafe recovery enters exit force leader stage"
 		if u.err != nil {
```
Comment (Connor1996) [inline server/cluster/unsafe_recovery_controller.go:487]: should set `u.err = nil` here, otherwise, it will call `handleErr` again after generate the exit force leader plan which change stage failed directly.

File: server/cluster/unsafe_recovery_controller.go (hunk 3 above)
Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go]: Updated, it looks a bit messy though. PTAL

File: server/cluster/unsafe_recovery_controller.go (hunk 4 above)
Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go:500]: Done

File: server/cluster/unsafe_recovery_controller_test.go (hunk 2 above)
Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller_test.go]: Done

File: server/cluster/unsafe_recovery_controller.go (hunk 3 above)
Comment (Connor1996) [reply server/cluster/unsafe_recovery_controller.go]: That's really messy. Why not just not calling `changeStage(exitForceLeader)` in `handleErr`, and set stage with `exitForceLeader`. We need to collect the report again to make sure the TiKVs are notified.

Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go]: Updated, per our discussion offline.

File: server/cluster/unsafe_recovery_controller.go [hunk 5]
```diff
@@ -509,10 +517,10 @@ func (u *unsafeRecoveryController) changeStage(stage unsafeRecoveryStage) {
 	u.output = append(u.output, output)
 	data, err := json.Marshal(output)
 	if err != nil {
-		u.err = err
-		return
+		log.Error("Unsafe recovery fail to marshal json object", zap.String("err", err.Error()))
```
Comment (rleungx) [inline server/cluster/unsafe_recovery_controller.go:520]:
```suggestion
		log.Error("Unsafe recovery fail to marshal json object", zap.Error(err))
```

Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go]: Done

File: server/cluster/unsafe_recovery_controller.go (hunk 4 above)
Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go]: Reverted, we don't need to set `u.err = nil` for the newest implementation, besides, the existing test case `TestFailed` actually expect the error is not cleaned up.

Comment (Connor1996) [reply server/cluster/unsafe_recovery_controller.go]: Why? If it's not reset, it would hit `handleErr` on L356.

Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go]: Oh, that's right, seems we have another dilemma here, set `u.err = nil` makes `TestFailed` to fail, do you want to change the expectation?

Comment (Connor1996) [reply server/cluster/unsafe_recovery_controller.go]: change whatever you want

Comment (Connor1996) [reply server/cluster/unsafe_recovery_controller.go]: ping

Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go:493]: Done

File: server/cluster/unsafe_recovery_controller_test.go [hunk 6]
```diff
@@ -314,7 +315,7 @@ func TestFailed(t *testing.T) {
 		recoveryController.HandleStoreHeartbeat(req, resp)
 		applyRecoveryPlan(re, storeID, reports, resp)
 	}
-	re.Equal(failed, recoveryController.GetStage())
+	re.Equal(finished, recoveryController.GetStage())
```
Comment (Connor1996) [inline server/cluster/unsafe_recovery_controller_test.go:318]: why it would be finished

Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller_test.go:318]: `An error is triggered` -> `change stage to exit force leader` -> `u.err is cleaned up` -> `exit force leader succeed` -> `finished since u.err is nil`

Comment (Connor1996) [reply server/cluster/unsafe_recovery_controller_test.go:318]: Oh, that's definitely unexpected. I misunderstood your meaning before.

File: server/cluster/unsafe_recovery_controller.go [hunk 7]
```diff
@@ -281,53 +282,78 @@ func (u *unsafeRecoveryController) HandleStoreHeartbeat(heartbeat *pdpb.StoreHea
...
 	}
 
-	allCollected, err := u.collectReport(heartbeat)
-	if err != nil {
-		u.err = err
-		if u.handleErr() {
-			return
-		}
+	storeID := heartbeat.Stats.StoreId
+	if _, isFailedStore := u.failedStores[storeID]; isFailedStore {
```
Comment (Connor1996) [inline server/cluster/unsafe_recovery_controller.go:286]: why move it out from `collectReport`

Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go:286]: Was thinking moving all the error handling inside this function to make it more clear, since the logic has changed again, reverting this.

File: server/cluster/unsafe_recovery_controller.go [hunk 8]
```diff
@@ -281,53 +292,64 @@ func (u *unsafeRecoveryController) HandleStoreHeartbeat(heartbeat *pdpb.StoreHea
...
 					break
 				}
 				fallthrough
 			case forceLeaderForCommitMerge:
-				if u.generateForceLeaderPlan(newestRegionTree, peersMap, true) {
+				hasPlan, err = u.generateForceLeaderPlan(newestRegionTree, peersMap, true)
+				if err != nil {
+					break
+				}
+				if hasPlan {
```
Comment (Connor1996) [inline server/cluster/unsafe_recovery_controller.go:335]: if hasPlan, err = u.generateXXXPlan; hasPlan && err == nil {
    u.changeStage()
    break
}
if err != nil {
    break
}

File: server/cluster/unsafe_recovery_controller.go [hunk 9]
```diff
@@ -337,27 +359,40 @@ func (u *unsafeRecoveryController) HandleStoreHeartbeat(heartbeat *pdpb.StoreHea
...
-			if u.err != nil {
-				if u.handleErr() {
+			if err != nil {
+				if u.HandleErr(err) {
 					return
 				}
+				u.storePlanExpires = make(map[uint64]time.Time)
+				u.storeRecoveryPlans = make(map[uint64]*pdpb.RecoveryPlan)
+				// Clear the reports etc.
+				u.changeStage(exitForceLeader)
```
Comment (Connor1996) [inline server/cluster/unsafe_recovery_controller.go:388]: should we reset timeout as well?

**Review by Connor1996 — COMMENTED** [review]
rest LGTM

File: server/cluster/unsafe_recovery_controller.go (hunk 8 above)
Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go]: Done

File: server/cluster/unsafe_recovery_controller.go (hunk 9 above)
Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go:385]: It makes sense to reset the timeout if the failure is caused by "timeout". For rest of the errors, we probably should leave the timeout as it is, do you agree?

File: server/cluster/unsafe_recovery_controller.go [hunk 10]
```diff
@@ -509,10 +528,10 @@ func (u *unsafeRecoveryController) changeStage(stage unsafeRecoveryStage) {
 	u.output = append(u.output, output)
 	data, err := json.Marshal(output)
 	if err != nil {
-		u.err = err
-		return
+		log.Error("Unsafe recovery fail to marshal json object", zap.Error(err))
```
Comment (rleungx) [inline server/cluster/unsafe_recovery_controller.go:531]: Do we need to return here?

File: server/cluster/unsafe_recovery_controller.go [hunk 11]
```diff
@@ -261,8 +261,21 @@ func (u *unsafeRecoveryController) checkTimeout() bool {
 	}
 
 	if time.Now().After(u.timeout) {
-		u.err = errors.Errorf("Exceeds timeout %v", u.timeout)
-		return u.handleErr()
+		ret := u.HandleErr(errors.Errorf("Exceeds timeout %v", u.timeout))
+		time.Now().Add(storeRequestInterval)
```
[the remark this answers is not in the document]
Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go]: That was a mistake, I was trying to extend the timeout. Updated. PTAL.

File: server/cluster/unsafe_recovery_controller.go (hunk 10 above)
Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller.go:531]: I don't think we need to return here. This is a json parsing error of logging, does not affect the main logic.

**Review by rleungx — APPROVED** [review]

File: server/cluster/unsafe_recovery_controller_test.go [hunk 12]
```diff
@@ -1065,11 +1055,9 @@ func TestTimeout(t *testing.T) {
 
 	time.Sleep(time.Second)
 	req := newStoreHeartbeat(1, nil)
+	req.StoreReport = &pdpb.StoreReport{Step: 1}
 	resp := &pdpb.StoreHeartbeatResponse{}
 	recoveryController.HandleStoreHeartbeat(req, resp)
-	re.Equal(exitForceLeader, recoveryController.GetStage())
```
Comment (Connor1996) [inline server/cluster/unsafe_recovery_controller_test.go:1070]: exit force leader is not triggered for timeout?

Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller_test.go:1070]: No, because there is no force leader.

Comment (v01dstar) [reply server/cluster/unsafe_recovery_controller_test.go:1070]: In the past, the error handling function changes the stage to exit force leader regardless of whether there are force leaders or not. In the new implementation, we only change stage to exit force leader when needed, this is the difference.

**Review by Connor1996 — APPROVED** [review]
LGTM
