### PR TITLE
*: fix `TestGetTSOImmediately`

### LINKED ISSUE #6795: TestGetTSOImmediately failed
### Which jobs are failing
```
2023-07-12T16:54:44.1099413Z     testutil.go:178: 
2023-07-12T16:54:44.1099865Z         	Error Trace:	/home/runner/work/pd/pd/tests/server/apiv2/handlers/testutil.go:178
2023-07-12T16:54:44.1100997Z         	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/keyspace_group_manager_test.go:360
2023-07-12T16:54:44.1102034Z         	            				/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/asm_amd64.s:1598
2023-07-12T16:54:44.1102228Z         	Error:      	Not equal: 
2023-07-12T16:54:44.1102493Z         	            	expected: 200
2023-07-12T16:54:44.1102751Z         	            	actual  : 500
2023-07-12T16:54:44.1103080Z         	Test:       	TestGetTSOImmediately
2023-07-12T16:54:44.1103571Z         	Messages:   	"[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"
```
### CI link

https://github.com/tikv/pd/actions/runs/5534201396/jobs/10098828392?pr=6577

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #6795.

### What is changed and how does it work?

There might be a txn conflict error when loading the keyspace group and checking the split process.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

File: tests/server/apiv2/handlers/testutil.go [hunk 1]
```diff
@@ -181,6 +181,18 @@ func MustLoadKeyspaceGroupByID(re *require.Assertions, server *tests.TestServer,
 	return &kg
 }
 
+// TryLoadKeyspaceGroupByID loads the keyspace group by ID with HTTP API.
+func TryLoadKeyspaceGroupByID(re *require.Assertions, server *tests.TestServer, id uint32) (int, []byte) {
```
Comment (JmPotato) [inline tests/server/apiv2/handlers/testutil.go:185]: What about making `MustLoadKeyspaceGroupByID` 	reuse this part of the code?

**Review by lhy1024 — APPROVED** [review]
