### PR TITLE
operator: fix operator count conflict 

### LINKED ISSUE #8452: merge region reach limit while there is no any operator
### What did you do?

merge empty region

### What did you see instead?

there has been no operator check, but it still reaches limit

image

image

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #8452

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Manual test (add detailed scripts or steps below)
it will failed in master branch
```
--- FAIL: TestOperatorControllerTestSuite (0.01s)
    --- FAIL: TestOperatorControllerTestSuite/TestConcurrentMergeConflict (0.01s)
        /home/lhy1024/pd/pkg/schedule/operator/operator_controller_test.go:538: 
            	Error Trace:	/home/lhy1024/pd/pkg/schedule/operator/operator_controller_test.go:538
            	Error:      	Not equal: 
            	            	expected: 2
            	            	actual  : 3
            	Test:       	TestOperatorControllerTestSuite/TestConcurrentMergeConflict
FAIL
exit status 1
```

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/schedule/operator/operator_controller.go [hunk 1]
```diff
@@ -535,8 +531,21 @@ func (oc *Controller) addOperatorInner(op *Operator) bool {
 		operatorCounter.WithLabelValues(op.Desc(), "unexpected").Inc()
 		return false
 	}
-	oc.operators.Store(regionID, op)
+
+	old, loaded := oc.operators.LoadOrStore(regionID, op)
+	if loaded {
+		log.Debug("operator already exists",
```
Comment (rleungx) [inline pkg/schedule/operator/operator_controller.go:537]: How about also adding metrics?

File: pkg/schedule/operator/operator_controller_test.go [hunk 2]
```diff
@@ -493,6 +493,53 @@ func (suite *operatorControllerTestSuite) TestPollDispatchRegionForMergeRegion()
 	re.Equal(0, controller.opNotifierQueue.len())
 }
 
+func (suite *operatorControllerTestSuite) TestConcurrentMergeConflict() {
+	re := suite.Require()
+
+	for range 10 {
+		opts := mockconfig.NewTestOptions()
+		cluster := mockcluster.NewCluster(suite.ctx, opts)
```
Comment (JmPotato) [inline pkg/schedule/operator/operator_controller_test.go:501]: Can we reuse the same cluster and rebuild the region metadata within the loop? Creating separate clusters inside the loop seems a bit inefficient.

**Review by JmPotato — APPROVED** [review]

**Review by bufferflies — APPROVED** [review]
