### PR TITLE
core: fix some bug to improve the bucket compatibility

### LINKED ISSUE #10308: make report bucket work well
## Bug Report
Currently, bucket pointer CAS may use the new struct when bucket meta exists, which will cause CAS to always fail.

### What did you do?
notion

### What did you expect to see?
Cas success when region meta exist
### What did you see instead?
Cas failed
### What version of PD are you using (`pd-server -V`)?
master and release-nextgen-8.5

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #10308

### What is changed and how does it work?

```commit-message
1. Rename bucket point as the report bucket to understand more easily 
2. Inherit will work even if the meta bucket is still working to avoid the cas report bucket always being successful.
3. Cas operator wrap into the region inner function avoid using bucket meta to do cas.
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP APIs changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

## Release Notes

* **New Features**
  * Added monitoring metrics for region cache misses and update operation success/failure tracking.

* **Bug Fixes**
  * Improved region bucket update mechanism for better handling of concurrent updates and metadata synchronization.
  * Enhanced bucket information handling during region metadata upgrades.

### CODE REVIEW

**Comment by bufferflies** [comment]
@coderabbitai full review

File: pkg/core/region.go [hunk 1]
```diff
@@ -627,7 +627,32 @@ func (r *RegionInfo) UpdateBuckets(buckets, old *metapb.Buckets) bool {
...
+			return true
+		} else if reportVersion == old.GetVersion() {
+			versionNotChangeCounter.Inc()
+			return true
+		}
+	}
+	failpoint.Inject("concurrentBucketHeartbeat", func() {
+		time.Sleep(500 * time.Millisecond)
+	})
+	return atomic.CompareAndSwapPointer(&r.reportBuckets, unsafe.Pointer(old), unsafe.Pointer(buckets))
```
[the remark this answers is not in the document]
Comment (bufferflies) [reply pkg/core/region.go:655]: No need to use clone, because the value will not change again.

File: pkg/core/region.go [hunk 2]
```diff
@@ -627,7 +627,32 @@ func (r *RegionInfo) UpdateBuckets(buckets, old *metapb.Buckets) bool {
...
+	old := (*metapb.Buckets)(atomic.LoadPointer(&r.reportBuckets))
+	// region should not update if the version of the buckets is less than the old one.
+	if old != nil {
+		reportVersion := buckets.GetVersion()
+		if reportVersion < old.GetVersion() {
+			versionStaleCounter.Inc()
+			return true
+		} else if reportVersion == old.GetVersion() {
+			versionNotChangeCounter.Inc()
+			return true
```
[the remark this answers is not in the document]
Comment (bufferflies) [reply pkg/core/region.go:649]: yes, the return indicate that the caller should retry again.

File: tests/testutil.go [hunk 3]
```diff
@@ -684,16 +684,12 @@ func InitRegions(regionLen int) []*core.RegionInfo {
...
-				Version: 1,
-			}
-			region := core.NewRegionInfo(r, r.Peers[0], core.SetSource(core.Heartbeat), core.WithBucketMeta(meta))
 			buckets := &metapb.Buckets{
 				RegionId: r.Id,
 				Keys:     [][]byte{r.StartKey, r.EndKey},
 				Version:  1,
 			}
+			region := core.NewRegionInfo(r, r.Peers[0], core.SetSource(core.Heartbeat), core.SetBuckets(buckets))
 			region.UpdateBuckets(buckets, region.GetBuckets())
```
[the remark this answers is not in the document]
Comment (bufferflies) [reply tests/testutil.go:693]: Yes, I just hope the bucket meta is prioritized

File: pkg/core/region.go [hunk 4]
```diff
@@ -287,9 +287,9 @@ func (r *RegionInfo) Inherit(origin *RegionInfo, bucketEnable bool) {
 			r.approximateSize = EmptyRegionApproximateSize
 		}
 	}
-	if bucket := r.GetBuckets(); bucketEnable && bucket == nil && origin != nil {
-		inherited := atomic.LoadPointer(&origin.buckets)
-		atomic.StorePointer(&r.buckets, inherited)
+	if bucketEnable && origin != nil && atomic.LoadPointer(&r.reportBuckets) == nil {
+		inherited := atomic.LoadPointer(&origin.reportBuckets)
```
Comment (rleungx) [inline pkg/core/region.go:291]: Will it cause the bucket roll back to nil?

File: pkg/core/region.go [hunk 5]
```diff
@@ -627,7 +627,32 @@ func (r *RegionInfo) UpdateBuckets(buckets, old *metapb.Buckets) bool {
...
+	return atomic.CompareAndSwapPointer(&r.reportBuckets, unsafe.Pointer(old), unsafe.Pointer(newBuckets))
+}
+
+// GetReportBuckets returns the buckets of the region, only use by tests.
+func (r *RegionInfo) GetReportBuckets() *metapb.Buckets {
+	return (*metapb.Buckets)(atomic.LoadPointer(&r.reportBuckets))
+}
+
+// CompareAndSetReportBuckets compares and sets the report buckets of the region.
+func (r *RegionInfo) CompareAndSetReportBuckets(buckets *metapb.Buckets) bool {
```
Comment (rleungx) [inline pkg/core/region.go:639]: Same question for here, if tikv rollback, will bucket rollback too?

File: pkg/core/region.go (hunk 4 above)
Comment (bufferflies) [reply pkg/core/region.go:291]: Do you mean the reportBuckets points? It only set value even if the report bucket is nil

File: pkg/core/region.go (hunk 5 above)
Comment (bufferflies) [reply pkg/core/region.go:639]: The report bucket will not; it must increase. But the result of the GetBucket API may roll back because the bucket metadata may exceed the report bucket.

File: pkg/core/region.go (hunk 4 above)
Comment (rleungx) [reply pkg/core/region.go:291]: assume that the tikv rollback, and the bucket meta suddenly become nil

Comment (bufferflies) [reply pkg/core/region.go:291]: yes, but the bucket info will be refresh after restart, so the report bucket should be greater than the previous.

File: pkg/core/region.go (hunk 5 above)
Comment (lhy1024) [reply pkg/core/region.go:639]: I think there is still a rollback issue in the visible result of `GetBuckets()` for the same region.

  Case 1:
  - PD has an old report-bucket value `v1`
  - PD later receives a newer bucket meta from region heartbeat `v2`
  - `GetBuckets()` shows the newer bucket meta `v2`
  - when a later heartbeat does not carry bucket meta anymore, `GetBuckets()` falls back to the old report-bucket value `v1`

  Case 2:
  - PD has an old report-bucket value `v1`
  - PD later receives a newer bucket meta `v3`
  - before bucket meta disappears, PD receives a delayed report-bucket update `v2`, which is newer than the old report bucket but still older than the bucket meta
  - when a later heartbeat does not carry bucket meta anymore, `GetBuckets()` falls back to that delayed report-bucket value `v2` rather than `v3`

In both cases, the visible result of `GetBuckets()` rolls back to an older version than PD has already observed.

Could we add small unit tests in `pkg/core/region_test.go` for these two cases?

Comment (lhy1024) [reply pkg/core/region.go:639]: I tried two small unit tests locally, and both fail on the current patch.

  ```go
  func TestReportBucketsShouldNotFallBackBelowBucketMeta(t *testing.T) {
        re := require.New(t)
        origin := NewRegionInfo(&metapb.Region{Id: 1}, nil)
        re.True(origin.UpdateBuckets(&metapb.Buckets{
                RegionId: 1,
                Version:  1,
                Keys:     [][]byte{[]byte("a"), []byte("b")},
        }, nil))
        upgraded := origin.Clone(SetBuckets(&metapb.Buckets{
                RegionId: 1,
                Version:  3,
                Keys:     [][]byte{[]byte("a"), []byte("c")},
        }))
        upgraded.Inherit(origin, true)
        re.Equal(uint64(3), upgraded.GetBuckets().GetVersion())
        re.Equal(uint64(1), upgraded.GetReportBuckets().GetVersion())

        re.True(upgraded.CompareAndSetReportBuckets(&metapb.Buckets{
                RegionId: 1,
                Version:  2,
                Keys:     [][]byte{[]byte("a"), []byte("b")},
        }))
        re.Equal(uint64(2), upgraded.GetReportBuckets().GetVersion())
        re.Equal(uint64(3), upgraded.GetBuckets().GetVersion())

        downgraded := upgraded.Clone(SetBuckets(nil))
        downgraded.Inherit(upgraded, true)
        re.Equal(uint64(3), downgraded.GetBuckets().GetVersion())
  }

  func TestBucketMetaDisappearShouldNotRevealOldReportBuckets(t *testing.T) {
        re := require.New(t)

        origin := NewRegionInfo(&metapb.Region{Id: 1}, nil)
        re.True(origin.UpdateBuckets(&metapb.Buckets{
                RegionId: 1,
                Version:  1,
                Keys:     [][]byte{[]byte("a"), []byte("b")},
        }, nil))

        upgraded := origin.Clone(SetBuckets(&metapb.Buckets{
                RegionId: 1,
                Version:  3,
                Keys:     [][]byte{[]byte("a"), []byte("c")},
        }))
        re.Equal(uint64(3), upgraded.GetBuckets().GetVersion())

        downgraded := upgraded.Clone(SetBuckets(nil))
        downgraded.Inherit(upgraded, true)
        re.Equal(uint64(3), downgraded.GetBuckets().GetVersion())
  }

Comment (bufferflies) [reply pkg/core/region.go:639]: Yes, it may happen from a code perspective. But it will never happen because the source of the bucket meta and the report bucket is the same.

Comment (bufferflies) [reply pkg/core/region.go:639]: Only happen if the tikv rollback, but the bucket will refresh with bigger version

Comment (bufferflies) [reply pkg/core/region.go:639]: tikv code： https://github.com/tidbcloud/cloud-storage-engine/blob/285169685ecd9b0bd67b73e3a6ea1266af307104/components/rfstore/src/store/worker/pd.rs#L2113-L2141

Comment (lhy1024) [reply pkg/core/region.go:639]: Got it. This makes sense to me now.

On the normal TiKV path, both bucket meta and report bucket come from the same `bucket_stat`, so they should be produced together.
