### PR TITLE
client: fix tso service discovery

### LINKED ISSUE #9593: TSO service discovery may lose some TSO servers when updating primary
## Bug Report

We use `len(t.urls) == 0 || t.failureCount == len(t.urls)` to decide if we need to update urls according to the service discovery.
https://github.com/tikv/pd/blob/830a43945e096baa6e17b9582666e98bcdba775b/client/servicediscovery/tso_service_discovery.go#L586-L608

The failure count only increases when the request fails.
https://github.com/tikv/pd/blob/830a43945e096baa6e17b9582666e98bcdba775b/client/servicediscovery/tso_service_discovery.go#L432-L441

If the first TSO is registered and ready to serve, which means there are no errors for the request. The rest of the TSO servers won't be added to the urls.

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #9593.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

File: client/servicediscovery/tso_service_discovery.go [hunk 1]
```diff
@@ -583,28 +565,29 @@ func (c *tsoServiceDiscovery) getTSOServer(sd ServiceDiscovery) (string, error)
...
-		urls, err = sd.(*serviceDiscovery).discoverMicroservice(tsoService)
-		if err != nil {
-			return "", err
-		}
+	urls, err = sd.(*serviceDiscovery).discoverMicroservice(tsoService)
+	if err != nil {
+		return "", err
+	}
+
+	if len(t.urls) == 0 {
```
Comment (JmPotato) [inline client/servicediscovery/tso_service_discovery.go]: Perhaps put the check inisde the failpoint?

File: client/servicediscovery/tso_service_discovery.go [hunk 2]
```diff
@@ -583,28 +565,29 @@ func (c *tsoServiceDiscovery) getTSOServer(sd ServiceDiscovery) (string, error)
 		err  error
 	)
 	t := c.tsoServerDiscovery
```
Comment (JmPotato) [inline client/servicediscovery/tso_service_discovery.go]: Now this `t` is assigned across multiple lines in advance, which looks somewhat strange.

Comment (rleungx) [reply client/servicediscovery/tso_service_discovery.go]: Assign it after calling discoverMicroservice now.

File: client/servicediscovery/tso_service_discovery.go [hunk 3]
```diff
@@ -582,29 +564,31 @@ func (c *tsoServiceDiscovery) getTSOServer(sd ServiceDiscovery) (string, error)
 		urls []string
 		err  error
 	)
+	urls, err = sd.(*serviceDiscovery).discoverMicroservice(tsoService)
```
Comment (lhy1024) [inline client/servicediscovery/tso_service_discovery.go:564]: There will be more requests about `discoverMicroservice`. Will it introduce performance problems?

Comment (lhy1024) [inline client/servicediscovery/tso_service_discovery.go:564]:
```suggestion
	var (
		urls []string
		err  error
	)
	urls, err = sd.(*serviceDiscovery).discoverMicroservice(tsoService)
	if err != nil {
		return "", err
	}
	c.Lock()
	defer c.Unlock()
```

Comment (lhy1024) [reply client/servicediscovery/tso_service_discovery.go:564]: Maybe we could reduce lock time.

File: client/servicediscovery/tso_service_discovery.go [hunk 4]
```diff
@@ -431,15 +416,12 @@ func (c *tsoServiceDiscovery) updateMember() error {
 	if len(tsoServerURL) > 0 {
 		keyspaceGroup, err = c.findGroupByKeyspaceID(keyspaceID, tsoServerURL, UpdateMemberTimeout)
 		if err != nil {
-			if c.countFailure() {
-				log.Error("[tso] failed to find the keyspace group",
-					zap.Uint32("keyspace-id-in-request", keyspaceID),
-					zap.String("tso-server-url", tsoServerURL),
-					errs.ZapError(err))
-			}
+			log.Error("[tso] failed to find the keyspace group",
```
Comment (lhy1024) [inline client/servicediscovery/tso_service_discovery.go:419]: Will it print more logs?

File: client/servicediscovery/tso_service_discovery.go (hunk 3 above)
Comment (rleungx) [reply client/servicediscovery/tso_service_discovery.go:564]: Otherwise, we can't update the tso members.
