### PR TITLE
server: add `/operators/records` API to list completed operators 

### LINKED ISSUE #4630: PD can record all finished operators
## Enhancement Task
In past, PD only records the successful  operators and use them to describe the scheduler  trend  on stores.

It will be helpful to analyze operator failed reason if PD records all finish operator includes  `TIMEOUT`, `CANCELED`, `EXPIRED` .

### PR DESCRIPTION
**Pull request by bufferflies**
Signed-off-by: bufferflies <1045931706@qq.com>

### What problem does this PR solve?

Issue Number: Close  #4630

### What is changed and how it works?
Using OpRecords to store all finished operators.

### Check List

Tests

- Unit test
- Manual test (add detailed scripts or steps below)

Code changes

Side effects

- Possible performance regression

Related changes

### Release note

```release-note
add /operators/records API to list completed operators.
```

### CODE REVIEW

File: server/api/operator.go [hunk 1]
```diff
@@ -339,6 +340,32 @@ func (h *operatorHandler) Delete(w http.ResponseWriter, r *http.Request) {
 	h.r.JSON(w, http.StatusOK, "The pending operator is canceled.")
 }
 
+// @Tags operator
+// @Summary lists the finished operators in the given time.
+// @Param from query integer false "From Unix timestamp"
+// @Produce json
+// @Success 200 {object} Trend
```
Comment (rleungx) [inline server/api/operator.go:347]: Trend?

File: server/schedule/operator_controller.go [hunk 2]
```diff
@@ -65,6 +65,7 @@ type OperatorController struct {
 	hbStreams       *hbstream.HeartbeatStreams
 	fastOperators   *cache.TTLUint64
 	histories       *list.List
+	records         *list.List
```
Comment (rleungx) [inline server/schedule/operator_controller.go:68]: Why not combine them by recording the status?

File: server/api/operator.go [hunk 3]
```diff
@@ -339,6 +340,32 @@ func (h *operatorHandler) Delete(w http.ResponseWriter, r *http.Request) {
...
+// @Failure 400 {string} string "The request is invalid."
+// @Failure 500 {string} string "PD server failed to proceed the request."
+// @Router /operators/record [get]
+func (h *operatorHandler) Record(w http.ResponseWriter, r *http.Request) {
+	var from time.Time
+	if fromStr := r.URL.Query()["from"]; len(fromStr) > 0 {
```
Comment (rleungx) [inline server/api/operator.go:353]: It's better to add tests for this field.

File: server/schedule/operator_controller.go (hunk 2 above)
Comment (bufferflies) [reply server/schedule/operator_controller.go:68]: `histories` only records the successful operators and use them to describe the scheduler trend on stores. 
And it records `add-peer`, `remove-peer ` and `transfer-leader` steps not operaoter dimensionality.

File: server/api/operator.go (hunk 3 above)
Comment (bufferflies) [reply server/api/operator.go:353]: yes

File: tools/pd-ctl/pdctl/command/operator.go [hunk 4]
```diff
@@ -427,6 +428,29 @@ func removeOperatorCommandFunc(cmd *cobra.Command, args []string) {
...
+func NewHistoryOperatorCommand() *cobra.Command {
+	c := &cobra.Command{
+		Use:   "history <start>",
+		Short: "list all finished operators since start",
+		Run:   historyOperatorCommandFunc,
+	}
+	return c
+}
+
+func historyOperatorCommandFunc(cmd *cobra.Command, args []string) {
```
Comment (rleungx) [inline tools/pd-ctl/pdctl/command/operator.go:441]: How about adding a test for `pd-ctl`? And it's better to give an example about the format of time in the help message.

Comment (bufferflies) [reply tools/pd-ctl/pdctl/command/operator.go:441]: it is exist in [tests/pdctl/operator/operator_test.go](https://github.com/tikv/pd/pull/4631/files#diff-a0f6a1a99bc2f5052816b367d98307b7ed528eb7a0582c73f86e25cd35861933). The example is useful.

File: server/api/operator_test.go [hunk 5]
```diff
@@ -98,6 +105,9 @@ func (s *testOperatorSuite) TestAddRemovePeer(c *C) {
 
 	_, err = doDelete(testDialClient, regionURL)
 	c.Assert(err, IsNil)
+	records = mustReadURL(c, recordURL)
+	fmt.Printf("data:%s\n", records)
```
Comment (rleungx) [inline server/api/operator_test.go:109]: Please remove it.

File: server/schedule/operator/operator.go [hunk 6]
```diff
@@ -357,6 +357,37 @@ func (o *Operator) History() []OpHistory {
...
+// Record transfers the operator to OpRecord.
+func (o *Operator) Record(finishTime time.Time) *OpRecord {
+	step := atomic.LoadInt32(&o.currentStep)
+	record := &OpRecord{
+		Operator:   o,
+		FinishTime: finishTime,
+	}
+	start := o.GetStartTime()
+	if o.Status() != SUCCESS && step > 0 {
+		start = time.Unix(0, o.stepsTime[int(step-1)])
```
Comment (rleungx) [inline server/schedule/operator/operator.go:385]: Should we check the length of `stepsTime`?

File: server/schedule/operator_controller.go [hunk 7]
```diff
@@ -847,15 +832,17 @@ func (oc *OperatorController) SetOperator(op *operator.Operator) {
 
 // OperatorWithStatus records the operator and its status.
 type OperatorWithStatus struct {
-	Op     *operator.Operator
-	Status pdpb.OperatorStatus
+	Op         *operator.Operator
```
Comment (rleungx) [inline server/schedule/operator_controller.go:835]: How about:
```suggestion
	*operator.Operator
```

File: tools/pd-ctl/pdctl/command/operator.go (hunk 4 above)
Comment (rleungx) [reply tools/pd-ctl/pdctl/command/operator.go:441]: I mean in the command output, you can add an example in the `Short` or `Example` field.

File: server/schedule/operator_controller.go (hunk 7 above)
Comment (bufferflies) [reply server/schedule/operator_controller.go]: yes, it should be.

**Review by rleungx — APPROVED** [review]

File: server/api/operator.go [hunk 8]
```diff
@@ -339,6 +340,32 @@ func (h *operatorHandler) Delete(w http.ResponseWriter, r *http.Request) {
 	h.r.JSON(w, http.StatusOK, "The pending operator is canceled.")
 }
 
+// @Tags operator
+// @Summary lists the finished operators in the given time.
```
Comment (JmPotato) [inline server/api/operator.go:344]:
```suggestion
// @Summary lists the finished operators since the given timestamp in second.
```

File: server/grpc_service.go [hunk 9]
```diff
@@ -1410,8 +1410,8 @@ func (s *GrpcServer) GetOperator(ctx context.Context, request *pdpb.GetOperatorR
 	return &pdpb.GetOperatorResponse{
 		Header:   s.header(),
 		RegionId: requestID,
-		Desc:     []byte(r.Op.Desc()),
-		Kind:     []byte(r.Op.Kind().String()),
+		Desc:     []byte(r.Desc()),
+		Kind:     []byte(r.Kind().String()),
```
Comment (JmPotato) [inline server/grpc_service.go:1414]: Will this cause a compatibility problem?

File: server/api/operator.go [hunk 10]
```diff
@@ -339,6 +340,32 @@ func (h *operatorHandler) Delete(w http.ResponseWriter, r *http.Request) {
...
+	var from time.Time
+	if fromStr := r.URL.Query()["from"]; len(fromStr) > 0 {
+		fromInt, err := strconv.ParseInt(fromStr[0], 10, 64)
+		if err != nil {
+			h.r.JSON(w, http.StatusBadRequest, err.Error())
+			return
+		}
+		from = time.Unix(fromInt, 0)
+	}
+	records, err := h.GetRecords(from)
```
Comment (JmPotato) [inline server/api/operator.go:361]: The signature of this function argument is `start`, what about keeping them the same?

File: server/api/operator.go (hunk 8 above)
Comment (bufferflies) [reply server/api/operator.go:344]: fix

File: server/api/operator.go (hunk 10 above)
Comment (bufferflies) [reply server/api/operator.go:361]: fix, all signature should be `from`.

File: server/grpc_service.go (hunk 9 above)
Comment (bufferflies) [reply server/grpc_service.go:1414]: No, the `OperatorWithStatus` has inheritde `Operator` rather than one property. So the method of `Kind` returns some results.

**Review by JmPotato — APPROVED** [review]
