### PR TITLE
statistics: fix the bug that the isolation level is wrong when the store lacks label

### LINKED ISSUE #3455: When there are redundant labels in location-labels, the metrics is wrong
## Bug Report

* `location-labels = "region,zone,rack,host"`
* TiKV only used `zone,host`

### What did you expect to see?

image

### What did you see instead?

* Should be `zone`

### What version of PD are you using (`pd-server -V`)?

* v3.0.12

### PR DESCRIPTION
**Pull request by HunDunDM**
### What problem does this PR solve?

close #3455

### What is changed and how it works?

* statistics: fix the bug that the isolation level is wrong when the store lacks label

**example**

* pd location-labels: region,host
* tikv1 label: {host: 1}
* tikv2 label: {host: 2}
* tikv3 label: {host: 3}
* Before
  * image
* After
  *  image

### Check List

Tests

- Unit test

Related changes

- Need to cherry-pick to the release branch

### Release note

- fix the bug that the isolation level is wrong when the store lacks label

### CODE REVIEW

File: server/statistics/region_collection.go [hunk 1]
```diff
@@ -296,17 +280,35 @@ func getRegionLabelIsolation(stores []*core.StoreInfo, labels []string) string {
...
+			if len(stores) > 1 {
+				res = append(res, stores)
+			}
+		}
+	} else {
+		for _, stores := range valueStoresMap {
+			stores = append(stores, emptyValueStores...)
 			res = append(res, stores)
 		}
 	}
```
Comment (JmPotato) [inline server/statistics/region_collection.go:314]: What about adding some comments to these different situations? For example, for `valueStoresMap` is empty, it means no store has this label configured, for `emptyValueStores` is empty, it means every store has this label configured, and for `emptyValueStores` is not empty, it means this is at least one store has this label configured but not all.

Comment (HunDunDM) [reply server/statistics/region_collection.go:314]: good idea

**Review by JmPotato — APPROVED** [review]
