### PR TITLE
*: make `TestScheduler` stable

### LINKED ISSUE #5578: `TestScheduler` is flaky
### Which jobs are failing
```
--- FAIL: TestScheduler (6.34s)
    scheduler_test.go:73: 
        	Error Trace:	scheduler_test.go:73
        	            				scheduler_test.go:106
        	            				scheduler_test.go:133
        	Error:      	Received unexpected error:
        	            	invalid character '"' after top-level value
        	Test:       	TestScheduler
```

### CI link
https://github.com/tikv/pd/actions/runs/3216756484/jobs/5258969812

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Issue Number: Close #5578

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by CabinfeverB — APPROVED** [review]

File: tests/pdctl/scheduler/scheduler_test.go [hunk 1]
```diff
@@ -74,6 +75,15 @@ func TestScheduler(t *testing.T) {
 		return ""
 	}
 
+	mightExec := func(args []string, v interface{}) {
+		output, err := pdctl.ExecuteCommand(cmd, args...)
+		re.NoError(err)
+		if v == nil {
+			return
+		}
+		json.Unmarshal(output, v)
```
Comment (bufferflies) [inline tests/pdctl/scheduler/scheduler_test.go:84]: Should it ignore the error?

Comment (CabinfeverB) [reply tests/pdctl/scheduler/scheduler_test.go:84]: Yes, because there could be no result and it returns [500]. We should wait.

**Review by bufferflies — APPROVED** [review]
