### PR TITLE
statistics: fix data race in `IsRegionHot`

### LINKED ISSUE #8335: statistics: meet data race when check `IsRegionHot`
### What did you do?

`go test -timeout 120s -run ^TestSpecialUseHotRegion$ github.com/tikv/pd/pkg/schedule/schedulers -race`

### What did you expect to see?

no data race

### What did you see instead?

```
==================
WARNING: DATA RACE
Write at 0x00c00003b2f0 by goroutine 210:
  runtime.mapassign_fast64()
      /usr/lib/go/src/runtime/map_fast64.go:93 +0x0
  github.com/tikv/pd/pkg/statistics.(*HotPeerCache).putItem()
      /home/lhy1024/pd/pkg/statistics/hot_peer_cache.go:521 +0x14e
  github.com/tikv/pd/pkg/statistics.(*HotPeerCache).UpdateStat()
      /home/lhy1024/pd/pkg/statistics/hot_peer_cache.go:111 +0x64
  github.com/tikv/pd/pkg/statistics.(*HotCache).Update()
      /home/lhy1024/pd/pkg/statistics/hot_cache.go:202 +0x8c
  github.com/tikv/pd/pkg/mock/mockcluster.(*Cluster).AddLeaderRegionWithWriteInfo()
      /home/lhy1024/pd/pkg/mock/mockcluster/mockcluster.go:552 +0x464
  github.com/tikv/pd/pkg/schedule/schedulers.TestSpecialUseHotRegion()
      /home/lhy1024/pd/pkg/schedule/schedulers/scheduler_test.go:350 +0xa3b
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      /usr/lib/go/src/testing/testing.go:1742 +0x44

Previous read at 0x00c00003b2f0 by goroutine 214:
  runtime.mapaccess2_fast64()
      /usr/lib/go/src/runtime/map_fast64.go:53 +0x0
  github.com/tikv/pd/pkg/statistics.(*HotPeerCache).getHotPeerStat()
      /home/lhy1024/pd/pkg/statistics/hot_peer_cache.go:429 +0x57
  github.com/tikv/pd/pkg/statistics.(*HotPeerCache).isRegionHotWithPeer()
      /home/lhy1024/pd/pkg/statistics/hot_peer_cache.go:422 +0x9c
  github.com/tikv/pd/pkg/statistics.(*HotPeerCache).isRegionHotWithAnyPeers()
      /home/lhy1024/pd/pkg/statistics/hot_peer_cache.go:411 +0xd0
  github.com/tikv/pd/pkg/statistics.(*HotCache).IsRegionHot.func1()
      /home/lhy1024/pd/pkg/statistics/hot_cache.go:108 +0x4b
  github.com/tikv/pd/pkg/statistics.(*HotCache).runWriteTask()
      /home/lhy1024/pd/pkg/statistics/hot_cache.go:192 +0x5e
  github.com/tikv/pd/pkg/statistics.(*HotCache).runWriteTask-fm()
      <autogenerated>:1 +0x3d
  github.com/tikv/pd/pkg/statistics.(*HotCache).updateItems()
      /home/lhy1024/pd/pkg/statistics/hot_cache.go:176 +0x87
  github.com/tikv/pd/pkg/statistics.NewHotCache.gowrap2()
      /home/lhy1024/pd/pkg/statistics/hot_cache.go:49 +0x4f

Goroutine 210 (running) created at:
  testing.(*T).Run()
      /usr/lib/go/src/testing/testing.go:1742 +0x825
  testing.runTests.func1()
      /usr/lib/go/src/testing/testing.go:2161 +0x85
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1689 +0x21e
  testing.runTests()
      /usr/lib/go/src/testing/testing.go:2159 +0x8be
  testing.(*M).Run()
      /usr/lib/go/src/testing/testing.go:2027 +0xf17
  main.main()
      _testmain.go:227 +0x2bd

Goroutine 214 (running) created at:
  github.com/tikv/pd/pkg/statistics.NewHotCache()
      /home/lhy1024/pd/pkg/statistics/hot_cache.go:49 +0x444
  github.com/tikv/pd/pkg/statistics.NewHotStat()
      /home/lhy1024/pd/pkg/statistics/hot_stat.go:33 +0x34
  github.com/tikv/pd/pkg/mock/mockcluster.NewCluster()
      /home/lhy1024/pd/pkg/mock/mockcluster/mockcluster.go:70 +0x1a8
  github.com/tikv/pd/pkg/schedule/schedulers.prepareSchedulersTest()
      /home/lhy1024/pd/pkg/schedule/schedulers/scheduler_test.go:42 +0x91
  github.com/tikv/pd/pkg/schedule/schedulers.TestSpecialUseHotRegion()
      /home/lhy1024/pd/pkg/schedule/schedulers/scheduler_test.go:313 +0x73
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      /usr/lib/go/src/testing/testing.go:1742 +0x44
==================
--- FAIL: TestSpecialUseHotRegion (0.01s)
    testing.go:1398: race detected during execution of test
FAIL
```

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #8335

Before #8164 it is 
```
// IsRegionHot checks if the region is hot.
func (w *HotCache) IsRegionHot(region *core.RegionInfo, minHotDegree int) bool {
	checkRegionHotWriteTask := newCheckRegionHotTask(region, minHotDegree)
	checkRegionHotReadTask := newCheckRegionHotTask(region, minHotDegree)
	succ1 := w.CheckWriteAsync(checkRegionHotWriteTask)
	succ2 := w.CheckReadAsync(checkRegionHotReadTask)
	if succ1 && succ2 {
		return checkRegionHotWriteTask.waitRet(w.ctx) || checkRegionHotReadTask.waitRet(w.ctx)
	}
	return false
}
```

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

- Test1: 
This test will meet data race in master and is normal in this PR.
```
for i in {1..50}; do
	go clean -testcache
	go test -timeout 120s -run ^TestSpecialUseHotRegion$ github.com/tikv/pd/pkg/schedule/schedulers -race
done

```

- Test2:
This test will be successful in this PR and be failed in master branches
```
--- FAIL: TestIsHot (0.00s)
    /home/lhy1024/pd/pkg/statistics/hot_cache_test.go:34: 
        	Error Trace:	/home/lhy1024/pd/pkg/statistics/hot_cache_test.go:34
        	Error:      	Should be true
        	Test:       	TestIsHot
FAIL
```
### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/statistics/hot_cache.go [hunk 1]
```diff
@@ -113,18 +113,20 @@ func (w *HotCache) IsRegionHot(region *core.RegionInfo, minHotDegree int) bool {
 	succ1 := w.CheckWriteAsync(checkRegionHotWriteTask)
 	succ2 := w.CheckReadAsync(checkRegionHotReadTask)
 	if succ1 && succ2 {
```
Comment (lhy1024) [inline pkg/statistics/hot_cache.go:115]: If retRead and retWrite are true and false, we should return true, not either of them.

**Review by rleungx — APPROVED** [review]

**Comment by HuSharp** [comment]
img_v3_02c8_640a6768-c954-4a46-92a5-6de029e70fcg
CI can find the data race problem, but it's strange why it hasn't been found in two weeks.

**Review by HuSharp — APPROVED** [review]

**Comment by HuSharp** [comment]
> img_v3_02c8_640a6768-c954-4a46-92a5-6de029e70fcg CI can find the data race problem, but it's strange why it hasn't been found in two weeks.

fixed in https://github.com/tikv/pd/pull/8342
