### PR TITLE
tests: fix TestTSOKeyspaceGroupSplitElection

### LINKED ISSUE #9842: `TestTSOKeyspaceGroupSplitElection` is flaky
### Which jobs are failing
```
keyspace_group_manager_test.go:377: 
        	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/tso/keyspace_group_manager_test.go:377
        	Error:      	Not equal: 
        	            	expected: []string{"http://127.0.0.1:39531/"}
        	            	actual  : []string{"http://127.0.0.1:43701/"}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 ([]string) (len=1) {
        	            	- (string) (len=22) "http://127.0.0.1:39531/"
        	            	+ (string) (len=22) "http://127.0.0.1:43701/"
        	            	 }
        	Test:       	TestTSOKeyspaceGroupManagerSuite/TestTSOKeyspaceGroupSplitElection
```

### CI link
https://github.com/tikv/pd/actions/runs/18549657370/job/52874637660?pr=9841

### PR DESCRIPTION
**Pull request by liupan1111**
### What problem does this PR solve?

Issue Number: Close #9842

### What is changed and how does it work?

- pause split finish, and ensure two keyspace groups primary in the same tso server.
```commit-message
```

### Check List

Tests

- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

File: pkg/keyspace/tso_keyspace_group.go [hunk 1]
```diff
@@ -712,6 +702,11 @@ func (m *GroupManager) FinishSplitKeyspaceByID(splitTargetID uint32) error {
 	var splitTargetKg, splitSourceKg *endpoint.KeyspaceGroup
 	m.Lock()
 	defer m.Unlock()
+
+	failpoint.Inject("pauseTxn", func() {
+		time.Sleep(2 * time.Second)
+	})
+
```
Comment (liyishuai) [inline pkg/keyspace/tso_keyspace_group.go:707]: If the test failed without the 2-second pause, will the production system fail as well?
* If yes, then only injecting the failpoint doesn't fix the production.
* If no, then what's the difference between the integration test and the production system that caused such diversion?

File: tests/integrations/mcs/tso/keyspace_group_manager_test.go [hunk 2]
```diff
@@ -462,6 +462,9 @@ func (suite *tsoKeyspaceGroupManagerTestSuite) requestTSO(
 
 func (suite *tsoKeyspaceGroupManagerTestSuite) TestTSOKeyspaceGroupSplitElection() {
 	re := suite.Require()
+
+	re.NoError(failpoint.Enable("github.com/tikv/pd/pkg/tso/pauseTxn", `return(true)`))
```
Comment (ystaticy) [inline tests/integrations/mcs/tso/keyspace_group_manager_test.go]: Can we just use `return()` instead of `return(true)`?

Comment (liupan1111) [reply tests/integrations/mcs/tso/keyspace_group_manager_test.go]: I'm not very familiar with return yet—I just followed how others wrote it... 
Let me look into it and get back to you.

File: pkg/keyspace/tso_keyspace_group.go (hunk 1 above)
Comment (liupan1111) [reply pkg/keyspace/tso_keyspace_group.go:707]: it is not related about production system, it is just about this test case. This test case will check whether the primarys before splitting finish, but not well control the race condition

File: pkg/keyspace/tso_keyspace_group.go [hunk 3]
```diff
@@ -712,6 +702,11 @@ func (m *GroupManager) FinishSplitKeyspaceByID(splitTargetID uint32) error {
 	var splitTargetKg, splitSourceKg *endpoint.KeyspaceGroup
 	m.Lock()
 	defer m.Unlock()
+
+	failpoint.Inject("pauseTxn", func() {
+		time.Sleep(2 * time.Second)
```
Comment (rleungx) [inline pkg/keyspace/tso_keyspace_group.go]: How about using `pause` instead of sleep?

Comment (liupan1111) [reply pkg/keyspace/tso_keyspace_group.go]: Actually, I also considered "pause" last night, but @niubell and @ystaticy thought "sleep" was good enough, so I can't make up my mind... @niubell @ystaticy ping

File: tests/integrations/mcs/tso/keyspace_group_manager_test.go (hunk 2 above)
Comment (liupan1111) [reply tests/integrations/mcs/tso/keyspace_group_manager_test.go]: @ystaticy After investigate, I agree.

File: pkg/keyspace/tso_keyspace_group.go (hunk 3 above)
Comment (liupan1111) [reply pkg/keyspace/tso_keyspace_group.go]: @rleungx @ystaticy i 'v replaced sleep with pause, please take a look

File: tests/integrations/mcs/tso/keyspace_group_manager_test.go [hunk 4]
```diff
@@ -462,6 +462,9 @@ func (suite *tsoKeyspaceGroupManagerTestSuite) requestTSO(
 
 func (suite *tsoKeyspaceGroupManagerTestSuite) TestTSOKeyspaceGroupSplitElection() {
 	re := suite.Require()
+
+	re.NoError(failpoint.Enable("github.com/tikv/pd/pkg/tso/pauseTxn", `pause`))
```
Comment (rleungx) [inline tests/integrations/mcs/tso/keyspace_group_manager_test.go]: seem the path is incorrect

Comment (liupan1111) [reply tests/integrations/mcs/tso/keyspace_group_manager_test.go]: @rleungx thanks for correction, please take a look my change

File: pkg/keyspace/tso_keyspace_group.go [hunk 5]
```diff
@@ -712,6 +702,9 @@ func (m *GroupManager) FinishSplitKeyspaceByID(splitTargetID uint32) error {
 	var splitTargetKg, splitSourceKg *endpoint.KeyspaceGroup
 	m.Lock()
 	defer m.Unlock()
+
+	failpoint.Inject("pauseTxn", nil)
```
Comment (rleungx) [inline pkg/keyspace/tso_keyspace_group.go]: Perhaps, we can use a more meaningful name like pauseFinishSplit or something else. pauseTxn sounds too general. The rest LGTM

**Review by rleungx — APPROVED** [review]

**Comment by rleungx** [comment]
As for the PR title, usually we use the subsystem name or module name, see https://github.com/tikv/pd/blob/master/CONTRIBUTING.md

File: pkg/keyspace/tso_keyspace_group.go (hunk 5 above)
Comment (liupan1111) [reply pkg/keyspace/tso_keyspace_group.go]: Agree， let me change

**Comment by liupan1111** [comment]
> As for the PR title, usually we use the subsystem name or module name, see https://github.com/tikv/pd/blob/master/CONTRIBUTING.md

ok, let me modify

File: pkg/keyspace/tso_keyspace_group.go (hunk 5 above)
Comment (liupan1111) [reply pkg/keyspace/tso_keyspace_group.go]: @rleungx done
