### PR TITLE
tests: fix fake test for `TestAllocIDAfterLeaderChange`

### LINKED ISSUE #9869: flaky test: TestAllocIDAfterLeaderChange
## Enhancement Task
link: https://github.com/tikv/pd/actions/runs/18736899212/job/53445458780?pr=9845

 ```
server_test.go:120: 
        	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/scheduling/server_test.go:120
        	Error:      	Received unexpected error:
        	            	PD leader is not found
        	            	github.com/tikv/pd/pkg/mcs/scheduling/server.(*Cluster).getPDLeaderClient
        	            		/home/runner/work/pd/pd/pkg/mcs/scheduling/server/cluster.go:289
        	            	github.com/tikv/pd/pkg/mcs/scheduling/server.(*Cluster).AllocID
        	            		/home/runner/work/pd/pd/pkg/mcs/scheduling/server/cluster.go:266
        	            	github.com/tikv/pd/tests/integrations/mcs/scheduling.(*serverTestSuite).TestAllocIDAfterLeaderChange
        	            		/home/runner/work/pd/pd/tests/integrations/mcs/scheduling/server_test.go:119
        	            	reflect.Value.call
        	            		/opt/hostedtoolcache/go/1.23.12/x64/src/reflect/value.go:584
        	            	reflect.Value.Call
        	            		/opt/hostedtoolcache/go/1.23.12/x64/src/reflect/value.go:368
        	            	github.com/stretchr/testify/suite.Run.func1
        	            		/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:202
        	            	testing.tRunner
        	            		/opt/hostedtoolcache/go/1.23.12/x64/src/testing/testing.go:1690
        	            	runtime.goexit
        	            		/opt/hostedtoolcache/go/1.23.12/x64/src/runtime/asm_amd64.s:1700
        	Test:       	TestServerTestSuite/TestAllocIDAfterLeaderChange
```

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #9869

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/integrations/mcs/scheduling/server_test.go [hunk 1]
```diff
@@ -97,12 +98,24 @@ func (suite *serverTestSuite) TestAllocID() {
...
 	defer tc.Destroy()
 	tc.WaitForPrimaryServing(re)
-	id, _, err := tc.GetPrimaryServer().GetCluster().AllocID(1)
-	re.NoError(err)
+	id := retryAllocID(re, tc.GetPrimaryServer().GetCluster())
 	re.NotEqual(uint64(0), id)
 	re.NoError(failpoint.Disable("github.com/tikv/pd/pkg/mcs/scheduling/server/fastUpdateMember"))
 }
 
+func retryAllocID(re *require.Assertions, cluster *scheduling.Cluster) uint64 {
```
Comment (lhy1024) [inline tests/integrations/mcs/scheduling/server_test.go:106]: Do we need to add a retry in other tests that call `AllocID`?

Comment (bufferflies) [reply tests/integrations/mcs/scheduling/server_test.go:106]: image
only this test called `AllocID`
