### PR TITLE
tests: fix flaky TestRegionCheck by using reflect.DeepEqual in Eventually

### LINKED ISSUE #9968: TestRegionCheck is unstable
### Which jobs are failing
```
2025-12-01T04:16:31.7827839Z === NAME  TestRegionTestSuite/TestRegionCheck
2025-12-01T04:16:31.7828351Z     testutil.go:68: 
2025-12-01T04:16:31.7829348Z         	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/testutil.go:68
2025-12-01T04:16:31.7830865Z         	            				/home/runner/work/pd/pd/tests/server/api/region_test.go:444
2025-12-01T04:16:31.7832122Z         	            				/home/runner/work/pd/pd/tests/testutil.go:611
2025-12-01T04:16:31.7833274Z         	            				/home/runner/work/pd/pd/tests/testutil.go:430
2025-12-01T04:16:31.7834438Z         	            				/home/runner/work/pd/pd/tests/testutil.go:402
2025-12-01T04:16:31.7835803Z         	            				/home/runner/work/pd/pd/tests/server/api/region_test.go:353
2025-12-01T04:16:31.7836547Z         	Error:      	Condition never satisfied
2025-12-01T04:16:31.7837222Z         	Test:       	TestRegionTestSuite/TestRegionCheck
```

### CI link
https://github.com/tikv/pd/actions/runs/19810918299/job/56753260065?pr=9967

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: Close #9968

`TestRegionCheck` is flaky because `suite.Equal()` (which calls `t.Errorf()`) is used inside `testutil.Eventually()` retry loops. When `suite.Equal()` fails on an early retry tick before async data propagates, it permanently marks the test as failed via `t.Errorf()`, even though subsequent ticks succeed.

Additionally, there was a bug where `r4.Adjust()` was called instead of `r8.Adjust()` on the last Eventually block.

### What is changed and how does it work?

- Replaced `suite.Equal()` with `reflect.DeepEqual()` inside all `testutil.Eventually()` blocks in `checkRegionCheck` — these return a boolean without calling `t.Errorf()`
- Added `re.Equal()` assertions after each `Eventually()` to preserve test correctness
- Fixed `r4.Adjust()` → `r8.Adjust()` bug

```commit-message
Replace suite.Equal() calls inside Eventually retry loops with
reflect.DeepEqual() or direct == comparisons. suite.Equal() uses
assert.Equal() which calls t.Errorf() on failure, permanently marking
the test as failed even when the condition eventually becomes true on
a later retry. Move the assertion after Eventually to maintain test
correctness.

Also fix a bug where r4.Adjust() was called instead of r8.Adjust()
in the offline-peer check block.
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

## Summary by CodeRabbit

* **Tests**
  * Improved test assertions for API responses to enhance test reliability and maintainability.

### CODE REVIEW

File: tests/server/api/region_test.go [hunk 1]
```diff
@@ -374,13 +375,15 @@ func (suite *regionTestSuite) checkRegionCheck(cluster *tests.TestCluster) {
...
+	expected := &response.RegionsInfo{Count: 1, Regions: []response.RegionInfo{*response.NewAPIRegionInfo(r)}}
 	testutil.Eventually(re, func() bool {
 		if err := testutil.ReadGetJSON(re, tests.TestDialClient, url, r2); err != nil {
 			return false
 		}
 		r2.Adjust()
-		return suite.Equal(&response.RegionsInfo{Count: 1, Regions: []response.RegionInfo{*response.NewAPIRegionInfo(r)}}, r2)
+		return reflect.DeepEqual(expected, r2)
 	})
+	re.Equal(expected, r2)
```
Comment (rleungx) [inline tests/server/api/region_test.go]: seem no need to check again
