### PR TITLE
cluster: fix TiFlash store removal being blocked by TiKV replica check

### LINKED ISSUE #10350: TiFlash store removal incorrectly blocked by TiKV replica check
### What did you do?

Attempted to remove a TiFlash node from the cluster (scale-in operation):

1. Cluster setup: 3 TiKV nodes (max-replicas=3) + 4 TiFlash nodes
2. Delete TiFlash store using pd-ctl:
   ```bash
   pd-ctl -u http://127.0.0.1:2379 store delete 1540
   ```
3. Or remove TiFlash node using TiUP scale-in

### What did you expect to see?

Expected to successfully remove the TiFlash node because:
- TiFlash uses learner nodes for columnar storage
- TiFlash does not participate in Raft voting
- TiFlash removal should not affect Raft replica count check
- Cluster has 3 TiKV nodes, which satisfies max-replicas=3 requirement

### What did you see instead?

PD rejected the removal operation with error:

```
Failed to delete store 1540: [400] "[PD:core:ErrStoresNotEnough]can not remove store 1540 since the number of up stores would be 2 while need 3"
```

The TiFlash node removal failed even though the cluster has 3 TiKV nodes (satisfying max-replicas=3).

**Root Cause**:

The `checkReplicaBeforeOfflineStore` function at `server/cluster/cluster.go:1569`:
- Uses `getUpStores()` which only returns **TiKV stores**
- Incorrectly assumes ANY store deletion reduces TiKV count by 1
- Applies TiKV replica count validation logic to TiFlash stores

### What version of PD are you using (`pd-server -V`)?

`v9.0.0-beta.2.pre-315-gb2ac11253` (master branch)

**Environment**:
- TCMS test execution: 8056627
- Related issue: [pingcap/tiup#2449](https://github.com/pingcap/tiup/issues/2449)

### PR DESCRIPTION
**Pull request by liyishuai**
### What problem does this PR solve?

Issue Number: close #10350

### What is changed and how does it work?

```commit-message
When attempting to remove a TiFlash store, PD incorrectly applied
TiKV replica count validation, causing removal failures with
"ErrStoresNotEnough" even when TiKV stores were sufficient.

Root cause:
- checkReplicaBeforeOfflineStore() used getUpStores() which only
  returns TiKV stores
- The function assumed ANY store deletion reduces TiKV count by 1
- This is incorrect for non-TiKV stores which don't affect Raft replicas

Fix:
- Add store type check at the beginning of checkReplicaBeforeOfflineStore()
- Skip TiKV replica validation for non-TiKV stores using !store.IsTiKV()
- Only TiKV stores participate in Raft voting; non-TiKV stores (TiFlash, etc.)
  use learners and can be removed without affecting Raft replica count
```

### Check List

Tests

- Unit test (TestRemoveTiFlashStore)

Code changes

- Modified server/cluster/cluster.go to add non-TiKV store check in checkReplicaBeforeOfflineStore()

Side effects

- No

Related changes

- No

### Release note

```release-note
Fix TiFlash store removal being incorrectly blocked by TiKV replica check
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Added null-checks for store references to prevent errors during offline operations.
  * Replica validation now applies only to TiKV stores; other store types can bypass TiKV-specific replica checks during removal.

* **Tests**
  * Added test coverage validating removal of TiFlash stores while ensuring TiKV replication requirements and proper state transitions.

### CODE REVIEW

**Comment by liyishuai** [comment]
@coderabbitai help

**Comment by liyishuai** [comment]
@coderabbitai full review

**Comment by liyishuai** [comment]
@coderabbitai full review

File: server/cluster/cluster.go [hunk 1]
```diff
@@ -1567,6 +1567,17 @@ func (c *RaftCluster) RemoveStore(storeID uint64, physicallyDestroyed bool) erro
...
 
 func (c *RaftCluster) checkReplicaBeforeOfflineStore(storeID uint64) error {
+	store := c.GetStore(storeID)
+	if store == nil {
+		return errs.ErrStoreNotFound.FastGenByArgs(storeID)
+	}
+
+	// TiFlash stores don't affect Raft replica count, skip the check.
+	// TiFlash stores are for columnar storage and use learners, not Raft voters.
+	if store.IsTiFlashWrite() || store.IsTiFlashCompute() {
```
Comment (rleungx) [inline server/cluster/cluster.go]: Shall we use isTiKV?

Comment (liyishuai) [reply server/cluster/cluster.go]: Fixed.

File: server/cluster/cluster.go [hunk 2]
```diff
@@ -1567,6 +1567,18 @@ func (c *RaftCluster) RemoveStore(storeID uint64, physicallyDestroyed bool) erro
...
+	store := c.GetStore(storeID)
+	if store == nil {
+		return errs.ErrStoreNotFound.FastGenByArgs(storeID)
+	}
+
+	// Only TiKV stores participate in Raft voting and affect replica count.
+	// Non-TiKV stores (e.g., TiFlash) use learners and can be removed without
+	// affecting Raft replica validation.
+	if !store.IsTiKV() {
+		return nil
```
Comment (AndreMouche) [inline server/cluster/cluster.go:1579]: Should we consider the number of learners here? For example, if we create a table that need at least 3 learners, and we only have 3 TiFlash nodes, when we try to offline one TiFlash node , should we return an ErrTiflashsNotEnough error?

File: server/cluster/cluster.go [hunk 3]
```diff
@@ -1567,6 +1567,18 @@ func (c *RaftCluster) RemoveStore(storeID uint64, physicallyDestroyed bool) erro
...
+	}
+
 	upStores := c.getUpStores()
```
Comment (bufferflies) [inline server/cluster/cluster.go]: getUpStores should rename getUpTikvStores?

File: server/cluster/cluster.go [hunk 4]
```diff
@@ -1567,6 +1567,18 @@ func (c *RaftCluster) RemoveStore(storeID uint64, physicallyDestroyed bool) erro
 }
 
 func (c *RaftCluster) checkReplicaBeforeOfflineStore(storeID uint64) error {
```
Comment (bufferflies) [inline server/cluster/cluster.go]: ditto, the function should tell the caller that it only carries about the tikv engine?

File: server/cluster/cluster.go (hunk 2 above)
Comment (liyishuai) [reply server/cluster/cluster.go:1579]: @bufferflies any ideas here?

File: server/cluster/cluster.go (hunk 4 above)
Comment (liyishuai) [reply server/cluster/cluster.go]: Both renamed in 3e57fa7cf8d17f4b9671f6eb54dfee95c3d566fe

File: server/cluster/cluster.go (hunk 2 above)
Comment (bufferflies) [reply server/cluster/cluster.go:1579]: We can't consider all cases when using placement rules; it's too difficult. If not match the rules after scale-in this node, it will be stuck and wait for the user to scale out another node.

**Review by rleungx — APPROVED** [review]
