### PR TITLE
*: fix the wrong store monitor

### LINKED ISSUE #5391: The low space store is not accurate in the monitor
### What did you do?

Start a new cluster with 6 TiKV and all TiKV used space are higher than low-space-ratio.

### What did you expect to see?

There are 6 TiKV in the low space state.

### What did you see instead?

Only 3 TiKV in low space state from the Grafana.
Screen Shot 2022-08-03 at 2 36 48 PM
Screen Shot 2022-08-03 at 2 36 56 PM

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Issue Number: Close #5391.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Manual test

### Release note

```release-note
None
```

### CODE REVIEW

File: server/core/store.go [hunk 1]
```diff
@@ -425,13 +425,14 @@ func (s *StoreInfo) AvailableRatio() float64 {
...
+// than InitClusterRegionThreshold and available space more than initialMinSpace
 func (s *StoreInfo) IsLowSpace(lowSpaceRatio float64) bool {
 	if s.GetStoreStats() == nil {
 		return false
 	}
-	// issue #3444
-	if s.regionCount < initialMaxRegionCounts && s.GetAvailable() > initialMinSpace {
+	// See https://github.com/tikv/pd/issues/3444 and https://github.com/tikv/pd/issues/5391
+	// TODO: we need find a better way to get the init region number when starting a new cluster.
+	if s.regionCount < InitClusterRegionThreshold && s.GetAvailable() > initialMinSpace {
```
Comment (bufferflies) [inline server/core/store.go:435]: maybe using the start time is better?

Comment (rleungx) [reply server/core/store.go:434]: Add a TODO here since using start time could also be inaccurate.

**Review by bufferflies — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
