### PR TITLE
tests: fix unstable test `pdctl/TestScheduler`

### LINKED ISSUE #5667: `pdctl/TestScheduler` is unstable
https://github.com/tikv/pd/actions/runs/3368718923/jobs/5587582938

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #5667

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by HunDunDM — APPROVED** [review]

File: tests/pdctl/scheduler/scheduler_test.go [hunk 1]
```diff
@@ -390,6 +391,7 @@ func TestScheduler(t *testing.T) {
 	mustExec([]string{"-u", pdAddr, "scheduler", "config", "balance-hot-region-scheduler"}, &conf1)
 	// cannot set qps as write-peer-priorities
 	mustExec([]string{"-u", pdAddr, "scheduler", "config", "balance-hot-region-scheduler", "set", "write-peer-priorities", "query,byte"}, nil)
+	time.Sleep(sche.MinScheduleInterval * 2) // wait for the scheduler to run
```
Comment (bufferflies) [inline tests/pdctl/scheduler/scheduler_test.go:394]: how about use event?

**Review by bufferflies — COMMENTED** [review]
rest LGTM

**Review by bufferflies — APPROVED** [review]
